import type { Row } from './api';
import type { LiveMetadataCatalog } from './metadata';
import type { MetadataSnapshot, Relationship, FieldDef, Evidence } from '../features/er/types/domain';
const text=(v:unknown)=>v==null?'':String(v);
export const sourceIdentity=(id:string)=>'shared-source:'+id;
export const entityIdentity=(id:string)=>'shared-table:'+id;
export const fieldIdentity=(id:string)=>'shared-column:'+id;
export const canonicalId=(id:string)=>{if(!/^shared-(source|table|column):/.test(id))throw new Error('只能使用共享元数据中的对象');return id.slice(id.indexOf(':')+1);};
export function relationJson(value:unknown):Row {if(value==null||value==='')return {};const parsed=typeof value==='string'?JSON.parse(value):value;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('关系定义格式损坏，不能用空定义覆盖');return parsed as Row;}
const truth=(v:unknown):'true'|'false'|'unknown'=>[true,1,'1','true'].includes(v as never)?'true':[false,0,'0','false'].includes(v as never)?'false':'unknown';
const family=(t:string):FieldDef['typeFamily']=>/int|number\(\d+\)/i.test(t)?'integer':/decimal|numeric|number/i.test(t)?'decimal':/float|double|real/i.test(t)?'float':/timestamp|datetime/i.test(t)?'timestamp':/^date/i.test(t)?'date':/char|text|clob|string/i.test(t)?'string':/bool/i.test(t)?'boolean':/binary|blob/i.test(t)?'binary':'unknown';
export function metadataSnapshot(catalog:LiveMetadataCatalog,scope:string):MetadataSnapshot{
 const columns=new Map<string,Row[]>();for(const c of catalog.columns){const list=columns.get(c.table_id)||[];list.push(c);columns.set(c.table_id,list);}
 return {schemaVersion:'1.0',id:'shared-metadata:'+scope,capturedAt:catalog.tables.map(t=>text(t.updated_time)).filter(Boolean).sort().at(-1)||'',sources:catalog.sources.map(s=>({id:sourceIdentity(s.tid),name:s.db_name,engine:s.db_type,capabilities:{catalogConstraints:false,fieldProfiles:false,referenceValidation:false,crossSourceValidation:false,fullValidation:false}})),entities:catalog.tables.map(t=>{const fields=(columns.get(t.tid)||[]).map(c=>({id:fieldIdentity(c.tid),name:text(c.column_name),path:text(c.column_name),comment:text(c.column_comment),ordinal:Number(c.ordinal_position||0),nativeType:text(c.column_type||c.data_type),typeFamily:family(text(c.column_type||c.data_type)),length:Number(c.length)||undefined,nullable:truth(c.nullable)}));const primary=(columns.get(t.tid)||[]).filter(c=>truth(c.primary_key)==='true').map(c=>fieldIdentity(c.tid));const unique=(columns.get(t.tid)||[]).filter(c=>truth(c.is_unique)==='true');return {id:entityIdentity(t.tid),sourceId:sourceIdentity(t.datasource_id),name:t.table_name,displayName:text(t.table_name_cn)||(!/^(VIEW|TABLE)$/i.test(t.table_comment||'')?t.table_comment:'')||t.table_name,kind:/view|视图/i.test(t.table_type||'')?'view' as const:'table' as const,comment:t.table_comment,shapeBasis:fields.length>0&&Number(t.field_count)===fields.length?'declared_complete' as const:'unknown' as const,constraintsAvailability:'unknown' as const,fields,keys:[...(primary.length?[{id:'primary:'+t.tid,kind:'primary' as const,fieldIds:primary,enforced:'unknown' as const}]:[]),...unique.map(c=>({id:'unique:'+c.tid,kind:'unique' as const,fieldIds:[fieldIdentity(c.tid)],enforced:'unknown' as const}))]};}),catalogRelationships:[]};
}
export function metadataRelationship(row:Row,snapshotId:string,scope:string):Relationship{
 const status=String(row.relation_status||row.status||'CONFIRMED').toLowerCase();const origin=String(row.relation_origin||row.origin||'MANUAL').toLowerCase();
 const definition=relationJson(row.definition_json),validation=relationJson(row.validation_json),physical=relationJson(row.physical_fk_json);
 const sourceEntityId=entityIdentity(text(row.source_table_id)),targetEntityId=entityIdentity(text(row.target_table_id));const mappings=(definition.mappings||[{sourceColumnId:row.source_column_id,targetColumnId:row.target_column_id}]).map((m:Row)=>({sourceFieldId:fieldIdentity(text(m.sourceColumnId)),targetFieldId:fieldIdentity(text(m.targetColumnId)),comparisonRule:'exact' as const}));
 return {id:text(row.tid||row.id),workspaceId:scope,snapshotId,name:text(row.relation_name)||'逻辑关联',sourceEntityId,targetEntityId,mappings,conditions:(definition.conditions||[]).map((t:Row)=>({side:t.side,fieldId:fieldIdentity(text(t.columnId)),operator:t.operator,value:t.value})),targetsPerSource:definition.targetsPerSource,sourcesPerTarget:definition.sourcesPerTarget,semanticType:row.relation_type==='JOIN'?'join':'reference',origin:origin==='inference'?'inference':'manual',reviewStatus:['confirmed','suggested','rejected','archived'].includes(status)?status as Relationship['reviewStatus']:'confirmed',lifecycle:row.broken?'broken':'current',fingerprint:JSON.stringify([sourceEntityId,targetEntityId,mappings,definition.conditions||[]]),description:text(row.description),createdAt:text(row.created_time||row.updated_time),updatedAt:text(row.updated_time),version:Number(row.version_no||1),physicalForeignKey:Object.keys(physical).length?physical:undefined,verification:validation.id?{status:validation.validationStatus,evidenceId:validation.id,verifiedAt:validation.capturedAt,targetUniquenessBasis:validation.targetUniquenessBasis,consistency:'best_effort'}:{status:'not_run'},recommendation:origin==='inference'?{score:Number(row.confidence||0),level:'structure_only',ruleVersion:'shared-metadata-structure-v1',isCalibratedProbability:false,unmetChecks:['结构推荐不是业务语义的正确率']} :null};
}
export function metadataEvidence(row:Row,snapshotId:string):Evidence[]{const v=relationJson(row.validation_json);return v.id?[{...v,id:v.id,relationshipId:text(row.tid),snapshotId,kind:'data',summary:'真实联合键与条件范围验证',capturedAt:v.capturedAt,simulated:false} as Evidence]:[];}
