import type { FieldMode } from '../../features/er/core/model';
import { memo, useCallback, useEffect, useMemo, useRef, useState, type DragEvent } from 'react';
import { Alert, App, Button, Checkbox, Dropdown, Empty, Form, Input, InputNumber, Modal, Popover, Select, Space, Tabs, Tag, Tooltip } from 'antd';
import { ArrowDownOutlined, ArrowUpOutlined, CloseOutlined, DeleteOutlined, EditOutlined, FullscreenExitOutlined, FullscreenOutlined, LockOutlined, PlusOutlined, SaveOutlined, SearchOutlined, SunOutlined, MoonOutlined, UnlockOutlined } from '@ant-design/icons';
import { ReactFlow, ReactFlowProvider, Handle, Position, MiniMap, Background, BaseEdge, EdgeLabelRenderer, getSmoothStepPath, applyNodeChanges, useReactFlow, useViewport, useUpdateNodeInternals, ConnectionMode, type Node, type NodeProps, type EdgeProps, type Edge, type NodeChange, type Connection } from '@xyflow/react';
import { useNavigate, useParams } from 'react-router-dom';
import { useResource } from '../services/context';
import { TechnicalEntitySelect } from '../components/TechnicalEntitySelect';
import { FusionJoinDialog, FusionMappingDialog } from '../components/FusionDialogs';
import type { DesignEntity, DesignField, FusionJoin, FusionMapping, LogicalModel, ModelContent } from '../domain/types';
import type { FieldMapping, Relationship } from '../../features/er/types/domain';
import { fieldFamily, logicalTypes, logicalType, validateModel, validateDesignRelation } from '../domain/rules';
import { fingerprint } from '../../features/er/core/relations';
import { preserveLockedNodes } from '../../features/er/core/layout';
import { alignNodes } from '../../features/er/core/alignment';
import { isEditingTarget, hasBlockingLayer, escapeAction } from '../../features/er/core/interaction';
import { Icon } from '../../features/er/components/Icon';
import { ResizeHandle } from '../../features/er/components/ResizeHandle';
import { draftState, useDraftGuard } from '../app/leave';
import { CenterSwitcher } from '../../shared/centers/CenterSwitcher';
import { SourceIcon } from '../../design/Visuals';
import { EditDialog, required, timeText, saveFile, PsIcon } from '../components/ui';
import { resourceSessionScope } from '../services/transport';
import { applySelectionChanges, canvasInteractionProps, designVisibleFields, parseDesignHandle, pinDesignField, validViewport } from '../domain/canvasUX';
const uuid = () => crypto.randomUUID();
const NODE_WIDTH = 320;
const contentOf = (m: LogicalModel): ModelContent => structuredClone({ entities: m.entities, relationships: m.relationships, nodes: m.nodes, outputEntityId: m.outputEntityId, fusion: m.fusion });
type EntityData = {
  entity: DesignEntity; engine?: string; locked: boolean; collapsed: boolean;
  fields: DesignField[]; hiddenCount: number; activeField?: string; highlighted: string[];
  open: (id: string) => void; openField: (id: string, fid: string) => void;
  toggle: (id: string) => void; action: (id: string, action: string) => void;
};
type EntityFlowNode = Node<EntityData, 'design'>;
const DesignNode = memo(function DesignNode({ id, data, selected }: NodeProps<EntityFlowNode>) {
  const update = useUpdateNodeInternals();
  const signature = data.fields.map(f => f.id).join('|');
  useEffect(() => { update(id); }, [id, signature, data.collapsed, update]);
  const keys = data.entity.keys?.filter(k => k.kind === 'primary').flatMap(k => k.fieldIds) ?? [];
  return <section className={`ps-entity-node ${selected ? 'selected' : ''} ${data.entity.reference ? 'reference' : ''} ${data.entity.role === 'OUTPUT' ? 'fusion-output' : data.entity.role === 'SOURCE' ? 'fusion-source' : ''}`} data-testid={`design-entity-${data.entity.name}`}>
    <header className="ps-node-handle">
      {data.engine ? <SourceIcon engine={data.engine} small/> : <PsIcon name="models"/>}
      <div className="ps-node-title"><strong title={data.entity.displayName || data.entity.name}>{data.entity.displayName || data.entity.name}</strong><small>{data.entity.name}</small></div>
      {data.locked && <LockOutlined/>}
      <Dropdown trigger={['click']} menu={{items:[
        {key:'detail',label:'查看实体与字段',icon:<Icon name="table"/>},
        {key:'edit',label:'编辑设计实体',disabled:!!data.entity.reference||data.entity.role==='SOURCE',icon:<Icon name="edit"/>},
        {key:'field',label:'添加设计字段',disabled:!!data.entity.reference||data.entity.role==='SOURCE',icon:<Icon name="plus"/>},
        {key:'output',label:'设为唯一输出表 D（旧模型）',disabled:!!data.entity.reference||!!data.entity.role,icon:<Icon name="table"/>},
        {key:'focus',label:'仅看相关关系',icon:<Icon name="eye"/>},
        {type:'divider'},
        {key:'lock',label:data.locked?'取消固定位置':'固定位置',icon:<Icon name={data.locked?'unlock':'lock'}/>},
        {key:'collapse',label:data.collapsed?'展开字段':'折叠字段',icon:<Icon name="collapse"/>},
        {type:'divider'},
        {key:'remove',label:'删除草稿设计实体',danger:true,icon:<Icon name="close"/>}
      ],onClick:({key})=>data.action(id,key)}}><button className="ps-node-more nodrag nopan" aria-label={`${data.entity.displayName || data.entity.name}更多操作`} onClick={e=>e.stopPropagation()}><Icon name="more" size={18}/></button></Dropdown>
    </header>
    {data.entity.reference && <div className="ps-reference-badge">冻结版本参照 · 只读</div>}
    {data.entity.role && <div className="ps-fusion-role">{data.entity.role==='OUTPUT'?'目标输出表 D':'来源表 · 只读快照'}</div>}
    {data.fields.map(f=><div className={`ps-design-field ${data.activeField===f.id||data.highlighted.includes(f.id)?'field-highlighted':''}`} key={f.id} title={`${f.businessName||f.name} · ${f.logicalType}`}>
      <Handle className="ps-port" type="source" position={Position.Left} id={`f:${f.id}::left`}/>
      <span className={`ps-key ${keys.includes(f.id)?'is-key':f.standard?'is-standard':''}`} title={keys.includes(f.id)?'设计主键成员':f.standard?'已绑定标准':''}>{keys.includes(f.id)?<PsIcon name="key"/>:f.standard?'S':<span>·</span>}</span>
      <button className="nodrag nopan" onClick={event=>{event.stopPropagation();data.openField(id,f.id);}}>{f.name}</button><small>{f.logicalType}</small>
      <Handle className="ps-port" type="source" position={Position.Right} id={`f:${f.id}::right`}/>
    </div>)}
    <footer className="ps-node-bottom"><Handle type="source" position={Position.Left} id="summary::left" isConnectable={false}/><button className="nodrag nopan" onClick={event=>{event.stopPropagation();data.collapsed?data.toggle(id):data.open(id);}}>{data.collapsed?`${data.entity.fields.length} 个字段 · 展开` : data.hiddenCount ? `还有 ${data.hiddenCount} 个字段 · 查看详情` : `${data.entity.fields.length} 个字段`}</button><span>{data.entity.role==='OUTPUT'?'目标 D':data.entity.role==='SOURCE'?'来源':'设计实体'}</span><Handle type="source" position={Position.Right} id="summary::right" isConnectable={false}/></footer>
  </section>;
});
type DesignEdgeData={name:string;composite:number;self:boolean;showLabel:boolean;kind?:'JOIN'|'MAP'|'LEGACY'};
function DesignEdge(p:EdgeProps<Edge<DesignEdgeData>>) {
  const [normal,x,y]=getSmoothStepPath({...p,borderRadius:14,offset:30});
  const edgePath=p.data?.self?`M ${p.sourceX} ${p.sourceY} C ${p.sourceX+100} ${p.sourceY},${p.sourceX+100} ${p.sourceY-110},${p.sourceX-150} ${p.sourceY-110} S ${p.targetX-70} ${p.targetY},${p.targetX} ${p.targetY}`:normal;
  return <><BaseEdge path={edgePath} style={{stroke:p.selected?'var(--ps-primary)':p.data?.kind==='MAP'?'#5ad0bd':'var(--ps-blue)',strokeWidth:p.selected?2.4:p.data?.kind==='MAP'?2:1.6,strokeDasharray:p.data?.kind==='MAP'?'5 4':undefined}}/>{p.data?.showLabel&&<EdgeLabelRenderer><div className="ps-edge-label nodrag nopan" style={{transform:`translate(-50%,-50%) translate(${p.data.self?p.sourceX+40:x}px,${p.data.self?p.sourceY-70:y}px)`}}>{p.data.name}{p.data.composite>1?` · ${p.data.composite} 字段`:''}</div></EdgeLabelRenderer>}</>;
}
const nodeTypes={design:DesignNode};const edgeTypes={design:DesignEdge};
export function Designer({dark,onTheme}:{dark:boolean;onTheme:()=>void}) {return <ReactFlowProvider><CanvasSession dark={dark} onTheme={onTheme}/></ReactFlowProvider>;}
function CanvasSession({dark,onTheme}:{dark:boolean;onTheme:()=>void}) {
 const {id=''}=useParams(),nav=useNavigate(),{data,act}=useResource(),{message,modal}=App.useApp();
 const model=data.state.models.find(m=>m.id===id);
 const [draft,setDraft]=useState<ModelContent>(()=>model?contentOf(model):{entities:[],relationships:[],nodes:[]});
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[layoutBusy,setLayoutBusy]=useState(false);
 const [selected,setSelected]=useState(''),[selectedIds,setSelectedIds]=useState<string[]>([]),[selectedEdge,setSelectedEdge]=useState(''),[activeField,setActiveField]=useState(''),[inspectorOpen,setInspectorOpen]=useState(false);
 const [entityEdit,setEntityEdit]=useState<DesignEntity|{id:''}|null>(null),[fieldEdit,setFieldEdit]=useState<DesignField|{id:''}|null>(null),[relationEdit,setRelationEdit]=useState<Relationship|null>(null);
 const [joinEdit,setJoinEdit]=useState<FusionJoin|null>(null),[mappingEdit,setMappingEdit]=useState<FusionMapping|null>(null);
 const [bulkSourceId,setBulkSourceId]=useState(''),[bulkFieldIds,setBulkFieldIds]=useState<string[]>([]),[bulkQuery,setBulkQuery]=useState('');
 const [leftTab,setLeftTab]=useState('entities'),[q,setQ]=useState(''),[focus,setFocus]=useState(false),[focusId,setFocusId]=useState('');
 const [fieldMode,setFieldMode]=useState<FieldMode>('key'),[snap,setSnap]=useState(true),[grid,setGrid]=useState(true),[minimap,setMinimap]=useState(true),[labels,setLabels]=useState(true),[panMode,setPanMode]=useState(false),[space,setSpace]=useState(false);
 const [libraryOpen,setLibraryOpen]=useState(()=>innerWidth>=768),[libraryWidth,setLibraryWidth]=useState(280),[inspectorWidth,setInspectorWidth]=useState(400);
 const [searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(''),[searchIndex,setSearchIndex]=useState(0),[helpOpen,setHelpOpen]=useState(false);
 const [reverse,setReverse]=useState(false),[reverseIds,setReverseIds]=useState<string[]>([]),[refOpen,setRefOpen]=useState(false),[refId,setRefId]=useState(''),[refRev,setRefRev]=useState('');
 const [savedAt,setSavedAt]=useState(model?.updatedAt),[conflict,setConflict]=useState(false),[saveError,setSaveError]=useState(''),[history,setHistory]=useState<ModelContent[]>([]),[future,setFuture]=useState<ModelContent[]>([]);
 const draftRef=useRef(draft);draftRef.current=draft;
 const version=useRef(model?.version??0),seq=useRef(0),savedSequence=useRef(0),pendingSave=useRef<Promise<void>|null>(null),root=useRef<HTMLDivElement>(null);
 const [fieldForm]=Form.useForm(),logical=Form.useWatch('logicalType',fieldForm);
 const flow=useReactFlow<EntityFlowNode>(),viewport=useViewport();
 const viewportKey=`panshi:canvas-view:${resourceSessionScope()}:${id}`;
 const initialView=useMemo(()=>{try{const v=JSON.parse(localStorage.getItem(viewportKey)||'null');return validViewport(v)?v:undefined;}catch{return undefined;}},[viewportKey]);
 const current=draft.entities.find(e=>e.id===selected),currentRelation=draft.relationships.find(r=>r.id===selectedEdge);
 const currentJoin=draft.fusion?.joins.find(j=>j.id===selectedEdge),currentMapping=draft.fusion?.mappings.find(m=>m.id===selectedEdge);
 useEffect(()=>{if(!model)return;const c=contentOf(model);setDraft(c);draftRef.current=c;version.current=model.version;setDirty(false);setHistory([]);setFuture([]);setSelected('');setSelectedIds([]);setSelectedEdge('');setInspectorOpen(false);seq.current++;savedSequence.current=seq.current;root.current?.focus();},[id]);
 const mutate=useCallback((fn:(c:ModelContent)=>void,record=true)=>{const prior=draftRef.current,next=structuredClone(prior);fn(next);if(record)setHistory(h=>[...h.slice(-49),structuredClone(prior)]);setFuture([]);draftRef.current=next;setDraft(next);setDirty(true);seq.current++;},[]);
 const save=useCallback(async()=>{
  if(pendingSave.current)await pendingSave.current;
  if(!model)throw new Error('模型不存在');if(savedSequence.current===seq.current)return;
  const started=seq.current;
  const task=(async()=>{setBusy(true);try{const latest=await act<LogicalModel>(`models/${id}`,{content:structuredClone(draftRef.current)},version.current,'PUT');version.current=latest.version;setSavedAt(latest.updatedAt);setConflict(false);setSaveError('');savedSequence.current=started;if(started===seq.current){setDirty(false);draftState.dirty=false;}}catch(e){setSaveError(e instanceof Error?e.message:'保存未完成');setConflict(true);throw e;}finally{setBusy(false);}})();
  pendingSave.current=task;try{await task;}finally{if(pendingSave.current===task)pendingSave.current=null;}
 },[act,id,model]);
 useDraftGuard(dirty,save);const autosave=useRef(save);autosave.current=save;
 useEffect(()=>{if(!dirty||busy||conflict||entityEdit||fieldEdit||relationEdit||joinEdit||mappingEdit||bulkSourceId||reverse||refOpen)return;const timer=setTimeout(()=>void autosave.current().catch(()=>{}),950);return()=>clearTimeout(timer);},[draft,dirty,busy,conflict,entityEdit,fieldEdit,relationEdit,joinEdit,mappingEdit,bulkSourceId,reverse,refOpen]);
 const close=async()=>{try{if(dirty)await save();nav('/resource/models');}catch(e){message.error(e instanceof Error?e.message:String(e));}};
 const beforeSwitch=async()=>{if(dirty)await save();return true;};
 const undo=()=>{if(!history.length)return;const prior=history.at(-1)!;setFuture(f=>[structuredClone(draftRef.current),...f]);setHistory(h=>h.slice(0,-1));setDraft(prior);draftRef.current=prior;seq.current++;setDirty(true);};
 const redo=()=>{if(!future.length)return;setHistory(h=>[...h,structuredClone(draftRef.current)]);const next=future[0];setFuture(f=>f.slice(1));setDraft(next);draftRef.current=next;seq.current++;setDirty(true);};
 const inspectEntity=useCallback((eid:string)=>{setSelected(eid);setSelectedIds([eid]);setSelectedEdge('');setInspectorOpen(true);setFocus(false);},[]);
 const openField=useCallback((eid:string,fid:string)=>{inspectEntity(eid);setActiveField(fid);},[inspectEntity]);
 useEffect(()=>{if(activeField&&inspectorOpen)requestAnimationFrame(()=>document.getElementById(`ps-inspector-field-${activeField}`)?.scrollIntoView({block:'nearest'}));},[activeField,inspectorOpen]);
 const collapse=useCallback((eid:string)=>{if(fieldMode==='summary')setFieldMode('key');mutate(c=>{const n=c.nodes.find(n=>n.entityId===eid);if(n)n.collapsed=fieldMode==='summary'?false:!n.collapsed;});},[mutate,fieldMode]);
 const removeEntities=(ids:string[])=>{if(!ids.length)return;if(ids.includes(draftRef.current.outputEntityId||'')){message.warning('目标输出表 D 不能删除，可编辑表名和字段');return;}modal.confirm({title:`删除 ${ids.length} 个草稿设计实体？`,content:'同时删除当前设计稿中的关联。来源技术快照、已物化资源与历史冻结版本不变；此操作可以撤销。',okText:'删除草稿实体',okButtonProps:{danger:true},cancelText:'取消',onOk:()=>{mutate(c=>{const fields=c.entities.filter(e=>ids.includes(e.id)).flatMap(e=>e.fields.map(f=>f.id));c.entities=c.entities.filter(e=>!ids.includes(e.id));c.nodes=c.nodes.filter(n=>!ids.includes(n.entityId));c.relationships=c.relationships.filter(r=>!ids.includes(r.sourceEntityId)&&!ids.includes(r.targetEntityId));if(c.fusion){c.fusion.joins=c.fusion.joins.filter(j=>!ids.includes(j.leftEntityId)&&!ids.includes(j.rightEntityId));c.fusion.mappings=c.fusion.mappings.filter(m=>!ids.includes(m.sourceEntityId)&&!fields.includes(m.targetFieldId));if(ids.includes(c.fusion.baseEntityId||''))c.fusion.baseEntityId=c.entities.find(e=>e.role==='SOURCE')?.id;}});setSelected('');setSelectedIds([]);setInspectorOpen(false);}});};
 const onDeleteEntity=(eid:string)=>removeEntities([eid]);
 const nodeAction=(eid:string,action:string)=>{const e=draftRef.current.entities.find(x=>x.id===eid);if(!e)return;if(action==='detail')inspectEntity(eid);if(action==='edit'&&!e.reference&&e.role!=='SOURCE'){inspectEntity(eid);setEntityEdit(e);}if(action==='field'&&!e.reference&&e.role!=='SOURCE'){inspectEntity(eid);setFieldEdit({id:''});}if(action==='output'&&!draftRef.current.outputEntityId&&!e.reference)mutate(c=>{c.outputEntityId=eid;c.entities.forEach(x=>{if(!x.reference)x.role=x.id===eid?'OUTPUT':'SOURCE';});c.fusion={baseEntityId:c.entities.find(x=>x.role==='SOURCE')?.id,joins:[],mappings:[]};});if(action==='focus')setFocusId(f=>f===eid?'':eid);if(action==='collapse')collapse(eid);if(action==='lock')mutate(c=>{const n=c.nodes.find(x=>x.entityId===eid);if(n)n.locked=!n.locked;});if(action==='remove')removeEntities([eid]);};
 const relatedIds=useMemo(()=>focusId?new Set([focusId,...draft.relationships.filter(r=>r.sourceEntityId===focusId||r.targetEntityId===focusId).flatMap(r=>[r.sourceEntityId,r.targetEntityId]),...(draft.fusion?.joins??[]).filter(j=>j.leftEntityId===focusId||j.rightEntityId===focusId).flatMap(j=>[j.leftEntityId,j.rightEntityId]),...(draft.fusion?.mappings??[]).filter(m=>m.sourceEntityId===focusId||draft.outputEntityId===focusId).flatMap(m=>[m.sourceEntityId,draft.outputEntityId||''])]):null,[focusId,draft.relationships,draft.fusion,draft.outputEntityId]);
 const highlighted=currentRelation?.mappings?.flatMap(p=>[p.sourceFieldId,p.targetFieldId])??currentJoin?.pairs.flatMap(p=>[p.leftFieldId,p.rightFieldId])??(currentMapping?[currentMapping.sourceFieldId,currentMapping.targetFieldId]:[]);
 const nodes=useMemo<EntityFlowNode[]>(()=>draft.entities.map((e,i)=>{const n=draft.nodes.find(n=>n.entityId===e.id),visible=designVisibleFields(e,draft.relationships,fieldMode,n);return {id:e.id,type:'design',position:n?.position??{x:(i%3)*430+80,y:Math.floor(i/3)*410+80},selected:selectedIds.includes(e.id),hidden:!!relatedIds&&!relatedIds.has(e.id),dragHandle:'.ps-node-handle',draggable:!n?.locked,data:{entity:e,engine:data.sources.find(s=>s.id===data.entities.find(x=>x.id===e.origin?.entityId)?.sourceId)?.engine,locked:!!n?.locked,collapsed:!!n?.collapsed||fieldMode==='summary',fields:visible.fields as DesignField[],hiddenCount:visible.hidden.length,activeField,highlighted,open:inspectEntity,openField,toggle:collapse,action:nodeAction}};}),[draft,selectedIds,relatedIds,fieldMode,activeField,selectedEdge,data.sources,data.entities]);
 const edges=useMemo<Edge<DesignEdgeData>[]>(()=>{
  const legacy=draft.relationships.map(r=>{const sf=r.mappings?.[0]?.sourceFieldId,tf=r.mappings?.[0]?.targetFieldId,a=nodes.find(n=>n.id===r.sourceEntityId),b=nodes.find(n=>n.id===r.targetEntityId),self=r.sourceEntityId===r.targetEntityId;const right=self||!a||!b||b.position.x>=a.position.x;const side=right?'right':'left',other=right?'left':'right';return {id:r.id,source:r.sourceEntityId,target:r.targetEntityId,type:'design' as const,selected:selectedEdge===r.id,hidden:!!relatedIds&&(!relatedIds.has(r.sourceEntityId)||!relatedIds.has(r.targetEntityId)),sourceHandle:a?.data.fields.some(f=>f.id===sf)?`f:${sf}::${side}`:`summary::${side}`,targetHandle:b?.data.fields.some(f=>f.id===tf)?`f:${tf}::${other}`:`summary::${other}`,data:{name:r.name,composite:r.mappings?.length??0,self,showLabel:labels,kind:'LEGACY' as const}};});
  const joins=(draft.fusion?.joins??[]).map(j=>{const source=nodes.find(n=>n.id===j.leftEntityId),target=nodes.find(n=>n.id===j.rightEntityId),right=!source||!target||target.position.x>=source.position.x,from=right?'right':'left',to=right?'left':'right',leftField=j.pairs[0]?.leftFieldId,rightField=j.pairs[0]?.rightFieldId;return {id:j.id,source:j.leftEntityId,target:j.rightEntityId,type:'design' as const,selected:selectedEdge===j.id,sourceHandle:source?.data.fields.some(f=>f.id===leftField)?`f:${leftField}::${from}`:`summary::${from}`,targetHandle:target?.data.fields.some(f=>f.id===rightField)?`f:${rightField}::${to}`:`summary::${to}`,data:{name:`${j.joinType} JOIN`,composite:j.pairs.length,self:false,showLabel:labels,kind:'JOIN' as const}};});
  const mappings=(draft.fusion?.mappings??[]).map(m=>{const source=nodes.find(n=>n.id===m.sourceEntityId),target=nodes.find(n=>n.id===draft.outputEntityId);const right=!source||!target||target.position.x>=source.position.x;const from=right?'right':'left',to=right?'left':'right';return {id:m.id,source:m.sourceEntityId,target:draft.outputEntityId!,type:'design' as const,selected:selectedEdge===m.id,sourceHandle:source?.data.fields.some(f=>f.id===m.sourceFieldId)?`f:${m.sourceFieldId}::${from}`:`summary::${from}`,targetHandle:target?.data.fields.some(f=>f.id===m.targetFieldId)?`f:${m.targetFieldId}::${to}`:`summary::${to}`,data:{name:draft.entities.find(e=>e.id===draft.outputEntityId)?.fields.find(f=>f.id===m.targetFieldId)?.name||'字段映射',composite:1,self:false,showLabel:labels,kind:'MAP' as const}};});
  return [...legacy,...joins,...mappings];
 },[draft,nodes,labels,selectedEdge,relatedIds]);
 const onNodesChange=useCallback((changes:NodeChange<EntityFlowNode>[])=>{const positions=changes.filter(c=>c.type==='position'&&!draftRef.current.nodes.find(n=>n.entityId===c.id)?.locked);if(positions.length){const updated=applyNodeChanges(positions,nodes);mutate(c=>{for(const n of updated){const old=c.nodes.find(x=>x.entityId===n.id);if(old)old.position=n.position;}},false);}const selections=changes.filter(c=>c.type==='select');if(selections.length)setSelectedIds(prev=>applySelectionChanges(prev,selections));},[nodes,mutate]);
 const fit=()=>void flow.fitView({padding:.12,duration:250,maxZoom:1,minZoom:.2});
 const locate=(eid:string,fid?:string)=>{setFocus(false);setFocusId('');setSelected(eid);setSelectedIds([eid]);if(fid){setFieldMode('key');mutate(c=>{const index=c.nodes.findIndex(n=>n.entityId===eid);if(index>=0)c.nodes[index]=pinDesignField(c.nodes[index],fid);});openField(eid,fid);}const n=nodes.find(n=>n.id===eid);if(n)void flow.setCenter(n.position.x+NODE_WIDTH/2,n.position.y+(flow.getNode(eid)?.measured?.height??260)/2,{zoom:Math.max(.9,viewport.zoom),duration:250});};
  const newRelation=(connection?:Connection)=>{const now=new Date().toISOString();setRelationEdit({id:uuid(),workspaceId:resourceSessionScope(),snapshotId:'panshi-design',sourceEntityId:connection?.source??draft.entities[0]?.id??'',targetEntityId:connection?.target??draft.entities[1]?.id??'',mappings:[{sourceFieldId:parseDesignHandle(connection?.sourceHandle),targetFieldId:parseDesignHandle(connection?.targetHandle),comparisonRule:'exact'}],name:'业务关联',semanticType:'join',origin:'manual',reviewStatus:'confirmed',fingerprint:'',lifecycle:'current',verification:{status:'not_run'},targetsPerSource:{min:'unknown',max:'unknown',basis:'business'},sourcesPerTarget:{min:'unknown',max:'unknown',basis:'business'},createdAt:now,updatedAt:now});setFocus(false);};
  const removeSelectedEdge=()=>{if(!selectedEdge)return;modal.confirm({title:'删除当前设计连线？',onOk:()=>{mutate(c=>{c.relationships=c.relationships.filter(r=>r.id!==selectedEdge);if(c.fusion){c.fusion.joins=c.fusion.joins.filter(j=>j.id!==selectedEdge);c.fusion.mappings=c.fusion.mappings.filter(m=>m.id!==selectedEdge);}});setSelectedEdge('');setInspectorOpen(false);}});};
 const connectFusion=(connection:Connection)=>{
  const a=draftRef.current.entities.find(e=>e.id===connection.source),b=draftRef.current.entities.find(e=>e.id===connection.target);
  if(!draftRef.current.outputEntityId||!a||!b){newRelation(connection);return;}
  if((a.role==='SOURCE'&&b.role==='OUTPUT')||(a.role==='OUTPUT'&&b.role==='SOURCE')){
   const source=a.role==='SOURCE'?a:b,target=a.role==='OUTPUT'?a:b;
   const sourceFieldId=parseDesignHandle(a.role==='SOURCE'?connection.sourceHandle:connection.targetHandle);
   const targetFieldId=parseDesignHandle(a.role==='OUTPUT'?connection.sourceHandle:connection.targetHandle);
   if(!sourceFieldId||!targetFieldId){message.warning('请从来源字段端点连到 D 表的目标字段端点');return;}
   const previous=draftRef.current.fusion?.mappings.find(m=>m.targetFieldId===targetFieldId);
   setMappingEdit({id:previous?.id||uuid(),targetFieldId,sourceEntityId:source.id,sourceFieldId,transform:previous?.transform||'DIRECT'});
   setSelected(target.id);setInspectorOpen(true);return;
  }
  if(a.role==='SOURCE'&&b.role==='SOURCE'){
   const pair={leftFieldId:parseDesignHandle(connection.sourceHandle),rightFieldId:parseDesignHandle(connection.targetHandle)};
   const old=draftRef.current.fusion?.joins.find(j=>j.leftEntityId===a.id&&j.rightEntityId===b.id);
   setJoinEdit(old?{...old,pairs:pair.leftFieldId&&pair.rightFieldId&&!old.pairs.some(p=>p.leftFieldId===pair.leftFieldId&&p.rightFieldId===pair.rightFieldId)?[...old.pairs,pair]:old.pairs}:{id:uuid(),leftEntityId:a.id,rightEntityId:b.id,joinType:'LEFT',pairs:[pair],rightCardinality:'ONE',dedupe:'NONE'});
   return;
  }
  message.warning('请连接两张来源表以配置关联，或连接来源字段与目标表 D 字段以建立映射');
 };
 const openMappingForTarget=(fieldId:string)=>{const previous=draftRef.current.fusion?.mappings.find(m=>m.targetFieldId===fieldId),source=draftRef.current.entities.find(e=>e.role==='SOURCE');if(!source){message.warning('请先添加来源表');return;}setMappingEdit(previous?structuredClone(previous):{id:uuid(),targetFieldId:fieldId,sourceEntityId:source.id,sourceFieldId:source.fields[0]?.id||'',transform:'DIRECT'});};
 const addSourceFieldsToOutput=(sourceId:string,fieldIds:string[])=>{const source=draftRef.current.entities.find(e=>e.id===sourceId),target=draftRef.current.entities.find(e=>e.id===draftRef.current.outputEntityId);if(!source||!target||!fieldIds.length)return;let added=0;mutate(c=>{const output=c.entities.find(e=>e.id===target.id)!;c.fusion??={joins:[],mappings:[]};for(const fieldId of fieldIds){const field=source.fields.find(f=>f.id===fieldId);if(!field||c.fusion.mappings.some(m=>m.sourceEntityId===sourceId&&m.sourceFieldId===fieldId))continue;const targetFieldId=uuid();let base=/^[A-Za-z][A-Za-z0-9_]{0,62}$/.test(field.name)?field.name:'field_'+String(output.fields.length+1);let name=base,index=2;while(output.fields.some(f=>f.name.toLowerCase()===name.toLowerCase()))name=`${base.slice(0,58)}_${index++}`;output.fields.push({...structuredClone(field),id:targetFieldId,name,path:name,ordinal:output.fields.length,standard:undefined});c.fusion.mappings.push({id:uuid(),targetFieldId,sourceEntityId:sourceId,sourceFieldId:fieldId,transform:'DIRECT'});for(const [entityId,fid] of [[sourceId,fieldId],[target.id,targetFieldId]]){const node=c.nodes.find(n=>n.entityId===entityId);if(node)Object.assign(node,pinDesignField(node,fid));}added++;}});if(added)message.success(`已向目标表 D 加入 ${added} 个字段并建立映射`);else message.info('所选字段均已映射到目标表 D');};
 const addSourceFieldToOutput=(sourceId:string,fieldId:string)=>addSourceFieldsToOutput(sourceId,[fieldId]);
 const bulkSource=draft.entities.find(e=>e.id===bulkSourceId);
 const bulkFields=(bulkSource?.fields??[]).filter(f=>!(draft.fusion?.mappings??[]).some(m=>m.sourceEntityId===bulkSourceId&&m.sourceFieldId===f.id));
 const visibleBulkFields=bulkFields.filter(f=>(f.name+' '+(f.businessName??'')).toLowerCase().includes(bulkQuery.trim().toLowerCase()));
 const layout=async(direction:'RIGHT'|'DOWN'|'SELECTED'='RIGHT')=>{if(layoutBusy)return;const revision=seq.current;setLayoutBusy(true);const worker=new Worker(new URL('../../features/er/workers/layout.worker.ts',import.meta.url),{type:'module'});try{const heights=Object.fromEntries(nodes.map(n=>[n.id,flow.getNode(n.id)?.measured?.height??92+n.data.fields.length*30]));const positions=await new Promise<Record<string,{x:number;y:number}>>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('布局计算超时，保留当前布局')),12000);worker.onerror=()=>{clearTimeout(timer);reject(new Error('布局 Worker 加载失败，保留原位置'));};worker.onmessage=e=>{clearTimeout(timer);e.data.error?reject(new Error(e.data.error)):resolve(e.data.positions);};worker.postMessage({id:uuid(),direction:direction==='DOWN'?'DOWN':'RIGHT',children:nodes.map(n=>({id:n.id,width:NODE_WIDTH,height:heights[n.id]})),edges:edges.filter(e=>e.source!==e.target).map(e=>({id:e.id,sources:[e.source],targets:[e.target]}))});});if(seq.current!==revision){message.info('布局期间模型已改变，已丢弃旧布局结果');return;}const original=draftRef.current.nodes;const layoutNodes=original.map(n=>({...n,locked:n.locked||(direction==='SELECTED'&&!selectedIds.includes(n.entityId))}));const proposal=preserveLockedNodes(layoutNodes,positions,heights);mutate(c=>{c.nodes=proposal.map(n=>({...n,locked:original.find(o=>o.entityId===n.entityId)?.locked}));});setTimeout(fit,80);}catch(e){message.error(e instanceof Error?e.message:String(e));}finally{worker.terminate();setLayoutBusy(false);}};
 const reverseBusy=useRef(false);
 const deriveShared=async(eid:string,position?:{x:number;y:number})=>{const existing=draftRef.current.entities.find(e=>e.origin?.entityId===eid);if(existing){locate(existing.id);message.info('该快照已派生到当前模型，已定位');return;}if(reverseBusy.current)return;reverseBusy.current=true;try{await save();const previousIds=new Set(draftRef.current.entities.map(e=>e.id));const next=await act<LogicalModel>(`models/${id}/reverse`,{entityIds:[eid]},version.current);version.current=next.version;const c=contentOf(next);draftRef.current=c;setDraft(c);savedSequence.current=seq.current;setDirty(false);const added=c.entities.find(e=>!previousIds.has(e.id));if(added&&position)mutate(d=>{const n=d.nodes.find(x=>x.entityId===added.id);if(n)n.position=position;});if(added){setSelected(added.id);setSelectedIds([added.id]);}message.success('已将技术表加入画布作为只读来源');}catch(e){message.error(e instanceof Error?e.message:String(e));}finally{reverseBusy.current=false;}};
 const onDrop=(e:DragEvent)=>{e.preventDefault();const sourceId=e.dataTransfer.getData('application/panshi-shared'),designId=e.dataTransfer.getData('application/panshi-design'),position=flow.screenToFlowPosition({x:e.clientX,y:e.clientY});if(sourceId)void deriveShared(sourceId,position);else if(designId){if(!draftRef.current.nodes.find(n=>n.entityId===designId)?.locked)mutate(c=>{const n=c.nodes.find(x=>x.entityId===designId);if(n)n.position=position;});locate(designId);}};
 const addStandard=(st:Record<string,any>)=>{if(!current||current.reference||current.role==='SOURCE'){message.warning('请先选择目标输出表 D');return;}const native={id:uuid(),name:'field_'+uuid().slice(0,6),path:'',ordinal:current.fields.length,nativeType:st.type,typeFamily:st.type,nullable:'true',length:st.length??128,precision:18,scale:2,comment:st.definition} as DesignField;const f={...native,path:native.name,businessName:st.name,logicalType:logicalType(native),standard:{id:st.id,revisionId:st.publishedRevisionId}};mutate(c=>c.entities.find(e=>e.id===current.id)!.fields.push(f));};
 const searchResults=useMemo(()=>{const term=search.trim().toLowerCase();return draft.entities.flatMap(e=>[{id:e.id,eid:e.id,fid:'',name:e.displayName||e.name,detail:e.name},...e.fields.map(f=>({id:f.id,eid:e.id,fid:f.id,name:f.businessName||f.name,detail:`${e.displayName||e.name} / ${f.name}`}))]).filter(r=>!term||(r.name+' '+r.detail).toLowerCase().includes(term)).slice(0,80);},[draft.entities,search]);
 const chooseResult=(index:number)=>{const r=searchResults[index];if(!r)return;setSearchOpen(false);locate(r.eid,r.fid||undefined);};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const editing=isEditingTarget(e.target),blocked=hasBlockingLayer();if(e.code==='Space'&&!editing&&!blocked){e.preventDefault();setSpace(true);}if(e.key==='Escape'){const action=escapeAction({blocking:blocked,editing,panel:inspectorOpen,focused:!!focusId,presentation:focus});if(action==='presentation')setFocus(false);else if(action==='panel')setInspectorOpen(false);else if(action==='focus')setFocusId('');else if(action==='close')void close();return;}if(editing||blocked)return;const mod=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(mod&&key==='k'){e.preventDefault();setSearchOpen(true);setSearch('');setSearchIndex(0);}else if(mod&&key==='s'){e.preventDefault();void save().then(()=>message.success('模型已保存')).catch(e=>message.error(e.message));}else if(mod&&key==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(mod&&key==='y'){e.preventDefault();redo();}else if(!mod&&key==='f'){e.preventDefault();fit();}else if(!mod&&(e.key==='Delete'||e.key==='Backspace')){e.preventDefault();if(selectedEdge)removeSelectedEdge();else removeEntities(selectedIds);}};const up=(e:KeyboardEvent)=>{if(e.code==='Space')setSpace(false);};const blur=()=>setSpace(false);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};});
 const tool=(name:string,label:string,onClick:()=>void,disabled=false,active=false)=><Tooltip title={label}><Button aria-label={label} type="text" disabled={disabled} className={active?'ps-tool-active':''} icon={<Icon name={name} size={18}/>} onClick={onClick}/></Tooltip>;
 const displaySettings=<Space direction="vertical"><Checkbox checked={grid} onChange={e=>setGrid(e.target.checked)}>显示网格</Checkbox><Checkbox checked={snap} onChange={e=>setSnap(e.target.checked)}>网格吸附</Checkbox><Checkbox checked={labels} onChange={e=>setLabels(e.target.checked)}>关系标签</Checkbox><Checkbox checked={minimap} onChange={e=>setMinimap(e.target.checked)}>小地图</Checkbox></Space>;
 if(!model)return <div className="ps-designer"><Empty description="模型不存在，或已从工作区删除"/><Button onClick={()=>nav('/resource/models')}>返回模型列表</Button></div>;
 return <div className={`ps-designer ${focus?'focus':''}`} role="dialog" aria-modal="true" aria-label="全屏逻辑模型设计器" tabIndex={-1} ref={root}>
  <header className="ps-designer-header"><div className="ps-designer-brand"><CenterSwitcher center="panshi" collapsed beforeLeave={beforeSwitch}/></div><div className="ps-design-name"><strong>{model.name}</strong><small>{busy?'保存中…':saveError?'尚未保存，请处理保存异常':dirty?'有未保存修改':`已保存 ${timeText(savedAt)}`}</small></div><Tag color="green">{model.frozen.length?`冻结 v${model.frozen.at(-1)!.number}`:'草稿'}</Tag><div className="ps-designer-actions">
    <Button className="ps-text-action optional" onClick={()=>{try{validateModel(draftRef.current);message.success('结构校验通过，未执行数据验证');}catch(e){message.error(e instanceof Error?e.message:String(e));}}}>校验模型</Button>
    <Button className="ps-text-action" onClick={()=>modal.confirm({title:'冻结当前设计版本',content:'先保存设计草稿，再建立不可变修订。冻结不等于物化建表。',onOk:async()=>{await save();await act(`models/${id}/freeze`,{note:`冻结设计 · ${new Date().toLocaleDateString()}`},version.current);version.current++;message.success('设计版本已冻结');}})}>冻结版本</Button>
    <Button className="ps-text-action" onClick={async()=>{try{await save();nav('/resource/materializations?model='+id);}catch(e){message.error(String(e));}}}>物化建表</Button>
    {tool('search','搜索表、字段（Ctrl / ⌘ + K）',()=>{setSearchOpen(true);setSearch('');setSearchIndex(0);})}
    <Button type="primary" icon={<SaveOutlined/>} loading={busy} onClick={()=>void save().then(()=>message.success('模型已保存')).catch(e=>message.error(e.message))}>保存</Button>
    <Tooltip title="切换主题"><Button aria-label="切换主题" icon={dark?<SunOutlined/>:<MoonOutlined/>} onClick={onTheme}/></Tooltip>
    <Tooltip title={focus?'退出专注模式':'专注画布'}><Button aria-label={focus?'退出专注模式':'专注画布'} icon={focus?<FullscreenExitOutlined/>:<FullscreenOutlined/>} onClick={()=>setFocus(!focus)}/></Tooltip>
    <Button aria-label="关闭设计器" icon={<CloseOutlined/>} onClick={()=>void close()}/>
  </div></header>
  {conflict&&<Alert type="warning" showIcon title={saveError||'当前草稿尚未保存'} action={<Space><Button onClick={()=>saveFile(JSON.stringify(draftRef.current,null,2),model.code+'-draft.json')}>导出草稿</Button><Button onClick={()=>{const c=contentOf(model);setDraft(c);draftRef.current=c;version.current=model.version;savedSequence.current=seq.current;setDirty(false);setConflict(false);setSaveError('');}}>载入已保存版本</Button></Space>}/>} 
  <div className="ps-designer-body">
   {!focus&&libraryOpen&&<><aside className="ps-designer-library" style={{width:libraryWidth}}><div className="ps-library-header"><span>对象库</span>{tool('close','收起对象库',()=>setLibraryOpen(false))}</div><Tabs activeKey={leftTab} onChange={setLeftTab} items={[{key:'entities',label:'模型实体'},{key:'standards',label:'标准字段'},{key:'shared',label:'共享结构'}]}/><Input prefix={<SearchOutlined/>} value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索表、字段或标准" allowClear/>
    {leftTab==='entities'&&<><div className="ps-library-actions"><Button block icon={<PlusOutlined/>} onClick={()=>draft.outputEntityId?setReverse(true):setEntityEdit({id:''})}>{draft.outputEntityId?'添加来源表':'新建设计实体'}</Button><Button type="link" onClick={()=>setRefOpen(true)}>引用冻结模型</Button></div>{draft.entities.filter(e=>(e.name+(e.displayName??'')+e.fields.map(f=>f.name+f.businessName).join(' ')).toLowerCase().includes(q.toLowerCase())).map(e=><button draggable onDragStart={ev=>{ev.dataTransfer.setData('application/panshi-design',e.id);ev.dataTransfer.effectAllowed='move';}} className={`ps-library-entity ${selectedIds.includes(e.id)?'selected':''}`} key={e.id} onClick={()=>locate(e.id)} onDoubleClick={()=>inspectEntity(e.id)}><PsIcon name="table"/><div><strong>{e.displayName||e.name}</strong><small>{e.name} · {e.fields.length} 字段{e.reference?' · 只读参照':''}</small></div></button>)}</>}
    {leftTab==='standards'&&<><p className="ps-muted">选择设计实体后，点击标准添加字段。</p>{data.standards.filter(st=>st.status==='PUBLISHED'&&(st.name+st.code).toLowerCase().includes(q.toLowerCase())).map(st=><button key={st.id} className="ps-standard-choice" onClick={()=>addStandard(st)}><span><strong>{st.name}</strong><small>{st.type} · {st.code}</small></span><PlusOutlined/></button>)}</>}
    {leftTab==='shared'&&<><p className="ps-muted">拖入或双击技术表，添加为只读来源表；在画布上连线完成融合和字段映射。</p><Button block onClick={()=>setReverse(true)}>搜索全部技术表并派生</Button><small className="ps-muted">下方为已加载结构，更多数据表请通过上方搜索选择。</small>{data.entities.filter(e=>(e.name+(e.displayName??'')).toLowerCase().includes(q.toLowerCase())).map(e=><button draggable onDragStart={ev=>{ev.dataTransfer.setData('application/panshi-shared',e.id);ev.dataTransfer.effectAllowed='copy';}} className="ps-library-entity" key={e.id} onDoubleClick={()=>void deriveShared(e.id)} title="拖入画布或双击派生"><SourceIcon engine={data.sources.find(s=>s.id===e.sourceId)?.engine} small/><div><strong>{e.displayName||e.name}</strong><small>{e.name}</small></div></button>)}</>}
   </aside><ResizeHandle side="library" width={libraryWidth} onChange={setLibraryWidth}/></>}
   <main className="ps-design-canvas">
    <div className="ps-canvas-tools" role="toolbar" aria-label="画布工具栏">
     {!libraryOpen&&tool('panels','展开对象库',()=>setLibraryOpen(true))}
     <div className="ps-tool-group">{tool('cursor','选择工具',()=>setPanMode(false),false,!panMode)}{tool('hand','平移工具（或按住空格）',()=>setPanMode(true),false,panMode)}</div><span className="ps-tool-divider"/>
     <Dropdown trigger={['click']} menu={{items:[{key:'RIGHT',label:'从左到右'},{key:'DOWN',label:'从上到下'},{key:'SELECTED',label:`仅整理选中实体（${selectedIds.length}）`,disabled:!selectedIds.length}],onClick:({key})=>void layout(key as 'RIGHT'|'DOWN'|'SELECTED')}}><Button type="text" icon={<Icon name="layout" size={18}/>} loading={layoutBusy} disabled={!nodes.length}>自动布局 <Icon name="down" size={12}/></Button></Dropdown>
     <Dropdown trigger={['click']} menu={{selectable:true,selectedKeys:[fieldMode],items:[{key:'key',label:'关键字段'},{key:'all',label:'全部字段（节点最多 12 行）'},{key:'summary',label:'仅表摘要'}],onClick:({key})=>setFieldMode(key as FieldMode)}}><Button className="ps-field-mode" type="text" icon={<Icon name="table" size={17}/>}>{fieldMode==='key'?'关键字段':fieldMode==='all'?'全部字段':'仅表摘要'} <Icon name="down" size={12}/></Button></Dropdown>
     <Popover trigger="click" content={displaySettings} title="画布显示设置">{tool('settings','显示设置',()=>{})}</Popover><span className="ps-tool-divider"/>
     {tool('undo','撤销（Ctrl / ⌘ + Z）',undo,!history.length)}{tool('redo','重做（Ctrl / ⌘ + Shift + Z）',redo,!future.length)}
      <div className="ps-toolbar-tail"><Button type="text" icon={<PlusOutlined/>} onClick={()=>draft.outputEntityId?setReverse(true):setEntityEdit({id:''})}>{draft.outputEntityId?'添加来源表':'实体'}</Button><Button type="text" disabled={!draft.entities.length} icon={<Icon name="link" size={17}/>} onClick={()=>draft.outputEntityId?setJoinEdit({id:uuid(),leftEntityId:draft.fusion?.baseEntityId||draft.entities.find(e=>e.role==='SOURCE')?.id||'',rightEntityId:'',joinType:'LEFT',pairs:[{leftFieldId:'',rightFieldId:''}],rightCardinality:'ONE',dedupe:'NONE'}):newRelation()}>{draft.outputEntityId?'关联来源':'关系'}</Button>{draft.outputEntityId&&<Button type="text" icon={<Icon name="table" size={17}/>} onClick={()=>setMappingEdit({id:uuid(),sourceEntityId:draft.entities.find(e=>e.role==='SOURCE')?.id||'',sourceFieldId:'',targetFieldId:'',transform:'DIRECT'})}>字段映射</Button>}{tool('info','操作帮助',()=>setHelpOpen(true))}</div>
    </div>
    <div className="ps-canvas-workspace" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect=e.dataTransfer.types.includes('application/panshi-shared')?'copy':'move';}} onDrop={onDrop}>
     <ReactFlow<EntityFlowNode,Edge<DesignEdgeData>> nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} colorMode={dark?'dark':'light'} onNodesChange={onNodesChange} connectionMode={ConnectionMode.Loose} {...canvasInteractionProps(panMode,space)} snapToGrid={snap} deleteKeyCode={null}
       onNodeDragStart={()=>setHistory(h=>[...h.slice(-49),structuredClone(draftRef.current)])} onSelectionDragStart={()=>setHistory(h=>[...h.slice(-49),structuredClone(draftRef.current)])}
       onNodeClick={(e,n)=>{if(!e.shiftKey){setActiveField('');inspectEntity(n.id);}}}
       onNodeDoubleClick={(_e,n)=>inspectEntity(n.id)}
        onEdgeClick={(_e,edge)=>{setSelectedEdge(edge.id);setSelected('');setSelectedIds([]);setActiveField('');setInspectorOpen(true);}}
       onPaneClick={()=>{setSelected('');setSelectedIds([]);setSelectedEdge('');setInspectorOpen(false);setActiveField('');}}
        onConnect={connectFusion} fitView={!initialView} defaultViewport={initialView} fitViewOptions={{padding:.14,maxZoom:1,minZoom:.2}}
       onMoveEnd={(_e,v)=>{try{localStorage.setItem(viewportKey,JSON.stringify(v));}catch{/* View preference only; business saving is independent. */}}} attributionPosition="bottom-right">
      {grid&&<Background color={dark?'#344d3c':'#d8e7dc'} gap={20} size={1}/>}
      {minimap&&<MiniMap position="bottom-right" style={{width:156,height:100,bottom:22,right:10,background:'var(--ps-surface)'}} maskColor="var(--minimap-mask)" nodeColor="var(--minimap-node)" pannable zoomable/>}
     </ReactFlow>
     {selectedIds.length>1&&<div className="ps-selection-tools" role="toolbar" aria-label="选中实体操作"><strong>已选 {selectedIds.length} 项</strong><Dropdown trigger={['click']} menu={{items:[{key:'left',label:'左对齐'},{key:'top',label:'顶对齐'},{key:'horizontal',label:'水平等距分布',disabled:selectedIds.filter(s=>!draft.nodes.find(n=>n.entityId===s)?.locked).length<3}],onClick:({key})=>{const positions=alignNodes(draft.nodes,selectedIds,key as 'left'|'top'|'horizontal');if(Object.keys(positions).length)mutate(c=>{for(const n of c.nodes)if(positions[n.entityId])n.position=positions[n.entityId];});else message.info('至少选择两个未固定实体，等距分布需要三个。');}}}><Button type="text" size="small" icon={<Icon name="layout" size={17}/>}>对齐</Button></Dropdown>{tool('lock','固定选中实体',()=>mutate(c=>c.nodes.forEach(n=>{if(selectedIds.includes(n.entityId))n.locked=true;})))}{tool('unlock','取消固定选中实体',()=>mutate(c=>c.nodes.forEach(n=>{if(selectedIds.includes(n.entityId))n.locked=false;})))}<Button type="text" danger size="small" onClick={()=>removeEntities(selectedIds)}>删除</Button></div>}
     {focusId&&<div className="ps-focus-banner">仅看相关关系 <Button type="link" size="small" onClick={()=>setFocusId('')}>显示全部</Button></div>}
     {draft.entities.length===0&&<div className="ps-canvas-empty"><h2>从业务实体开始设计</h2><p>新建实体，或从对象库拖入共享技术快照。</p><Space><Button type="primary" onClick={()=>setEntityEdit({id:''})}>新建实体</Button><Button onClick={()=>setReverse(true)}>逆向派生</Button></Space></div>}
     <div className="ps-zoom-tools">{tool('minus','缩小',()=>void flow.zoomOut({duration:150}))}<button className="ps-zoom-value" title="恢复 100%" onClick={()=>void flow.setViewport({...viewport,zoom:1},{duration:180})}>{Math.round(viewport.zoom*100)}%</button>{tool('plus','放大',()=>void flow.zoomIn({duration:150}))}{tool('fit','适应画布（F）',fit)}</div>
    </div>
     <footer className="ps-canvas-status"><span>{draft.outputEntityId?`${draft.entities.filter(e=>e.role==='SOURCE').length} 张来源表 · 1 张输出表 · ${draft.fusion?.joins.length||0} 条关联 · ${draft.fusion?.mappings.length||0} 条映射`:`${draft.entities.length} 个实体 · ${draft.relationships.length} 条关系`}</span><span>{panMode||space?'平移工具':'选择工具'} · {draft.outputEntityId?'来源字段连到 D 字段建立映射 · 来源表相连配置融合':'点击实体或字段查看属性'}</span></footer>
   </main>
    {!focus&&inspectorOpen&&(current||currentRelation||currentJoin||currentMapping)&&<><ResizeHandle side="inspector" width={inspectorWidth} onChange={setInspectorWidth}/><aside className="ps-designer-inspector" style={{width:inspectorWidth}}><header><h3>{currentJoin?'来源关联':currentMapping?'字段映射':currentRelation?'关系详情':'实体与字段属性'}</h3><Button type="text" aria-label="关闭属性" icon={<CloseOutlined/>} onClick={()=>setInspectorOpen(false)}/></header><div className="ps-inspector-body">
    {currentJoin&&<><h2>{currentJoin.joinType} JOIN</h2><p>{draft.entities.find(e=>e.id===currentJoin.leftEntityId)?.name} → {draft.entities.find(e=>e.id===currentJoin.rightEntityId)?.name}</p>{currentJoin.pairs.map((pair,i)=><div className="ps-relation-pair" key={i}><span>{draft.entities.find(e=>e.id===currentJoin.leftEntityId)?.fields.find(f=>f.id===pair.leftFieldId)?.name}</span><span>=</span><span>{draft.entities.find(e=>e.id===currentJoin.rightEntityId)?.fields.find(f=>f.id===pair.rightFieldId)?.name}</span></div>)}<Space style={{marginTop:16}}><Button onClick={()=>setJoinEdit(structuredClone(currentJoin))}>编辑关联</Button><Button danger onClick={()=>modal.confirm({title:'删除来源关联？',onOk:()=>{mutate(c=>{if(c.fusion)c.fusion.joins=c.fusion.joins.filter(j=>j.id!==currentJoin.id);});setSelectedEdge('');setInspectorOpen(false);}})}>删除</Button></Space></>}
    {currentMapping&&<><h2>目标字段映射</h2><p>{draft.entities.find(e=>e.id===currentMapping.sourceEntityId)?.fields.find(f=>f.id===currentMapping.sourceFieldId)?.name} → {draft.entities.find(e=>e.id===draft.outputEntityId)?.fields.find(f=>f.id===currentMapping.targetFieldId)?.name}</p><Tag color="cyan">{currentMapping.transform}</Tag><Space style={{marginTop:16}}><Button onClick={()=>setMappingEdit(structuredClone(currentMapping))}>编辑映射</Button><Button danger onClick={()=>modal.confirm({title:'解除字段映射？',onOk:()=>{mutate(c=>{if(c.fusion)c.fusion.mappings=c.fusion.mappings.filter(m=>m.id!==currentMapping.id);});setSelectedEdge('');setInspectorOpen(false);}})}>解除</Button></Space></>}
    {currentRelation?<><h2>{currentRelation.name}</h2><Tag color="green">业务逻辑关联</Tag><p>{currentRelation.description||'暂无业务说明'}</p><h3>完整字段映射</h3>{currentRelation.mappings?.map((p,i)=><div className="ps-relation-pair" key={i}><span>{draft.entities.find(e=>e.id===currentRelation.sourceEntityId)?.fields.find(f=>f.id===p.sourceFieldId)?.name||p.sourceFieldId}</span><span>→</span><span>{draft.entities.find(e=>e.id===currentRelation.targetEntityId)?.fields.find(f=>f.id===p.targetFieldId)?.name||p.targetFieldId}</span></div>)}<Button icon={<EditOutlined/>} onClick={()=>setRelationEdit(structuredClone(currentRelation))}>编辑关系</Button><Alert style={{marginTop:20}} type="info" title="只维护设计关系，不创建数据库外键。"/></>:current&&<><h2>{current.displayName||current.name}</h2><p className="ps-muted">{current.name} {current.reference&&<Tag>只读参照</Tag>}{current.role==='SOURCE'&&<Tag color="blue">来源技术快照</Tag>}{current.role==='OUTPUT'&&<Tag color="cyan">唯一输出表 D</Tag>}</p><Space wrap><Button disabled={!!current.reference||current.role==='SOURCE'} icon={<EditOutlined/>} onClick={()=>setEntityEdit(current)}>编辑实体</Button>{current.role==='SOURCE'&&<Button type={draft.fusion?.baseEntityId===current.id?'primary':'default'} onClick={()=>mutate(c=>{c.fusion??={joins:[],mappings:[]};c.fusion.baseEntityId=current.id;})}>{draft.fusion?.baseEntityId===current.id?'当前驱动表':'设为驱动表'}</Button>}<Button icon={nodes.find(n=>n.id===current.id)?.data.locked?<UnlockOutlined/>:<LockOutlined/>} onClick={()=>nodeAction(current.id,'lock')}>{nodes.find(n=>n.id===current.id)?.data.locked?'解除固定':'固定位置'}</Button></Space><p style={{marginTop:14}}>{current.comment||'暂无业务说明'}</p><h3>{current.role==='SOURCE'?'来源字段':'目标字段设计'} {current.role==='SOURCE'?<Button type="link" onClick={()=>{setBulkSourceId(current.id);setBulkFieldIds([]);setBulkQuery('');}}>批量选择字段加入 D</Button>:<Button type="link" disabled={!!current.reference} onClick={()=>setFieldEdit({id:''})}>添加字段</Button>}</h3>
    {current.role === 'OUTPUT' && current.fields.length > 0 && <Button danger type="link" onClick={() => modal.confirm({ title: '清空目标表 D 的字段与映射？', content: '可重新从来源表批量选取字段；此操作只修改草稿，可撤销。', onOk: () => mutate(c => { const output = c.entities.find(e => e.id === c.outputEntityId); if (!output) return; output.fields = []; output.keys = []; if (c.fusion) c.fusion.mappings = []; c.relationships = c.relationships.filter(r => r.sourceEntityId !== output.id && r.targetEntityId !== output.id); const node = c.nodes.find(n => n.entityId === output.id); if (node) node.pinnedFieldIds = []; }) })}>清空 D 字段，重新选取</Button>}
    {current.fields.map((f,i)=><div className={`ps-editable-field ${activeField===f.id?'is-active':''}`} id={`ps-inspector-field-${f.id}`} key={f.id}><button disabled={!!current.reference||current.role==='SOURCE'} onClick={()=>setFieldEdit(f)}><strong>{f.businessName||f.name}</strong><small>{f.name} · {f.logicalType}</small></button><Space size={4}>{current.role==='SOURCE'&&<Button size="small" type="link" onClick={()=>addSourceFieldToOutput(current.id,f.id)}>加入 D</Button>}{current.role==='OUTPUT'&&draft.entities.some(e=>e.role==='SOURCE')&&<Button size="small" type="link" onClick={()=>openMappingForTarget(f.id)}>{draft.fusion?.mappings.some(m=>m.targetFieldId===f.id)?'修改映射':'建立映射'}</Button>}<Button size="small" type="text" aria-label="上移字段" disabled={i===0||!!current.reference||current.role==='SOURCE'} icon={<ArrowUpOutlined/>} onClick={()=>mutate(c=>{const e=c.entities.find(e=>e.id===current.id)!;[e.fields[i-1],e.fields[i]]=[e.fields[i],e.fields[i-1]];e.fields.forEach((f,n)=>f.ordinal=n);})}/><Button size="small" type="text" aria-label="下移字段" disabled={i===current.fields.length-1||!!current.reference||current.role==='SOURCE'} icon={<ArrowDownOutlined/>} onClick={()=>mutate(c=>{const e=c.entities.find(e=>e.id===current.id)!;[e.fields[i+1],e.fields[i]]=[e.fields[i],e.fields[i+1]];e.fields.forEach((f,n)=>f.ordinal=n);})}/></Space></div>)}<Button danger type="text" icon={<DeleteOutlined/>} onClick={()=>onDeleteEntity(current.id)}>删除此草稿设计实体</Button><Alert type="info" showIcon title="只修改设计稿" description="来源技术快照和已冻结版本保持不变。"/></>}
   </div></aside></>}
  </div>
  <Modal open={searchOpen} title="查找模型实体与字段" onCancel={()=>setSearchOpen(false)} footer={null} width={680} afterOpenChange={open=>{if(open)document.getElementById('ps-model-search')?.focus();}}><Input id="ps-model-search" autoFocus prefix={<SearchOutlined/>} value={search} placeholder="输入表名、字段名或业务名称" onChange={e=>{setSearch(e.target.value);setSearchIndex(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setSearchIndex(n=>Math.min(n+1,searchResults.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setSearchIndex(n=>Math.max(0,n-1));}if(e.key==='Enter')chooseResult(searchIndex);}}/><div className="ps-search-results">{searchResults.map((r,i)=><button className={`ps-search-result ${searchIndex===i?'ps-tool-active':''}`} key={r.id} onClick={()=>chooseResult(i)}><PsIcon name={r.fid?'field':'table'}/><span><strong>{r.name}</strong><small>{r.detail}</small></span></button>)}{!searchResults.length&&<Empty description="没有匹配的实体或字段"/>}</div></Modal>
  <Modal open={helpOpen} title="模型工作台操作" onCancel={()=>setHelpOpen(false)} footer={<Button type="primary" onClick={()=>setHelpOpen(false)}>知道了</Button>} width={680}><p>拖动表头移动实体，点击字段查看属性。将来源表字段连到目标表 D 的字段可建立映射；连接两张来源表配置关联条件。也可在右侧把来源字段直接加入 D。</p><div className="ps-shortcut-grid">{[['搜索表 / 字段','Ctrl / ⌘ + K'],['保存设计','Ctrl / ⌘ + S'],['撤销 / 重做','Ctrl + Z / Shift + Z'],['平移画布','按住 Space'],['多选实体','Shift + 单击'],['适应画布','F'],['删除设计对象','Delete'],['关闭弹层 / 返回','Esc']].map(([label,key])=><p key={label}><span>{label}</span><kbd>{key}</kbd></p>)}</div><Alert style={{marginTop:20}} type="info" title="资源中心保留新增字段、依标建模、冻结版本与物化等设计能力。删除的是设计稿，不是万象技术快照。"/></Modal>
 <EditDialog open={!!entityEdit} title={entityEdit?.id ? '实体属性' : '新建设计实体'} initial={entityEdit ?? undefined} onClose={() => setEntityEdit(null)} onSave={async (v) => { const eid = entityEdit?.id || uuid(); if (draft.entities.some(e => e.id !== eid && e.name.toUpperCase() === v.name.toUpperCase()))
        throw new Error('模型中已有同名技术实体'); mutate(c => { const old = c.entities.find(e => e.id === eid); if (old)
        Object.assign(old, { name: v.name, displayName: v.displayName, comment: v.comment, grain: v.grain });
    else {
        c.entities.push({ id: eid, sourceId: 'panshi-design', kind: 'table', name: v.name, displayName: v.displayName, comment: v.comment, grain: v.grain || '', fields: [], keys: [] });
        const center = flow.screenToFlowPosition({ x: innerWidth / 2, y: innerHeight / 2 });
        c.nodes.push({ entityId: eid, position: { x: center.x - 100, y: center.y - 80 } });
    } }); setSelected(eid); setSelectedIds([eid]); setInspectorOpen(true); }}><Form.Item name="displayName" label="实体业务名称" rules={required}><Input /></Form.Item><Form.Item name="name" label="技术名称" rules={[...required, { pattern: /^[A-Za-z][A-Za-z0-9_]{0,62}$/, message: '字母开头，仅字母数字下划线，最多63字符' }]}><Input placeholder="dim_customer"/></Form.Item><Form.Item name="grain" label="业务粒度"><Input placeholder="一行代表一个客户 / 一次业务事件"/></Form.Item><Form.Item name="comment" label="业务说明"><Input.TextArea rows={3}/></Form.Item></EditDialog>
 <EditDialog open={!!fieldEdit && !!current} title={fieldEdit?.id ? '编辑设计字段' : '新增设计字段'} form={fieldForm} initial={fieldEdit ? { ...fieldEdit, logicalType: 'logicalType' in fieldEdit ? fieldEdit.logicalType : 'String', length: 'length' in fieldEdit ? fieldEdit.length : 128, precision: 'precision' in fieldEdit ? fieldEdit.precision : 18, scale: 'scale' in fieldEdit ? fieldEdit.scale : 2, nullable: 'nullable' in fieldEdit ? fieldEdit.nullable : 'true', primary: !!current?.keys?.some(k => k.kind === 'primary' && k.fieldIds.includes(fieldEdit.id)), standardId: 'standard' in fieldEdit ? fieldEdit.standard?.id : undefined } : undefined} onClose={() => setFieldEdit(null)} onSave={async (v) => { if (!current)
        return; const fid = fieldEdit?.id || uuid(); if (current.fields.some(f => f.id !== fid && f.name.toLowerCase() === v.name.toLowerCase()))
        throw new Error('当前实体已有同名字段'); const type = v.logicalType; if (type === 'String' && !(v.length > 0 && v.length <= 4000))
        throw new Error('字符长度须在1–4000之间'); if (type === 'Decimal' && (!(v.precision > 0 && v.precision <= 38) || v.scale < 0 || v.scale > v.precision))
        throw new Error('请检查精度和小数位'); const st = data.standards.find(s => s.id === v.standardId); mutate(c => { const e = c.entities.find(e => e.id === current.id)!; const f: DesignField = { id: fid, name: v.name, path: v.name, ordinal: e.fields.findIndex(f => f.id === fid) < 0 ? e.fields.length : e.fields.findIndex(f => f.id === fid), businessName: v.businessName || v.name, logicalType: type, typeFamily: fieldFamily(type), nativeType: type, nullable: v.nullable || 'true', length: v.length, precision: v.precision, scale: v.scale, comment: v.comment, standard: st ? { id: st.id, revisionId: st.publishedRevisionId } : undefined }; const old = e.fields.findIndex(f => f.id === fid); if (old < 0)
        e.fields.push(f);
    else
        e.fields[old] = f; const ids = (e.keys?.find(k => k.kind === 'primary')?.fieldIds ?? []).filter(id => id !== fid); if (v.primary)
        ids.push(fid); e.keys = (e.keys ?? []).filter(k => k.kind !== 'primary'); if (ids.length)
        e.keys.push({ id: 'pk-' + e.id, kind: 'primary', fieldIds: ids, enforced: 'unknown', scope: 'full' }); }); }} width={700}><div className="ps-form-two"><Form.Item name="businessName" label="业务名称" rules={required}><Input /></Form.Item><Form.Item name="name" label="技术字段名" rules={[...required, { pattern: /^[A-Za-z][A-Za-z0-9_]{0,62}$/, message: '字母开头，仅字母数字下划线' }]}><Input /></Form.Item><Form.Item name="logicalType" label="逻辑类型" rules={required}><Select options={logicalTypes.map(t => ({ value: t, label: t }))}/></Form.Item><Form.Item name="nullable" label="是否可空"><Select options={[{ value: 'true', label: '可空' }, { value: 'false', label: '不可空' }]}/></Form.Item>{logical === 'String' && <Form.Item name="length" label="字符长度"><InputNumber min={1} max={4000}/></Form.Item>}{logical === 'Decimal' && <><Form.Item name="precision" label="精度"><InputNumber min={1} max={38}/></Form.Item><Form.Item name="scale" label="小数位"><InputNumber min={0} max={38}/></Form.Item></>}</div><Form.Item name="primary" valuePropName="checked"><Checkbox>加入设计主键（多个成员形成联合主键）</Checkbox></Form.Item><Form.Item name="standardId" label="绑定已发布标准"><Select allowClear showSearch optionFilterProp="label" options={data.standards.filter(st => st.status === 'PUBLISHED').map(st => ({ value: st.id, label: st.name + ' · ' + st.code }))}/></Form.Item><Form.Item name="comment" label="字段说明"><Input.TextArea rows={2}/></Form.Item>{fieldEdit?.id && <Button danger type="text" onClick={() => modal.confirm({ title: '删除设计字段？', content: '涉及该字段的草稿关系和键成员也将移除，历史版本不变。', onOk: () => { mutate(c => { const e = c.entities.find(e => e.id === current!.id)!; e.fields = e.fields.filter(f => f.id !== fieldEdit.id); e.keys = e.keys?.map(k => ({ ...k, fieldIds: k.fieldIds.filter(id => id !== fieldEdit.id) })).filter(k => k.fieldIds.length); c.relationships = c.relationships.filter(r => !r.mappings?.some(p => p.sourceFieldId === fieldEdit.id || p.targetFieldId === fieldEdit.id)); if(c.fusion)c.fusion.mappings=c.fusion.mappings.filter(m=>m.targetFieldId!==fieldEdit.id); }); setFieldEdit(null); } })}>删除字段</Button>}</EditDialog>
  <RelationDialog relation={relationEdit} draft={draft} onClose={() => setRelationEdit(null)} onSave={r => { mutate(c => { const i = c.relationships.findIndex(x => x.id === r.id); if (i < 0)
        c.relationships.push(r);
    else
        c.relationships[i] = r; }); setRelationEdit(null); }} onDelete={rid => { mutate(c => { c.relationships = c.relationships.filter(r => r.id !== rid); }); setRelationEdit(null); }}/>
  <FusionJoinDialog value={joinEdit} content={draft} onClose={()=>setJoinEdit(null)} onSave={join=>{mutate(c=>{c.fusion??={joins:[],mappings:[]};const index=c.fusion.joins.findIndex(j=>j.id===join.id);if(index<0)c.fusion.joins.push(join);else c.fusion.joins[index]=join;});setJoinEdit(null);setSelectedEdge(join.id);setInspectorOpen(true);}}/>
  <FusionMappingDialog value={mappingEdit} content={draft} onClose={()=>setMappingEdit(null)} onSave={mapping=>{mutate(c=>{c.fusion??={joins:[],mappings:[]};c.fusion.mappings=c.fusion.mappings.filter(m=>m.id!==mapping.id&&m.targetFieldId!==mapping.targetFieldId);c.fusion.mappings.push(mapping);for(const [entityId,fieldId] of [[mapping.sourceEntityId,mapping.sourceFieldId],[c.outputEntityId,mapping.targetFieldId]]){const n=c.nodes.find(n=>n.entityId===entityId);if(n&&entityId&&fieldId)Object.assign(n,pinDesignField(n,fieldId));}});setMappingEdit(null);setSelectedEdge(mapping.id);setInspectorOpen(true);}}/>
 <Modal open={!!bulkSourceId} title={`画布选字段 · ${bulkSource?.displayName||bulkSource?.name||''}`} width={650} onCancel={()=>setBulkSourceId('')} okText={`加入 D 并建立 ${bulkFieldIds.length} 条映射`} okButtonProps={{disabled:!bulkFieldIds.length}} onOk={()=>{addSourceFieldsToOutput(bulkSourceId,bulkFieldIds);setBulkSourceId('');}}>
   <p className="ps-muted">在当前融合画布中选择来源字段，加入目标表 D 并建立逐字段映射。已映射字段不再重复显示。</p>
   <Input allowClear prefix={<SearchOutlined/>} placeholder="搜索字段名称" value={bulkQuery} onChange={e=>setBulkQuery(e.target.value)}/>
   <div style={{display:'flex',justifyContent:'space-between',margin:'12px 0'}}><span>可选 {bulkFields.length} 个字段</span><Button type="link" onClick={()=>setBulkFieldIds(ids=>Array.from(new Set([...ids,...visibleBulkFields.map(f=>f.id)])))}>选择当前结果</Button></div>
   <div style={{maxHeight:300,overflowY:'auto',display:'grid',gap:10}}>{visibleBulkFields.map(field=><Checkbox key={field.id} checked={bulkFieldIds.includes(field.id)} onChange={e=>setBulkFieldIds(ids=>e.target.checked?[...ids,field.id]:ids.filter(id=>id!==field.id))}>{field.businessName||field.name} <span className="ps-muted">{field.name} · {field.logicalType}</span></Checkbox>)}{!visibleBulkFields.length&&<Empty description="没有可选择的字段"/>}</div>
 </Modal>
 <Modal open={reverse} title="添加来源技术表到融合画布" width={760} onCancel={() => setReverse(false)} okText="添加来源表" onOk={async () => { try {
        if (!reverseIds.length)
            throw new Error('请选择至少一个共享实体');
        await save();
        const next = await act<LogicalModel>(`models/${id}/reverse`, { entityIds: reverseIds }, version.current);
        version.current = next.version;
        const c = contentOf(next);
        setDraft(c);
        draftRef.current = c;
        setDirty(false);
        setReverse(false);
        setReverseIds([]);
    }
    catch (e) {
        message.error(e instanceof Error ? e.message : String(e));
    } }}><p className="ps-muted">选择一张或多张已采集技术表。来源结构只读；字段取舍、关联和映射请直接在当前画布完成。</p><TechnicalEntitySelect mode="multiple" style={{ width: '100%', marginTop: 20 }} value={reverseIds} onChange={setReverseIds}/></Modal>
 <Modal open={refOpen} title="引用模型冻结版本" onCancel={() => setRefOpen(false)} okText="添加只读参照" onOk={async () => { try {
        if (!refRev)
            throw new Error('请选择冻结版本');
        await save();
        const m = await act<LogicalModel>(`models/${id}/reference`, { modelId: refId, revisionId: refRev }, version.current);
        version.current = m.version;
        setDraft(contentOf(m));
        draftRef.current = contentOf(m);
        setDirty(false);
        setRefOpen(false);
    }
    catch (e) {
        message.error(e instanceof Error ? e.message : String(e));
    } }}><Alert type="info" title="引用节点只读，不进入本模型物化；更新来源版本不会自动覆盖。"/><Select style={{ width: '100%', marginTop: 16 }} placeholder="来源模型" value={refId || undefined} onChange={v => { setRefId(v); setRefRev(''); }} options={data.state.models.filter(m => m.id !== id && m.frozen.length).map(m => ({ value: m.id, label: m.name }))}/><Select style={{ width: '100%', marginTop: 16 }} placeholder="冻结版本" value={refRev || undefined} onChange={setRefRev} options={data.state.models.find(m => m.id === refId)?.frozen.map(r => ({ value: r.id, label: `v${r.number} · ${r.note}` }))}/></Modal></div>;
}
function RelationDialog({ relation, draft, onClose, onSave, onDelete }: {
    relation: Relationship | null;
    draft: ModelContent;
    onClose: () => void;
    onSave: (r: Relationship) => void;
    onDelete: (id: string) => void;
}) { const [value, setValue] = useState<Relationship | null>(null), { message, modal } = App.useApp(); useEffect(() => setValue(relation ? structuredClone(relation) : null), [relation]); const source = draft.entities.find(e => e.id === value?.sourceEntityId), target = draft.entities.find(e => e.id === value?.targetEntityId); const pair = (i: number, v: Partial<FieldMapping>) => { if (value)
    setValue({ ...value, mappings: value.mappings?.map((p, n) => n === i ? { ...p, ...v } : p) }); }; return <Modal open={!!relation} title="设计关系与复合映射" width={850} maskClosable={false} onCancel={onClose} okText="保存设计关系" onOk={() => { if (!value)
    return; const errors = validateDesignRelation(value, draft, draft.relationships, value.id); if (errors.length) {
    message.error(errors.join('；'));
    return;
} onSave({ ...value, reviewStatus: 'confirmed', fingerprint: fingerprint(value), updatedAt: new Date().toISOString() }); }}>{value && <Form layout="vertical" className="ps-form"><Form.Item label="关系名称"><Input value={value.name} onChange={e => setValue({ ...value, name: e.target.value })}/></Form.Item><div className="ps-form-two"><Form.Item label="引用方"><Select value={value.sourceEntityId} onChange={v => setValue({ ...value, sourceEntityId: v, mappings: [{ sourceFieldId: '', targetFieldId: '' }] })} options={draft.entities.map(e => ({ value: e.id, label: e.displayName || e.name }))}/></Form.Item><Form.Item label="被引用方"><Select value={value.targetEntityId} onChange={v => setValue({ ...value, targetEntityId: v, mappings: [{ sourceFieldId: '', targetFieldId: '' }] })} options={draft.entities.map(e => ({ value: e.id, label: e.displayName || e.name }))}/></Form.Item></div><Form.Item label="关系语义"><Select value={value.semanticType} onChange={v => setValue({ ...value, semanticType: v })} options={[{ value: 'join', label: '一般业务关联（不声明目标唯一）' }, { value: 'reference', label: '唯一目标引用（检查完整候选键）' }]}/></Form.Item><label>字段映射 · 所有映射作为同一条关系保存</label>{value.mappings?.map((p, i) => <div key={i} className="ps-mapping-row"><Select placeholder="引用字段" value={p.sourceFieldId || undefined} onChange={v => pair(i, { sourceFieldId: v })} options={source?.fields.map(f => ({ value: f.id, label: f.name }))}/><span>→</span><Select placeholder="目标字段" value={p.targetFieldId || undefined} onChange={v => pair(i, { targetFieldId: v })} options={target?.fields.map(f => ({ value: f.id, label: f.name }))}/><Button danger type="text" disabled={value.mappings!.length === 1} icon={<DeleteOutlined />} aria-label="移除映射" onClick={() => setValue({ ...value, mappings: value.mappings!.filter((_p, n) => n !== i) })}/></div>)}<Button type="dashed" icon={<PlusOutlined />} onClick={() => setValue({ ...value, mappings: [...value.mappings ?? [], { sourceFieldId: '', targetFieldId: '', comparisonRule: 'exact' }] })}>添加复合字段映射</Button><Form.Item style={{ marginTop: 16 }} label="业务说明"><Input.TextArea value={value.description ?? ''} onChange={e => setValue({ ...value, description: e.target.value })}/></Form.Item><Alert type="info" title="设计关系不会创建数据库外键，基数未知时不自动推断为一对多。"/>{draft.relationships.some(r => r.id === value.id) && <Button danger type="text" onClick={() => modal.confirm({ title: '删除这条设计关系？', onOk: () => onDelete(value.id) })}>删除整条关系</Button>}</Form>}</Modal>; }
