import { useEffect, useState } from 'react';
import { Alert, App, Button, Checkbox, Drawer, Empty, Form, Select, Space, Tabs, Tag } from 'antd';
import { FileAddOutlined } from '@ant-design/icons';
import { useSearchParams } from 'react-router-dom';
import { useResource } from '../services/context';
import { type Row } from '../../services/api';
import { Hero, NameCell, PTable, StateTag, useCommand } from '../components/ui';
import type { DesignField } from '../domain/types';
import { logicalType } from '../domain/rules';
import { goCenter } from '../../shared/centers/navigation';
import { standardizationModel } from './modelSelection';

export { ModelsPage, ModelPreview } from './ModelManagementPage';
export { ModelLogsPage } from './ModelLogsPage';
export function StandardizationPage(){const {data,act,refresh}=useResource(),s=data.state,[params,setParams]=useSearchParams(),{run,busy}=useCommand(),{message}=App.useApp();const [tab,setTab]=useState('fields'),[target,setTarget]=useState<{e:string;f:DesignField}|null>(null),[standard,setStandard]=useState(''),[apply,setApply]=useState(false);const activeModels=s.models.filter(x=>x.state==='ACTIVE');const requestedModelId=params.get('model');const m=standardizationModel(s.models,requestedModelId);const itemSets=m?s.itemSets.filter(x=>x.modelId===m.id):[];const fields=m?.entities.flatMap(e=>e.fields.map(f=>({...f,entity:e})))??[];const standards=data.standards.filter(st=>st.status==='PUBLISHED'&&st.publishedRevisionId);const suggestions=target?standards.map(st=>{let score=0;if(st.name===target.f.businessName)score+=55;else if((target.f.businessName+target.f.name).includes(st.name))score+=30;if(logicalType({...target.f,typeFamily:st.type})===target.f.logicalType)score+=30;if(st.length===target.f.length)score+=15;return {...st,score} as Row&{score:number};}).filter(st=>st.score>=30).sort((a,b)=>b.score-a.score):[];
 useEffect(()=>{if(requestedModelId&&!activeModels.some(x=>x.id===requestedModelId))setParams(m?{model:m.id}:{},{replace:true});},[requestedModelId,m?.id,setParams]);
 return <><Hero page="standardization" actions={<Button type="primary" disabled={!m} icon={<FileAddOutlined/>} onClick={()=>void run(async()=>{if(!m)return;await act(`models/${m.id}/items`,{},m.version);setTab('items');},'数据项集已生成')}>生成数据项集</Button>}/><div className="ps-model-controls"><Select aria-label="选择有效模型" showSearch optionFilterProp="label" placeholder="暂无可用模型" value={m?.id} onChange={v=>{setTarget(null);setParams({model:v});}} options={activeModels.map(x=>({value:x.id,label:`${x.name} · ${x.code}`}))}/><span className="ps-muted">{fields.filter(f=>f.standard).length} / {fields.length} 字段已绑定 · 引用标准修订，不直接修改技术表</span></div><Tabs activeKey={tab} onChange={setTab} items={[{key:'fields',label:'字段对标',children:<PTable rows={fields} onRefresh={refresh} emptyTitle="暂无可标准化的模型字段" emptyDescription="请先创建或选择有效模型。" columns={[{title:'设计字段',render:(_,f)=><NameCell name={f.businessName||f.name} code={`${f.entity.name}.${f.name}`}/>},{title:'逻辑类型',dataIndex:'logicalType'},{title:'绑定标准',render:(_,f)=>f.standard?<NameCell name={data.standards.find(s=>s.id===f.standard!.id)?.name??'标准已失效'} code={data.standards.find(s=>s.id===f.standard!.id)?.publishedRevisionId===f.standard.revisionId?'已发布修订':'引用版本需复核'}/>:<Tag>未绑定</Tag>},{title:'操作',render:(_,f)=><Button type="link" disabled={!!f.entity.reference} onClick={()=>{setTarget({e:f.entity.id,f});setStandard(f.standard?.id??'');setApply(false);}}>对标／查看推荐</Button>}]}/>},{key:'items',label:`数据项集 (${itemSets.length})`,children:<PTable rows={itemSets} columns={[{title:'数据项集',dataIndex:'name'},{title:'字段数',render:(_,v)=>v.items.length},{title:'状态',render:(_,v)=><StateTag state={v.state}/>},{title:'候选受理情况',render:(_,v)=>`${v.items.filter(i=>i.candidateId).length} 个草稿候选`},{title:'操作',render:(_,v)=><Space><Button type="link" disabled={v.state==='SUBMITTED'} onClick={()=>void run(()=>act(`itemsets/${v.id}/submit`,{},v.version),'已送入万象数据元草稿，尚未发布')}>提交标准候选</Button><Button type="link" onClick={()=>goCenter('wanxiang','/governance/standards/elements')}>到万象处理</Button></Space>}]}/>}]} />
 <Drawer open={!!target} width={540} title="字段标准化" onClose={()=>setTarget(null)} footer={<div className="ps-dialog-footer"><Button onClick={()=>setTarget(null)}>取消</Button><Button type="primary" loading={busy} disabled={!standard} onClick={()=>void run(async()=>{if(!m||!target)return;await act(`models/${m.id}/bind`,{entityId:target.e,fieldId:target.f.id,standardId:standard,apply},m.version);setTarget(null);})}>确认绑定</Button></div>}>{target&&<><NameCell name={target.f.businessName} code={target.f.name}/><p>类型：{target.f.logicalType} · 长度：{target.f.length??'—'}</p><Alert type="info" showIcon title="推荐分仅用于排序，需人工确认" description="依据名称、逻辑类型与长度计算，不代表业务正确概率。"/><h3>规则推荐</h3>{suggestions.length?suggestions.map(st=><button className={`ps-standard-choice ${standard===st.id?'selected':''}`} key={st.id} onClick={()=>setStandard(st.id)}><span><strong>{st.name}</strong><small>{st.type} / {st.length??'—'} · 已发布版本</small></span><b>{st.score} 分</b></button>):<Empty description="未找到满足规则的候选，可手动搜索标准"/>}<Form layout="vertical"><Form.Item label="选择已发布标准"><Select value={standard||undefined} onChange={setStandard} showSearch optionFilterProp="label" options={standards.map(st=>({value:st.id,label:`${st.name} / ${st.code}`}))}/></Form.Item><Checkbox checked={apply} onChange={e=>setApply(e.target.checked)}>同时按该标准更新此设计字段的名称、逻辑类型和长度</Checkbox><p className="ps-muted">不影响来源技术字段或已经冻结的模型版本。</p><Button type="link" onClick={()=>{message.info('将打开万象的已发布数据标准');goCenter('wanxiang','/governance/standards/elements');}}>查看万象标准定义</Button></Form></>}</Drawer></>;}
