import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {test} from 'node:test';
const require=createRequire(import.meta.url);
const {parse,babelParse}=require('vue/compiler-sfc');
const source=fs.readFileSync(new URL('../../data-elements/db/migrations/resources/registration-review-metrics-20260926/pages/register-confirm.vue',import.meta.url),'utf8');
const script=parse(source).descriptor.scriptSetup.content;
const nodes=babelParse(script,{sourceType:'module',plugins:['typescript']}).program.body;
const definitions=new Map();for(const n of nodes){if(n.type==='FunctionDeclaration')definitions.set(n.id.name,n);if(n.type==='VariableDeclaration')for(const d of n.declarations)if(d.id.name)definitions.set(d.id.name,n);}
function install(scope,names){for(const name of names){const n=definitions.get(name);assert.ok(n,name);vm.runInNewContext(script.slice(n.start,n.end)+'\nthis.'+name+'='+name+';',scope);}}
function context(rows=[]){const scope={console,computed:fn=>({get value(){return fn();}}),realtimeTables:{value:rows},physicalTableTotal:{value:7177},fieldMap:{value:{}},catalogsByTableKey:{value:new Map()},tableChangeSnapshot:{value:null},tableChangeLoading:{value:false},tableChangeError:{value:''}};install(scope,['firstNonEmpty','tableChineseName','tableRows','uniqueTables','isCompletedTableRegistration','annotatedTables','tables','catalogFor','governanceConfig','fieldsFor','timeRoleLabels','normalizeTimeRoles','timeRolesFor','timeRoleFieldFor','missingRequiredTimeRoles','businessLogTables','timestampRequiredTables','timeRoleCompleteTableCount','standardMatchedFieldCount','markedCoreCount','annotationTypeTotal','physicalTableCount','isPendingBusinessType','uncertainTables','completedRegistrationTableCount','pendingRegistrationTableCount','applyTableChangeSnapshot','tableChangeKind','tableChangeSummary']);for(const row of rows)scope.catalogsByTableKey.value.set('id:'+row.tid,row);return scope;}
function row(tid,businessType,config={}){return {tid,tableName:'OWNER.T_'+tid,annotated:1,assetStatus:2,businessType,fieldGovernanceConfig:JSON.stringify(config)};}
test('all annotation types count, rather than only dictionary/business/log',()=>{const s=context([row('1','字典表'),row('2','业务表'),row('3','日志表'),row('4','过程表'),row('5','备份表')]);assert.equal(s.markedCoreCount.value,5);assert.equal(s.annotationTypeTotal.value,5);});
test('annotated and completed status remain independent',()=>{const a=row('1','业务表');a.assetStatus=0;const b=row('2','过程表');const s=context([a,b]);assert.equal(s.markedCoreCount.value,2);assert.equal(s.completedRegistrationTableCount.value,1);});
test('time and uniform format metrics read saved config before lazy field loading',()=>{const a=row('1','业务表',{fields:[{columnName:'CARD_NO',standardField:'SFZH'},{columnName:'CREATE_TIME',timeRoles:['timestamp','business'],standardField:'DATETIME'}]});const s=context([a]);assert.equal(s.timeRoleCompleteTableCount.value,1);assert.equal(s.standardMatchedFieldCount.value,2);assert.deepEqual(Object.keys(s.fieldMap.value),[]);});
test('direct timestamp column is sufficient; dictionary does not require time',()=>{const a=row('1','业务表');a.timestampField='UPDATE_TIME';const d=row('2','字典表');const s=context([a,d]);assert.equal(s.timeRoleCompleteTableCount.value,1);assert.equal(s.timestampRequiredTables.value.length,1);assert.equal(s.missingRequiredTimeRoles(d).length,0);});
test('7177 snapshot total and 301 saved registrations imply 6876 pending, not live owner total',()=>{const rows=Array.from({length:301},(_,i)=>row(String(i),'业务表'));const s=context(rows);assert.equal(s.physicalTableCount.value,7177);assert.equal(s.pendingRegistrationTableCount.value,6876);assert.equal(s.markedCoreCount.value,301);});
test('302 unmatched collection rows are not mislabeled physical deletions or modifications',()=>{const s=context();s.applyTableChangeSnapshot({deletedCount:302,addedCount:1});assert.equal(s.tableChangeSummary.value.total,302);assert.equal(s.tableChangeSummary.value.deleted,0);assert.equal(s.tableChangeSummary.value.modified,0);assert.match(s.tableChangeSummary.value.hint,/待核对 302/);});
test('review uses same persisted snapshot/status as step two and never triggers reExplore',()=>{const n=definitions.get('refreshReviewSummary');const code=script.slice(n.start,n.end);assert.match(code,/tables\/snapshot/);assert.match(code,/annotatedOnly: true, includeGovernance: true/);assert.doesNotMatch(code,/tables\/preview/);const c=definitions.get('refreshTableChangeSummary');assert.match(script.slice(c.start,c.end),/collection\/status/);assert.doesNotMatch(script.slice(c.start,c.end),/reExplore/);assert.match(source,/snapshotOnly: true/);});
if(process.env.REGISTRATION_REVIEW_ROWS){test('published actual tenant rows produce the confirmed review metrics',()=>{const rows=JSON.parse(fs.readFileSync(process.env.REGISTRATION_REVIEW_ROWS,'utf8'));const s=context(rows);assert.equal(s.markedCoreCount.value,301);assert.equal(s.completedRegistrationTableCount.value,301);assert.equal(s.pendingRegistrationTableCount.value,6876);assert.equal(s.timeRoleCompleteTableCount.value,105);assert.equal(s.timestampRequiredTables.value.length,105);assert.equal(s.standardMatchedFieldCount.value,471);});}
