import { enrichSeed } from './premium-seed.ts';
import { platformTitle } from './branding.ts';
import type { Database, Base, Domain, Settings, User } from './types.ts';
export function createSeed(now = new Date()): Database {
    const time = now.toISOString();
    const base = (id: string, name: string, domain: Domain = 'workforce', status = 'enabled'): Base => ({ id, name, domain, status, createdAt: time, updatedAt: time, version: 1 });
    const orgNames = ['星河集团', '数字化中心', '产品研发部', '应用平台部', '数据管理部', '综合管理部', '财务管理部', '华东分公司', '客户服务部', '华南分公司', '运营支持部', '信息安全部'];
    const parents = [null, 'o0', 'o1', 'o1', 'o1', 'o0', 'o0', 'o0', 'o7', 'o0', 'o9', 'o1'];
    const orgs = orgNames.map((n, i) => ({ ...base(`o${i}`, n), code: `ORG${String(i + 1).padStart(3, '0')}`, parentId: parents[i], leader: ['陈知远', '林若安', '周予宁'][i % 3], line: i % 2 ? '数字化' : '综合管理' }));
    const names = ['林若安', '陈知远', '周予宁', '许清和', '沈书言', '江子墨', '顾星辰', '宋景行', '夏予初', '陆予白', '程之遥', '叶清川', '唐思远', '韩云舟', '苏语桐', '秦知夏', '赵明澈', '何以宁', '吴安然', '郑亦凡', '方景明', '魏知南', '罗清越', '谢予恒', '彭星野', '萧予言', '姚清淮', '白若川', '许言蹊', '孟星河', '田远洲', '高予晨', '胡嘉宁', '邵言清', '蒋书禾', '杜知遇'];
    const users: User[] = names.map((name, i) => ({ ...base(`u${i + 1}`, name, 'workforce', i === 7 || i === 21 ? 'disabled' : i === 28 ? 'pending' : 'enabled'), account: `user${String(i + 1).padStart(3, '0')}`, email: `user${i + 1}@example.com`, phone: `1380000${String(i + 1).padStart(4, '0')}`, orgId: `o${1 + i % 11}`, post: ['产品经理', '研发工程师', '数据专员', '部门负责人'][i % 4], kind: 'person', locked: i === 5 || i === 18, appointments: [{ orgId: `o${1 + i % 11}`, post: ['产品经理', '研发工程师', '数据专员', '部门负责人'][i % 4], primary: true }], verified: true, history: [{ time, text: '由身份中心创建账号并建立主职任职' }] }));
    users.unshift({ ...base('u-admin', '平台管理员'), account: 'admin', email: 'admin@example.com', phone: '13800009999', orgId: 'o1', post: '平台管理', kind: 'admin', locked: false, appointments: [{ orgId: 'o1', post: '平台管理', primary: true }], verified: true, history: [{ time, text: '平台管理账号，不具有业务应用访问权限' }] });
    for (let i = 0; i < 15; i++)
        users.push({ ...base(`p${i + 1}`, names[(i + 7) % 36], 'public', i === 9 ? 'disabled' : 'enabled'), account: `citizen${String(i + 1).padStart(3, '0')}`, email: `citizen${i + 1}@example.org`, phone: `1390000${String(i + 1).padStart(4, '0')}`, orgId: '', post: '', kind: 'citizen', locked: false, appointments: [], verified: i % 4 !== 0, history: [{ time, text: '通过统一注册入口创建账户' }] });
    const appNames = ['万象数据治理', '协同办公平台', '数据资产中心', '项目管理系统', '财务共享平台', '统一服务门户', '运营分析平台', '知识管理平台', '人事服务平台', '便民服务平台', '企业服务平台', '统一办事大厅'];
    const apps = appNames.map((name, i) => ({ ...base(`a${i + 1}`, name, i < 9 ? 'workforce' : 'public', i === 6 ? 'disabled' : i === 8 ? 'pending' : 'enabled'), code: ['data-governance', 'office', 'data-assets', 'projects', 'finance', 'portal', 'analytics', 'knowledge', 'human-resources', 'citizen', 'business', 'service'][i], group: i < 3 ? '数据服务' : i < 6 ? '协同办公' : i < 9 ? '业务系统' : '公众服务', description: ['集中管理数据资产与治理业务', '打通身份体系，协同业务流程', '为业务提供安全、统一的访问入口'][i % 3], protocol: 'OIDC', environment: 'production', homepage: `https://app${i + 1}.example.com`, redirectUris: `https://app${i + 1}.example.com/auth/callback`, logoutUri: `https://app${i + 1}.example.com/logout/callback`, owner: names[i], clientId: `iam_${String(i + 1).padStart(4, '0')}_web`, clientType: i % 2 === 0 ? 'confidential' as const : 'public' as const, mfa: i % 3 === 0, accessTtl: 900, scopes: ['openid', 'profile', 'email'], secretVersion: 1 }));
    const resources = apps.flatMap(a => [{ ...base(`${a.id}-res1`, '工作台', a.domain), appId: a.id, parentId: null, code: `${a.code}:dashboard:view`, type: 'menu' as const, path: '/dashboard', method: '' }, { ...base(`${a.id}-res2`, '业务管理', a.domain), appId: a.id, parentId: null, code: `${a.code}:records:view`, type: 'menu' as const, path: '/records', method: '' }, { ...base(`${a.id}-res3`, '新增记录', a.domain), appId: a.id, parentId: `${a.id}-res2`, code: `${a.code}:records:create`, type: 'button' as const, path: '', method: '' }, { ...base(`${a.id}-res4`, '导出记录', a.domain), appId: a.id, parentId: `${a.id}-res2`, code: `${a.code}:records:export`, type: 'api' as const, path: '/api/records/export', method: 'POST' }]);
    const roles = apps.flatMap(a => [{ ...base(`${a.id}-r1`, '业务查看者', a.domain), appId: a.id, code: 'viewer', description: '查看已授权的业务页面，不包含编辑和导出', resourceIds: [`${a.id}-res1`, `${a.id}-res2`] }, { ...base(`${a.id}-r2`, '业务维护者', a.domain), appId: a.id, code: 'editor', description: '在业务应用中维护记录，按业务范围操作', resourceIds: [`${a.id}-res1`, `${a.id}-res2`, `${a.id}-res3`] }]);
    const groups = [{ ...base('g1', '数据业务协同组'), description: '数据管理人员常用应用与角色的组合', userIds: ['u1', 'u2', 'u3', 'u4'], items: [{ appId: 'a1', roleIds: ['a1-r1'] }, { appId: 'a3', roleIds: ['a3-r2'] }] }, { ...base('g2', '办公基础权限'), description: '新入职人员的基础办公应用', userIds: ['u3', 'u5', 'u6', 'u9', 'u10'], items: [{ appId: 'a2', roleIds: ['a2-r1'] }, { appId: 'a6', roleIds: ['a6-r1'] }] }, { ...base('g3', '项目负责人'), description: '跨应用协作与项目维护', userIds: ['u11', 'u12'], items: [{ appId: 'a4', roleIds: ['a4-r2'] }, { appId: 'a8', roleIds: ['a8-r1'] }] }];
    const past = new Date(now.getTime() - 30 * 86400000).toISOString();
    const grants = Array.from({ length: 26 }, (_, i) => ({ ...base(`gr${i + 1}`, `应用访问授权${i + 1}`), source: 'user' as const, subjectId: `u${1 + i % 20}`, appId: `a${1 + i % 8}`, roleIds: [`a${1 + i % 8}-r${i % 3 === 0 ? 2 : 1}`], includeChildren: false, startsAt: past, expiresAt: i === 5 ? new Date(now.getTime() - 86400000).toISOString() : null, reason: '业务岗位需要' }));
    const mixed: Database['grants'] = [...grants, { ...base('gr-org1', '数字化中心基础权限'), source: 'org', subjectId: 'o1', appId: 'a2', roleIds: ['a2-r1'], includeChildren: true, startsAt: past, expiresAt: null, reason: '数字化中心统一办公' }, { ...base('gr-org2', '集团服务门户'), source: 'org', subjectId: 'o0', appId: 'a6', roleIds: ['a6-r1'], includeChildren: true, startsAt: past, expiresAt: null, reason: '全员门户访问' }];
    for (const g of groups)
        for (const item of g.items)
            mixed.push({ ...base(`gr-${g.id}-${item.appId}`, g.name), source: 'group', subjectId: g.id, appId: item.appId, roleIds: item.roleIds, includeChildren: false, startsAt: past, expiresAt: null, reason: '权限组关联' });
    for (let i = 0; i < 12; i++)
        mixed.push({ ...base(`pgr${i}`, '公众应用访问', 'public'), source: 'user', subjectId: `p${i + 1}`, appId: `a${10 + i % 3}`, roleIds: [`a${10 + i % 3}-r1`], includeChildren: false, startsAt: past, expiresAt: null, reason: '公众服务访问资格' });
    const syncConfigs = apps.slice(0, 5).map((a, i) => ({ ...base(`sc${i + 1}`, `${a.name}同步`), appId: a.id, endpoint: `https://app${i + 1}.example.com/api/identity/sync`, mode: i % 2 ? 'manual' : 'realtime', orgIds: ['o0'], entities: ['user', 'org'], mapping: 'userId → externalId\nname → displayName\norgId → departmentId', timeout: 30 }));
    const tasks: Database['tasks'] = syncConfigs.slice(0, 3).map((c, i) => ({ ...base(`task${i + 1}`, `${c.name} · 全量任务`, 'workforce', i === 1 ? 'partial' : 'success'), configId: c.id, appId: c.appId, mode: 'full', progress: 100, attempt: 1, items: users.filter(u => u.domain === 'workforce' && u.kind !== 'admin').slice(0, 16).map((u, j) => ({ id: u.id, name: u.name, type: 'user' as const, status: i === 1 && j % 7 === 0 ? 'failed' as const : 'success' as const, reason: i === 1 && j % 7 === 0 ? '下游请求超时（HTTP 504）' : '' })) }));
    const logs: Database['logs'] = Array.from({ length: 245 }, (_, i) => { const when = new Date(now.getTime() - (i % 14) * 86400000 - (i % 23) * 3600000 - (i % 50) * 60000).toISOString(); const domain: Domain = i % 6 === 0 ? 'public' : 'workforce'; const app = domain === 'public' ? apps[9 + i % 3] : apps[i % 9]; return { ...base(`log${i}`, `${i % 4 === 0 ? '操作' : '登录'}事件`, domain), createdAt: when, updatedAt: when, type: (i % 11 === 0 ? 'api' : i % 4 === 0 ? 'operation' : 'login') as Database['logs'][number]['type'], actor: domain === 'public' ? `citizen${String(1 + i % 15).padStart(3, '0')}` : `user${String(1 + i % 36).padStart(3, '0')}`, module: i % 4 === 0 ? '授权管理' : '统一认证', action: i % 11 === 0 ? '查询身份' : i % 4 === 0 ? '调整应用授权' : '账号密码登录', target: app.name, result: i % 17 === 0 ? '失败' : '成功', ip: `192.0.2.${1 + i % 200}`, appId: app.id, traceId: `trace_${String(i + 1).padStart(8, '0')}`, before: i % 4 === 0 ? '未授权' : '—', after: i % 4 === 0 ? '已分配业务查看角色' : '—' }; }).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    const catalog: Database['catalog'] = [
        ...['数据服务', '协同办公', '业务系统', '公众服务'].map((n, i) => ({ ...base(`cat-group${i}`, n, i === 3 ? 'public' : 'workforce'), category: 'app-group', code: `group-${i}`, description: '应用分组', parentId: '', appId: '', orgId: '', userId: '', memberIds: [], permissions: [], value: '', expiresAt: '', subjectType: '' })),
        ...['数字化', '综合管理', '财务条线'].map((n, i) => ({ ...base(`line${i}`, n), category: 'line', code: `line-${i}`, description: '支持机构条线归属与继承', parentId: '', appId: '', orgId: 'o0', userId: '', memberIds: [], permissions: [], value: '', expiresAt: '', subjectType: '' })),
        ...['部门负责人', '研发工程师', '数据专员', '产品经理'].map((n, i) => ({ ...base(`dict${i}`, n), category: 'dictionary', code: `post-${i}`, description: '职务岗位字典', parentId: '', appId: '', orgId: '', userId: '', memberIds: [], permissions: [], value: '岗位', expiresAt: '', subjectType: '' })),
        ...(['workforce', 'public'] as Domain[]).flatMap(d => ['平台管理员', '审计查看者', '应用管理员', '机构管理员'].map((n, i) => ({ ...base(`${d}-sysrole${i}`, n, d), category: 'system-role', code: ['admin', 'auditor', 'appmanager', 'orgadmin'][i], description: ['维护平台功能与应用授权', '只读查询登录与操作审计', '仅管理已授权应用', '管理指定机构及下级人员'][i], parentId: '', appId: i === 2 ? 'a1' : '', orgId: i === 3 ? 'o1' : '', userId: '', memberIds: [], permissions: i === 1 ? ['audit:read'] : ['read', 'write'], value: '', expiresAt: '', subjectType: '' }))),
        ...(['workforce', 'public'] as Domain[]).map(d => ({ ...base(`${d}-admin`, '平台管理员', d), category: 'admin', code: 'admin', description: '平台管理账号', parentId: '', appId: '', orgId: 'o0', userId: 'u-admin', memberIds: [], permissions: ['admin'], value: '', expiresAt: '', subjectType: '' })),
        { ...base('delegate1', '数字化中心管理员'), category: 'delegate', code: 'delegate-digit', description: '仅维护数字化中心及下级机构', parentId: '', appId: '', orgId: 'o1', userId: 'u2', memberIds: [], permissions: ['users:write', 'orgs:write'], value: '包含下级', expiresAt: '', subjectType: '' },
        { ...base('field1', '员工编号'), category: 'extension', code: 'employee_no', description: '用户扩展属性', parentId: '', appId: '', orgId: '', userId: '', memberIds: [], permissions: [], value: '文本', expiresAt: '', subjectType: '用户' },
        { ...base('api1', '读取用户基本信息'), category: 'api-grant', code: 'users:read', description: '最小字段读取权限', parentId: '', appId: 'a1', orgId: '', userId: '', memberIds: [], permissions: ['users:read'], value: '', expiresAt: '', subjectType: 'app' },
        { ...base('api2', '读取组织机构'), category: 'api-grant', code: 'orgs:read', description: '授权人员查询机构', parentId: '', appId: '', orgId: 'o1', userId: 'u2', memberIds: [], permissions: ['orgs:read'], value: '', expiresAt: '', subjectType: 'user' }
    ];
    const setting: Settings = { title: platformTitle, subtitle: '统一身份 · 安全访问 · 高效协同', logoUrl: '', minLength: 12, lockThreshold: 5, lockMinutes: 30, forceChange: true, mfaRequired: true, passwordDays: 0, passwordBlacklist: 'password\n123456\nadmin', accessTtl: 900, refreshTtl: 28800, idleMinutes: 30, singleLogout: true, allowConcurrent: false, encryptionEnabled: true, encryptionPolicy: '由统一密钥管理服务维护字段保护策略', maskedFields: ['phone', 'email'], apiWhitelist: '', ipBlacklist: '', apiRateLimit: 600 };
    const legalEntities = Array.from({ length: 8 }, (_, i) => ({ ...base(`legal${i + 1}`, ['星河科技服务有限公司', '云栖数字技术有限公司', '青禾企业管理有限公司', '远川信息咨询有限公司', '启明软件服务有限公司', '北辰创新服务有限公司', '映川科技有限公司', '明川技术有限公司'][i], 'public', i === 5 ? 'disabled' : 'enabled'), code: `ENT-${String(i + 1).padStart(4, '0')}`, contact: users.find(u => u.id === `p${i + 1}`)?.name || '', contactId: `p${i + 1}`, phone: `1390000${String(i + 1).padStart(4, '0')}`, verified: i % 3 !== 0, subAccountIds: [`p${i + 1}`, `p${i + 2}`] }));
    return enrichSeed({ schema: 1, users, orgs, apps, roles, resources, groups, grants: mixed, syncConfigs, tasks, logs, catalog, legalEntities, settings: { workforce: { ...setting }, public: { ...setting } } }, now);
}
