import type { GraphData } from "./types";

export const DEFAULT_GRAPH_DATA: GraphData = {
  nodes: [
    {
      id: "citizen",
      nameCn: "公民",
      nameEn: "CITIZEN",
      color: "#1677ff",
      icon: "person",
      remark: "人员关系同行/同住关联表",
      fields: [
        {
          id: "f1",
          fieldNameEn: "ZJHM",
          fieldNameCn: "证件号码",
          fieldType: "VARCHAR",
          fieldLength: 32,
          isPrimaryKey: true,
          isRelationField: false,
        },
        {
          id: "f2",
          fieldNameEn: "XM",
          fieldNameCn: "姓名",
          fieldType: "VARCHAR",
          fieldLength: 64,
          isPrimaryKey: false,
          isRelationField: false,
        },
        {
          id: "f3",
          fieldNameEn: "TXXB",
          fieldNameCn: "同行/同住性别",
          fieldType: "VARCHAR",
          fieldLength: 16,
          isPrimaryKey: false,
          isRelationField: true,
        },
      ],
    },
    {
      id: "property",
      nameCn: "房产",
      nameEn: "PROPERTY",
      color: "#fa8c16",
      icon: "home",
      fields: [
        {
          id: "f4",
          fieldNameEn: "FCZH",
          fieldNameCn: "房产证号",
          fieldType: "VARCHAR",
          fieldLength: 64,
          isPrimaryKey: true,
          isRelationField: false,
        },
        {
          id: "f5",
          fieldNameEn: "FCDZ",
          fieldNameCn: "房产地址",
          fieldType: "VARCHAR",
          fieldLength: 200,
          isPrimaryKey: false,
          isRelationField: false,
        },
      ],
    },
    {
      id: "company",
      nameCn: "企业",
      nameEn: "ENTERPRISE",
      color: "#722ed1",
      icon: "business",
      fields: [
        {
          id: "f6",
          fieldNameEn: "TYSHXYDM",
          fieldNameCn: "统一社会信用代码",
          fieldType: "VARCHAR",
          fieldLength: 18,
          isPrimaryKey: true,
          isRelationField: false,
        },
        {
          id: "f7",
          fieldNameEn: "QYMC",
          fieldNameCn: "企业名称",
          fieldType: "VARCHAR",
          fieldLength: 200,
          isPrimaryKey: false,
          isRelationField: false,
        },
      ],
    },
    {
      id: "vehicle",
      nameCn: "车辆",
      nameEn: "VEHICLE",
      color: "#f5222d",
      icon: "directions_car",
      fields: [
        {
          id: "f8",
          fieldNameEn: "CPHM",
          fieldNameCn: "车牌号码",
          fieldType: "VARCHAR",
          fieldLength: 10,
          isPrimaryKey: true,
          isRelationField: false,
        },
        {
          id: "f9",
          fieldNameEn: "CLPP",
          fieldNameCn: "车辆品牌",
          fieldType: "VARCHAR",
          fieldLength: 64,
          isPrimaryKey: false,
          isRelationField: false,
        },
      ],
    },
    {
      id: "family",
      nameCn: "家庭成员",
      nameEn: "FAMILY",
      color: "#52c41a",
      icon: "group",
      fields: [
        {
          id: "f10",
          fieldNameEn: "HZJM",
          fieldNameCn: "户主证件码",
          fieldType: "VARCHAR",
          fieldLength: 32,
          isPrimaryKey: true,
          isRelationField: false,
        },
        {
          id: "f11",
          fieldNameEn: "CYRS",
          fieldNameCn: "成员人数",
          fieldType: "INT",
          fieldLength: 4,
          isPrimaryKey: false,
          isRelationField: false,
        },
      ],
    },
  ],
  edges: [
    { id: "e1", source: "citizen", target: "property", relNameEn: "owns", relNameCn: "持有" },
    {
      id: "e2",
      source: "citizen",
      target: "company",
      relNameEn: "legal_rep",
      relNameCn: "法人代表",
    },
    {
      id: "e3",
      source: "citizen",
      target: "vehicle",
      relNameEn: "registered_owner",
      relNameCn: "登记所有人",
    },
    {
      id: "e4",
      source: "citizen",
      target: "family",
      relNameEn: "has_kinship",
      relNameCn: "亲属关系",
    },
  ],
};
