import { useEffect, useState } from 'react';
import { Alert, App, Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag } from 'antd';
import { foundationApi, refreshWorkspace } from '../services/workspace';
import { useDatabase, useSession } from '../mock/store';
import { PageTitle, RecordEditor, type FormValues } from '../components/common';
import type { Domain } from '../domain/types';

interface Account { id: string; subjectId: string; name: string; username: string; domain: Domain; status: string; mustChangePassword: boolean; version: number; legalEntityId?: string; }
export function AuthAccounts({ domain }: { domain: Domain }) {
    const db = useDatabase(); const session = useSession()!; const writable = session.globalPermissions?.includes('auth-accounts:write'); const [rows, setRows] = useState<Account[]>([]); const [editing, setEditing] = useState<Account | null>(null); const [open, setOpen] = useState(false); const [reset, setReset] = useState<Account | null>(null); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const { message } = App.useApp();
    const load = async () => { try { setRows(await foundationApi.read('/idaas/auth-accounts/list?domain=' + domain)); setError(''); } catch (e) { setError(e instanceof Error ? e.message : '无法读取认证账号'); } }; useEffect(() => { void load(); }, [domain]);
    return <><PageTitle title="认证账号" description="为中央人员建立独立的统一认证凭据，分别维护账号状态、改密和法人办理上下文。" extra={<Button type="primary" disabled={!writable} onClick={() => { setEditing(null); setOpen(true); }}>建立认证账号</Button>} /><Alert type="info" title="初始化密码要求首次登录修改" description="人员档案、平台操作账号和各应用本地密码分别维护。" showIcon />{error && <Alert type="error" title={error} showIcon />}<Table size="small" rowKey="id" dataSource={rows} scroll={{ x: 'max-content' }} columns={[{ title: '认证账号', dataIndex: 'username' }, { title: '姓名', dataIndex: 'name' }, { title: '状态', render: (_, r) => <Tag>{r.status === 'ACTIVE' ? '启用' : '停用'}</Tag> }, { title: '密码设置', render: (_, r) => r.mustChangePassword ? '需要改密' : '已设置' }, { title: '法人上下文', render: (_, r) => db.legalEntities.find(e => e.id === r.legalEntityId)?.name || '个人' }, { title: '操作', render: (_, r) => <Space><Button type="link" disabled={!writable} onClick={() => { setEditing(r); setOpen(true); }}>维护</Button><Button type="link" disabled={!writable} onClick={() => { setReset(r); setPassword(''); }}>重置密码</Button>{domain === 'public' && <Select style={{ minWidth: 180 }} disabled={!writable} allowClear placeholder="法人办理上下文" value={r.legalEntityId} options={db.legalEntities.map(e => ({ label: e.name, value: e.id }))} onChange={entityId => { void foundationApi.write('/idaas/auth-accounts/bind-entity', { id: r.id, version: r.version, domain, entityId: entityId || null }).then(load).catch(e => message.error(e.message)); }} />}</Space> }]} /><RecordEditor open={open} title={editing ? '维护认证账号' : '建立认证账号'} onClose={() => setOpen(false)} initial={(editing || { username: '', subjectId: '', status: 'ACTIVE' }) as unknown as FormValues} fields={[{ name: 'subjectId', label: '关联人员', type: 'select', required: true, disabled: !!editing, options: db.users.filter(u => u.domain === domain).map(u => ({ value: u.id, label: u.name + ' · ' + u.account })) }, { name: 'username', label: '认证账号', required: true, disabled: !!editing, pattern: /^[A-Za-z][A-Za-z0-9_.-]{2,99}$/ }, ...(!editing ? [{ name: 'password', label: '初始密码', type: 'password' as const, required: true, min: 8 }] : []), { name: 'status', label: '账号状态', type: 'select', options: [{ value: 'ACTIVE', label: '启用' }, { value: 'DISABLED', label: '停用' }] }]} onSave={async record => { await foundationApi.write('/idaas/auth-accounts/save', { creating: !editing, record: { ...editing, ...record, domain } }); await load(); }} /><Modal title="重置统一认证密码" open={!!reset} onCancel={() => setReset(null)} onOk={async () => { try { await foundationApi.write('/idaas/auth-accounts/reset', { id: reset!.id, version: reset!.version, domain, password }); setReset(null); setPassword(''); await load(); message.success('密码已重置，账号下次登录须改密'); } catch (e) { message.error(e instanceof Error ? e.message : '重置失败'); } }}><Input.Password value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" placeholder="填写独立的新密码" /></Modal></>;
}
interface Provider { id?: string; version?: number; providerCode: string; endpoint: string; enabled: boolean; status: string; }
export function VerificationAdministration() {
    const session = useSession()!; const writable = session.globalPermissions?.includes('public:write'); const [form] = Form.useForm(); const [provider, setProvider] = useState<Provider | null>(null); const [rows, setRows] = useState<Array<{ id: string; targetType: string; status: string; providerCode: string; requestedTime: string; resultCode: string }>>([]); const [error, setError] = useState(''); const { message } = App.useApp();
    const load = async () => { try { const p = await foundationApi.read<Provider>('/idaas/verifications/provider'); setProvider(p); form.setFieldsValue(p); setRows(await foundationApi.read('/idaas/verifications/list')); } catch (e) { setError(e instanceof Error ? e.message : '无法读取核验配置'); } }; useEffect(() => { void load(); }, []);
    return <><PageTitle title="身份核验" description="配置受信任的核验渠道，查看自然人和法人核验的实际结果与有效期。" />{error && <Alert type="error" title={error} showIcon />}<Card size="small" title="核验提供方" extra={<Tag>{provider?.status === 'UNCONFIGURED' ? '未配置' : '已配置'}</Tag>}><Form size="small" form={form} layout="vertical" disabled={!writable} onFinish={async v => { try { await foundationApi.write('/idaas/verifications/save-provider', { ...v, version: provider?.version }); await load(); message.success('核验提供方配置已保存'); } catch (e) { setError(e instanceof Error ? e.message : '保存失败'); } }}><Form.Item name="providerCode" label="渠道编码" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="endpoint" label="核验接口地址" rules={[{ required: true }]} extra="填写支持平台核验请求与签名回执的接口地址；生产环境使用HTTPS。"><Input /></Form.Item><Form.Item name="secret" label="接入密钥" extra="已配置时留空保留当前密钥。密钥保存后不再返回。"><Input.Password autoComplete="new-password" /></Form.Item><Form.Item name="enabled" label="启用核验渠道" valuePropName="checked"><Switch /></Form.Item><Button type="primary" htmlType="submit">保存配置</Button></Form></Card><Card size="small" title="核验申请" style={{ marginTop: 16 }}><Table size="small" rowKey="id" dataSource={rows} scroll={{ x: 'max-content' }} columns={[{ title: '申请时间', dataIndex: 'requestedTime' }, { title: '主体类型', dataIndex: 'targetType' }, { title: '渠道', dataIndex: 'providerCode' }, { title: '结果', dataIndex: 'status' }, { title: '结果说明', dataIndex: 'resultCode' }]} /></Card></>;
}
