import { useEffect, useState } from 'react';
import { Alert, App, Button, Card, Descriptions, Form, Input, QRCode, Space, Table, Tabs, Tag } from 'antd';
import { useNavigate } from 'react-router-dom';
import { hasIdentitySession, identityApi, identityRequest, retainIdentityToken, type IdentityProfile } from '../services/identity';
import { logoutWarningText, showLogoutWarning } from '../services/logoutFeedback';
import { foundationApi, setSession } from '../services/workspace';
import { SelfLegalEntities } from '../components/SelfLegalEntities';
import { PageTitle, Text } from '../components/common';

export function MfaBinding({ realm = 'platform' }: { realm?: 'platform' | 'auth-account' }) {
    const [bound, setBound] = useState(false); const [setup, setSetup] = useState<{ secret: string; uri: string } | null>(null); const [codes, setCodes] = useState<string[]>([]); const [changed, setChanged] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate();
    const relogin = () => { if (realm === 'platform') setSession(null); else retainIdentityToken(''); nav(realm === 'platform' ? '/login' : '/auth/identity/login'); };
    const call = <T,>(path: string, body: Record<string, unknown>) => realm === 'platform' ? foundationApi.write<T>(path, body) : identityRequest<T>(path, { ...body, realm });
    useEffect(() => { void call<{ bound: boolean }>('/idaas/mfa/status', { realm }).then(v => setBound(v.bound)).catch(e => setError(e.message)); }, [realm]);
    const submit = async (values: { password?: string; code?: string }) => { setBusy(true); setError(''); try {
        if (!bound && !setup) setSetup(await call('/idaas/mfa/setup', { realm, password: values.password }));
        else { const value = await call<{ recoveryCodes?: string[] }>('/idaas/mfa/' + (bound ? 'disable' : 'bind'), { realm, code: values.code }); setCodes(value.recoveryCodes || []); setSetup(null); setBound(!bound); setChanged(true); if (realm === 'auth-account') retainIdentityToken(''); }
    } catch (e) { setError(e instanceof Error ? e.message : '操作未完成'); } finally { setBusy(false); } };
    return <Card size="small" title="动态口令"><Space orientation="vertical" style={{ width: '100%' }}>{error && <Alert type="error" title={error} showIcon />}{codes.length > 0 ? <><Alert type="success" title="绑定成功，请保存恢复码" description="恢复码仅在此展示一次，每个码只能使用一次。账号会话已撤销，保存后请重新登录。" showIcon /><Input.TextArea rows={10} readOnly value={codes.join('\n')} /><Button type="primary" onClick={relogin}>已保存，重新登录</Button></> : changed ? <><Alert type='success' title='动态口令已解绑' description='账号会话已撤销，请重新登录后继续操作。' showIcon /><Button type='primary' onClick={relogin}>重新登录</Button></> : changed ? <><Alert type='success' title='动态口令已解绑' description='账号会话已撤销，请重新登录后继续操作。' showIcon /><Button type='primary' onClick={relogin}>重新登录</Button></> : <><Tag color={bound ? 'success' : 'default'}>{bound ? '已绑定' : '未绑定'}</Tag>{setup && <><QRCode value={setup.uri} /><Input readOnly value={setup.secret} /><Text type="secondary">请在口令应用中添加此账号，并填写当前六位动态口令。设置有效期为五分钟。</Text></>}<Form size="small" layout="vertical" onFinish={submit}>{!bound && !setup ? <Form.Item name="password" label="当前密码" rules={[{ required: true }]}><Input.Password autoComplete="current-password" /></Form.Item> : <Form.Item name="code" label={bound ? '填写动态口令以解绑' : '动态口令'} rules={[{ required: true }, { pattern: /^\d{6}$/, message: '填写六位动态口令' }]}><Input autoComplete="one-time-code" maxLength={6} /></Form.Item>}<Button type="primary" htmlType="submit" loading={busy}>{bound ? '解绑动态口令' : setup ? '验证并绑定' : '设置动态口令'}</Button></Form></>}</Space></Card>;
}
export default function IdentityCenter() {
    const [profile, setProfile] = useState<IdentityProfile | null>(null); const [sessions, setSessions] = useState<Array<{ id: string; appId: string; issuedAt: string; expiresAt: string; revokedAt?: string }>>([]); const [verifications, setVerifications] = useState<Array<{ id: string; status: string; resultCode: string; requestedTime: string }>>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate(); const { message } = App.useApp();
    const load = async () => { try { const p = await identityApi.me(); setProfile(p); setSessions(await identityRequest('/idaas/auth-account/sessions')); if (p.domain === 'public') setVerifications(await identityRequest('/idaas/verifications/mine')); } catch (e) { setError(e instanceof Error ? e.message : '无法加载个人资料'); } };
    useEffect(() => { void load(); }, []);
    const changePassword = async (v: { oldPassword: string; password: string }) => { setBusy(true); try { await identityApi.password(v.oldPassword, v.password); message.success('密码已更新，请重新登录'); nav('/auth/identity/login'); } catch (e) { setError(e instanceof Error ? e.message : '更新失败'); } finally { setBusy(false); } };
    const verify = async (v: { document: string; consent: boolean }) => { setBusy(true); try { const result = await identityRequest<{ status: string }>('/idaas/verifications/submit', { ...v, consent: true, documentType: 'IDENTITY_CARD', targetType: 'SUBJECT', requestId: crypto.randomUUID() }); message.info(result.status === 'VERIFIED' ? '核验通过' : '核验申请已提交，请查看结果'); await load(); } catch (e) { setError(e instanceof Error ? e.message : '核验未完成'); } finally { setBusy(false); } };
    const logout = () => {
        const revocation = identityApi.logout();
        nav('/auth/identity/login', { replace: true });
        void revocation.catch(() => { if (hasIdentitySession()) message.warning(logoutWarningText); else showLogoutWarning('auth-account'); });
    };
    return <div className="identity-center"><PageTitle title="个人身份中心" description="维护统一认证账号的安全设置，查看自己的应用会话和身份核验。" extra={<Button onClick={logout}>退出登录</Button>} />{error && <Alert type="error" title={error} showIcon style={{ marginBottom: 16 }} />}{profile && <><Card size="small" title="认证账号"><Descriptions column={{ xs: 1, sm: 2 }} items={[{ key: 'name', label: '姓名', children: profile.name }, { key: 'account', label: '账号', children: profile.username }, { key: 'domain', label: '身份域', children: profile.domain === 'public' ? '公众身份域' : '政企身份域' }, { key: 'verification', label: '核验状态', children: profile.verificationStatus === 'VERIFIED' ? '已实名' : profile.verificationStatus === 'EXPIRED' ? '核验已到期' : '尚未实名' }]} /></Card><Tabs size="small" items={[{ key: 'password', label: '修改密码', children: <Card size="small"><Form size="small" layout="vertical" onFinish={changePassword}><Form.Item name="oldPassword" label="原密码" rules={[{ required: true }]}><Input.Password autoComplete="current-password" /></Form.Item><Form.Item name="password" label="新密码" rules={[{ required: true }, { min: 8 }]}><Input.Password autoComplete="new-password" /></Form.Item><Button type="primary" htmlType="submit" loading={busy}>更新密码</Button></Form></Card> }, { key: 'mfa', label: '二次验证', children: <MfaBinding realm="auth-account" /> }, { key: 'sessions', label: '应用会话', children: <Table size="small" rowKey="id" dataSource={sessions} scroll={{ x: 'max-content' }} columns={[{ title: '应用', dataIndex: 'appId' }, { title: '签发时间', dataIndex: 'issuedAt' }, { title: '状态', render: (_, r) => r.revokedAt ? '已撤销' : Date.parse(r.expiresAt) < Date.now() ? '已到期' : '有效' }, { title: '操作', render: (_, r) => <Button disabled={!!r.revokedAt} onClick={() => { void identityRequest('/idaas/auth-account/revoke-session', { id: r.id }).then(load).catch(e => setError(e.message)); }}>撤销</Button> }]} /> }, ...(profile.domain === 'public' ? [{ key: 'legal', label: '法人办理身份', children: <SelfLegalEntities currentEntityId={profile.legalEntityId} /> }, { key: 'verification', label: '实名核验', children: <Card size="small"><Alert type="info" title="注册不等于实名" description="只有已配置核验服务并收到有效结果后才会显示已实名。" showIcon /><Form size="small" layout="vertical" onFinish={verify} style={{ marginTop: 16 }}><Form.Item name="document" label="身份证件号码" rules={[{ required: true }]}><Input.Password autoComplete="off" /></Form.Item><Text type="secondary">提交即表示同意由已配置的核验服务处理本次资料，仅用于身份核验。</Text><div style={{ marginTop: 16 }}><Button type="primary" htmlType="submit" loading={busy}>同意并申请核验</Button></div></Form><Table size="small" style={{ marginTop: 24 }} rowKey="id" dataSource={verifications} columns={[{ title: '申请时间', dataIndex: 'requestedTime' }, { title: '核验状态', dataIndex: 'status' }, { title: '结果说明', dataIndex: 'resultCode' }]} /></Card> }] : [])]} /></>}</div>;
}
