import { useEffect, useState } from 'react';
import { App, Button, Input, Select, Table, Tabs } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { DeleteOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { assetsApi } from '../../../services/assets';
import type { FavoriteResult, WorkbenchItem, WorkbenchPage } from '../../../services/assets.types';
import { ConsumerError, ConsumerName, ConsumerPage, ConsumerStatus, formatTime, kindNames, stateNames, useConsumerAction, useConsumerRead } from '../market/consumerShared';
import { DemandDrawer } from './DemandDrawer';
import { DemandDetailDrawer } from './DemandDetailDrawer';
import { SubscriptionProgressDrawer } from './SubscriptionProgressDrawer';
import { TaskDrawer, type ReviewTask } from './TaskDrawer';

const tabs = [{ key: 'todos', api: 'TODO', label: '我的待办' }, { key: 'subscriptions', api: 'SUBSCRIPTIONS', label: '我的订阅' }, { key: 'demands', api: 'DEMANDS', label: '我的供需' }, { key: 'favorites', api: 'FAVORITES', label: '我的收藏' }, { key: 'history', api: 'HISTORY', label: '我的足迹' }];
const taskNames: Record<string, string> = { CATALOG_PUBLICATION: '目录发布', SUBSCRIPTION_APPROVAL: '目录订阅', DEMAND_RESPONSE: '供需对接' };
const statusOptions: Record<string, string[]> = { subscriptions: ['DRAFT', 'IN_REVIEW', 'RETURNED', 'APPROVED', 'REJECTED', 'WITHDRAWN'], demands: ['DRAFT', 'SUBMITTED', 'TRIAGED', 'MATCHING', 'MATCHED', 'FULFILLED', 'CLOSED', 'WITHDRAWN'] };

export function AssetWorkbenchPage() {
  const params = useParams(), [search, setSearch] = useSearchParams(), nav = useNavigate(), { modal } = App.useApp();
  const active = tabs.find(item => item.key === params.tab) || tabs[0];
  const [keyword, setKeyword] = useState(''), [status, setStatus] = useState<string>(), [page, setPage] = useState(1), [size, setSize] = useState(15), [sort, setSort] = useState({ sortBy: 'updatedAt', sortOrder: 'desc' });
  const [taskType, setTaskType] = useState<string>(), [createDemand, setCreateDemand] = useState(false), [subscriptionId, setSubscriptionId] = useState<string>(), [demandId, setDemandId] = useState<string>(), [task, setTask] = useState<ReviewTask>(); const { busy, run, operation } = useConsumerAction();
  const query = useConsumerRead(`workbench:${active.key}:${keyword}:${status}:${page}:${size}:${sort.sortBy}:${sort.sortOrder}`, signal => assetsApi.get<WorkbenchPage>('/workbench', { tab: active.api, keyword, status, pageNo: page, pageSize: size, ...sort }, { signal }));
  const counts = useConsumerRead('workbench-counts', async signal => { const result = await Promise.allSettled(tabs.slice(0, 3).map(item => assetsApi.get<WorkbenchPage>('/workbench', { tab: item.api, pageNo: 1, pageSize: 1 }, { signal }))); return Object.fromEntries(result.map((item, index) => [tabs[index].key, item.status === 'fulfilled' ? item.value.page.total : null])); });
  useEffect(() => { setPage(1); setStatus(undefined); setKeyword(''); setTaskType(undefined); }, [active.key]);
  useEffect(() => { if (search.get('create') === '1' && active.key === 'demands') { setCreateDemand(true); const next = new URLSearchParams(search); next.delete('create'); setSearch(next, { replace: true }); } if (search.get('subscriptionId')) setSubscriptionId(search.get('subscriptionId') || undefined); if (search.get('demandId')) setDemandId(search.get('demandId') || undefined); }, [search, active.key]);
  const openObject = (item: WorkbenchItem) => { if (!item.object || item.object.available === false) return; nav(item.object.kind === 'CATALOG' ? `/assets/market/${encodeURIComponent(item.object.id)}` : `/assets/map?kind=${item.object.kind}&id=${encodeURIComponent(item.object.id)}`); };
  const view = (item: WorkbenchItem) => { if (active.key === 'subscriptions') setSubscriptionId(item.subscription?.id || item.id); else if (active.key === 'demands') setDemandId(item.id); else if (item.task?.taskType === 'DEMAND_RESPONSE') setDemandId(item.task.businessId); else if (item.task) setTask(item.task); else openObject(item); };
  const removeFavorite = (item: WorkbenchItem) => { if (!item.object) return; void run(() => assetsApi.put<FavoriteResult>(`/favorites/${item.object!.kind}/${encodeURIComponent(item.object!.id)}`, { favorited: false }), '已取消收藏'); };
  const clearHistory = (ids?: string[]) => modal.confirm({ title: ids ? '清除这条浏览记录？' : '清空个人浏览足迹？', content: '此操作仅清理您的浏览记录。', okText: '清除', cancelText: '取消', onOk: () => { const body = ids ? { action: 'CLEAR_SELECTED', visitIds: ids } : { action: 'CLEAR_ALL' }; return assetsApi.post('/visits', body, operation(body)); } });
  const columns: ColumnsType<WorkbenchItem> = [
    { title: '#', width: 52, align: 'center', render: (_, __, index) => (page - 1) * size + index + 1 },
    { title: active.key === 'todos' ? '待办名称' : active.key === 'demands' ? '需求名称' : active.key === 'subscriptions' ? '申请名称' : '资产名称', key: 'name', width: 300, ellipsis: true, sorter: true, sortOrder: sort.sortBy === 'name' ? sort.sortOrder === 'asc' ? 'ascend' : 'descend' : null, render: (_, row) => <ConsumerName name={row.title} code={row.object?.code || row.id} onClick={() => view(row)}/> },
    { title: active.key === 'todos' ? '事项类型' : '资源类型', width: 135, render: (_, row) => row.task ? taskNames[row.task.taskType] : row.object ? kindNames[row.object.kind] : active.key === 'subscriptions' ? '目录订阅' : '数据需求' },
    ...(active.key === 'history' ? [{ title: '浏览次数', width: 100, align: 'right' as const, render: (_: unknown, row: WorkbenchItem) => row.visitCount ?? '—' }] : ['todos', 'subscriptions', 'demands'].includes(active.key) ? [{ title: active.key === 'subscriptions' ? '申请状态' : '状态', width: 130, render: (_: unknown, row: WorkbenchItem) => <ConsumerStatus value={row.subscription?.status || row.task?.status || row.status}/> }] : [{ title: '当前状态', width: 110, render: (_: unknown, row: WorkbenchItem) => row.object?.available === false ? <span className="hy-text-muted">暂不可访问</span> : <ConsumerStatus value={row.status || 'LISTED'}/> }]),
    { title: active.key === 'history' ? '最近浏览时间' : '更新时间', key: 'updatedAt', dataIndex: 'updatedAt', width: 168, sorter: true, sortOrder: sort.sortBy === 'updatedAt' ? sort.sortOrder === 'asc' ? 'ascend' : 'descend' : null, render: formatTime },
    { title: '操作', key: 'actions', fixed: 'right', className: 'hy-actions-column', align: 'center', width: active.key === 'favorites' || active.key === 'history' ? 155 : 128, render: (_, row) => <div className="hy-table-actions"><Button type="link" disabled={row.object?.available === false && ['favorites', 'history'].includes(active.key)} onClick={() => view(row)}>{active.key === 'todos' && row.task?.status === 'PENDING' ? '办理' : active.key === 'subscriptions' ? '查看进度' : active.key === 'demands' ? '查看对接' : '查看详情'}</Button>{active.key === 'favorites' && <Button type="link" disabled={busy} onClick={() => removeFavorite(row)}>取消收藏</Button>}{active.key === 'history' && <Button type="link" danger onClick={() => clearHistory([row.id])}>清除</Button>}</div> },
  ];
  const rows = (query.data?.items || []).filter(item => active.key !== 'todos' || !taskType || item.task?.taskType === taskType);
  return <ConsumerPage title="部门工作台" description="处理部门事项，跟踪申请与交付，继续您关注的数据工作。" actions={<Button type="primary" icon={<PlusOutlined/>} onClick={() => setCreateDemand(true)}>提交数据需求</Button>}>
    <div className="hy-work-summary">{[{ key: 'todos', label: '我的待办', hint: '来自实际流程任务' }, { key: 'subscriptions', label: '我的订阅', hint: '申请与交付分别跟踪' }, { key: 'demands', label: '我的供需', hint: '查看匹配与对接进展' }].map(item => <button key={item.key} onClick={() => nav(`/assets/workbench/${item.key}`)}><span>{item.label}</span><strong>{counts.data?.[item.key] == null ? '—' : counts.data[item.key]}</strong><small>{item.hint}</small></button>)}<button onClick={() => nav('/assets/market')}><span>发现更多数据</span><strong style={{ fontSize: 21 }}>数据超市 →</strong><small>浏览已发布的可申请资源</small></button></div>
    <div className="hy-panel"><Tabs className="hy-work-tabs" activeKey={active.key} onChange={key => nav(`/assets/workbench/${key}`)} items={tabs.map(item => ({ key: item.key, label: item.label }))}/><div className="hy-consumer-toolbar"><div className="hy-toolbar-filters"><Input.Search key={active.key} allowClear aria-label="搜索工作台记录" placeholder="搜索名称或申请编号" onSearch={value => { setKeyword(value.trim()); setPage(1); }}/><span className="hy-workbench-count">{query.error && !query.data ? '读取失败' : query.loading && !query.data ? '读取中…' : `${query.data?.page.total ?? 0} 条记录`}</span></div><div className="hy-toolbar-filters">{active.key === 'todos' && <Select allowClear value={taskType} aria-label="当前页事项类型" placeholder="当前页全部类型" onChange={setTaskType} options={Object.entries(taskNames).map(([value, label]) => ({ value, label }))}/>} {statusOptions[active.key] && <Select allowClear value={status} aria-label="工作台状态" placeholder="全部状态" onChange={value => { setStatus(value); setPage(1); }} options={statusOptions[active.key].map(value => ({ value, label: stateNames[value] || value }))}/>} {active.key === 'history' && <Button danger icon={<DeleteOutlined/>} disabled={!query.data?.items.length} onClick={() => clearHistory()}>清空足迹</Button>}<Button aria-label="刷新工作台" icon={<ReloadOutlined/>} onClick={() => { query.refresh(); counts.refresh(); }}/></div></div><ConsumerError error={query.error} retry={query.refresh}/><Table<WorkbenchItem> rowKey="id" tableLayout="fixed" loading={query.loading} dataSource={rows} columns={columns} scroll={{ x: 960 }} pagination={{ current: page, pageSize: size, total: query.data?.page.total || 0, showSizeChanger: true, showTotal: total => `共 ${total} 条`, onChange: (next, nextSize) => { setPage(nextSize === size ? next : 1); setSize(nextSize); } }} onChange={(_, __, sorter, extra) => { if (extra.action !== 'sort') return; const selected = Array.isArray(sorter) ? sorter[0] : sorter; setSort(selected.order ? { sortBy: String(selected.columnKey), sortOrder: selected.order === 'ascend' ? 'asc' : 'desc' } : { sortBy: 'updatedAt', sortOrder: 'desc' }); setPage(1); }} locale={{ emptyText: query.error ? '读取失败，请重试' : `暂无${active.label.slice(2)}记录` }}/></div>
    {createDemand && <DemandDrawer onClose={() => setCreateDemand(false)} onSaved={() => { query.refresh(); nav('/assets/workbench/demands'); }}/>}
    {subscriptionId && <SubscriptionProgressDrawer id={subscriptionId} onClose={() => { setSubscriptionId(undefined); const next = new URLSearchParams(search); next.delete('subscriptionId'); setSearch(next, { replace: true }); }}/>} {demandId && <DemandDetailDrawer id={demandId} onClose={() => { setDemandId(undefined); const next = new URLSearchParams(search); next.delete('demandId'); setSearch(next, { replace: true }); }}/>} {task && <TaskDrawer task={task} onClose={() => { setTask(undefined); query.refresh(); }}/>} 
  </ConsumerPage>;
}
