import { useState } from 'react';
import { Alert, Button, Descriptions, Drawer, Form, Input, Modal, Skeleton, Table, Tabs } from 'antd';
import { DownloadOutlined, ReloadOutlined } from '@ant-design/icons';
import { assetsApi } from '../../../services/assets';
import type { DeliveryAccess, DeliveryDetail, DeliveryItem, Subscription, SubscriptionProgress } from '../../../services/assets.types';
import { ConsumerEmpty, ConsumerError, ConsumerName, ConsumerStatus, EventHistory, can, channelNames, formatTime, useConsumerAction, useConsumerRead } from '../market/consumerShared';
import { SubscriptionDrawer, type EditableSubscription } from '../market/SubscriptionDrawer';

export function SubscriptionProgressDrawer({ id, onClose }: { id: string; onClose: () => void }) {
  const query = useConsumerRead(`subscription-progress:${id}`, signal => assetsApi.get<SubscriptionProgress & { subscription: EditableSubscription }>(`/subscriptions/${encodeURIComponent(id)}/progress`, {}, { signal }));
  const delivery = useConsumerRead(`subscription-delivery:${id}`, signal => assetsApi.get<DeliveryDetail>(`/subscriptions/${encodeURIComponent(id)}/delivery`, {}, { signal }), query.data?.subscription.status === 'APPROVED');
  const { busy, run, operation } = useConsumerAction(); const [withdraw, setWithdraw] = useState(false), [editing, setEditing] = useState(false), [access, setAccess] = useState<DeliveryAccess>(); const [form] = Form.useForm<{ reason: string }>();
  const subscription = query.data?.subscription, resource = subscription?.resources[0];
  const recommendation = subscription?.draft?.recommendedCatalogId && subscription.draft.recommendedVersionId ? { catalogId: subscription.draft.recommendedCatalogId, versionId: subscription.draft.recommendedVersionId } : undefined;
  const doWithdraw = async () => { const values = await form.validateFields(); if (!subscription) return; const payload = { expectedRevision: subscription.revision, reason: values.reason.trim() }; await run(async () => { await assetsApi.post<Subscription>(`/subscriptions/${encodeURIComponent(id)}/withdraw`, payload, operation({ action: 'WITHDRAW', id, ...payload })); setWithdraw(false); query.refresh(); }, '申请已撤回'); };
  const requestAccess = async (item: DeliveryItem) => {
    const action = item.channel === 'FILE' ? 'DOWNLOAD' : item.channel === 'API' ? 'INVOKE_INFO' : 'QUERY_SESSION';
    const body = { expectedRevision: item.revision, action };
    await run(async () => { const result = await assetsApi.post<DeliveryAccess>(`/deliveries/${encodeURIComponent(item.id)}/access`, body, operation({ id: item.id, ...body })); setAccess(result); });
  };
  const safeDownloadUrl = (url?: string) => { if (!url) return undefined; try { const value = new URL(url, location.origin); return ['http:', 'https:'].includes(value.protocol) ? value.href : undefined; } catch { return undefined; } };
  return <><Drawer className="hy-consumer-drawer" title="订阅进度与交付" open size={650} onClose={onClose} extra={<Button icon={<ReloadOutlined/>} onClick={() => { query.refresh(); delivery.refresh(); }}>刷新</Button>} footer={subscription && <div className="hy-dialog-footer">{can(subscription.allowedActions, 'WITHDRAW') && <Button disabled={busy} onClick={() => setWithdraw(true)}>撤回申请</Button>}{(can(subscription.allowedActions, 'EDIT') || can(subscription.allowedActions, 'RESUBMIT')) && <Button type="primary" onClick={() => setEditing(true)}>编辑{subscription.status === 'RETURNED' ? '并重提' : '申请'}</Button>}</div>}>
    <ConsumerError error={query.error} retry={query.refresh}/>{query.loading && !subscription ? <Skeleton active/> : subscription && <><ConsumerName name={subscription.title} code={`申请编号 ${subscription.id} · 第 ${subscription.submissionVersion} 次提交`}/><div className="hy-progress-state" style={{ marginTop: 18 }}><span>申请状态</span><ConsumerStatus value={subscription.status}/>{query.data?.deliveryStatus && <><span>交付状态</span><ConsumerStatus value={query.data.deliveryStatus}/></>}</div><Tabs destroyOnHidden items={[
      { key: 'progress', label: '处理进度', children: <><EventHistory events={query.data?.events || []}/>{!!query.data?.activeTasks.length && <><h3 className="hy-section-subtitle">当前处理环节</h3>{query.data.activeTasks.map(task => <div className="hy-progress-resource" key={task.id}><ConsumerName name={task.title}/><p><ConsumerStatus value={task.status}/></p></div>)}</>}</> },
      { key: 'scope', label: '申请范围', children: <><Descriptions column={1} items={[{ key: 'purpose', label: '使用用途', children: subscription.draft?.purpose || subscription.purpose || '—' }, { key: 'scenario', label: '业务场景', children: subscription.draft?.businessScenario || subscription.businessScenario || '—' }, { key: 'from', label: '开始日期', children: formatTime(subscription.draft?.validFrom || subscription.validFrom) }, { key: 'until', label: '截止日期', children: formatTime(subscription.draft?.validUntil || subscription.validUntil) }]}/><Table size="middle" pagination={false} rowKey={row => `${row.catalogId}:${row.attachmentId}`} dataSource={subscription.resources} scroll={{ x: 540 }} columns={[{ title: '目录 / 版本', width: 210, ellipsis: true, render: (_, row) => <ConsumerName name={row.catalogId} code={row.versionId}/> }, { title: '交付方式', width: 130, render: (_, row) => channelNames[row.channel] }, { title: '数据项数量', width: 110, align: 'right', render: (_, row) => row.itemIds.length }]}/></> },
      { key: 'delivery', label: '授权交付', children: subscription.status !== 'APPROVED' ? <ConsumerEmpty text="申请通过后查看授权与交付进展"/> : <><ConsumerError error={delivery.error} retry={delivery.refresh}/>{delivery.loading && !delivery.data ? <Skeleton active/> : delivery.data?.items.length ? delivery.data.items.map(item => <div className="hy-progress-resource" key={item.id}><h3>{channelNames[item.channel]} · {item.catalogId}</h3><div><ConsumerStatus value={item.grantStatus}/><ConsumerStatus value={item.deliveryStatus}/></div><Descriptions size="small" column={1} items={[{ key: 'valid', label: '有效期至', children: formatTime(item.validUntil) }, { key: 'attempt', label: '最近尝试', children: formatTime(item.lastAttemptAt) }]}/>{item.failureMessage && <Alert type="error" showIcon title={item.failureMessage}/>} {item.deliveryStatus === 'READY' && item.grantStatus === 'ACTIVE' && <Button type="primary" loading={busy} disabled={!can(item.allowedActions, item.channel === 'FILE' ? 'DOWNLOAD' : item.channel === 'API' ? 'INVOKE_INFO' : 'QUERY_SESSION')} onClick={() => void requestAccess(item)}>{item.channel === 'FILE' ? '获取下载入口' : item.channel === 'API' ? '查看调用信息' : '打开受控查询'}</Button>}</div>) : !delivery.error && <ConsumerEmpty text="审批已通过，尚无可用交付资源"/>}<EventHistory events={delivery.data?.events || []}/></> },
    ]}/></>}
  </Drawer><Modal title="撤回申请" open={withdraw} onCancel={() => setWithdraw(false)} confirmLoading={busy} okText="确认撤回" cancelText="取消" onOk={() => void doWithdraw().catch(() => undefined)}><Form form={form} layout="vertical"><Form.Item name="reason" label="撤回原因" rules={[{ required: true, whitespace: true, message: '填写撤回原因' }]}><Input.TextArea maxLength={2000} rows={3}/></Form.Item></Form></Modal>
    <Modal title="资源使用方式" open={!!access} onCancel={() => setAccess(undefined)} footer={<Button onClick={() => setAccess(undefined)}>关闭</Button>}><div className="hy-delivery-access">{access && <><Descriptions column={1} items={[{ key: 'expires', label: '入口有效期至', children: formatTime(access.expiresAt) }, { key: 'fields', label: '授权数据项', children: access.allowedItemIds.length }]}/>{access.kind === 'SIGNED_DOWNLOAD' && safeDownloadUrl(access.downloadUrl) && <Button type="primary" icon={<DownloadOutlined/>} href={safeDownloadUrl(access.downloadUrl)}>下载授权文件</Button>}{access.kind === 'API_INSTRUCTIONS' && <><p>{access.method} {access.publicEndpoint}</p><pre>{access.authenticationInstructions}</pre></>}{access.kind === 'QUERY_SESSION' && <p>查询会话：{access.querySessionId}</p>}</>}</div></Modal>
    {editing && subscription && (resource || recommendation) && <SubscriptionDrawer catalogId={(resource || recommendation)!.catalogId} versionId={(resource || recommendation)!.versionId} initial={subscription} onClose={() => setEditing(false)} onSaved={query.refresh}/>}
    {editing && subscription && !resource && !recommendation && <Alert type="warning" title="草稿未选择资源，请从数据超市选择目录继续申请" closable onClose={() => setEditing(false)}/>}
  </>;
}
