import { useState } from 'react';
import { Alert, Button, Descriptions, Drawer, Form, Input, Select, Skeleton, Table } from 'antd';
import { assetsApi } from '../../../services/assets';
import type { SubscriptionProgress, TaskHandleResult, TaskSummary, VersionDetail } from '../../../services/assets.types';
import { ConsumerError, ConsumerName, EventHistory, channelNames, displayType, useConsumerAction, useConsumerRead } from '../market/consumerShared';

export type ReviewTask = TaskSummary & { catalogId?: string; versionId?: string };
export function TaskDrawer({ task, onClose }: { task: ReviewTask; onClose: () => void }) {
  const isSubscription = task.taskType === 'SUBSCRIPTION_APPROVAL', isPublication = task.taskType === 'CATALOG_PUBLICATION';
  const subscription = useConsumerRead(`review-subscription:${task.businessId}`, signal => assetsApi.get<SubscriptionProgress>(`/subscriptions/${encodeURIComponent(task.businessId)}/progress`, {}, { signal }), isSubscription);
  const publication = useConsumerRead(`review-publication:${task.catalogId}:${task.versionId}`, signal => assetsApi.get<VersionDetail>(`/catalogs/${encodeURIComponent(task.catalogId || '')}/versions/${encodeURIComponent(task.versionId || '')}`, {}, { signal }), isPublication && !!task.catalogId && !!task.versionId);
  const [form] = Form.useForm<{ action: string; opinion: string }>(), [result, setResult] = useState<TaskHandleResult>(); const { busy, run, operation } = useConsumerAction();
  const labels: Record<string, string> = { APPROVE: '同意', RETURN: '退回补正', REJECT: '拒绝', ACCEPT: '受理', COMPLETE: '完成' };
  const reviewReady = isSubscription ? !!subscription.data : isPublication ? !!publication.data : false;
  const submit = async () => { const values = await form.validateFields(); const body = { expectedRevision: task.revision, action: values.action, opinion: values.opinion.trim(), ...(isSubscription ? { expectedSubmissionVersion: subscription.data?.subscription.submissionVersion } : {}) }; await run(async () => { const response = await assetsApi.post<TaskHandleResult>(`/tasks/${encodeURIComponent(task.id)}/handle`, body, operation({ id: task.id, ...body })); setResult(response); }, '任务处理已提交'); };
  return <Drawer className="hy-consumer-drawer" open size={660} title={isSubscription ? '办理订阅审批' : '办理目录发布'} onClose={onClose} footer={<div className="hy-dialog-footer"><Button onClick={onClose}>{result ? '关闭' : '取消'}</Button>{!result && <Button type="primary" disabled={!reviewReady} loading={busy} onClick={() => void submit().catch(() => undefined)}>提交处理</Button>}</div>}><ConsumerName name={task.title} code={task.id}/>
    <ConsumerError error={subscription.error || publication.error} retry={() => { subscription.refresh(); publication.refresh(); }}/>
    {(subscription.loading || publication.loading) && <Skeleton active/>}
    {isPublication && (!task.catalogId || !task.versionId) && <Alert style={{ marginTop: 18 }} type="warning" title="任务尚未返回发布快照，暂不能办理" description="请刷新待办，待服务端提供完整审批对象后继续。"/>}
    {subscription.data && <><Descriptions style={{ marginTop: 20 }} column={1} items={[{ key: 'round', label: '提交轮次', children: subscription.data.subscription.submissionVersion }, { key: 'applicant', label: '申请人', children: subscription.data.subscription.applicantUserId }, { key: 'department', label: '申请部门', children: subscription.data.subscription.departmentId }]}/><h3 className="hy-section-subtitle">申请资源范围</h3><Table size="middle" rowKey={row => `${row.catalogId}:${row.attachmentId}`} dataSource={subscription.data.subscription.resources} pagination={false} columns={[{ title: '目录 / 版本', width: 240, ellipsis: true, render: (_, row) => <ConsumerName name={row.catalogId} code={row.versionId}/> }, { title: '交付方式', width: 120, render: (_, row) => channelNames[row.channel] }, { title: '数据项数量', width: 110, align: 'right', render: (_, row) => row.itemIds.length }]}/><EventHistory events={subscription.data.events}/></>}
    {publication.data && <><h3 className="hy-section-subtitle" style={{ marginTop: 22 }}>{publication.data.catalogName} · v{publication.data.version.versionNo}</h3><Descriptions column={1} items={[{ key: 'share', label: '共享方式', children: publication.data.sharingPolicy.shareType === 'CONDITIONAL' ? '有条件共享' : publication.data.sharingPolicy.shareType === 'UNCONDITIONAL' ? '无条件共享' : '不予共享' }, { key: 'condition', label: '使用条件', children: publication.data.sharingPolicy.useConditions || '—' }]}/><Table size="middle" pagination={{ pageSize: 8, hideOnSinglePage: true }} rowKey={row => row.id || row.code} dataSource={publication.data.items} columns={[{ title: '数据项名称', width: 250, ellipsis: true, render: (_, row) => <ConsumerName name={row.name} code={row.code}/> }, { title: '类型 / 长度', width: 150, render: (_, row) => displayType(row) }]}/></>}
    {result ? <Alert type="success" showIcon title="处理已记录" description={result.deliveryPending ? '审批结果已记录，授权交付正在准备。' : '后续进度以流程当前状态为准。'}/> : <Form form={form} layout="vertical" style={{ marginTop: 22 }}><Form.Item name="action" label="处理决定" rules={[{ required: true, message: '选择处理决定' }]}><Select options={task.allowedActions.filter(action => labels[action]).map(value => ({ value, label: labels[value] }))}/></Form.Item><Form.Item name="opinion" label="处理意见" rules={[{ required: true, whitespace: true, message: '填写处理意见' }]}><Input.TextArea rows={4} maxLength={4000}/></Form.Item></Form>}
  </Drawer>;
}
