"""Offline visual review only. The test data below NEVER enters src or the local data service.
Uses shipped CSS with simplified component DOM; not React/Ant Design/E2E certification.
"""
from pathlib import Path
import re, json, html
BASE=Path(__file__).resolve().parents[2]; OUT=BASE/'tests/visual/fixtures';OUT.mkdir(exist_ok=True)
def esc(v):return html.escape(str(v),quote=True)
shapes={
'database':'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',
'grid':'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
'search':'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>','arrow':'<path d="M4 12h16m-6-6 6 6-6 6"/>','close':'<path d="m6 6 12 12M18 6 6 18"/>','menu':'<path d="M4 5h16M4 12h16M4 19h16"/>','moon':'<path d="M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z"/>','bell':'<path d="M7 9a5 5 0 0 1 10 0v5l3 3H4l3-3Zm3 11h4"/>','table':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M9 9v11"/>','model':'<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="16" width="6" height="5" rx="1"/><rect x="16" y="16" width="6" height="5" rx="1"/><path d="M12 7v5M5 16v-4h14v4"/>','shield':'<path d="m12 2 8 3v6c0 5-5 9-8 11C9 20 4 16 4 11V5Zm-4 9 3 3 5-6"/>','file':'<path d="M5 2h10l4 4v16H5Zm9 0v6h5M8 12h8M8 16h8"/>','plus':'<path d="M12 4v16M4 12h16"/>','play':'<path d="m7 3 14 9L7 21Z"/>','refresh':'<path d="M19 8A8 8 0 1 0 20 16M19 3v6h-6"/>','setting':'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="9" cy="18" r="2"/>','download':'<path d="M12 2v13m-5-5 5 5 5-5M4 17v5h16v-5"/>','copy':'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/>','edit':'<path d="m4 15 12-12 5 5L9 20l-6 1Z"/>','delete':'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>','down':'<path d="m6 9 6 6 6-6"/>'}
def icon(k='grid'):return '<span class="anticon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+shapes.get(k,shapes['grid'])+'</svg></span>'
def btn(t='',k=None,kind='',aria=None):return f'<button class="ant-btn {"ant-btn-"+kind if kind else ""} {"ant-btn-icon-only" if not t else ""}" aria-label="{esc(aria or t or k)}">{icon(k) if k else ""}{t}</button>'
def status(t='已完成',tone='success'):return f'<span class="wx-status tone-{tone}"><i></i>{t}</span>'
def search(ph='搜索名称、代码或字段…',cls='wx-table-search'):return f'<label class="ant-input-affix-wrapper {cls}">{icon("search")}<input aria-label="{ph}" placeholder="{ph}"></label>'
def select(t):return f'<div class="ant-select" role="combobox" aria-label="{t}" tabindex="0">{t}{icon("down")}</div>'
def brand():return (BASE/'public/brand/wanxiang-mark.svg').read_text().replace('<svg xmlns=', '<svg class="wx-brand-mark" xmlns=')

def source(n,e,db='business'):return f'<div class="source-name-cell"><span class="wx-source-icon source-{e.lower()}">{icon("database")}</span><div><strong>{n}</strong><small>{e} · {db}</small></div></div>'
navgroups=[('治理工作台',[('overview','治理总览')]),('元数据管理',[('sources','数据源管理'),('collection','元数据采集'),('catalog','元数据目录'),('models','数据模型'),('er','ER 关系图'),('mapping','元数据对标'),('lineage','数据血缘')]),('数据标准',[('elements','数据元'),('review','数据元审核'),('landing','标准落地'),('codes','标准代码'),('encoding','编码标准')]),('数据质量',[('profiling','数据质量探查'),('profile-reports','探查报告'),('rules','数据质量规则'),('plans','质检方案与任务'),('reports','质量报告'),('workorders','质检工单')])]
titles=dict(x for _,g in navgroups for x in g)
subtitles={'overview':'连接多源数据，建立可信标准，让每一项治理结果清晰可见。','sources':'登记连接、测试读取权限，再选择需要采集的表或集合。','models':'用清晰的关系图连接业务。跨来源组织数据表，在全屏工作台中协作与设计。','catalog':'目录与 ER 使用同一份实体、字段和结构快照。选择多个来源的表，可加入同一模型。','collection':'计划固定对象范围。执行结果由后端发布为结构快照，失败不会被当作空表删除。','mapping':'对标引用稳定字段和具体标准版本，源数据库的技术注释不会被覆盖。','lineage':'独立维护来源字段、加工任务和目标字段。表结构采集不会自动产生完整 ETL 血缘。','elements':'维护数据元定义和不可变修订，发布后的标准可用于字段对标。','review':'审核具体修订，业务说明与类型约束同时可见。','landing':'按已发布标准统计可见字段的映射情况，未映射不等同于质量失败。','codes':'维护代码集及其版本。已发布内容不可原地修改，需复制为新草稿。','encoding':'以受控分段规则定义编码格式；校验和预览不预留号码，也不承担全局唯一发号。','profiling':'读取授权范围内的实际数据，区分全量检查与抽样观测。','profile-reports':'查看历史探查结果、统计方法和未完成项目。','rules':'以模板定义质量约束，规则修订与实际执行结果分别保存。','plans':'绑定具体规则版本，按范围执行质量检查。','reports':'报告来自实际执行记录，不将失败或无数据计为满分。','workorders':'记录整改过程，关联复检证据后关闭问题。'}

def shell(content,key='overview'):
 menu=''
 for group,items in navgroups:
  menu+=f'<li class="ant-menu-item-group-title">{group}</li>'
  for slug,label in items:menu+=f'<li class="ant-menu-item {"ant-menu-item-selected" if slug==key else ""}">{icon("database" if slug in ["sources","collection"] else "model" if slug in ["models","er","lineage"] else "table" if slug=="catalog" else "file" if group=="数据标准" else "grid")}<span class="ant-menu-title-content menu-text">{label}</span></li>'
 return f'''<div id="root"><div class="ant-app"><div class="application-frame"><div class="ant-layout ant-layout-has-sider app-shell governance-shell"><aside class="ant-layout-sider side-nav"><div class="ant-layout-sider-children"><button class="wanxiang-wordmark">{brand()}<div><b>万象数据治理</b><small>DATA ELEMENTS · WANXIANG</small></div></button><ul class="ant-menu">{menu}</ul><div class="side-nav-footer"><span>数据治理工作空间</span>{btn('', 'moon','text', '切换主题')}</div></div></aside><div class="ant-layout shell-main"><header class="ant-layout-header topbar">{btn('','menu','text','展开导航')}{search('搜索数据表、字段或功能…','global-search')}<span class="topbar-spacer"></span><div class="workspace-selector">{select('企业数据工作区')}</div>{btn('','moon','text','切换浅深主题')}{btn('','bell','text','任务中心')}<button class="wx-user-menu"><span class="wx-avatar">李</span><span class="wx-user-copy"><b>李明</b><small>工作区管理员</small></span>{icon('down')}</button></header><main class="ant-layout-content main-content">{content}</main></div></div></div></div></div>'''

def heading(key,action=''):
 return f'<header class="platform-page-heading"><div class="page-heading-copy"><span class="platform-eyebrow">万象数据治理 <i></i> WANXIANG</span><h1>{titles.get(key,key)}</h1><p>{subtitles.get(key,"查看业务对象，管理工作区数据。")}</p></div><div class="ant-space page-heading-actions">{action}</div><div class="page-atmosphere"><i></i><i></i><i></i></div></header>'
def page(key,body,action=''):return f'<section class="platform-page" data-page="{titles.get(key,key)}">{heading(key,action)}{body}</section>'
def panel(title,body,desc='',cls='',more='查看详情'):return f'<section class="wx-insight-panel {cls}"><header><div><h2>{title}</h2>{"<p>"+desc+"</p>" if desc else ""}</div>{btn(more,None,"link")}</header><div class="wx-panel-body">{body}</div></section>'
def progress(n):return f'<div class="ant-progress"><div class="ant-progress-inner"><div class="ant-progress-bg" style="width:{n}%"></div></div></div>'
def table(cols,rows,actions='',filter=False):
 thead='<th class="ant-table-cell">#</th>'+''.join(f'<th class="ant-table-cell">{x}</th>' for x in cols)
 tbody=''.join('<tr class="ant-table-row">'+f'<td class="ant-table-cell">{i+1}</td>'+''.join(f'<td class="ant-table-cell">{c}</td>' for c in r)+'</tr>' for i,r in enumerate(rows))
 return f'<div class="platform-panel"><div class="platform-table-toolbar">{search()}<span class="table-count">{len(rows)} 条记录</span><span class="grow"></span><div class="table-toolbar-actions">{(select("全部类型")+select("全部状态")).replace('class="ant-select"','class="ant-select table-source-filter"') if filter else ""}{actions}{btn("","refresh",aria="刷新")}{btn("","setting",aria="列设置")}{btn("","download",aria="导出")}</div></div><div class="ant-table-wrapper"><div class="ant-table ant-table-small"><div class="ant-table-container"><div class="ant-table-content"><table><thead class="ant-table-thead"><tr>{thead}</tr></thead><tbody class="ant-table-tbody">{tbody}</tbody></table></div></div></div><ul class="ant-pagination"><li>共 {len(rows)} 条</li><li>‹</li><li class="ant-pagination-item-active">1</li><li>›</li><li>{select('15 条 / 页')}</li></ul></div></div>'
def tabs(items):return '<div class="ant-tabs-nav">'+''.join(f'<div class="ant-tabs-tab {"ant-tabs-tab-active" if i==0 else ""}">{v}</div>' for i,v in enumerate(items))+'</div>'
def thumb(seed=0):
 nodes=''.join(f'<g transform="translate({x} {y})"><rect class="thumb-node" width="180" height="118" rx="10"/><rect class="thumb-head" width="180" height="27" rx="9"/>'+''.join(f'<path class="thumb-line" d="M15 {yy}h80 M130 {yy}h35"/>' for yy in [47,68,89,108])+'</g>' for x,y in [(30,20),(290,70),(550,10),(210,250),(550,235)][:3+seed%3])
 return f'<div class="wx-model-thumbnail"><svg viewBox="0 0 770 420" aria-hidden="true">{nodes}</svg><span class="thumbnail-badge">ER</span></div>'

def overview():
 metrics=''.join(f'<button class="wx-metric"><span class="metric-icon tone-{tone}">{icon(ic)}</span><span class="metric-copy"><span class="metric-label">{label}</span><strong>{val}</strong><small>{note}</small></span><span class="metric-arrow">›</span></button>' for label,val,note,ic,tone in [('数据源数量','16','已登记的数据连接','database','purple'),('已采集实体','2,468','表、视图及集合','table','blue'),('数据模型','48','跨来源业务关系视图','model','indigo'),('待处理问题','23','需要跟进的质量问题','shield','rose'),('数据元数量','186','工作区已登记标准','file','teal')])
 cats=[('mysql','MySQL',6,37.5),('dm8','达梦 DM8',5,31.25),('postgresql','PostgreSQL',3,18.75),('mongodb','MongoDB',2,12.5)]
 offset=0;arcs='';leg=''
 for e,l,c,p in cats:
  arcs+=f'<circle class="source-{e}" cx="60" cy="60" r="47" pathLength="100" stroke-dasharray="{p-1} 100" stroke-dashoffset="{-offset}" transform="rotate(-90 60 60)"/>';offset+=p;leg+=f'<div><span><i class="source-{e}"></i>{l}</span><b>{c}</b><small>{p:.1f}%</small></div>'
 chart1=f'<div class="distribution-content"><div class="distribution-ring"><svg viewBox="0 0 120 120">{arcs}</svg><div><strong>16</strong><span>数据源</span></div></div><div class="distribution-legend">{leg}</div></div>'
 chart2='<div class="coverage-content"><div class="coverage-ring"><svg viewBox="0 0 120 120"><circle class="ring-track" cx="60" cy="60" r="49"/><circle class="ring-value" cx="60" cy="60" r="49" pathLength="100" stroke-dasharray="78.6 100" transform="rotate(-90 60 60)"/></svg><div><strong>78.6<small>%</small></strong><span>标准覆盖率</span></div></div><div class="coverage-facts"><p><span><i></i>已映射字段</span><b>1,886</b></p><p><span><i></i>可见字段</span><b>2,400</b></p><small>按已发布标准统计</small></div></div>'
 chart3='<div class="task-distribution">'+''.join(f'<div class="task-tone-{tone}"><span>{l}</span>{progress(v)}<b>{n}</b></div>' for l,v,n,tone in [('已完成',75,36,'success'),('执行中',12.5,6,'info'),('排队中',8.3,4,'purple'),('需关注',4.2,2,'warning')])+'<p>按实际执行记录汇总，不包含尚未启动的计划。</p></div>'
 jobs=[('客户主数据采集','结构规范化',66,'执行中','info','10:24'),('订单业务质量检查','检查完成',100,'已完成','success','09:36'),('组织机构采集','快照发布完成',100,'已完成','success','09:10'),('客户与合同关系发现','名称与类型分析',35,'执行中','info','08:42'),('财务指标数据探查','等待来源连接',0,'排队中','neutral','08:30')]
 jhtml='<div class="wx-dashboard-table"><table><thead><tr><th>任务名称</th><th>进度</th><th>状态</th><th>开始时间</th><th>操作</th></tr></thead><tbody>'+''.join(f'<tr><td><b>{n}</b><small>{phase}</small></td><td><div class="task-progress">{progress(pc)}<span>{pc}%</span></div></td><td>{status(st,tone)}</td><td class="muted">09/27 {dt}</td><td>{btn("详情",None,"link")}</td></tr>' for n,phase,pc,st,tone,dt in jobs)+'</tbody></table></div>'
 quick='<div class="quick-actions">'+''.join(f'<button>{icon(ic)}<span><b>{n}</b><small>{d}</small></span></button>' for n,d,ic in [('登记数据源','接入业务库','database'),('发起采集','整理表与字段','play'),('打开 ER 模型','查看跨库关联','model'),('新建数据标准','定义业务规范','file')])+'</div><div class="workspace-safety">'+icon('shield')+'<p>数据源只读访问；模型与逻辑关系保存在万象，不修改源数据库。</p></div>'
 recent='<div class="recent-models">'+''.join(f'<button class="wx-model-card">{thumb(i)}<div><h3>{n}</h3><p><span>{d}</span><span>{ct} 个实体</span></p></div></button>' for i,(n,d,ct) in enumerate([('客户订单域模型','客户域',12),('财务结算模型','财务域',8),('组织与权限模型','组织域',6)]))+'</div>'
 risks='<div class="risk-list">'+''.join(f'<button><i class="tone-{tone}"></i><span>{s}</span><b>{n}</b>{icon("arrow")}</button>' for s,n,tone in [('待处理质量问题',23,'danger'),('连接异常的数据源',1,'warning'),('失败或部分完成的任务',2,'warning'),('尚待测试的数据源',3,'info')])+'</div>'
 return page('overview',f'<div class="wx-metric-grid">{metrics}</div><div class="wx-dashboard-charts">{panel("数据源类型分布",chart1,"当前工作区可见的数据连接")}{panel("标准落地进度",chart2,"让业务字段与标准形成对应关系")}{panel("任务运行概况",chart3,"已记录任务的当前执行状态")}</div><div class="wx-dashboard-work">{panel("最近执行任务",jhtml,cls="recent-tasks",more="查看全部")}{panel("快捷操作",quick,"从连接到治理，一步进入任务",more="")}</div><div class="wx-dashboard-bottom">{panel("最近更新模型",recent,"接着上次的工作，继续完善业务关系")}{panel("需要关注",risks,"从异常来源和质量问题开始处理")}</div>',btn('登记数据源','database','primary'))

source_rows=[]
for i,(name,e,code,db) in enumerate([('客户主数据中心','DM8','dm_customer','CUSTOMER'),('交易订单库','MySQL','mysql_orders','orders_prod'),('财务结算数仓','PostgreSQL','pg_finance','finance_dw'),('组织机构服务','DM8','dm_org','ORGANIZATION'),('合同业务平台','Oracle','oracle_contract','CONTRACTS'),('用户事件日志','MongoDB','mongo_events','events'),('全文检索服务','Elasticsearch','es_search','assets')]):source_rows.append([source(name,e,db),f'<span class="muted">{code}</span>',status('异常','danger') if i==4 else status('可连接'),f'2026/09/27 0{9-i}:24','<div class="ant-space row-actions">'+btn('测试连接',None,'link')+btn('选择表并采集',None,'link')+btn('编辑',None,'link')+'</div>'])
def sources():
 stats='<div class="source-summary-strip">'+''.join(f'<div><span>{l}</span><strong>{v}</strong><small>{d}</small></div>' for l,v,d in [('全部数据源',7,'当前工作区'),('可连接',6,'最近测试通过'),('需要关注',1,'连接状态异常'),('待配置',0,'完善连接后开始采集')])+'</div>'
 return page('sources',stats+table(['数据源','代码','状态','最新测试','操作'],source_rows,filter=True),btn('登记数据源','plus','primary'))
def models():
 cards=''
 for i,(name,domain,code) in enumerate([('客户订单域模型','客户域','customer_orders'),('财务结算主题模型','财务域','finance_settlement'),('组织权限关系图','组织域','organization_access'),('商品与库存模型','商品域','product_inventory'),('合同全生命周期','合同域','contract_lifecycle'),('多渠道业务视图','渠道域','channels')]):
  cards+=f'<article class="wx-model-card"><button class="model-preview-button">{thumb(i)}</button><div class="model-card-body"><div class="model-card-title">{icon("model")}<button>{name}</button></div><p class="model-code">{code}</p><div class="model-card-meta"><span class="ant-tag">{domain}</span><span>{8+i} 个实体</span></div></div><footer><small>2026/09/27 09:30</small><div class="ant-space row-actions">{btn("全屏设计",None,"link")}{btn("","edit","text")}{btn("","copy","text")}{btn("","delete","text")}</div></footer></article>'
 return page('models',f'<div class="wx-model-toolbar">{search("搜索模型名称、代码或业务域…")}<span class="table-count">6 个模型</span><span class="grow"></span>{select("最近更新")}{btn("刷新")}</div><div class="wx-model-grid">{cards}</div>',btn('卡片','grid')+btn('列表','menu')+btn('创建模型','plus','primary'))

configs={
'collection':(['采集计划','状态','创建时间','操作'],[['客户业务库 · 结构采集',status('启用'),'2026/09/27 09:24',btn('开始采集','play','link')],['财务结算 · 表及约束采集',status('启用'),'2026/09/26 16:10',btn('开始采集','play','link')],['组织权限 · 定期整理',status('草稿','neutral'),'2026/09/26 10:38',btn('开始采集','play','link')]],'选择数据源与采集范围',['采集计划','执行记录']),
'catalog':(['名称','物理名称','来源','Schema','类型','字段数','版本'],[[btn(n,None,'link'),name,db,'BUSINESS','table',str(ct),'<span class="muted">snap-09-27</span>'] for n,name,db,ct in [('客户基础信息','customers','客户主数据中心',28),('订单主表','orders','交易订单库',34),('订单明细','order_items','交易订单库',18),('商品信息','products','财务结算数仓',24),('组织机构','organizations','组织机构服务',21),('合同记录','contracts','合同业务平台',32)]],'加入模型 · 0',[]),
'mapping':(['字段','类型','目标版本 / 字段','状态','说明','操作'],[['customers.customer_id','STANDARD','客户编号 · v2',status('已确认'),'主数据统一客户标识',btn('替换对标',None,'link')],['orders.total_amount','STANDARD','订单总金额 · v1',status('已确认'),'人民币金额，保留两位小数',btn('替换对标',None,'link')],['customers.phone','QUALITY','手机号格式规则',status('待确认','warning'),'补充质量约束',btn('替换对标',None,'link')]],'登记字段对标',[]),
'lineage':(['名称','代码','节点数','创建时间','操作'],[['客户主数据加工链路','customer_pipeline',12,'2026/09/27 09:30',btn('全屏血缘画布',None,'link')],['订单到结算加工过程','settlement_pipeline',18,'2026/09/26 18:10',btn('全屏血缘画布',None,'link')]],'创建血缘图',[]),
'elements':(['名称','代码','当前修订','状态','创建时间','操作'],[[n,code,'v2',status('已发布'),'2026/09/27 09:30',btn('详情',None,'link')+btn('新建修订',None,'link')] for n,code in [('客户编号','CUSTOMER_ID'),('客户名称','CUSTOMER_NAME'),('订单编号','ORDER_ID'),('交易金额','TRANSACTION_AMOUNT'),('组织机构代码','ORG_CODE')]],'新建数据元',[]),
'review':(['数据元','提交修订','状态','提交时间','操作'],[[n,'v3',status('待审核','warning'),'2026/09/27 10:20',btn('查看与审核',None,'link')] for n in ['客户等级','机构统一代码','合同生效日期','订单结算金额']],'',[]),
'codes':(['名称','代码','状态','草稿版本','发布版本','操作'],[[n,c,status('已发布'),3,2,btn('代码条目',None,'link')+btn('新草稿',None,'link')] for n,c in [('客户类型','CUSTOMER_TYPE'),('业务状态','BUSINESS_STATUS'),('组织机构类型','ORG_TYPE'),('付款方式','PAYMENT_METHOD')]],'新建代码集',[]),
'encoding':(['名称','代码','状态','说明','操作'],[['统一客户编码','customer_code',status('启用'),'CUS 前缀 + 8位数字',btn('编辑',None,'link')+btn('格式校验',None,'link')],['组织机构编码','org_code',status('启用'),'机构分级编码，保留前导零',btn('编辑',None,'link')+btn('格式校验',None,'link')]],'新建编码规范',[]),
'profiling':(['任务','状态','阶段','创建时间','操作'],[['客户主数据字段探查',status('已完成'),'统计已完成','2026/09/27 09:30',btn('查看结果',None,'link')],['订单金额分布探查',status('执行中','info'),'按字段统计','2026/09/27 10:30',btn('查看任务',None,'link')]],'发起数据探查',[]),
'profile-reports':(['报告','实体','统计方法','状态','观测时间','操作'],[['客户主数据探查','customers','前 5,000 行观测',status('抽样观测','info'),'2026/09/27 09:45',btn('查看报告',None,'link')],['订单金额探查','orders','受控完整检查',status('完整观测'),'2026/09/26 18:45',btn('查看报告',None,'link')]],'',[]),
'rules':(['规则名称','模板','实体','状态','版本','操作'],[[n,t,e,status('启用'),'v2',btn('查看规则',None,'link')+btn('编辑',None,'link')] for n,t,e in [('客户编号不能为空','NOT_NULL','customers'),('客户联合键唯一','UNIQUE','customers'),('订单金额非负','RANGE','orders'),('手机号格式有效','REGEX','customers'),('订单引用客户','REFERENCE','orders')]],'创建质量规则',[]),
'plans':(['方案','状态','规则数','创建时间','操作'],[['客户数据日常质量检查',status('启用'),5,'2026/09/27 09:30',btn('执行检查','play','link')+btn('编辑方案',None,'link')],['订单结算专项检查',status('启用'),8,'2026/09/26 17:20',btn('执行检查','play','link')+btn('编辑方案',None,'link')]],'新建质检方案',['质检方案','执行记录']),
'reports':(['报告','方案','状态','检查规则','完成时间','操作'],[['客户主数据质量报告','客户数据日常检查',status('发现违例','warning'),5,'2026/09/27 10:15',btn('查看报告',None,'link')],['订单结算质量报告','订单结算专项检查',status('全量通过'),8,'2026/09/26 18:00',btn('查看报告',None,'link')]],'',[]),
'workorders':(['问题','实体','规则','状态','更新时间','操作'],[['客户编号缺失','customers','NOT_NULL',status('整改中','info'),'2026/09/27 10:15',btn('处理工单',None,'link')],['订单金额越界','orders','RANGE',status('待复检','warning'),'2026/09/27 09:30',btn('查看与复检',None,'link')],['客户手机号格式异常','customers','REGEX',status('待分派','warning'),'2026/09/26 18:00',btn('分派',None,'link')]],'',['质量问题','质检工单'])}
configs['landing']=(configs['mapping'][0],configs['mapping'][1],'登记字段对标',[])
def ordinary(k):
 cols,rows,act,tt=configs[k];content=tabs(tt) if tt else ''
 if k=='landing':content+='<div class="ant-alert"><div class="ant-alert-message">已映射 1,886 / 2,400 个可见字段</div><div class="ant-alert-description">当前标准覆盖率 78.6%。未映射不等同于数据质量失败。</div></div>'
 return page(k,content+table(cols,rows),btn(act,'plus','primary') if act else '')

def item(label,value='',kind='input',required=True):
 body=select(value) if kind=='select' else f'<textarea class="ant-input">{esc(value)}</textarea>' if kind=='textarea' else f'<input class="ant-input" value="{esc(value)}" {'type="password"' if kind=="password" else ""}/>'
 return f'<div class="ant-form-item"><div class="ant-form-item-label"><label class="{"required" if required else ""}">{label}</label></div>{body}</div>'
def drawer(title,body,footer=None):return '<div class="ant-drawer"><div class="ant-drawer-mask"></div><div class="ant-drawer-content-wrapper"><div class="ant-drawer-content"><header class="ant-drawer-header"><span class="ant-drawer-title">'+title+'</span>'+btn('','close','text')+'</header><div class="ant-drawer-body">'+body+'</div><footer class="ant-drawer-footer">'+(footer or '<div class="editor-footer"><span>连接信息仅提交到当前服务端</span><div class="ant-space">'+btn('取消')+btn('保存配置',None,'primary')+'</div></div>')+'</footer></div></div></div>'
def source_editor():
 body='<form class="ant-form wx-editor-form"><div class="source-form-intro"><span class="wx-source-icon source-dm8">'+icon('database')+'</span><div><strong>连接业务数据</strong><p>配置连接信息，保存后测试权限并选择采集范围。</p></div></div>'+item('数据源名称','客户主数据中心')+'<div class="ant-form-row">'+item('唯一代码','dm_customer')+item('数据库类型','达梦 DM8','select')+'</div><div class="ant-form-row">'+item('服务端可达的主机地址','db.customer.internal')+item('端口','5236')+'</div><div class="ant-form-row">'+item('数据库 / Catalog','CUSTOMER')+item('Schema（可选）','BUSINESS',required=False)+'</div>'+item('传输安全','TLS：验证服务器身份（推荐）','select')+'<div class="ant-alert">达梦 TLS 证书目录由部署端配置。</div>'+item('只读账号','wx_reader',required=False)+item('密码','private','password',False)+'<div class="ant-alert"><div class="ant-alert-message">密码只写入，不回显</div><div class="ant-alert-description">登记后由后端测试连接。127.0.0.1 指后端所在主机，不是浏览器所在电脑。</div></div></form>'
 return shell(sources(),'sources')+drawer('登记数据源',body)
def modal(title,body):return f'<div class="ant-drawer-mask" style="position:fixed;z-index:999"></div><div class="ant-modal fixture-modal"><div class="ant-modal-content"><header class="ant-modal-title">{title}</header><div class="ant-modal-body"><form class="ant-form">{body}</form></div><footer class="ant-modal-footer">{btn("取消")}{btn("保存",None,"primary")}</footer></div></div>'
def er():
 library='<aside class="fixture-er-library"><h3>数据对象</h3>'+search('搜索表名或字段…','library-search')
 for db,es in [('交易订单库 · MySQL',['orders 订单主表','order_items 订单明细','products 商品信息']),('客户主数据 · 达梦',['customers 客户信息','organizations 组织机构']),('合同平台 · PostgreSQL',['contracts 合同记录'])]:
  library+=f'<p>{db}</p>'+''.join(f'<button class="{"selected" if "orders " in x else ""}">{icon("table")}{x}</button>' for x in es)
 library+='</aside>'
 fields=[('id','BIGINT'),('tenant_id','BIGINT'),('customer_id','BIGINT'),('order_no','VARCHAR'),('order_date','TIMESTAMP'),('status','VARCHAR'),('amount','DECIMAL')]
 specs=[('订单主表','orders','MySQL',50,108,fields),('客户信息','customers','DM8',485,108,[('tenant_id','BIGINT'),('id','BIGINT'),('customer_name','VARCHAR'),('phone','VARCHAR'),('level','VARCHAR'),('created_at','TIMESTAMP')]),('订单明细','order_items','MySQL',50,518,[('id','BIGINT'),('order_id','BIGINT'),('product_id','BIGINT'),('quantity','INT'),('unit_price','DECIMAL')]),('合同记录','contracts','PostgreSQL',485,505,[('id','BIGINT'),('tenant_id','BIGINT'),('customer_id','BIGINT'),('contract_no','VARCHAR'),('signed_at','DATE')])]
 nodes=''
 for cn,en,db,x,y,ff in specs:
  rows=''.join(f'<div class="field-row {"field-highlighted" if f in ["customer_id","tenant_id"] else ""}"><span class="field-key primary-key">{"◇" if f in ["id","tenant_id"] else "·"}</span><span class="field-name">{f}</span><span class="field-type">{t}</span></div>' for f,t in ff)
  nodes+=f'<section class="entity-card {"is-selected" if en=="orders" else ""}" style="width:284px;left:{x}px;top:{y}px"><div class="node-header"><div class="entity-source-icon">{icon("table")}</div><div class="node-title-block"><div class="node-title">{cn}</div><div class="node-english">{en}</div></div><button class="node-more">···</button></div><div class="node-fields">{rows}</div><div class="node-footer"><span>{db}</span><span class="node-meta-right">{len(ff)} 字段 · 2 关联</span></div></section>'
 links='<svg class="links"><path d="M334 260H398V229H485" stroke="var(--primary)" fill="none" stroke-width="2"/><path d="M334 226H370V194H485" stroke="var(--primary)" fill="none" stroke-width="1.5"/><path d="M334 198H410V623H334" stroke="var(--edge-catalog)" fill="none" stroke-width="1.5"/><path d="M627 410V505" stroke="var(--warning)" stroke-dasharray="6 5" fill="none" stroke-width="2"/><rect x="364" y="250" width="92" height="24" rx="6" fill="var(--surface)" stroke="var(--border)"/><text x="378" y="266" fill="var(--primary)" font-size="12">逻辑 · 2 字段</text></svg>'
 tools='<div class="canvas-tools">'+btn('选择','grid')+btn('自动布局','model')+select('关键字段')+btn('发现关系','search','primary')+'</div>'
 inspector='<aside class="fixture-er-inspector"><div class="ant-tabs-nav"><span class="ant-tabs-tab ant-tabs-tab-active">关系详情</span><span class="ant-tabs-tab">表结构</span></div><h2>订单引用客户</h2>'+status('待确认','warning')+'<div><h3>字段映射</h3><div class="fixture-mapping"><b>orders → customers</b><span>tenant_id → tenant_id</span><span>customer_id → id</span></div></div><div><h3>推荐依据</h3><p>字段语义与类型相容</p><p>目标存在完整联合主键</p><p>作用域包含 tenant_id</p></div><hr><div><h3>验证情况</h3>'+status('尚未数据验证','neutral')+'<p>本次为结构推荐，不代表已经验证业务关系。</p></div><div class="ant-alert">跨来源关系保存在万象，不会在源数据库中创建外键。</div><footer>'+btn('确认关系',None,'primary')+btn('忽略推荐')+'</footer></aside>'
 return '<div id="root"><div class="ant-app"><section class="fullscreen-workspace"><header class="fullscreen-workspace-header"><div class="fullscreen-brand">'+brand()+'</div><div class="fullscreen-heading"><span>万象数据治理 / ER 设计工作台</span><strong>客户订单域模型</strong></div><span class="fullscreen-spacer"></span><span class="fullscreen-save-state save-saved"><i></i>已保存到服务端</span><div class="fullscreen-actions">'+btn('','search','text')+btn('专注画布','grid','text')+btn('','moon','text')+btn('保存','file')+btn('关闭','close')+'</div></header><div class="fullscreen-workspace-content"><div class="fixture-er-body">'+library+'<div class="fixture-er-canvas"><div class="fixture-er-world">'+links+nodes+'</div>'+tools+'<div class="graph-legend"><span><i></i>已确认逻辑</span><span><i style="background:var(--edge-catalog)"></i>目录外键</span><span><i class="dash"></i>待确认推荐</span></div></div>'+inspector+'</div></div></section></div></div>'

def login():return '<div id="root"><div class="ant-app"><div class="login-shell"><div class="login-brand">'+brand()+'<div><h1>万象数据治理</h1><p>DATA ELEMENTS · WANXIANG</p></div>'+btn('','moon','text')+'</div><div class="ant-card login-card"><div class="ant-card-body"><h2>登录工作区</h2><p class="muted">管理数据结构、业务关系与治理流程。</p><form class="ant-form">'+item('账号','')+item('密码','','password')+btn('登录',None,'primary')+'</form><p class="login-note">首次管理员由部署端创建，没有内置通用账号和密码。</p></div></div><p class="login-footer">结构清晰 · 关系可解释 · 结果可追溯</p></div></div></div>'

def make(k,content):
 css=''.join(f'<link rel="stylesheet" href="../../../{s}">' for s in ['tests/visual/fixture-base.css','src/features/er/styles/app.css','src/features/er/styles/wanxiang.css','src/styles/experience.css','src/styles/platform.css','src/styles/refined.css'])
 controls='<div class="fixture-controls"><button class="ant-btn" onclick="document.documentElement.dataset.theme=document.documentElement.dataset.theme===\'dark\'?\'light\':\'dark\'">切换主题</button></div>'
 js="document.documentElement.dataset.theme=new URLSearchParams(location.search).get('theme')==='dark'?'dark':'light';document.querySelectorAll('button[aria-label*=主题]').forEach(b=>b.addEventListener('click',()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark'));"
 (OUT/f'{k}.html').write_text(f'<!doctype html><html lang="zh-CN" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>隔离视觉检查 · {esc(titles.get(k,k))}</title>{css}</head><body>{content}{controls}<script>{js}</script></body></html>')

make('overview',shell(overview()))
make('sources',shell(sources(),'sources'))
make('models',shell(models(),'models'))
for k in configs:make(k,shell(ordinary(k),k))
make('er',er());make('login',login());make('source-editor',source_editor())
make('standard-editor',shell(ordinary('elements'),'elements')+modal('创建数据元',item('名称','客户统一编号')+item('唯一代码','CUSTOMER_IDENTIFIER')+item('业务定义','标识同一租户内唯一的客户，用于多个业务系统间的标准映射。','textarea')+'<div class="ant-form-row">'+item('标准数据类型','VARCHAR','select')+item('最大长度','64')+'</div>'+item('说明','保留前导零，不转换为整数。','textarea',False)))
make('rule-editor',shell(ordinary('rules'),'rules')+modal('创建质量规则',item('规则名称','客户编号不能为空')+item('规则模板','NOT_NULL · 非空检查','select')+item('元数据实体','customers · 客户主数据中心','select')+item('字段','customer_id','select')+item('规则说明','对授权范围内客户记录检查必填标识。','textarea',False)))
make('mapping-editor',shell(ordinary('mapping'),'mapping')+modal('登记字段对标',item('元数据实体','customers','select')+item('字段','customer_id','select')+item('对标类型','已发布的数据元修订','select')+item('目标','客户编号 · v2','select')+item('业务说明','','textarea',False)))
make('job-drawer',shell(ordinary('collection'),'collection')+drawer('任务详情 · 结构采集','<div class="ant-space">'+status('执行中','info')+'<span class="muted">2026/09/27 10:24</span></div><h3>当前进度</h3>'+progress(66)+'<p class="muted">已处理 32 / 48 个对象 · 正在读取约束</p><h3>执行日志</h3>'+''.join(f'<div class="job-event"><strong>{t}</strong><small>10:{24+i}:12</small><span>{d}</span></div>' for i,(t,d) in enumerate([('连接检查完成','已验证账号可读取所选目录'),('已冻结采集范围','48 个对象，主键及目录约束'),('开始读取结构','按顺序读取表与字段定义'),('读取约束信息','联合键按成员顺序归组')])),'<div class="editor-footer">'+btn('关闭')+btn('请求取消任务')+'</div>'))
make('encoding-editor',shell(ordinary('encoding'),'encoding')+modal('新建编码规范',item('规范名称','统一客户编码')+item('代码','customer_code')+'<p class="muted">按顺序定义每一段，不接受脚本或任意表达式。</p>'+''.join('<div class="ant-space encoding-segment"><div class="ant-space-item">'+item('类型',t,'select')+'</div><div class="ant-space-item">'+item('固定文本',v,required=False)+'</div><div class="ant-space-item">'+item('长度',n,required=False)+'</div><div class="ant-space-item" style="padding-top:28px">'+btn('','delete')+'</div></div>' for t,v,n in [('固定文本','CUS-','4'),('数字','','8')])+btn('增加编码段','plus')))
# This list determines the isolation test count. No production API or authentication is substituted.
manifest=[{'key':f.stem,'file':f.name,'label':titles.get(f.stem,f.stem)} for f in sorted(OUT.glob('*.html'))]
(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
print('Generated',len(manifest),'ISOLATED visual fixtures, using production CSS; no React/Ant runtime.')
