import { useState } from 'react';
import { Button, Empty, Progress, Segmented, Select, Space, Tooltip } from 'antd';
import { ArrowRightOutlined, DatabaseOutlined, FileProtectOutlined, FolderOutlined, ReloadOutlined, ShopOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { assetsApi, type Metric, type Statistics, type WorkbenchPage } from '../../../services/assets';
import { organizationOptions } from '../../../services/datasourceRegistrationApi';
import { platformApi } from '../../../shared/platformApi';
import { AssetError, AssetName, AssetPage, AssetPanel, AssetStatus, assetCount, assetDate, useAssetQuery } from '../shared';
type Stats=Statistics & {departments?:{id:string;name:string;value:number}[]};
const metricValue=(metric?:Metric)=>metric?.status==='AVAILABLE'?metric.value:null;
export function AssetOverviewPage(){
 const nav=useNavigate();const [layer,setLayer]=useState('OVERVIEW'),[department,setDepartment]=useState<string>(),[days,setDays]=useState(30);
 const stats=useAssetQuery('statistics:'+layer+':'+department+':'+days,signal=>assetsApi.get<Stats>('/statistics',{layer,departmentId:department,from:new Date(Date.now()-days*86400000).toISOString(),to:new Date().toISOString()},{signal}));
 const todos=useAssetQuery('overview:todos',signal=>assetsApi.get<WorkbenchPage>('/workbench',{tab:'TODOS',pageNo:1,pageSize:5},{signal}));
 const organizations=useAssetQuery('asset:organizations',async signal=>organizationOptions(await platformApi<unknown>('/sym/org/pageOrg',undefined,{signal})));
 const metrics=stats.data?.metrics??[];const metric=(code:string)=>metrics.find(m=>m.code===code);const value=(code:string)=>metricValue(metric(code));
 const coverage=value('STANDARD_COVERAGE'),quality=value('QUALITY_PASS_RATE');
 const jump=(code:string)=>{
  const target=metric(code)?.drilldownFilters??{};const params=new URLSearchParams();
  if(target.departmentId)params.set('departmentId',target.departmentId);if(target.applicationId)params.set('applicationId',target.applicationId);
  if(code==='LISTED_CATALOG_COUNT'){nav('/assets/market?'+params);return;}
  if(code==='ACTIVE_SUBSCRIPTION_COUNT'){nav('/assets/workbench/subscriptions');return;}
  if(code==='STANDARD_COVERAGE'){nav('/governance/standards/landing');return;}
  if(code==='QUALITY_PASS_RATE'){nav('/governance/quality/reports');return;}
  const kinds:Record<string,string>={APPLICATION_COUNT:'APPLICATION',DATASOURCE_COUNT:'DATASOURCE',TABLE_COUNT:'TABLE',FIELD_COUNT:'TABLE',CATALOG_COUNT:'CATALOG'};
  if(kinds[code])params.set('kinds',kinds[code]);nav('/assets/map?'+params);
 };
 const kpis=layer==='INGESTION'?[['APPLICATION_COUNT','应用系统',<FolderOutlined/>],['DATASOURCE_COUNT','业务数据源',<DatabaseOutlined/>],['TABLE_COUNT','已采集表',<DatabaseOutlined/>],['FIELD_COUNT','已采集字段',<FileProtectOutlined/>]] as const:layer==='PLATFORM'?[['TABLE_COUNT','技术表',<DatabaseOutlined/>],['CATALOG_COUNT','资源目录',<FolderOutlined/>],['STANDARD_COVERAGE','标准覆盖率',<FileProtectOutlined/>],['QUALITY_PASS_RATE','质量检查通过率',<FileProtectOutlined/>]] as const:[['CATALOG_COUNT','登记资源目录',<FolderOutlined/>],['LISTED_CATALOG_COUNT','已上架目录',<ShopOutlined/>],['ACTIVE_SUBSCRIPTION_COUNT','有效资源订阅',<FileProtectOutlined/>],['STANDARD_COVERAGE','标准覆盖率',<DatabaseOutlined/>]] as const;
 return <AssetPage title="数据资产全景" description="从数据来源到共享使用，掌握资产分布、治理情况与业务进展。" actions={<><Select allowClear showSearch optionFilterProp="label" placeholder="全部部门" value={department} options={organizations.data??[]} onChange={setDepartment} style={{width:170}}/><Select value={days} options={[{value:7,label:'近7天'},{value:30,label:'近30天'},{value:90,label:'近90天'}]} onChange={setDays}/><Button icon={<ReloadOutlined/>} onClick={()=>{stats.refresh();todos.refresh();}}>刷新</Button></>}>
 <AssetError error={stats.error} retry={stats.refresh}/>
 <div className="hy-layer-tabs"><Segmented value={layer} onChange={setLayer} options={[{value:'OVERVIEW',label:'总览'},{value:'INGESTION',label:'数据汇聚层'},{value:'PLATFORM',label:'大数据平台层'},{value:'SHARING',label:'共享开放层'}]}/><span className="hy-muted">统计更新 {assetDate(metrics.find(m=>m.asOf)?.asOf)}</span></div>
 <div className="hy-kpis">{kpis.map(([code,label,icon])=><button key={code} className="hy-kpi" onClick={()=>jump(code)}><span>{label}</span><i>{icon}</i><strong>{stats.loading&&!stats.data?'…':assetCount(value(code))}<small>{code.endsWith('RATE')||code==='STANDARD_COVERAGE'?'%':metric(code)?.unit??''}</small></strong><p>{metric(code)?.status==='AVAILABLE'?'查看明细 →':stats.loading?'正在读取':metric(code)?.status==='NOT_CONNECTED'?'尚未接入':'暂无统计结果'}</p></button>)}</div>
 <div className="hy-overview-main"><AssetPanel title="资产全流程分布" extra={<Button type="link" onClick={()=>nav('/assets/map')}>资产地图 <ArrowRightOutlined/></Button>}>
 <div className="hy-flow"><div><h3>数据汇聚层</h3><button onClick={()=>jump('APPLICATION_COUNT')}><span>应用系统</span><b>{assetCount(value('APPLICATION_COUNT'))}</b></button><button onClick={()=>jump('DATASOURCE_COUNT')}><span>业务数据源</span><b>{assetCount(value('DATASOURCE_COUNT'))}</b></button></div><ArrowRightOutlined className="hy-flow-arrow"/><div><h3>大数据平台层</h3><button className="hy-flow-catalog" onClick={()=>jump('CATALOG_COUNT')}><span>统一资源目录</span><b>{assetCount(value('CATALOG_COUNT'))}</b><small>标准关联 · 质量检查</small><small>{assetCount(value('TABLE_COUNT'))} 张技术表</small></button></div><ArrowRightOutlined className="hy-flow-arrow"/><div><h3>共享开放层</h3><button onClick={()=>jump('LISTED_CATALOG_COUNT')}><span>发布与上架</span><b>{assetCount(value('LISTED_CATALOG_COUNT'))}</b></button><button className="hy-flow-delivery" onClick={()=>jump('ACTIVE_SUBSCRIPTION_COUNT')}><span>有效资源订阅</span><b>{assetCount(value('ACTIVE_SUBSCRIPTION_COUNT'))}</b></button></div></div><p className="hy-caption">按当前租户与授权部门范围去重统计</p></AssetPanel>
 <AssetPanel title="治理就绪情况" extra={<Button type="link" className="hy-governance-link" onClick={()=>nav('/governance/overview')}>查看治理 →</Button>}><div className="hy-coverage"><Progress type="circle" percent={coverage??0} format={()=>coverage==null?'—':coverage+'%'} strokeColor="#56c8b1" size={106}/><div><span>标准覆盖率</span><p>已关联标准字段 <b>{assetCount(metric('STANDARD_COVERAGE')?.numerator)}</b></p><p>可统计字段 <b>{assetCount(metric('STANDARD_COVERAGE')?.denominator)}</b></p></div></div><div className="hy-quality-line"><span>质量检查通过率</span><b>{quality==null?'未取得检查结果':quality+'%'}</b><Progress percent={quality??0} showInfo={false} strokeColor="#56c8b1"/></div><Space wrap><Button onClick={()=>nav('/governance/metadata/collection')}>采集字段</Button><Button onClick={()=>nav('/governance/quality/reports')}>质量报告</Button></Space></AssetPanel></div>
 <div className="hy-overview-bottom"><AssetPanel title={stats.data?.departments?.length?'部门共享排行':'热门资源'} extra={<Button type="link" onClick={()=>nav('/assets/market')}>数据超市 →</Button>}>
 {stats.data?.departments?.length?<div className="hy-ranking">{stats.data.departments.slice(0,6).map((r,i)=><button key={r.id} onClick={()=>nav('/assets/market?departmentId='+encodeURIComponent(r.id))}><span>{String(i+1).padStart(2,'0')}</span><Tooltip title={r.name}><b>{r.name}</b></Tooltip><Progress percent={Math.max(1,r.value/Math.max(...stats.data!.departments!.map(d=>d.value),1)*100)} showInfo={false}/><strong>{assetCount(r.value)}</strong></button>)}</div>:stats.data?.rankings?.length?<div className="hy-ranking">{stats.data.rankings.slice(0,6).map((r,i)=><button key={r.object.kind+r.object.id} onClick={()=>nav('/assets/detail/'+r.object.kind+'/'+encodeURIComponent(r.object.id))}><span>{i+1}</span><b title={r.object.name}>{r.object.name}</b><Progress percent={r.value/Math.max(...stats.data!.rankings.map(v=>v.value),1)*100} showInfo={false}/><strong>{assetCount(r.value)}</strong></button>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={stats.loading?'正在读取排行':'暂无共享使用记录'}/>}</AssetPanel>
 <AssetPanel title="待处理事项" extra={<Button type="link" onClick={()=>nav('/assets/workbench/todos')}>工作台 →</Button>}><AssetError error={todos.error} retry={todos.refresh}/>{todos.data?.items?.length?<div className="hy-overview-todos">{todos.data.items.map(item=><div key={item.id} className="hy-todo-row"><AssetName name={item.title} onClick={()=>nav('/assets/workbench/todos?taskId='+encodeURIComponent(item.id))}/><AssetStatus value={item.status}/></div>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={todos.loading?'正在读取待办':'暂无待处理事项'}/>}</AssetPanel></div>
 </AssetPage>;
}
