import { useState } from 'react';
import { App, Button, Dropdown, Empty, Input, Select, Table, Tag, Tooltip } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useStudio } from '../store';
import type { ViewModel } from '../core/model';
import { displayDate, errorText } from '../core/model';
import { Icon } from './Icon';
function Thumbnail({diagram}:{diagram:ViewModel}){
  const data=useStudio(s=>s.data)!;const nodes=diagram.nodes.slice(0,20);const ids=new Set(nodes.map(n=>n.entityId));
  if(!nodes.length)return <div className="diagram-thumb empty"><Icon name="layout" size={30}/></div>;
  const minX=Math.min(...nodes.map(n=>n.position.x)),minY=Math.min(...nodes.map(n=>n.position.y));const maxX=Math.max(...nodes.map(n=>n.position.x))+284,maxY=Math.max(...nodes.map(n=>n.position.y))+230;
  return <svg className="diagram-thumb" viewBox={`${minX-40} ${minY-40} ${maxX-minX+80} ${maxY-minY+80}`} aria-hidden="true">{data.relationships.filter(r=>ids.has(r.sourceEntityId)&&ids.has(r.targetEntityId)&&diagram.relationFilter.includes(r.reviewStatus as 'observed'|'confirmed'|'suggested')&&!diagram.hiddenRelationshipIds.includes(r.id)).map(r=>{const s=nodes.find(n=>n.entityId===r.sourceEntityId)!,t=nodes.find(n=>n.entityId===r.targetEntityId)!;return <path key={r.id} d={`M${s.position.x+130},${s.position.y+60} L${t.position.x+130},${t.position.y+60}`} fill="none" stroke={r.origin==='catalog'?'var(--edge-catalog)':r.reviewStatus==='suggested'?'var(--edge-suggested)':'var(--edge-logical)'} strokeWidth={5} strokeDasharray={r.reviewStatus==='suggested'?'14 10':undefined}/>;})}{nodes.map(n=><g key={n.entityId} transform={`translate(${n.position.x},${n.position.y})`}><rect width={284} height={204} rx={12} fill="var(--surface)" stroke="var(--border)" strokeWidth={3}/><rect width={284} height={55} rx={12} fill="var(--surface-muted)"/><text x={17} y={36} fill="var(--text)" fontSize={22}>{data.snapshot.entities.find(e=>e.id===n.entityId)?.displayName??'Table'}</text>{[88,122,156].map(y=><path key={y} d={`M20 ${y}h120 M175 ${y}h60`} stroke="var(--border-strong)" strokeWidth={5}/>)}</g>)}</svg>;
}
export function DiagramList({onCreate,onRename}:{onCreate:()=>void;onRename:(id:string)=>void}){
  const data=useStudio(s=>s.data)!;const{modal,message}=App.useApp();const[query,setQuery]=useState('');const[grid,setGrid]=useState(false);const[sort,setSort]=useState('updated');
  const filtered=data.diagrams.filter(d=>`${d.name} ${d.description??''}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'zh-CN'):new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime());
  const relationCount=(d:ViewModel)=>{const ids=new Set(d.nodes.map(n=>n.entityId));return data.relationships.filter(r=>ids.has(r.sourceEntityId)&&ids.has(r.targetEntityId)&&d.relationFilter.includes(r.reviewStatus as 'observed'|'confirmed'|'suggested')&&!d.hiddenRelationshipIds.includes(r.id)).length;};
  function action(key:string,id:string){if(key==='open')void useStudio.getState().switchDiagram(id).catch(e=>message.error(errorText(e)));if(key==='rename')onRename(id);if(key==='copy')modal.confirm({title:'复制关系图',icon:null,content:'副本只复制范围与布局，继续共享同一工作区的逻辑关系。对关系的编辑会同步影响其他视图。',okText:'创建副本',cancelText:'取消',onOk:async()=>{await useStudio.getState().duplicateDiagram(id);message.success('已创建视图副本。');}});if(key==='delete')modal.confirm({title:'删除这张关系图？',icon:null,content:'只删除此视图，不删除实体、工作区关系或源数据库中的内容。',okText:'删除视图',cancelText:'取消',okButtonProps:{danger:true},onOk:async()=>{try{await useStudio.getState().deleteDiagram(id);message.success('关系图已删除。');}catch(e){message.error(errorText(e));throw e;}}});}
  const menu=(id:string)=>({items:[{key:'open',label:'打开关系图'},{key:'rename',label:'重命名'},{key:'copy',label:'复制视图'},{type:'divider' as const},{key:'delete',label:'删除视图',danger:true,disabled:data.diagrams.length<=1}],onClick:({key}:{key:string})=>action(key,id)});
  const columns:ColumnsType<ViewModel>=[{title:'关系图',dataIndex:'name',key:'name',sorter:(a,b)=>a.name.localeCompare(b.name,'zh-CN',{numeric:true}),render:(name:string,d)=><button className="diagram-name" onClick={()=>action('open',d.id)}><span className="diagram-icon"><Icon name="layout" size={22}/></span><span><strong>{name}{d.id===data.activeDiagramId&&<Tag bordered={false} color="blue">当前</Tag>}</strong><small>{d.description||'尚未填写说明'}</small></span></button>},{title:'实体',key:'nodes',width:90,render:(_,d)=>d.nodes.length},{title:'关系',key:'relations',width:90,render:(_,d)=>relationCount(d)},{title:'最近更新',dataIndex:'updatedAt',key:'time',width:150,sorter:(a,b)=>(Date.parse(a.updatedAt||'')||0)-(Date.parse(b.updatedAt||'')||0),render:(value:string)=>displayDate(value)},{title:'操作',className:'wx-action-column',fixed:'right',align:'center',key:'action',width:100,render:(_,d)=><div className="table-actions"><Button type="link" size="small" onClick={()=>action('open',d.id)}>打开</Button><Dropdown trigger={['click']} menu={menu(d.id)}><Button type="text" size="small" aria-label={`${d.name}操作`} icon={<Icon name="more" size={18}/>}/></Dropdown></div>}];
  return <main className="diagrams-page"><div className="page-heading"><div><div className="eyebrow">数据治理 / 数据模型</div><h1>关系图管理</h1><p>用不同视角组织数据，共享同一份关系模型。</p></div><Button type="primary" icon={<Icon name="plus" size={16}/>} onClick={onCreate}>新建关系图</Button></div><div className="list-toolbar"><Input placeholder="搜索关系图…" value={query} onChange={e=>setQuery(e.target.value)} prefix={<Icon name="search" size={16}/>} allowClear style={{maxWidth:320}}/><span>{filtered.length} 张关系图</span><Select aria-label="关系图排序" value={sort} onChange={setSort} options={[{value:'updated',label:'最近更新'},{value:'name',label:'名称排序'}]} style={{width:120,marginLeft:'auto'}}/><div className="view-switch"><Tooltip title="列表视图"><Button type={grid?'text':'default'} icon={<Icon name="list" size={16}/>} aria-label="列表视图" onClick={()=>setGrid(false)}/></Tooltip><Tooltip title="卡片视图"><Button type={grid?'default':'text'} icon={<Icon name="grid" size={16}/>} aria-label="卡片视图" onClick={()=>setGrid(true)}/></Tooltip></div></div>{grid?<div className="diagram-grid">{!filtered.length&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="没有找到关系图"/>}{filtered.map(d=><article className="diagram-tile" key={d.id}><button className="thumbnail-button" onClick={()=>action('open',d.id)}><Thumbnail diagram={d}/></button><div className="diagram-tile-body"><div><button className="tile-name" onClick={()=>action('open',d.id)}>{d.name}</button><Dropdown trigger={['click']} menu={menu(d.id)}><Button size="small" type="text" icon={<Icon name="more" size={17}/>} aria-label={`${d.name}操作`}/></Dropdown></div><p>{d.description||'尚未填写说明'}</p><footer>{d.nodes.length} 个实体 <span>·</span> {relationCount(d)} 条关系 <time>{displayDate(d.updatedAt)}</time></footer></div></article>)}</div>:<Table columns={columns} dataSource={filtered} rowKey="id" pagination={filtered.length>10?{pageSize:10}:false} locale={{emptyText:<Empty description="没有找到关系图"/>}}/>}</main>;
}
