import { useState } from 'react';
import { App, Alert, Button, Descriptions, Form, Input, Modal, Select, Space } from 'antd';
import { foundationApi, refreshWorkspace } from '../services/workspace';
import { useSession } from '../mock/store';
import type { Application } from '../domain/types';
interface Client { id: string; appId: string; version: number; clientType: string; name: string; }
interface Configuration { version: number; protocol: string; scopes: string[]; redirects: Array<{ uri: string; type: string }>; hasSecret: boolean; status: string; }
export function ProtocolConfiguration({ client, writable, onChanged }: { client: Client; writable: boolean; onChanged: () => Promise<void> }) {
    const domain = useSession()!.domain; const [open, setOpen] = useState(false); const [config, setConfig] = useState<Configuration | null>(null); const [error, setError] = useState(''); const [form] = Form.useForm(); const { message, modal } = App.useApp();
    const load = async () => { try { const value = await foundationApi.read<Configuration>(`/idaas/protocol-config/read?id=${client.id}&domain=${domain}`); setConfig(value); form.setFieldsValue({ scopes: value.scopes.length ? value.scopes : client.clientType === 'SERVICE' ? ['api'] : ['openid', 'profile'], redirects: value.redirects.filter(r => r.type === 'LOGIN').map(r => r.uri).join('\n'), logoutRedirects: value.redirects.filter(r => r.type === 'LOGOUT').map(r => r.uri).join('\n'), secret: '' }); setOpen(true); setError(''); } catch (e) { message.error(e instanceof Error ? e.message : '无法读取配置'); } };
    const changeMode = async (enabled: boolean) => { try { const apps = await foundationApi.read<Application[]>('/idaas/applications/list?domain=' + domain); const app = apps.find(a => a.id === client.appId); if (!app) throw new Error('无法读取当前应用版本'); await foundationApi.write('/idaas/protocol-config/federation', { id: client.id, version: config!.version, appVersion: app.version, domain, enabled }); await refreshWorkspace(); setOpen(false); await onChanged(); message.success(enabled ? '应用已启用统一认证' : '应用已恢复本地认证模式'); } catch (e) { setError(e instanceof Error ? e.message : '更新失败'); } };
    return <><Button type="link" onClick={() => void load()}>认证配置</Button><Modal open={open} title={'认证接入 · ' + client.name} width={640} onCancel={() => setOpen(false)} footer={null} destroyOnHidden>{error && <Alert type="error" title={error} showIcon />}<Alert type="info" title="认证配置与应用认证模式分别启用" description="配置客户端后，仍需明确启用应用的统一认证。原应用本地账号凭据保持独立。" showIcon /><Descriptions size="small" items={[{ key: 'protocol', label: '认证协议', children: config?.protocol }, { key: 'status', label: '状态', children: config?.status === 'ACTIVE' ? '启用' : '未启用' }]} style={{ marginTop: 16 }} /><Form size="small" form={form} layout="vertical" disabled={!writable} onFinish={async values => { try { const redirects = (name: string, type: string) => String(values[name] || '').split('\n').map(uri => uri.trim()).filter(Boolean).map(uri => ({ uri, type })); await foundationApi.write('/idaas/protocol-config/configure', { id: client.id, version: config!.version, domain, scopes: values.scopes, secret: values.secret, redirects: [...redirects('redirects', 'LOGIN'), ...redirects('logoutRedirects', 'LOGOUT')] }); await onChanged(); setOpen(false); message.success('客户端认证配置已保存'); } catch (e) { setError(e instanceof Error ? e.message : '配置失败'); } }}><Form.Item name="scopes" label="认证范围" rules={[{ required: true }]}><Select mode="multiple" options={(client.clientType === 'SERVICE' ? ['api'] : ['openid', 'profile', 'email', 'api']).map(value => ({ value, label: value }))} /></Form.Item>{client.clientType !== 'SERVICE' && <><Form.Item name="redirects" label="登录回调地址" extra="每行一个精确地址，生产使用HTTPS，开发可使用localhost。"><Input.TextArea rows={3} /></Form.Item><Form.Item name="logoutRedirects" label="退出回调地址"><Input.TextArea rows={2} /></Form.Item></>}{client.clientType !== 'PUBLIC' && <Form.Item name="secret" label="独立客户端密钥" extra={config?.hasSecret ? '留空保留当前密钥；填写新密钥会撤销旧认证会话。' : '使用32至72位独立随机字符。请通过部署的秘密管理妥善保管。'}><Input.Password autoComplete="new-password" /></Form.Item>}<Button type="primary" htmlType="submit">保存认证配置</Button></Form><Space wrap style={{ marginTop: 24 }}><Button disabled={!writable || config?.status !== 'ACTIVE'} onClick={() => modal.confirm({ title: '启用此应用的统一认证？', content: '请确认应用已实现OIDC接入，并配置了独立认证账号和有效应用授权。', onOk: () => changeMode(true) })}>启用应用统一认证</Button><Button disabled={!writable} onClick={() => void changeMode(false)}>使用本地认证模式</Button><Button danger disabled={!writable || config?.status !== 'ACTIVE'} onClick={() => { void foundationApi.write('/idaas/protocol-config/disable', { id: client.id, version: config!.version, domain }).then(async () => { setOpen(false); await onChanged(); }).catch(e => setError(e.message)); }}>停用客户端</Button></Space></Modal></>;
}
