import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Descriptions, Select, Skeleton, Table, Tabs, Tag } from 'antd';
import { AppstoreOutlined, ArrowLeftOutlined, CheckCircleOutlined, StarFilled, StarOutlined } from '@ant-design/icons';
import { useNavigate, useParams } from 'react-router-dom';
import { assetsApi } from '../../../services/assets';
import type { CatalogDetail, DataItem, FavoriteResult, ObjectDetail, PreviewResult, VersionPage } from '../../../services/assets.types';
import { ConsumerEmpty, ConsumerError, ConsumerName, ConsumerPage, ConsumerStatus, can, channelNames, displayType, formatTime, kindNames, useConsumerAction, useConsumerRead } from './consumerShared';
import { SubscriptionDrawer, type SubscriptionAttachment, type SubscriptionVersion } from './SubscriptionDrawer';

function CatalogPreview({ detail, versionId, attachments }: { detail: ObjectDetail; versionId: string; attachments: SubscriptionAttachment[] }) {
  const [attachmentId, setAttachmentId] = useState(attachments.find(item => item.resourceType === 'TABLE')?.id);
  const preview = useConsumerRead(`preview:${detail.summary.object.id}:${versionId}:${attachmentId}`, signal => assetsApi.post<PreviewResult>('/preview', { object: detail.summary.object, catalogVersionId: versionId, attachmentId, limit: 10 }, { signal }), !!attachmentId);
  return <><Select aria-label="预览资源" value={attachmentId} style={{ width: '100%', marginBottom: 16 }} onChange={setAttachmentId} options={attachments.filter(item => item.id && item.resourceType === 'TABLE').map(item => ({ value: item.id, label: item.resource.name }))}/><ConsumerError error={preview.error} retry={preview.refresh}/>{!attachmentId ? <ConsumerEmpty text="暂无可预览的数据表"/> : <Table tableLayout="fixed" size="middle" loading={preview.loading} pagination={false} scroll={{ x: Math.max(600, (preview.data?.columns.length || 0) * 160) }} dataSource={(preview.data?.rows || []).map((row, index) => ({ key: index, ...Object.fromEntries(row.cells.map(cell => [cell.itemId, cell.value])) }))} columns={(preview.data?.columns || []).map(item => ({ title: item.name, dataIndex: item.id || item.code, width: 160, ellipsis: true, render: value => value == null ? '—' : String(value) }))} locale={{ emptyText: preview.error ? '数据预览读取失败' : '暂无可预览数据' }}/>}</>;
}

export function AssetMarketDetailPage() {
  const { catalogId = '' } = useParams(), nav = useNavigate(), [tab, setTab] = useState('items'), [subscription, setSubscription] = useState(false), [attachmentId, setAttachmentId] = useState<string>();
  const { busy, run } = useConsumerAction();
  const detail = useConsumerRead(`market-detail:${catalogId}`, signal => assetsApi.get<ObjectDetail>(`/objects/CATALOG/${encodeURIComponent(catalogId)}`, { view: 'MARKET' }, { signal }));
  const info = detail.data?.details as CatalogDetail | undefined;
  const versionId = detail.data?.summary.publishedVersionId || info?.versionId || '';
  const version = useConsumerRead(`market-version:${catalogId}:${versionId}`, signal => assetsApi.get<SubscriptionVersion>(`/catalogs/${encodeURIComponent(catalogId)}/versions/${encodeURIComponent(versionId)}`, {}, { signal }), !!versionId);
  const history = useConsumerRead(`market-history:${catalogId}`, signal => assetsApi.get<VersionPage>(`/catalogs/${encodeURIComponent(catalogId)}/versions`, { pageNo: 1, pageSize: 30, sortBy: 'createdAt', sortOrder: 'desc' }, { signal }), tab === 'history');
  const visited = useRef('');
  useEffect(() => { if (detail.data?.summary.object && visited.current !== catalogId) { visited.current = catalogId; void assetsApi.post('/visits', { action: 'RECORD', object: detail.data.summary.object }).catch(() => { /* Visiting succeeds independently of optional footprint recording. */ }); } }, [catalogId, detail.data]);
  const attachments = version.data?.attachments || (info?.attachments as SubscriptionAttachment[] | undefined) || [], items = version.data?.items || info?.items || [], policy = version.data?.sharingPolicy || info?.sharingPolicy;
  const delivery = attachments.filter(item => item.bindingRole === 'DELIVERY' && item.resourceType !== 'DIRECTORY' && item.channel);
  const selectedAttachmentId = attachmentId || delivery[0]?.id;
  const canSubscribe = detail.data?.summary.listingStatus === 'LISTED' && !!version.data && policy?.shareType !== 'PROHIBITED' && (can(detail.data?.summary.allowedActions, 'SUBSCRIBE') || can(version.data?.allowedActions, 'SUBSCRIBE'));
  const itemColumns = [{ title: '数据项名称', key: 'name', width: 210, ellipsis: true, sorter: (a: DataItem, b: DataItem) => a.name.localeCompare(b.name, 'zh-CN'), render: (_: unknown, row: DataItem) => <ConsumerName name={row.name} code={row.code}/> }, { title: '类型 / 长度', key: 'type', width: 150, ellipsis: true, render: (_: unknown, row: DataItem) => displayType(row) }, { title: '数据标准', dataIndex: 'standardCode', key: 'standard', width: 165, ellipsis: true, render: (value: string) => value ? <span style={{ color: '#56c8b1' }}>{value}</span> : <span className="hy-text-muted">未关联标准</span> }, { title: '可空', dataIndex: 'nullable', key: 'nullable', width: 70, render: (value: boolean) => value ? '是' : '否' }];
  return <ConsumerPage title="资源目录详情" description="查看发布范围与数据项，按业务所需申请使用。" actions={<Button icon={<ArrowLeftOutlined/>} onClick={() => nav('/assets/market')}>返回数据超市</Button>}>
    <ConsumerError error={detail.error} retry={detail.refresh}/>
    {detail.loading && !detail.data ? <Skeleton active paragraph={{ rows: 8 }}/> : detail.data && <div className="hy-detail-grid"><section className="hy-panel"><div className="hy-detail-hero"><div className="hy-detail-hero-top"><span className="hy-resource-icon"><AppstoreOutlined/></span><div><h2>{detail.data.summary.object.name}</h2><div className="hy-detail-hero-code">{info?.catalogCode || detail.data.summary.object.code || '—'}</div></div></div><div className="hy-detail-meta"><span>{detail.data.summary.departmentName || '提供部门未填写'}</span>{version.data && <span>发布版本 v{version.data.version.versionNo}</span>}<span>更新于 {formatTime(detail.data.summary.updatedAt)}</span></div>{detail.data.description && <p>{detail.data.description}</p>}</div>
      <ConsumerError error={version.error} retry={version.refresh}/>
      <Tabs className="hy-detail-tabs" activeKey={tab} onChange={setTab} destroyOnHidden items={[
        { key: 'items', label: <>数据项 <Tag>{items.length}</Tag></>, children: <div className="hy-detail-tab-content"><Table<DataItem> rowKey={item => item.id || item.code} tableLayout="fixed" columns={itemColumns} dataSource={items} size="middle" pagination={{ pageSize: 10, showSizeChanger: false, hideOnSinglePage: true }} scroll={{ x: 595 }} locale={{ emptyText: '暂无数据项' }}/></div> },
        { key: 'resources', label: '挂接资源', children: <div className="hy-detail-tab-content hy-resource-list">{attachments.length ? attachments.map(item => <div className="hy-resource-row" key={item.id || item.resource.id}><ConsumerName name={item.resource.name} code={item.resource.code}/><div><Tag>{kindNames[item.resource.kind]}</Tag><Tag>{item.bindingRole === 'DELIVERY' ? channelNames[item.channel || ''] || '交付资源' : item.bindingRole === 'REFERENCE' ? '关联目录' : '来源资源'}</Tag></div></div>) : <ConsumerEmpty text="暂无挂接资源"/>}</div> },
        { key: 'preview', label: '数据预览', children: <div className="hy-detail-tab-content">{policy?.previewMode === 'MASKED_SAMPLE' && can(detail.data.summary.allowedActions, 'PREVIEW') ? <CatalogPreview detail={detail.data} versionId={versionId} attachments={attachments}/> : <ConsumerEmpty text="当前目录未开放数据预览"/>}</div> },
        { key: 'history', label: '更新记录', children: <div className="hy-detail-tab-content"><ConsumerError error={history.error} retry={history.refresh}/><Table rowKey="id" size="middle" loading={history.loading} pagination={false} dataSource={history.data?.items || []} columns={[{ title: '版本', width: 90, render: (_, row) => `v${row.versionNo}` }, { title: '状态', width: 110, render: (_, row) => <ConsumerStatus value={row.status}/> }, { title: '发布时间', dataIndex: 'publishedAt', render: formatTime, sorter: (a, b) => (a.publishedAt || '').localeCompare(b.publishedAt || '') }]} locale={{ emptyText: '暂无发布记录' }}/></div> },
      ]}/></section><aside className="hy-panel hy-detail-aside"><h2>申请使用该资源</h2>{delivery.length ? delivery.map(item => <button className={`hy-channel-option ${selectedAttachmentId === item.id ? 'is-selected' : ''}`} key={item.id} onClick={() => setAttachmentId(item.id)}><div>{channelNames[item.channel || '']}<small>{item.resource.name}</small></div>{selectedAttachmentId === item.id && <CheckCircleOutlined style={{ color: '#d7aa62' }}/>}</button>) : <ConsumerEmpty text="暂无交付资源"/>}
      <div className="hy-aside-row"><span>共享方式</span><strong>{policy?.shareType === 'CONDITIONAL' ? '有条件共享' : policy?.shareType === 'UNCONDITIONAL' ? '无条件共享' : policy?.shareType === 'PROHIBITED' ? '不予共享' : '未配置'}</strong></div><div className="hy-aside-row"><span>提供部门</span><strong>{detail.data.summary.departmentName || '—'}</strong></div>{policy?.maxUseDays && <div className="hy-aside-row"><span>最长使用期限</span><strong>{policy.maxUseDays} 天</strong></div>}{policy?.useConditions && <p className="hy-use-conditions">{policy.useConditions}</p>}
      <Button type="primary" size="large" block disabled={!canSubscribe || !delivery.length} onClick={() => setSubscription(true)}>申请订阅</Button><Button block loading={busy} icon={detail.data.summary.favorite ? <StarFilled/> : <StarOutlined/>} onClick={() => void run(() => assetsApi.put<FavoriteResult>(`/favorites/CATALOG/${encodeURIComponent(catalogId)}`, { favorited: !detail.data!.summary.favorite }), detail.data!.summary.favorite ? '已取消收藏' : '已收藏')}>{detail.data.summary.favorite ? '已收藏' : '收藏目录'}</Button><div className="hy-flow-stages"><span>提交申请</span><span>→</span><span>审批</span><span>→</span><span>授权交付</span></div>
      {detail.data.summary.listingStatus !== 'LISTED' && <Alert type="warning" title="当前目录未上架，暂不能申请"/>}
      <Descriptions size="small" column={1} items={[{ key: 'quality', label: '治理状态', children: detail.data.summary.governance?.qualityStatus === 'PASSED' ? '检查通过' : detail.data.summary.governance?.qualityStatus === 'ISSUES' ? '存在待处理问题' : '暂无已通过的检查结果' }]}/>
    </aside></div>}
    {subscription && versionId && <SubscriptionDrawer catalogId={catalogId} versionId={versionId} initialAttachmentId={selectedAttachmentId} onClose={() => setSubscription(false)}/>}
  </ConsumerPage>;
}
