import { useState } from 'react';
import { Button, Input, Pagination, Select, Skeleton, Tag, Tooltip } from 'antd';
import { AppstoreOutlined, ArrowRightOutlined, ReloadOutlined, SearchOutlined, StarFilled, StarOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { assetsApi } from '../../../services/assets';
import type { AssetPage, FavoriteResult } from '../../../services/assets.types';
import { ConsumerEmpty, ConsumerError, ConsumerPage, channelNames, formatTime, useConsumerAction, useConsumerRead } from './consumerShared';

export function AssetMarketPage() {
  const nav = useNavigate(), [keyword, setKeyword] = useState(''), [channel, setChannel] = useState<string>(), [topic, setTopic] = useState(''), [page, setPage] = useState(1), [size, setSize] = useState(12), [order, setOrder] = useState('updatedAt:desc');
  const { run, busy } = useConsumerAction(); const [sortBy, sortOrder] = order.split(':');
  const list = useConsumerRead(`market:${keyword}:${channel}:${topic}:${page}:${size}:${order}`, signal => assetsApi.get<AssetPage>('/search', { view: 'MARKET', kinds: 'CATALOG', keyword, channel, topicCode: topic, pageNo: page, pageSize: size, sortBy, sortOrder }, { signal }));
  const favorite = (id: string, favorited: boolean) => run(() => assetsApi.put<FavoriteResult>(`/favorites/CATALOG/${encodeURIComponent(id)}`, { favorited }), favorited ? '已收藏' : '已取消收藏');
  return <ConsumerPage title="数据超市" description="发现可申请的数据资源，让业务需求与可信数据相遇。" actions={<Button onClick={() => nav('/assets/workbench/demands?create=1')}>提交数据需求</Button>}>
    <div className="hy-market-search"><div><h2>找到业务需要的每一份数据</h2><p>按目录名称、编码或业务关键词查找已上架资源</p></div><Input.Search size="large" allowClear aria-label="搜索数据资源" placeholder="搜索目录名称、编码或关键词" prefix={<SearchOutlined/>} onSearch={value => { setKeyword(value.trim()); setPage(1); }}/></div>
    <ConsumerError error={list.error} retry={list.refresh}/>
    <div className="hy-consumer-toolbar" style={{ padding: 0 }}><div className="hy-toolbar-filters"><Select allowClear aria-label="资源交付方式" placeholder="全部交付方式" value={channel} onChange={value => { setChannel(value); setPage(1); }} options={Object.entries(channelNames).map(([value, label]) => ({ value, label }))}/><Input allowClear aria-label="主题代码" placeholder="主题代码，回车筛选" style={{ width: 190 }} onPressEnter={event => { setTopic(event.currentTarget.value.trim()); setPage(1); }} onChange={event => { if (!event.target.value) { setTopic(''); setPage(1); } }}/><span className="hy-workbench-count">{list.loading && !list.data ? '读取中…' : list.error && !list.data ? '读取失败' : `共 ${list.data?.page.total ?? 0} 个资源目录`}</span></div><div className="hy-toolbar-actions"><Select aria-label="目录排序" value={order} onChange={value => { setOrder(value); setPage(1); }} options={[{ value: 'updatedAt:desc', label: '最近更新' }, { value: 'updatedAt:asc', label: '最早更新' }, { value: 'name:asc', label: '名称升序' }, { value: 'name:desc', label: '名称降序' }]}/><Button icon={<ReloadOutlined/>} aria-label="刷新数据超市" onClick={list.refresh}/></div></div>
    {list.loading && !list.data ? <div className="hy-market-grid">{Array.from({ length: 6 }, (_, index) => <div className="hy-market-card" key={index}><Skeleton active paragraph={{ rows: 3 }}/></div>)}</div> : list.data?.items.length ? <div className="hy-market-grid">{list.data.items.map(item => <article className="hy-market-card" key={item.object.id}><div className="hy-market-card-top"><span className="hy-resource-icon"><AppstoreOutlined/></span><Tooltip title={item.favorite ? '取消收藏' : '收藏资源'}><Button type="text" aria-label={`${item.favorite ? '取消收藏' : '收藏'}${item.object.name}`} disabled={busy} icon={item.favorite ? <StarFilled style={{ color: '#d7aa62' }}/> : <StarOutlined/>} onClick={() => void favorite(item.object.id, !item.favorite)}/></Tooltip></div><h3><Tooltip title={item.object.name}><button onClick={() => nav(`/assets/market/${encodeURIComponent(item.object.id)}`)}>{item.object.name}</button></Tooltip></h3><p className="hy-market-card-code" title={item.object.code}>{item.object.code || '—'}</p><p>{item.departmentName || '提供部门未填写'}</p><div className="hy-tags">{item.channels?.map(value => <Tag key={value}>{channelNames[value] || value}</Tag>)}{item.tags?.slice(0, 3).map(value => <Tag key={value}>{value}</Tag>)}</div><div className="hy-market-card-bottom"><span>{formatTime(item.updatedAt)}</span><Button type="link" onClick={() => nav(`/assets/market/${encodeURIComponent(item.object.id)}`)}>查看资源<ArrowRightOutlined/></Button></div></article>)}</div> : !list.error && <div className="hy-panel"><ConsumerEmpty text={keyword || topic || channel ? '没有符合筛选条件的资源目录' : '暂无已上架资源目录'}/></div>}
    {!!list.data?.page.total && <Pagination className="hy-market-pagination" current={page} pageSize={size} total={list.data.page.total} showSizeChanger pageSizeOptions={[12, 24, 48]} onChange={(next, nextSize) => { setPage(nextSize === size ? next : 1); setSize(nextSize); }}/>}
  </ConsumerPage>;
}
