import { useEffect,useRef,useState } from 'react';
import { Alert,App,Button,Drawer,Input,Select,Space,Table,Tag } from 'antd';
import type { Row } from '../../services/api';
import { compileFieldMapping,mappingDependencies,normalizeMapping,recommendFieldMapping,validateFieldMapping,dictionaryLookupTemplate } from '../../services/lineage';
import { ErrorNotice } from './common';
const blank=()=>({version:'1.0',passthroughUnmapped:false,passthroughCaseSensitive:true,onMissingSource:'NULL',onTypeMismatch:'SKIP_ROW',mappings:[]});
const kind=(m:Row)=>m.userFunction?'function':m.lookup?'lookup':Object.hasOwn(m,'constant')?'constant':m.fromList?'concat':m.transform?.fn==='jsonValue'?'json':m.transform?'transform':m.expression!=null?'expression':'from';
const functionNames=(text:string)=>{try{return Object.keys(JSON.parse(text));}catch{return [];}};
function mappingArguments(m:Row):Row {
 const {functionArgsText,transformArgsText,...value}=m;
 for(const [text,key]of [[functionArgsText,'userFunction'],[transformArgsText,'transform']])if(text!==undefined){let args;try{args=JSON.parse(text||'[]');if(!Array.isArray(args)||args.length>8)throw Error();}catch{throw new Error('函数常量参数须为最多 8 项的 JSON 数组');}value[key]={...value[key],args};}
 return value;
}
export function FieldMappingEditor({node,tables,columns,onClose,onApply}:{node:Row|null;tables:Row[];columns:Row[];onClose:()=>void;onApply:(config:Row)=>void}){
 const [source,setSource]=useState(''),[target,setTarget]=useState(''),[spec,setSpec]=useState<Row>(blank),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[compiled,setCompiled]=useState<Row|null>(null),[functions,setFunctions]=useState('{}');const {message,modal}=App.useApp(),dirty=useRef(false);
 useEffect(()=>{let active=true;if(!node)return;dirty.current=false;setReady(false);setSpec(blank());setSource(node.config?.sourceTableId||'');setTarget(node.config?.targetTableId||'');setCompiled(null);setError('');setBusy(true);normalizeMapping(node.config?.mappings||blank()).then(s=>{if(active){setSpec(s);setFunctions(JSON.stringify(s.functions||{},null,2));setReady(true);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[node]);
 const fields=(id:string)=>columns.filter(c=>c.table_id===id).map(c=>({name:c.column_name,path:'/'+c.column_name,type:c.column_type||c.data_type||'string',nullable:![0,'0',false].includes(c.nullable),isPk:[1,'1',true].includes(c.primary_key)}));
 const sourceFields=fields(source),targetFields=fields(target),names=sourceFields.map(f=>f.name);
 const setMappings=(items:Row[])=>{dirty.current=true;setSpec(s=>({...s,mappings:items}));setCompiled(null);setError('');};
 const close=()=>{if(busy)return;if(dirty.current)modal.confirm({title:'放弃尚未应用的字段规则？',okText:'放弃修改',cancelText:'继续编辑',onOk:onClose});else onClose();};
 const update=(index:number,patch:Row)=>setMappings(spec.mappings.map((m:Row,i:number)=>i===index?{...m,...patch}:m));
 const attempt=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const check=async()=>{if(!ready)throw new Error('原规则尚未成功读取，不能覆盖');if(!source||!target||!sourceFields.length||!targetFields.length)throw new Error('请选择已采集字段的源表和目标表');if(!spec.mappings?.length)throw new Error('至少配置一条字段规则');let definitions:Row;try{definitions=JSON.parse(functions);if(!definitions||Array.isArray(definitions)||typeof definitions!=='object'||Object.keys(definitions).length>16)throw Error();}catch{throw new Error('自定义函数须为最多 16 项的 JSON 对象');}const normalized=await normalizeMapping({...spec,mappings:spec.mappings.map(mappingArguments),functions:definitions});const validation=await validateFieldMapping(normalized,sourceFields,targetFields);if(!validation.valid)throw new Error(validation.errors.map((r:Row)=>r.message||r.code).join('；'));const result=await compileFieldMapping(normalized);setCompiled({...result,warnings:validation.warnings});return {...result,spec:normalized};};
 return <Drawer open={!!node} title={`${node?.label||'转换节点'} · 字段转换规则`} width="min(1120px, 100vw)" zIndex={1100} mask={{closable:false}} onClose={close} extra={<Space><Button disabled={!ready} loading={busy} onClick={()=>attempt(async()=>{await check();message.success('字段规则校验和编译通过');})}>校验并推导</Button><Button type="primary" disabled={!ready} loading={busy} onClick={()=>attempt(async()=>{const result=await check();onApply({...node?.config,sourceTableId:source,targetTableId:target,mappings:JSON.stringify(result.spec)});message.success('规则已应用到画布，请再保存加工图');})}>应用到画布</Button></Space>}>
  <Alert className="mb16" type="info" showIcon title="共享转换规则，不执行加工" description="复用 NiFi 的推荐、校验和 SQL 编译接口。字段依赖由显式映射和表达式推导；不是已执行的运行血缘。保存画布后原接入任务也能读取这些规则。"/>
  <Space className="mb16" wrap><Select style={{width:330}} showSearch optionFilterProp="label" aria-label="转换源表" placeholder="选择源表" value={source||undefined} onChange={v=>{dirty.current=true;setSource(v);setCompiled(null);}} options={tables.map(t=>({value:t.tid,label:`${t.table_name_cn||t.table_comment||t.table_name} · ${t.table_name}`}))}/><span>→</span><Select style={{width:330}} showSearch optionFilterProp="label" aria-label="转换目标表" placeholder="选择目标表" value={target||undefined} onChange={v=>{dirty.current=true;setTarget(v);setCompiled(null);}} options={tables.map(t=>({value:t.tid,label:`${t.table_name_cn||t.table_comment||t.table_name} · ${t.table_name}`}))}/><Button disabled={busy||!ready||!source||!target} onClick={()=>modal.confirm({title:'按共享推荐替换当前映射？',content:'将替换当前节点尚未保存的映射，其他节点不变。',onOk:()=>attempt(async()=>{const r=await recommendFieldMapping(sourceFields,targetFields);dirty.current=true;setSpec(r.spec);setCompiled(null);})})}>推荐字段映射</Button></Space>
  <ErrorNotice error={error}/><Table rowKey={(_,i)=>String(i)} dataSource={spec.mappings||[]} pagination={false} scroll={{x:1000}} columns={[
   {title:'规则类型',width:145,render:(_,m,i)=><Select aria-label={`规则类型${i+1}`} value={kind(m)} options={[['from','直接映射'],['transform','基础函数'],['expression','转换表达式'],['constant','常量'],['concat','多字段拼接'],['json','JSON 标量提取'],['lookup','字典查询'],['function','自定义表达式函数']].map(([value,label])=>({value,label}))} onChange={mode=>{const next={...m};for(const key of ['from','expression','fromList','constant','lookup','transform','userFunction','functionArgsText','transformArgsText','lookupTableId','lookupKeyColumn','lookupValueColumn'])delete next[key];if(mode==='expression')next.expression='';else if(mode==='constant')next.constant='';else if(mode==='concat'){next.fromList=[];next.transform={fn:'concat',args:['']};}else {next.from='';if(mode==='transform')next.transform={fn:'upper'};if(mode==='json')next.transform={fn:'jsonValue',args:['$.value']};if(mode==='lookup')next.lookup={};if(mode==='function'){next.userFunction={name:'',from:'',args:[]};delete next.from;}}setMappings(spec.mappings.map((r:Row,n:number)=>i===n?next:r));}}/>},
   {title:'来源 / 转换表达式',width:360,render:(_,m,i)=><MappingControls mapping={m} fields={sourceFields} tables={tables} columns={columns} functions={functionNames(functions)} busy={busy} onChange={patch=>update(i,patch)} onAttempt={attempt}/>},
   {title:'目标字段',width:220,render:(_,m,i)=><Select aria-label={`目标字段${i+1}`} showSearch optionFilterProp="label" value={m.to} options={targetFields.map(f=>({value:f.path,label:f.name}))} onChange={to=>update(i,{to})}/>},
   {title:'推导的来源依赖',width:230,render:(_,m)=>mappingDependencies(m,names).join('、')||(m.lookup?'字典及其参数（保留）':'常量 / 暂无可解析字段')},
   {title:'操作',className:'wx-action-column',fixed:'right',align:'center',width:80,render:(_,_m,i)=><Button type="link" danger disabled={busy} onClick={()=>setMappings(spec.mappings.filter((_m:Row,n:number)=>i!==n))}>删除</Button>}
  ]}/><Button className="mt16" disabled={busy} onClick={()=>setMappings([...spec.mappings,{from:'',to:''}])}>添加转换规则</Button>
  <details className="mt16"><summary>自定义表达式函数 · 可复用规则</summary><p className="muted">以 JSON 定义命名的表达式函数，例如 {JSON.stringify({normalizeCode:{expression:'UPPER(TRIM(${value}))'}})}。${'{value}'} 表示选定来源字段，${'{arg:0}'} 表示常量参数；编译为共享 QueryRecord SQL，不执行任意 Java、脚本或未注册的原生函数。</p><Input.TextArea aria-label="自定义函数定义" value={functions} rows={6} maxLength={16000} onChange={e=>{dirty.current=true;setFunctions(e.target.value);setCompiled(null);}}/></details>
  {compiled&&<><h3>编译后的加工 SQL</h3><pre style={{whiteSpace:'pre-wrap',padding:16,background:'var(--surface-muted)'}}>{compiled.finalQuery||compiled.query}</pre>{compiled.warnings?.map((w:Row,i:number)=><Alert key={i} type="warning" title={w.message||w.code}/>)}</>}
 </Drawer>;
}

function MappingControls({mapping:m,fields,tables,columns,functions,busy,onChange,onAttempt}:{mapping:Row;fields:Row[];tables:Row[];columns:Row[];functions:string[];busy:boolean;onChange:(patch:Row)=>void;onAttempt:(action:()=>Promise<void>)=>Promise<void>}) {
 const mode=kind(m),options=fields.map(f=>({value:f.path,label:f.name})),dictionary=columns.filter(c=>c.table_id===m.lookupTableId).map(c=>({value:c.column_name,label:c.column_comment||c.column_name}));
 if(mode==='expression')return <Input.TextArea aria-label="转换表达式" rows={2} value={m.expression} maxLength={4000} placeholder={'例如 UPPER(${field:name})'} onChange={e=>onChange({expression:e.target.value})}/>;
 if(mode==='constant')return <Space direction="vertical"><Select value={m.constant===null?'null':typeof m.constant} options={[{value:'string',label:'文本常量'},{value:'number',label:'数值常量'},{value:'boolean',label:'布尔常量'},{value:'null',label:'NULL 常量'}]} onChange={type=>onChange({constant:type==='null'?null:type==='number'?0:type==='boolean'?false:''})}/>{m.constant!==null&&(typeof m.constant==='boolean'?<Select value={m.constant} options={[{value:true,label:'true'},{value:false,label:'false'}]} onChange={constant=>onChange({constant})}/>:<Input value={m.constant} type={typeof m.constant==='number'?'number':'text'} onChange={e=>onChange({constant:typeof m.constant==='number'?Number(e.target.value):e.target.value})}/>)}</Space>;
 if(mode==='concat')return <Space direction="vertical"><Select mode="multiple" style={{width:330}} value={m.fromList} options={options} onChange={fromList=>onChange({fromList})}/><Input addonBefore="分隔符" value={m.transform?.args?.[0]||''} onChange={e=>onChange({transform:{fn:'concat',args:[e.target.value]}})}/></Space>;
 if(mode==='function')return <Space direction="vertical"><Select style={{width:330}} placeholder="选择函数定义" value={m.userFunction?.name||undefined} options={functions.map(value=>({value,label:value}))} onChange={name=>onChange({userFunction:{...m.userFunction,name}})}/><Select style={{width:330}} placeholder="函数来源字段" value={m.userFunction?.from} options={options} onChange={from=>onChange({userFunction:{...m.userFunction,from}})}/><Input placeholder="常量参数 JSON 数组（可空）" maxLength={4000} value={m.functionArgsText??JSON.stringify(m.userFunction?.args||[])} onChange={e=>onChange({functionArgsText:e.target.value})}/></Space>;
 const source=<Select style={{width:330}} aria-label="来源字段" showSearch optionFilterProp="label" value={m.from} options={options} onChange={from=>onChange({from})}/>;
 if(mode==='json')return <Space direction="vertical">{source}<Input addonBefore="JSON 路径" placeholder="$.person.id 或 $.items[0].code" value={m.transform?.args?.[0]} onChange={e=>onChange({transform:{fn:'jsonValue',args:[e.target.value]}})}/></Space>;
 if(mode==='transform')return <Space direction="vertical">{source}<Select style={{width:330}} value={m.transform?.fn} options={['upper','lower','trim','ltrim','rtrim','toInt','toLong','toDouble','toDecimal','cast','coalesce','nvl','enumMap'].map(value=>({value,label:value}))} onChange={fn=>onChange({transform:{fn,args:[]},transformArgsText:'[]'})}/><Input placeholder={'函数常量参数 JSON 数组，例如 ["VARCHAR"]'} maxLength={4000} value={m.transformArgsText??JSON.stringify(m.transform?.args||[])} onChange={e=>onChange({transformArgsText:e.target.value})}/></Space>;
 if(mode==='lookup')return <Space direction="vertical">{source}<Select style={{width:330}} placeholder="已登记字典表" value={m.lookupTableId} showSearch optionFilterProp="label" options={tables.map(t=>({value:t.tid,label:t.table_name_cn||t.table_name}))} onChange={lookupTableId=>onChange({lookupTableId,lookupKeyColumn:undefined,lookupValueColumn:undefined})}/><Space><Select placeholder="字典键" value={m.lookupKeyColumn} options={dictionary} onChange={lookupKeyColumn=>onChange({lookupKeyColumn})}/><Select placeholder="字典值" value={m.lookupValueColumn} options={dictionary} onChange={lookupValueColumn=>onChange({lookupValueColumn})}/></Space><Select value={m.lookup?.onMissing||'NULL'} options={[{value:'NULL',label:'无命中 → NULL'},{value:'KEEP_SOURCE',label:'无命中 → 保留原值'},{value:'FAIL',label:'无命中 → 错误路由'}]} onChange={onMissing=>onChange({lookup:{...m.lookup,onMissing}})}/><Button disabled={busy||!m.lookupTableId||!m.lookupKeyColumn||!m.lookupValueColumn} onClick={()=>onAttempt(async()=>{const table=tables.find(t=>t.tid===m.lookupTableId);const lookup=await dictionaryLookupTemplate({datasourceId:table?.datasource_id,tableId:m.lookupTableId,keyColumn:m.lookupKeyColumn,valueColumn:m.lookupValueColumn});onChange({lookup:{...lookup,onMissing:m.lookup?.onMissing||'NULL'}});})}>生成参数化字典规则</Button>{!m.lookupTableId&&m.lookup.sql&&<Tag>原字典规则已保留，可重新选表替换</Tag>}</Space>;
 return source;
}
