import { useState } from 'react';
import { Alert, App, Button, Drawer, Form, Input, Modal, Select, Space, Tabs } from 'antd';
import { ReactFlow, Background, Controls, MiniMap, applyNodeChanges, applyEdgeChanges, addEdge, type Node, type Edge } from '@xyflow/react';
import { api, all, canManage, canWrite, loadSession, versionOf, type Row } from '../../services/api';
import { useWorkspaceQuery } from '../../services/useWorkspaceQuery';
import { FullscreenWorkspace } from '../../app/FullscreenWorkspace';
import { useStudio } from '../er/store';
import { DataTable, EditorModal, JobDrawer, JsonDetail, Page, download, date, opts, required, statusColumn, timeColumn, useAction } from './common';
export function TaskCenter({ open, onClose }: {
    open: boolean;
    onClose: () => void;
}) { const q = useWorkspaceQuery(`task-center-${open}`, s => open ? all('jobs', {}, s) : Promise.resolve([]), open); const [id, setId] = useState<string | null>(null); return <><Drawer open={open} width={900} title="任务中心" onClose={onClose}><DataTable rows={q.data} loading={q.loading} error={q.error} onRefresh={q.refresh} columns={[{ title: '任务标识', dataIndex: 'id', ellipsis: true }, { title: '类型', dataIndex: 'type' }, statusColumn, { title: '阶段', dataIndex: 'phase' }, { title: '创建时间', dataIndex: 'created_at', render: date }, { title: '操作', width: 116, render: (_, r) => <Button type="link" onClick={() => setId(r.id)}>日志与结果</Button> }]}/></Drawer><JobDrawer id={id} onClose={() => setId(null)}/></>; }
function ScheduleFields({ collections, quality }: {
    collections: Row[];
    quality: Row[];
}) { const f = Form.useFormInstance(), type = Form.useWatch('type', f); return <><Form.Item name="name" label="调度名称" rules={required}><Input /></Form.Item><Form.Item name="type" label="任务类型" rules={required}><Select onChange={() => f.setFieldValue('definitionId', undefined)} options={[{ value: 'COLLECTION', label: '元数据采集' }, { value: 'QUALITY', label: '数据质量检查' }]}/></Form.Item><Form.Item name="definitionId" label="任务方案" rules={required}><Select options={opts(type === 'COLLECTION' ? collections : quality)}/></Form.Item><Form.Item name="cron" label="六字段 Cron（秒 分 时 日 月 周）" rules={required}><Input placeholder="0 0 2 * * *"/></Form.Item><Form.Item name="timezone" label="IANA 时区" rules={required}><Input placeholder="Asia/Shanghai"/></Form.Item><Form.Item name="status" label="状态"><Select options={[{ value: 'ACTIVE', label: '启用' }, { value: 'DISABLED', label: '停用' }]}/></Form.Item><Alert showIcon type="info" title="调度仅在当前浏览器打开时执行" description="关闭页面期间暂停；再次打开时最多补执行一次，不会持续在后台运行。"/></>; }
export function SchedulesPanel() { const q = useWorkspaceQuery('schedules-admin', s => Promise.all([all('schedules', {}, s), all('collection-plans', {}, s), all('quality-plans', {}, s)])); const [edit, setEdit] = useState<Row | null>(), [times, setTimes] = useState<Row | null>(null); const [rows, collections, quality] = q.data ?? [[], [], []]; const { run } = useAction(); return <><Button type="primary" onClick={() => setEdit(null)} style={{ marginBottom: 16 }}>新建调度</Button><DataTable rows={rows} error={q.error} loading={q.loading} onRefresh={q.refresh} columns={[{ title: '名称', dataIndex: 'name' }, { title: 'Cron', dataIndex: 'cron_expression' }, statusColumn, { title: '下次触发', dataIndex: 'next_fire_at', render: date }, { title: '操作', width: 128, render: (_, r) => <Space><Button type="link" onClick={() => setEdit(r)}>编辑</Button><Button type="link" onClick={() => run(async () => setTimes(await api('schedules/preview', { method: 'POST', body: { cron: r.cron_expression, timezone: r.timezone } })), '')}>预计时间</Button></Space> }]}/><EditorModal open={edit !== undefined} title="本地任务调度" initial={edit ? { ...edit, type: edit.job_type, definitionId: edit.definition_id, cron: edit.cron_expression } : { type: 'COLLECTION', cron: '0 0 2 * * *', timezone: 'Asia/Shanghai', status: 'ACTIVE' }} onCancel={() => setEdit(undefined)} onSave={v => api(edit ? `schedules/${edit.id}` : 'schedules', { method: edit ? 'PUT' : 'POST', version: edit ? versionOf(edit) : undefined, body: v })}><ScheduleFields collections={collections} quality={quality}/></EditorModal><Modal open={!!times} title="后续触发时间" onCancel={() => setTimes(null)} footer={<Button onClick={() => setTimes(null)}>关闭</Button>}><p>时区：{times?.timezone}</p>{times?.times.map((t: string) => <p key={t}>{t} · {date(t)}</p>)}</Modal></>; }
export function Administration({ open, onClose }: {
    open: boolean;
    onClose: () => void;
}) { const q = useWorkspaceQuery(`members-admin-${open}`, s => open ? Promise.all([api('members', { signal: s }), all('sources', {}, s)]) : Promise.resolve<[
    Row,
    Row[]
]>([{ items: [] }, []])); const [edit, setEdit] = useState(false), [grant, setGrant] = useState<Row | null>(null), [source, setSource] = useState<string>(), [permissions, setPermissions] = useState<string[]>(['metadata.read']); const { busy, run } = useAction(); const [members, sources] = q.data ?? [{ items: [] }, []]; return <Drawer width={1000} open={open} title="工作区管理" onClose={onClose}><Tabs items={[{ key: 'members', label: '成员与来源授权', children: <><Alert className="mb16" type="info" showIcon title="工作身份用于本地流程与操作权限展示" description="审核人不能处理自己的申请。所有记录位于同一浏览器，角色设置不构成真实的安全隔离。"/><Button type="primary" onClick={() => setEdit(true)} style={{ marginBottom: 16 }}>添加或调整成员</Button><DataTable rows={members.items.map((m: Row) => ({ ...m, id: m.principalId }))} loading={q.loading} error={q.error} onRefresh={q.refresh} columns={[{ title: '姓名', dataIndex: 'name' }, { title: '账号', dataIndex: 'username' }, { title: '角色', dataIndex: 'role' }, { title: '操作', width: 116, render: (_, r) => <Button type="link" onClick={() => { setGrant(r); setPermissions(['metadata.read']); setSource(undefined); }}>来源授权</Button> }]}/></> }, { key: 'schedule', label: '计划调度', children: open ? <SchedulesPanel /> : null }]}/><EditorModal open={edit} title="添加或调整成员" initial={{ role: 'EDITOR' }} onCancel={() => setEdit(false)} onSave={v => api('members', { method: 'POST', body: v })}><Form.Item name="username" label="工作账号" rules={required}><Input autoComplete="off"/></Form.Item><Form.Item name="name" label="显示姓名" rules={required}><Input /></Form.Item><Form.Item name="role" label="工作区角色" rules={required}><Select options={['OWNER', 'STEWARD', 'EDITOR', 'VIEWER', 'REVIEWER'].map(value => ({ value, label: value }))}/></Form.Item></EditorModal><Modal open={!!grant} title={`来源授权 · ${grant?.name ?? ''}`} onCancel={() => setGrant(null)} confirmLoading={busy} onOk={() => run(async () => { await api('source-grants', { method: 'POST', body: { principalId: grant!.principalId, sourceId: source, permissions } }); setGrant(null); })}><Form layout="vertical"><Form.Item label="数据源"><Select options={opts(sources)} value={source} onChange={setSource}/></Form.Item><Form.Item label="允许的权限（替换所选来源原授权）"><Select mode="multiple" value={permissions} onChange={setPermissions} options={['metadata.read', 'collect', 'profile', 'validate', 'preview', 'export'].map(value => ({ value, label: value }))}/></Form.Item></Form></Modal></Drawer>; }
export function BackupDrawer({open,onClose,onImported}:{open:boolean;onClose:()=>void;onImported:(workspace:string)=>void}) {
 const [preview,setPreview]=useState<Row|null>(null),[name,setName]=useState('导入工作区');const {busy,run}=useAction();
 return <Drawer width={760} open={open} title="工作区备份" onClose={onClose}>
  <Alert showIcon type="info" title="将当前工作区保存为 JSON 文件" description="包含结构、模型、治理记录和本地数据集，不包含数据库密码。导入会创建新的工作区，原工作区保持不变。"/>
  <Space wrap style={{margin:'24px 0'}}><Button type="primary" disabled={!canManage()} loading={busy} onClick={()=>run(async()=>{const b=await api('backup');download(JSON.stringify(b,null,2),`万象本地工作区-${new Date().toISOString().slice(0,10)}.json`);},'工作区已导出')}>导出工作区备份</Button>
  <Button disabled={busy||!canManage()} onClick={()=>document.getElementById('local-backup-file')?.click()}>导入并预检</Button><input id="local-backup-file" hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setPreview(null);await run(async()=>{if(f.size>20*1024*1024)throw new Error('文件不能超过20MB');const content=JSON.parse(await f.text());setPreview(await api('imports',{method:'POST',body:content}));},'预检完成，尚未创建新工作区');}}/></Space>
  {preview&&<><h3>预检结果</h3><JsonDetail value={preview}/><Form layout="vertical"><Form.Item label="新工作区名称"><Input value={name} onChange={e=>setName(e.target.value)} maxLength={128}/></Form.Item></Form><Button type="primary" loading={busy} onClick={()=>run(async()=>{const out=await api(`imports/${preview.batchId}/commit`,{method:'POST',version:versionOf(preview),body:{name}});await loadSession();setPreview(null);onImported(out.workspaceId);onClose();},'已导入到新工作区')}>确认导入新工作区</Button></>}
  <h3>导入格式</h3><p>支持本版完整工作区 JSON、ER 工作区 JSON，以及统一元数据 JSON。导入后，人工逻辑关系恢复为待确认，历史验证证据不会冒充新的验证结果。</p>
  <p className="muted">结构导入不会自动生成源表记录。没有本地记录时，探查结果显示“无可验证数据”；可从元数据目录录入本地记录。</p>
  <Alert type="warning" showIcon title="请定期导出备份" description="清除浏览器站点数据、使用隐私窗口或切换网址，可能使本地记录不可用。工作区数据没有云端副本。"/>
 </Drawer>;
}
export function AuditPanel({ open, onClose }: {
    open: boolean;
    onClose: () => void;
}) { const q = useWorkspaceQuery(`audit-${open}`, s => open ? all('audit', {}, s) : Promise.resolve([])); return <Drawer width={1000} open={open} title="本地操作记录" onClose={onClose}><DataTable rows={q.data} loading={q.loading} error={q.error} onRefresh={q.refresh} columns={[{ title: '时间', dataIndex: 'created_at', render: date }, { title: '动作', dataIndex: 'action' }, { title: '对象类型', dataIndex: 'object_type' }, { title: '对象', dataIndex: 'object_id', ellipsis: true }, { title: '操作者', dataIndex: 'principal_id', ellipsis: true }, { title: '结果', dataIndex: 'outcome' }]}/></Drawer>; }
export function LineagePage() { const q = useWorkspaceQuery('lineage', s => Promise.all([all('lineage', {}, s), all('directory', {}, s)])); const [edit, setEdit] = useState<Row | null>(), [current, setCurrent] = useState<Row | null>(null), [nodes, setNodes] = useState<Node[]>([]), [edges, setEdges] = useState<Edge[]>([]), [dirty, setDirty] = useState(false), [add, setAdd] = useState(false), [kind, setKind] = useState('entity'), [eid, setEid] = useState<string>(), [fid, setFid] = useState<string>(), [label, setLabel] = useState(''); const { busy, run } = useAction(); const { message, modal } = App.useApp(); const theme = useStudio(s => s.theme); const [rows, entities] = q.data ?? [[], []]; const open = (r: Row) => { const graph = r.graph_json ?? {}; const layout = r.layout_json ?? {}; setNodes((graph.nodes ?? []).map((n: Row, i: number) => ({ id: n.id, position: layout.positions?.[n.id] ?? { x: 80 + (i % 3) * 300, y: 80 + Math.floor(i / 3) * 170 }, data: { label: n.label ?? n.name ?? n.id, domain: n }, type: 'default' }))); setEdges((graph.edges ?? []).map((e: Row) => ({ id: e.id ?? crypto.randomUUID(), source: e.source, target: e.target, label: e.label }))); setCurrent(r); setDirty(false); }; const save = async () => { if (!current || !dirty)
    return; const graph = { nodes: nodes.map(n => ({ ...n.data.domain as Row, id: n.id, label: n.data.label })), edges: edges.map(e => ({ id: e.id, source: e.source, target: e.target, label: e.label ?? '' })) }; const r = await api(`lineage/${current.id}`, { method: 'PUT', version: versionOf(current), body: { name: current.name, code: current.code_norm, graph, layout: { positions: Object.fromEntries(nodes.map(n => [n.id, n.position])) } } }); setCurrent(r); setDirty(false); }; const close = () => { if (dirty) {
    modal.confirm({ title: '保存血缘布局后关闭？', okText: '保存并关闭', cancelText: '继续编辑', onOk: async () => { await save(); setCurrent(null); } });
}
else
    setCurrent(null); }; return <Page title="数据血缘" description="独立维护来源字段、加工任务和目标字段。表结构采集不会自动产生完整 ETL 血缘。" actions={canWrite() && <Button type="primary" onClick={() => setEdit(null)}>创建血缘图</Button>}><DataTable rows={rows.filter((r: Row) => r.status !== 'ARCHIVED')} error={q.error} loading={q.loading} onRefresh={q.refresh} columns={[{ title: '名称', dataIndex: 'name' }, { title: '代码', dataIndex: 'code_norm' }, { title: '节点数', render: (_, r) => r.graph_json?.nodes?.length ?? 0 }, timeColumn, { title: '操作', width: 168, render: (_, r) => <Space><Button type="link" onClick={() => open(r)}>全屏血缘画布</Button>{canWrite() && <Button type="link" danger onClick={() => modal.confirm({ title: '归档此血缘图？', onOk: () => api(`lineage/${r.id}`, { method: 'DELETE', version: versionOf(r) }) })}>归档</Button>}</Space> }]}/><EditorModal open={edit !== undefined} title="创建血缘图" onCancel={() => setEdit(undefined)} onSave={v => api('lineage', { method: 'POST', body: { ...v, graph: { nodes: [], edges: [] }, layout: {} } })}><Form.Item name="name" label="名称" rules={required}><Input /></Form.Item><Form.Item name="code" label="代码"><Input /></Form.Item></EditorModal>{current && <FullscreenWorkspace kind="lineage" title={current.name} busy={busy} onClose={close} onSave={() => { void run(save); }}><div className="lineage-workspace"><div className="lineage-toolbar"><Space><span>{dirty ? '待保存' : '已保存到当前浏览器'}</span><Button disabled={!canWrite()} onClick={() => { setAdd(true); setKind('entity'); setEid(undefined); setFid(undefined); setLabel(''); }}>添加表 / 字段 / 加工节点</Button><span className="muted">从节点端点拖拽连接加工链路，Delete 删除选中项</span></Space></div><ReactFlow colorMode={theme} nodes={nodes} edges={edges} onNodesChange={changes => { setNodes(ns => applyNodeChanges(changes, ns)); if (changes.some(c => c.type !== 'select') && canWrite())
    setDirty(true); }} onEdgesChange={changes => { if (!canWrite())
    return; setEdges(es => applyEdgeChanges(changes, es)); if (changes.some(c => c.type !== 'select'))
    setDirty(true); }} onConnect={connection => { if (canWrite()) {
    setEdges(es => addEdge({ ...connection, id: crypto.randomUUID() }, es));
    setDirty(true);
} }} nodesDraggable={canWrite()} nodesConnectable={canWrite()} deleteKeyCode={canWrite() ? 'Delete' : null} fitView><Background /><Controls /><MiniMap /></ReactFlow></div><Modal open={add} title="添加血缘节点" onCancel={() => setAdd(false)} onOk={() => { if (kind !== 'process' && !eid) {
    message.warning('请选择实体');
    return;
} if (kind === 'field' && !fid) {
    message.warning('请选择字段');
    return;
} const entity = entities.find((e: Row) => e.id === eid); const name = label.trim() || (kind === 'field' ? `${entity?.name}.${entity?.fields?.find((f: Row) => f.id === fid)?.name}` : entity?.name); if (!name) {
    message.warning('请输入加工节点名称');
    return;
} const id = crypto.randomUUID(); setNodes(ns => [...ns, { id, position: { x: 120 + ns.length % 3 * 300, y: 100 + Math.floor(ns.length / 3) * 150 }, data: { label: name, domain: { id, kind, ...(kind === 'process' ? {} : { entityId: eid }), ...(kind === 'field' ? { fieldId: fid } : {}) } } }]); setDirty(true); setAdd(false); }}><Form layout="vertical"><Form.Item label="类型"><Select value={kind} onChange={setKind} options={[{ value: 'entity', label: '表 / 集合' }, { value: 'field', label: '字段' }, { value: 'process', label: '加工任务' }]}/></Form.Item>{kind !== 'process' && <Form.Item label="实体"><Select showSearch optionFilterProp="label" value={eid} onChange={id => { setEid(id); setFid(undefined); }} options={opts(entities, 'id', 'name')}/></Form.Item>}{kind === 'field' && <Form.Item label="字段"><Select value={fid} onChange={setFid} options={opts(entities.find((e: Row) => e.id === eid)?.fields ?? [])}/></Form.Item>}<Form.Item label={kind === 'process' ? '加工任务名称' : '显示名称（可选）'}><Input value={label} onChange={e => setLabel(e.target.value)}/></Form.Item></Form></Modal></FullscreenWorkspace>}</Page>; }
