import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { Alert,App,Button,Drawer,Empty,Form,Input,Select,Space } from 'antd';
import { ReactFlow,Background,Controls,MiniMap,applyNodeChanges } from '@xyflow/react';
import type { Connection,Node,Edge,NodeChange } from '@xyflow/react';
import type { Row } from '../../services/api';
import { lineageTasks,lineageGraph,runtimeLineage,saveLineageGraph,processingNodeTemplate,validateProcessingGraph,deleteLineageGraph,lineageLifecycle,lineageStatus,processingEdge } from '../../services/lineage';
import { readMetadata,metadataWritable } from '../../services/metadata';
import { useWorkspaceQuery } from '../../services/useWorkspaceQuery';
import { useStudio } from '../er/store';
import { FullscreenWorkspace } from '../../app/FullscreenWorkspace';
import { FieldMappingEditor } from './FieldMappingEditor';
import { DataTable,EditorModal,ErrorNotice,Page,date,useAction,required } from './common';
export function SharedLineagePage({embedded=false,initialPipelineId}:{embedded?:boolean;initialPipelineId?:string}={}){
 const q=useWorkspaceQuery('shared-lineage-tasks',s=>lineageTasks(s)),metadata=useWorkspaceQuery('lineage-owned-tables',readMetadata);
 const [current,setCurrent]=useState<Row|null>(null),[node,setNode]=useState<string>(),[edge,setEdge]=useState<string>(),[evidence,setEvidence]=useState<Row|null>(null),[error,setError]=useState(''),[mapping,setMapping]=useState<Row|null>(null),[create,setCreate]=useState(false),[add,setAdd]=useState(false),[editing,setEditing]=useState(false);
 const {busy,run}=useAction(),{message,modal}=App.useApp();const theme=useStudio(s=>s.theme),dirty=useRef(false),lastDeepLink=useRef('');
 const status=useWorkspaceQuery('shared-lineage-status:'+current?.id,s=>current?.id?lineageStatus(current.id,s):Promise.resolve(null),current?.nifiProcessGroupId?5000:false);
 const lifecycle=(action:'deploy'|'start'|'stop'|'undeploy')=>{if(!current)return;const label={deploy:'部署',start:'启动',stop:'停止',undeploy:'撤销部署'}[action];modal.confirm({title:`${label}当前加工流程？`,content:action==='start'?'启动将读取来源并向配置的目标写入业务数据；请核对目标表、过滤和清空策略。':action==='deploy'?'部署会对原 NiFi 流程创建或更新组件；不会自动启动。请确认当前配置适用于目标环境。':action==='undeploy'?'撤销部署将移除 NiFi 流程，可能丢弃队列内数据；保存的设计保留。':'停止 NiFi 流程，不删除已写入的业务数据。',okText:`确认${label}`,okButtonProps:{danger:action==='undeploy'},onOk:()=>run(async()=>{await lineageLifecycle(current.id,action);setCurrent(await lineageGraph(current.id));status.refresh();q.refresh();},`${label}请求已完成`)})};
 const removeGraph=(row:Row)=>modal.confirm({title:'删除共享加工图？',content:'会停止并删除其已部署的 NiFi 流程（包括队列），并删除关联接入任务配置；不删除业务表。此操作同时影响原数据接入平台。',okText:'确认删除',okButtonProps:{danger:true},onOk:()=>run(async()=>{await deleteLineageGraph(row.id);q.refresh();},'共享加工图已删除')});
 const open=(row:Row)=>run(async()=>{setCurrent(await lineageGraph(row.id));setNode(undefined);setEdge(undefined);setEvidence(null);setError('');setEditing(false);dirty.current=false;},'');
 useEffect(()=>{if(!initialPipelineId||lastDeepLink.current===initialPipelineId)return;lastDeepLink.current=initialPipelineId;open({id:initialPipelineId});},[initialPipelineId]);
 const change=(dsl:Row)=>{dirty.current=true;setCurrent(r=>r?{...r,dsl}:r);};
 const close=()=>{if(dirty.current)modal.confirm({title:'放弃尚未保存的加工图修改？',okText:'放弃修改',cancelText:'继续编辑',onOk:()=>setCurrent(null)});else setCurrent(null);};
 const save=()=>run(async()=>{if(!current)return;const saved=await saveLineageGraph(current);setCurrent(saved);dirty.current=false;q.refresh();},'加工图已保存到共享后端（未部署、未启动）');
 const runtime=()=>run(async()=>{if(!current?.id||!node)return;setError('');try{const r=await runtimeLineage(current.id,node);setEvidence(r);if(!r.nodes.length)message.info(r.message||'当前节点暂无运行血缘事件');}catch(e){setError(e instanceof Error?e.message:String(e));}},'');
 const connect=(c:Connection)=>{if(!current||!c.source||!c.target)return;const from=current.dsl.nodes.find((n:Row)=>n.id===c.source),to=current.dsl.nodes.find((n:Row)=>n.id===c.target);try{if(from.category==='sink'||to.category==='source')throw new Error('目标节点不能出线，来源节点不能接收上游');if(current.dsl.edges.some((e:Row)=>e.source===c.source&&e.target===c.target))throw new Error('此连线已存在');const dsl={...current.dsl,edges:[...current.dsl.edges,processingEdge(crypto.randomUUID(),c.source,c.target)]};validateProcessingGraph(dsl);change(dsl);}catch(e){message.warning(e instanceof Error?e.message:String(e));}};
 const nodes:Node[]=useMemo(()=>(current?.dsl.nodes||[]).map((n:Row,i:number)=>({id:n.id,type:n.category==='source'?'input':n.category==='sink'?'output':'default',selected:node===n.id,position:{x:Number.isFinite(n.x)?n.x:100+(i%4)*300,y:Number.isFinite(n.y)?n.y:100+Math.floor(i/4)*170},data:{label:n.label||n.manifestKey}})),[current,node]);
 const [canvasNodes,setCanvasNodes]=useState<Node[]>([]);
 useEffect(()=>setCanvasNodes(nodes),[nodes]);
 const onNodesChange=useCallback((changes:NodeChange[])=>setCanvasNodes(previous=>applyNodeChanges(changes,previous)),[]);
 const edges:Edge[]=(current?.dsl.edges||[]).map((e:Row)=>({id:e.id,source:e.source,target:e.target,label:e.outlet,selected:edge===e.id}));
 const selected=current?.dsl.nodes.find((n:Row)=>n.id===node);
 const headerActions=<Space><Button loading={q.loading} onClick={q.refresh}>刷新接入任务</Button><Button type="primary" disabled={!metadataWritable()} onClick={()=>setCreate(true)}>新建加工图</Button></Space>;
 const content=<>{embedded&&<div className="lineage-embedded-actions">{headerActions}</div>}<DataTable rows={q.data} loading={q.loading} error={q.error} onRefresh={q.refresh} titleKey="shared-lineage-tasks" columns={[
  {title:'链路 / 接入任务',dataIndex:'name',width:270},{title:'节点数',dataIndex:'nodeCount',align:'right',width:100},{title:'运行血缘',width:140,render:(_,r)=>r.nifiProcessGroupId?'可查询运行事件':'尚未部署'},{title:'更新时间',dataIndex:'updatedAt',width:175,render:date},{title:'说明',dataIndex:'description',width:260},{title:'操作',width:184,render:(_,r)=><Space><Button type="link" loading={busy&&current?.id===r.id} onClick={()=>open(r)}>全屏加工与血缘</Button><Button type="link" danger disabled={busy||!metadataWritable()} onClick={()=>removeGraph(r)}>删除</Button></Space>}
 ]}/>{current&&<FullscreenWorkspace kind="lineage" title={current.name} busy={busy} onClose={close} onSave={editing?save:undefined}>
 <div className="lineage-workspace"><div className="lineage-toolbar"><Space wrap>
 <Button type={editing?'primary':'default'} disabled={busy||!metadataWritable()} onClick={()=>setEditing(v=>!v)}>{editing?'结束编辑':'编辑加工图'}</Button>
 {!editing&&<><span className="wx-status">{status.data?.status||'读取运行状态中'}</span><Button disabled={busy||dirty.current||!metadataWritable()} onClick={()=>lifecycle('deploy')}>部署</Button><Button disabled={busy||dirty.current||!current.nifiProcessGroupId||!metadataWritable()} onClick={()=>lifecycle('start')}>启动</Button><Button disabled={busy||!current.nifiProcessGroupId||!metadataWritable()} onClick={()=>lifecycle('stop')}>停止</Button><Button danger disabled={busy||!current.nifiProcessGroupId||!metadataWritable()} onClick={()=>lifecycle('undeploy')}>撤销部署</Button></>}
 {editing&&<><Button disabled={busy||!!metadata.error} onClick={()=>setAdd(true)}>添加节点</Button><Button disabled={busy||!selected?.manifestKey?.startsWith('transform.field-')} onClick={()=>setMapping(selected)}>字段转换规则</Button><Button danger disabled={busy||!node&&!edge} onClick={()=>modal.confirm({title:'从加工图移除所选节点或连线？',content:'保存后影响设计，不删除业务表，也不立即改变已部署的流程。',onOk:()=>{change({...current.dsl,nodes:current.dsl.nodes.filter((n:Row)=>n.id!==node),edges:current.dsl.edges.filter((e:Row)=>e.id!==edge&&e.source!==node&&e.target!==node)});setNode(undefined);setEdge(undefined);}})}>移除所选</Button></>}
 <Select style={{width:220}} aria-label="运行血缘查询节点" placeholder="选择节点" value={node} onChange={v=>{setNode(v);setEdge(undefined);}} options={current.dsl.nodes.map((n:Row)=>({value:n.id,label:n.label||n.id}))}/><Button loading={busy} disabled={!current.nifiProcessGroupId||!node} onClick={runtime}>查询运行血缘</Button><span className="muted">{dirty.current?'有修改，请保存':'共享已保存设计'} · 保存不部署、不启动</span>
 </Space></div><ErrorNotice error={error||status.error} retry={status.refresh}/>
 <ReactFlow colorMode={theme} nodes={canvasNodes} onNodesChange={onNodesChange} edges={edges} nodesDraggable={editing&&!busy} nodesConnectable={editing&&!busy} onConnect={connect} onNodeClick={(_,n)=>{setNode(n.id);setEdge(undefined);}} onEdgeClick={(_,e)=>{setEdge(e.id);setNode(undefined);}} onNodeDoubleClick={(_,n)=>{const row=current.dsl.nodes.find((r:Row)=>r.id===n.id);if(editing&&row.manifestKey.startsWith('transform.field-'))setMapping(row);}} onNodeDragStop={(_,n)=>change({...current.dsl,nodes:current.dsl.nodes.map((r:Row)=>r.id===n.id?{...r,x:n.position.x,y:n.position.y}:r)})} deleteKeyCode={null} fitView><Background/><Controls/><MiniMap/></ReactFlow>
 </div></FullscreenWorkspace>}
 <EditorModal open={create} title="新建加工图" initial={{}} onCancel={()=>setCreate(false)} saveMessage="加工图已创建，尚未部署或执行" onSave={async v=>{const saved=await saveLineageGraph({...v,dsl:{version:1,nodes:[],edges:[]}});setCurrent(saved);setEditing(true);dirty.current=false;setNode(undefined);setEdge(undefined);q.refresh();return saved;}}><Form.Item name="name" label="名称" rules={required}><Input maxLength={200}/></Form.Item><Form.Item name="description" label="说明"><Input.TextArea maxLength={1000}/></Form.Item></EditorModal>
 <EditorModal open={add} title="添加加工节点" initial={{key:'source.jdbc'}} onCancel={()=>setAdd(false)} saveMessage="节点已加入画布，请保存加工图" onSave={async v=>{if(!current)throw new Error('工作区已关闭');const category=v.key.startsWith('source.')?'source':v.key.startsWith('sink.')?'sink':'transform';const template=await processingNodeTemplate({key:v.key,tableId:v.tableId,sourceTableId:v.sourceTableId,targetTableId:v.targetTableId});const n={id:crypto.randomUUID(),label:v.label,manifestKey:template.manifestKey,category,x:80+current.dsl.nodes.length%4*280,y:80+Math.floor(current.dsl.nodes.length/4)*160,config:{...template.config,...(category==='transform'?{sourceTableId:v.sourceTableId,targetTableId:v.targetTableId}:{})}};change({...current.dsl,nodes:[...current.dsl.nodes,n]});setAdd(false);return n;}}><Form.Item name="label" label="节点名称" rules={required}><Input maxLength={200}/></Form.Item><ProcessingFields tables={metadata.data?.tables||[]}/></EditorModal>
 <FieldMappingEditor node={mapping} tables={metadata.data?.tables||[]} columns={metadata.data?.columns||[]} onClose={()=>setMapping(null)} onApply={config=>{if(!current||!mapping)return;change({...current.dsl,nodes:current.dsl.nodes.map((n:Row)=>n.id===mapping.id?{...n,config}:n)});setMapping(null);}}/>
 <Drawer title="运行血缘 · NiFi 事件" open={!!evidence} width="min(950px, 100vw)" zIndex={1100} onClose={()=>setEvidence(null)}>{evidence&&<><Alert type="info" showIcon title={evidence.anchorEventId?'真实运行事件血缘':'暂无运行事件'} description={evidence.message||'由 NiFi provenance 返回，不是逻辑关系。'}/>{evidence.nodes.length?<div style={{height:570,marginTop:18}}><ReactFlow colorMode={theme} nodes={evidence.nodes.map((n:Row,i:number)=>({id:String(n.id),position:{x:(i%3)*260,y:Math.floor(i/3)*170},data:{label:[n.type,n.eventType,n.id].filter(Boolean).join(' · ')}}))} edges={evidence.edges.map((e:Row,i:number)=>({id:String(e.id||i),source:String(e.sourceId||e.source),target:String(e.targetId||e.target)}))} nodesDraggable={false} nodesConnectable={false} deleteKeyCode={null} fitView><Background/><Controls/></ReactFlow></div>:<Empty description="当前节点暂无可追踪事件"/>}</>}</Drawer></>;
 return embedded?content:<Page title="数据血缘" actions={headerActions}>{content}</Page>;
}
function ProcessingFields({tables}:{tables:Row[]}){const form=Form.useFormInstance(),key=Form.useWatch('key',form)||'source.jdbc';const options=tables.map(t=>({value:t.tid,label:`${t.table_name_cn||t.table_comment||t.table_name} · ${t.table_name}`}));return <><Form.Item name="key" label="节点类型" rules={required}><Select options={[{value:'source.jdbc',label:'已登记表 → 来源节点'},{value:'transform.field-mapping',label:'字段映射与转换'},{value:'sink.jdbc',label:'已登记表 → 目标节点'}]}/></Form.Item>{key.startsWith('transform.')?<><Form.Item name="sourceTableId" label="源表" rules={required}><Select showSearch optionFilterProp="label" options={options}/></Form.Item><Form.Item name="targetTableId" label="目标表" rules={required}><Select showSearch optionFilterProp="label" options={options}/></Form.Item></>:<Form.Item name="tableId" label="已登记数据表" rules={required}><Select showSearch optionFilterProp="label" options={options}/></Form.Item>}<Alert type="info" title="复用共享节点模板" description="读取当前租户已登记表的配置，不显示或编辑数据库密码。"/></>;}
