import { useEffect, useRef, useState, type Key } from 'react';
import { Alert, App, Button, Col, Descriptions, Drawer, Dropdown, Form, Input, InputNumber, Popover, Select, Space, Tabs, Tooltip, Row as GridRow } from 'antd';
import { PlusOutlined, PlayCircleOutlined, MoreOutlined, CheckCircleOutlined, EditOutlined, EyeOutlined, FolderOpenOutlined, CopyOutlined, ArrowRightOutlined, ArrowLeftOutlined, DeleteOutlined } from '@ant-design/icons';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { getSession, type Row } from '../../services/api';
import { canManageSources as canManage, connectionFailureMessage, listSources, sourceChoices, editSource, readSource, matchesSourceProjection, saveSource, testSource, sourceTablesPage, collectionStatus, sharedSourceApi, engineToBackend, draftFromForm, type SourceTablePage } from '../../services/datasources';
import { SourceCollectionDrawer } from './SourceCollectionDrawer';
import type { SourceChoices } from '../../services/datasourceRegistrationApi';
import { connectionFields, datasourceRegistrationApi, draftFromDetail, makeJdbcUrl, type SourceDraft } from '../../services/datasourceRegistrationApi';
import { useWorkspaceQuery } from '../../services/useWorkspaceQuery';
import { SourceIcon, Panel } from '../../design/Visuals';
import { ModuleIcon } from '../../design/ModuleIcon';
import { engineLabel, nextEnginePort } from '../../shared/presentation';
import { sourceEndpoint, sourceScope, objectKindLabel } from '../../shared/sourcePresentation';
import { DataTable, EditorModal, Page, Status, date, required, useAction } from './common';

const engineTypes = ['DM8','MYSQL','POSTGRESQL','ORACLE','SQLSERVER','MONGODB','ELASTICSEARCH','MARIADB'];
const safeConnectionText = (value: unknown) => String(value ?? '').replace(/((?:password|passwd|pwd|token|secret|access[_-]?key)\s*=\s*)[^&;\s]+/gi, '$1••••');
async function copyText(value: string): Promise<void> {
  if (navigator.clipboard?.writeText) {
    try { await navigator.clipboard.writeText(value); return; } catch { /* Fall back for browsers that deny clipboard API access. */ }
  }
  const input = document.createElement('textarea');
  input.value = value; input.style.position = 'fixed'; input.style.opacity = '0';
  document.body.appendChild(input); input.select();
  try { if (!document.execCommand('copy')) throw new Error('copy failed'); }
  finally { input.remove(); }
}
function SourceFields({editing,choices}:{editing:boolean;choices:SourceChoices}) {
 const form=Form.useFormInstance();const engine=Form.useWatch('engine',form);
 return <>
  <div className="source-form-intro"><SourceIcon engine={engine??'MYSQL'}/><div><strong>{editing?'完善来源与治理信息':'让业务数据拥有统一入口'}</strong><p>先登记来源，再采集结构，按业务主题建立数据关联。</p></div></div>
  <div className="wx-form-section-title"><span>01</span> 基本信息</div>
  <Form.Item name="name" label="数据源名称" rules={required}><Input maxLength={128} placeholder="例如：客户主数据中心"/></Form.Item>
  <GridRow gutter={16}><Col xs={24} sm={12}><Form.Item name="code" label="唯一代码" extra="使用数据中台生成的统一数据源标识"><Input disabled placeholder="保存后自动生成"/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="engine" label="数据库类型" rules={required}><Select disabled={editing} options={engineTypes.map(value=>({value,disabled:!engineToBackend[value]||!choices.types.some(t=>t.value===engineToBackend[value]),label:<span className="engine-option"><SourceIcon small engine={value}/>{engineLabel(value)}{!engineToBackend[value]?'（后端暂未支持）':''}</span>}))} onChange={value=>{form.setFieldValue(['connection','port'],nextEnginePort(engine,value,form.getFieldValue(['connection','port'])));form.setFieldValue(['connection','jdbcURL'],'');}}/></Form.Item></Col></GridRow>
  <div className="wx-form-section-title"><span>02</span> 命名空间与地址</div>
  <GridRow gutter={16}><Col xs={24} sm={16}><Form.Item name={['connection','host']} label="主机标识" rules={required}><Input placeholder="数据库主机名或 IP"/></Form.Item></Col><Col xs={24} sm={8}><Form.Item name={['connection','port']} label="端口" rules={required}><InputNumber min={1} max={65535} style={{width:'100%'}}/></Form.Item></Col></GridRow>
  <GridRow gutter={16}><Col xs={24} sm={12}><Form.Item name={['connection','database']} label="数据库 / Catalog" rules={required}><Input placeholder="例如：customer_center"/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name={['connection','schema']} label="Schema"><Input placeholder="可选，例如 public"/></Form.Item></Col></GridRow>
  <GridRow gutter={16}><Col xs={24} sm={12}><Form.Item name={['connection','username']} label="连接账号" rules={required}><Input autoComplete="off" placeholder="数据库用户名"/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name={['connection','password']} label="连接密码" extra={editing?'留空保留已保存的密码，不回显原密码':'凭据仅提交给数据中台，不存入浏览器工作区'}><Input.Password autoComplete="new-password" placeholder={editing?'留空不修改':'数据库密码'}/></Form.Item></Col></GridRow>
  {engine==='ORACLE'&&<GridRow gutter={16}><Col span={12}><Form.Item name={['connection','jdbcType']} label="Oracle 连接方式"><Select options={[{value:'serviceName',label:'服务名'},{value:'sid',label:'SID'}]}/></Form.Item></Col><Col span={12}><Form.Item name={['connection','serviceName']} label="服务名 / SID"><Input/></Form.Item></Col></GridRow>}
  <Form.Item name={['connection','jdbcURL']} label="JDBC 连接地址" extra="通常由地址、端口、数据库自动生成；特殊连接参数可在此填写"><Input placeholder="可选，自定义 JDBC 连接地址"/></Form.Item>
  <div className="wx-form-section-title"><span>03</span> 业务归属</div>
  <GridRow gutter={16}><Col xs={24} sm={12}><Form.Item name="domain" label="业务域" extra="现有接口暂未提供业务域字段"><Input disabled placeholder="暂不支持保存"/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="owner" label="责任人 / 团队"><Input maxLength={128} placeholder="保存为数据源联系人"/></Form.Item></Col></GridRow>
  <GridRow gutter={16}><Col xs={24} sm={12}><Form.Item name="appId" label="业务系统"><Select allowClear showSearch optionFilterProp="label" options={choices.applications} placeholder="选择已登记的业务系统"/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="environment" label="环境标签" extra="现有接口暂未提供环境标签字段"><Input disabled placeholder="暂不支持保存"/></Form.Item></Col></GridRow>
  <GridRow gutter={16}><Col xs={24} sm={12}><Form.Item name="orgId" label="数据提供部门" rules={required}><Select showSearch optionFilterProp="label" options={choices.organizations} placeholder="选择所属部门"/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="storageDomain" label="所属网域"><Select allowClear options={choices.networks} placeholder="选择数据源所在网域"/></Form.Item></Col></GridRow>
  <Form.Item name="description" label="来源说明"><Input.TextArea rows={2} maxLength={600} showCount placeholder="记录数据用途、责任边界或采集约定"/></Form.Item>
  <Alert showIcon type="info" title="与元数据管理平台共用数据源" description="保存不自动发起采集。连接测试访问真实数据库，采集只读取表结构和字段元数据，不读取业务记录。"/>
 </>;
}
export function SourcesPage() {
 const q=useWorkspaceQuery('platform-sources',s=>listSources(s));
 const choicesQuery=useWorkspaceQuery('platform-source-choices',()=>sourceChoices());
 const choices=choicesQuery.data??{types:[],networks:[],organizations:[],applications:[],nodes:[]};
 const nav=useNavigate(),[params]=useSearchParams();const {message,modal}=App.useApp();const {busy,run}=useAction();
 const returnTo=params.get('returnTo');const assetReturnTo=returnTo?.startsWith('/assets/')&&!returnTo.startsWith('//')?returnTo:null;
 const [edit,setEdit]=useState<Row|null>();const [details,setDetails]=useState<string>();const [detailsTab,setDetailsTab]=useState('summary');
 useEffect(()=>{const sourceId=params.get('sourceId');if(sourceId){setDetailsTab('summary');setDetails(sourceId);}},[params.get('sourceId')]);
 const [engineFilter,setEngineFilter]=useState<string>();const [stateFilter,setStateFilter]=useState<string>();const [domainFilter,setDomainFilter]=useState<string>();
 const [collectionFilter,setCollectionFilter]=useState('all');const [selectedSources,setSelectedSources]=useState<Key[]>([]);
 const [browse,setBrowse]=useState<Row|null>(null),[connectionError,setConnectionError]=useState(''),[pendingIndexes,setPendingIndexes]=useState<string[]>([]);
 const [confirmedSources,setConfirmedSources]=useState<Row[]>([]);const syncingIndexes=useRef(new Set<string>());
 const detailsQuery=useWorkspaceQuery('platform-source-detail-'+(details||''),async()=>details?draftFromDetail(await datasourceRegistrationApi.detail(details)):null);
 const metadataQuery=useWorkspaceQuery('platform-source-metadata-'+(details||''),async()=>details?collectionStatus(details):null);
 const [detailTablePage,setDetailTablePage]=useState(1),[detailTableSize,setDetailTableSize]=useState(15),[detailTableKeyword,setDetailTableKeyword]=useState('');
 const [detailTables,setDetailTables]=useState<SourceTablePage>({rows:[],total:0,page:1,size:15});
 const [detailTablesLoading,setDetailTablesLoading]=useState(false),[detailTablesError,setDetailTablesError]=useState(''),[detailTablesRevision,setDetailTablesRevision]=useState(0);
 useEffect(()=>{setDetailTablePage(1);setDetailTableKeyword('');},[details]);
 useEffect(()=>{if(!details)return;let live=true;setDetailTablesLoading(true);setDetailTablesError('');void sourceTablesPage(details,detailTablePage,detailTableSize,detailTableKeyword).then(page=>{if(live)setDetailTables(page);}).catch(cause=>{if(live)setDetailTablesError(cause instanceof Error?cause.message:String(cause));}).finally(()=>{if(live)setDetailTablesLoading(false);});return()=>{live=false;};},[details,detailTablePage,detailTableSize,detailTableKeyword,detailTablesRevision]);
 const sources:Row[]=[...new Map([...(q.data??[]),...confirmedSources].map(s=>[s.id,s])).values()].map(s=>({...s,owner:s.owner||choices.organizations.find(o=>o.value===s.orgId)?.label||'',businessSystem:s.businessSystem||choices.applications.find(a=>a.value===s.appId)?.label||''}));
 const rawSource=sources.find(s=>s.id===details);const detailDraft=detailsQuery.data;const source:Row|undefined=rawSource?{...rawSource,connection:detailDraft?{...rawSource.connection,host:detailDraft.host,port:detailDraft.port,database:detailDraft.database,schema:detailDraft.schema}:rawSource.connection}:undefined;
 const connectionEntries=detailDraft?connectionFields(detailDraft.dbType,detailDraft.hiveConnectionMode).filter(field=>!field.secret&&!['dbVersion','apiHeaders','apiBody'].includes(field.name)).map(field=>({key:field.name,label:field.label,value:safeConnectionText(detailDraft[field.name]||(field.name==='jdbcURL'?makeJdbcUrl(detailDraft as SourceDraft):''))})).filter(field=>field.value):[];
 const latestJob=metadataQuery.data,history=latestJob?.exists?[{id:latestJob.jobId,name:'最近一次表结构采集',status:latestJob.status,phase:latestJob.phase}]:[];
 const collected=sources.filter(s=>s.entityCount>0).length,entityCount=sources.reduce((n,s)=>n+s.entityCount,0),fieldCount=sources.reduce((n,s)=>n+s.fieldCount,0);
 const categories=[...new Set(sources.map(s=>s.engine))];
 const rows=sources.filter(s=>(!engineFilter||s.engine===engineFilter)&&(!stateFilter||s.status===stateFilter)&&(!domainFilter||s.network===domainFilter)&&(collectionFilter==='all'||(collectionFilter==='collected'?s.entityCount>0:!s.entityCount)));
 const initial=edit??{engine:'MYSQL',orgId:getSession()?.user?.orgId||choices.organizations.find(o=>o.label===getSession()?.user?.orgName)?.value,connection:{host:'',port:3306,database:'',schema:'',username:'',password:''}};
 const syncIndex=async(id:string,confirmed?:Row)=>{if(syncingIndexes.current.has(id))return;syncingIndexes.current.add(id);setPendingIndexes(ids=>[...new Set([...ids,id])]);try{await sharedSourceApi.refreshIndex(id);const expected=confirmed??confirmedSources.find(s=>s.id===id);let visible=false;for(let attempt=0;attempt<10;attempt++){if((await listSources()).some(row=>row.id===id&&(!expected||matchesSourceProjection(row,expected)))){visible=true;break;}await new Promise(resolve=>setTimeout(resolve,500));}if(!visible)throw new Error('列表索引尚未可检索');setPendingIndexes(ids=>ids.filter(v=>v!==id));setConfirmedSources(rows=>rows.filter(row=>row.id!==id));q.refresh();}catch(e){message.warning('主记录已保存，但列表索引尚未同步。当前显示已核对的主记录，请重试列表同步，不要重复登记。',8);}finally{syncingIndexes.current.delete(id);}};
 const openEditor=(r:Row)=>run(async()=>{await sourceChoices();setConnectionError('');setEdit(await editSource(r.id));},'');
 const create=()=>{if(choicesQuery.error){message.error('无法读取登记选项，请重试');choicesQuery.refresh();return;}setConnectionError('');setEdit(null);};
 const inspect=(r:Row)=>run(async()=>{try{await testSource(r.id);setConnectionError('');message.success('数据库连接测试通过');q.refresh();}catch(e){setConnectionError(e instanceof Error?e.message:String(e));throw e;}},'');
 const openDetails=(r:Row,tab='summary')=>{setDetailsTab(tab);setDetails(r.id);};
 const copyConnection=async(value:string)=>{try{await copyText(value);message.success('已复制到剪贴板');}catch{message.warning('复制失败，请手动选择文本复制');}};
 const viewTables=(r:Row)=>{setDetails(undefined);setBrowse(r);};
 const remove=(r:Row)=>run(async()=>{const preview=await sharedSourceApi.deletePreview(r.id);if(preview.exists===false)throw new Error('数据源已不存在，请刷新列表');modal.confirm({title:'删除数据源登记？',content:<div><p>将删除“{r.name}”的登记记录及关联元数据；不会删除源数据库或其中的业务记录。</p>{preview.cleanup&&<p>影响范围：{Object.entries(preview.cleanup).map(([k,v])=>k+' '+v).join('，')}</p>}</div>,okText:'删除登记',okButtonProps:{danger:true},onOk:async()=>{const result=await sharedSourceApi.remove(r.id);if(!result.deleted&&!result.alreadyDeleted)throw new Error('后端未确认删除成功');message.success('数据源登记已删除');setConfirmedSources(rows=>rows.filter(row=>row.id!==r.id));setPendingIndexes(ids=>ids.filter(id=>id!==r.id));q.refresh();}});},'');
 const batchInspect=()=>run(async()=>{let success=0,skipped=0;const errors:string[]=[];for(const s of sources.filter(s=>selectedSources.includes(s.id))){if(s.status==='DISABLED'){skipped++;continue;}try{await testSource(s.id);success++;}catch(e){errors.push(s.name+'：'+(e instanceof Error?e.message:String(e)));}}modal.info({title:'批量连接测试结果',content:<div><p>通过 {success} 项 · 已停用跳过 {skipped} 项 · 失败 {errors.length} 项</p>{errors.map(e=><p key={e}>{e}</p>)}</div>});q.refresh();},'');
 const menu=(r:Row)=>({items:[{key:'details',label:'数据源详情',icon:<EyeOutlined/>},{key:'tables',label:'查看数据表',icon:<FolderOpenOutlined/>},{type:'divider' as const},{key:'edit',label:'编辑信息',icon:<EditOutlined/>,disabled:!canManage()||busy},{key:'delete',label:'删除登记',icon:<DeleteOutlined/>,danger:true,disabled:!canManage()||busy}],onClick:({key}:{key:string})=>{if(key==='details')openDetails(r);if(key==='tables')viewTables(r);if(key==='edit')void openEditor(r);if(key==='delete')void remove(r);}});
 return <Page title="数据源管理" actions={<Space>{assetReturnTo&&<Button icon={<ArrowLeftOutlined/>} onClick={()=>nav(assetReturnTo)}>返回皓月资产中心</Button>}{canManage()&&<Button type="primary" icon={<PlusOutlined/>} disabled={choicesQuery.loading} onClick={create}>登记数据源</Button>}</Space>}>
  {pendingIndexes.length>0&&<Alert className="mb16" type="warning" showIcon title="数据已保存，列表同步待完成" action={<Button onClick={()=>pendingIndexes.forEach(id=>void syncIndex(id))}>重试列表同步</Button>}/>}
  <div className="wx-source-kpis">
   {[
    {label:'数据源总数',value:q.data?sources.length:'—',note:`${categories.length} 种数据库类型`,icon:'sources',tone:'purple'},
    {label:'已采集表',value:q.data?entityCount:'—',note:`字段 ${fieldCount.toLocaleString()} 个`,icon:'catalog',tone:'blue'},
    {label:'已采集来源',value:q.data?collected:'—',note:`${sources.length-collected} 个来源待采集`,icon:'collection',tone:'teal'},
    {label:'需要关注',value:q.data?sources.filter(s=>['ERROR','REGISTERED'].includes(s.status)).length:'—',note:'待检查配置与完善来源',icon:'rules',tone:'amber'},
   ].map(k=><article key={k.label} className={`wx-source-kpi ${k.tone}`}><span className="source-kpi-icon"><ModuleIcon name={k.icon}/></span><div><span>{k.label}</span><strong>{k.value}</strong><small title={k.note}>{k.note}</small></div></article>)}
  </div>
  <div className="wx-source-collection-tabs"><div role="group" aria-label="按采集状态筛选">{[['all','全部来源',sources.length],['collected','已采集',collected],['pending','待采集',sources.length-collected]].map(([id,label,n])=><button type="button" className={collectionFilter===id?'is-active':''} key={id} aria-pressed={collectionFilter===id} onClick={()=>setCollectionFilter(String(id))}>{label}<span>{n}</span></button>)}</div><Button icon={<CheckCircleOutlined/>} disabled={!canManage()||!selectedSources.length} loading={busy} onClick={batchInspect}>批量检查{selectedSources.length?` · ${selectedSources.length}`:''}</Button></div>
  <div className="wx-source-table"><DataTable titleKey="sources-v3.4" rows={rows} loading={q.loading} error={q.error} onRefresh={q.refresh} rowSelection={{selectedRowKeys:selectedSources,onChange:setSelectedSources,columnWidth:42}} actions={<>
    <Select className="source-type-filter" allowClear placeholder="全部数据库类型" aria-label="筛选数据库类型" value={engineFilter} onChange={setEngineFilter} options={categories.map(v=>({value:v,label:engineLabel(v)}))}/>
    <Select className="source-state-filter" allowClear placeholder="全部状态" aria-label="筛选数据源状态" value={stateFilter} onChange={setStateFilter} options={[{value:'CONNECTED',label:'连接正常'},{value:'ERROR',label:'异常'},{value:'REGISTERED',label:'待测试连接'},{value:'DISABLED',label:'已停用'}]}/>
    <Select className="source-domain-filter" allowClear placeholder="全部网域" aria-label="筛选所属网域" value={domainFilter} onChange={setDomainFilter} options={[...new Set(sources.map(s=>s.network).filter(Boolean))].map(v=>({value:v,label:v}))}/>
    {(engineFilter||stateFilter||domainFilter||collectionFilter!=='all')&&<Button type="text" onClick={()=>{setEngineFilter(undefined);setStateFilter(undefined);setDomainFilter(undefined);setCollectionFilter('all');}}>重置</Button>}
   </>} columns={[
    {title:'数据源 / 数据库',key:'name',width:250,render:(_,r)=><div className="wx-source-name"><SourceIcon engine={r.engine}/><div><button className="wx-source-title" onClick={()=>openDetails(r)} title={r.name}>{r.name}</button><small title={`${engineLabel(r.engine)} · ${r.network||'未设置网域'}`}>{engineLabel(r.engine)} · {r.network||'未设置网域'}</small><small title={r.owner||'待指定责任方'}>{r.owner||'待指定责任方'}</small></div></div>},
    {title:'连接地址',key:'endpoint',width:165,render:(_,r)=><div className="wx-cell-stack"><Tooltip title="查看主机、端口和完整连接地址，可逐项复制"><button className="source-endpoint-link" onClick={()=>openDetails(r,'connection')}><span>{r.connection.host?sourceEndpoint(r):'查看连接信息'}</span><ArrowRightOutlined/></button></Tooltip><small>{sourceScope(r)!==r.name&&sourceScope(r)!=='未指定命名空间'?sourceScope(r):'点击查看详细配置'}</small></div>},
    {title:'已采集结构',key:'structure',width:110,render:(_,r)=><button className="wx-count-link" onClick={()=>viewTables(r)} disabled={!r.entityCount}><span><b>{r.entityCount??0}</b> 张表</span><small>{r.fieldCount??0} 个字段</small></button>},
    {title:'最近采集',key:'collected',width:210,render:(_,r)=><div className="wx-cell-stack"><span className="source-date">{r.lastCollectedAt?date(r.lastCollectedAt):r.entityCount?'已采集，时间未提供':'尚未采集'}</span><span className="source-activity-actions"><Popover trigger="click" title="连接状态" content={<div className="source-status-detail"><Status value={r.status}/><p>{r.status==='DISABLED'?'数据源已停用，请先恢复后再测试。':r.status==='CONNECTED'?'最近一次连接测试通过。':r.status==='ERROR'?'最近一次连接测试未通过，可重新测试。':'尚无成功的连接测试记录。'}</p><small>{r.last_test_at?`最近测试：${date(r.last_test_at)}`:'暂无测试时间'}</small></div>}><button className="source-status-trigger" aria-label={`${r.name}连接状态，点击查看说明`}><Status value={r.status}/></button></Popover><Button type="link" size="small" className="source-test-link" disabled={!canManage()||busy||r.status==='DISABLED'} onClick={()=>void inspect(r)}>测试连接</Button></span></div>},
    {title:'操作',key:'actions',fixed:'right',width:128,render:(_,r)=><Space className="wx-source-actions" size={6}><Tooltip title={r.status==='DISABLED'?'请先恢复数据源':'查看已采集结构，或发起真实元数据采集'}><Button size="small" className="source-collect-button" icon={<PlayCircleOutlined/>} disabled={r.status==='DISABLED'||!canManage()||busy} onClick={()=>setBrowse(r)}>采集</Button></Tooltip><Dropdown trigger={['click']} menu={menu(r)} placement="bottomRight"><Button size="small" type="text" icon={<MoreOutlined/>} aria-label={`${r.name}更多操作`}/></Dropdown></Space>},
   ]}/></div>
  <div className="wx-source-footer">
   <Panel title="多源结构分布" description="按登记类型查看数据资产组成" extra={<span className="source-insight-badge">{categories.length} 种类型</span>}><div className="wx-engine-distribution">{categories.map(engine=>{const own=sources.filter(s=>s.engine===engine);return <button key={engine} aria-pressed={engineFilter===engine} onClick={()=>setEngineFilter(engineFilter===engine?undefined:engine)}><SourceIcon small engine={engine}/><span>{engineLabel(engine)}</span><i><b style={{width:`${sources.length?own.length/sources.length*100:0}%`}}/></i><strong>{own.length}</strong></button>;})}</div></Panel>
   <Panel title="采集覆盖情况" description="统计当前租户已采集的真实结构"><div className="wx-coverage-number"><strong>{sources.length?Math.round(collected/sources.length*100):0}<small>%</small></strong><span>{collected} / {sources.length} 个来源已采集</span></div><div className="wx-coverage-track"><span style={{width:`${sources.length?collected/sources.length*100:0}%`}}/></div><div className="wx-coverage-split"><div><b>{entityCount}</b><span>数据对象</span></div><div><b>{fieldCount}</b><span>结构字段</span></div><div><b>{'—'}</b><span>集合与索引</span></div></div></Panel>
   <Panel title="从来源到业务模型" description="把分散的结构组织为可读的业务关系"><ol className="source-workflow"><li><span>01</span><div><b>登记与检查</b><small>明确来源类型、地址与业务归属</small></div></li><li><span>02</span><div><b>采集表与字段</b><small>复用登记流程的异步元数据采集</small></div></li><li><span>03</span><div><b>跨来源全屏建模</b><small>在同一画布中维护字段关联</small></div></li></ol><Button type="link" onClick={()=>nav('/governance/metadata/models')}>进入数据模型 <ArrowRightOutlined/></Button></Panel>
  </div>
  <EditorModal width={600} presentation="drawer" open={edit!==undefined} title={edit?'编辑数据源':'登记数据源'} initial={initial} onCancel={()=>setEdit(undefined)} saveMessage="数据源已保存到数据中台" storageHint="配置与元数据管理平台共享" onTest={async v=>{setConnectionError('');try{const result=await sharedSourceApi.test(draftFromForm(v,edit),edit?.id);if(result.connected!==true)throw new Error(connectionFailureMessage(result.error||result.message));}catch(e){const detail=connectionFailureMessage(e);setConnectionError(detail);throw new Error(detail);}}} onSave={async v=>{const saved=await saveSource(v,edit);if(!saved.tid)throw new Error('保存接口未返回数据源标识，请刷新核对后再操作');let confirmed:Row|undefined;try{confirmed=await readSource(saved.tid);if(edit){confirmed.entityCount=sources.find(s=>s.id===saved.tid)?.entityCount??confirmed.entityCount;confirmed.fieldCount=sources.find(s=>s.id===saved.tid)?.fieldCount??confirmed.fieldCount;}}catch{message.warning('保存已完成，暂未能读取主记录，请勿重复登记');}return {...saved,confirmed};}} onSaved={result=>{const saved=result as Row;if(saved.confirmed)setConfirmedSources(rows=>[...rows.filter(row=>row.id!==saved.tid),saved.confirmed]);void syncIndex(saved.tid,saved.confirmed);}}><>{connectionError&&<Alert className="wx-source-connection-alert" showIcon type="error" title="连接测试未通过" description={connectionError}/>}<SourceFields editing={!!edit} choices={choices}/></></EditorModal>
  <Drawer className="wx-source-detail-drawer" open={!!source} width={820} title="数据源详情" onClose={()=>setDetails(undefined)} extra={source&&canManage()&&<Button onClick={()=>{void openEditor(source);setDetails(undefined);}} icon={<EditOutlined/>}>编辑信息</Button>}>
   {detailsQuery.error&&<Alert type="error" showIcon title="数据源详情读取失败" description={String(detailsQuery.error)} action={<Button onClick={detailsQuery.refresh}>重试</Button>}/>}
   {source&&<><div className="wx-source-drawer-heading"><SourceIcon engine={source.engine}/><div><h2>{source.name}</h2><p>{engineLabel(source.engine)} · 数据源 ID：{source.code}</p></div><Status value={source.status}/></div><Tabs activeKey={detailsTab} onChange={setDetailsTab} items={[
    {key:'summary',label:'来源概览',children:<Descriptions column={{xs:1,sm:2}} bordered items={[
     {key:'owner',label:'责任方',children:source.owner||'未设置'},{key:'system',label:'业务系统',children:source.businessSystem||'未设置'},
     {key:'address',label:'登记地址',children:sourceEndpoint(source)},{key:'scope',label:'命名空间',children:sourceScope(source)},
     {key:'network',label:'所属网域',children:source.network||'未设置'},{key:'updated',label:'更新时间',children:date(source.updatedAt)},
     {key:'entity',label:'已采集对象',children:source.entityCount},{key:'field',label:'结构字段',children:source.fieldCount},
     {key:'desc',label:'业务说明',span:2,children:source.description||'暂无说明'},
    ]}/>},
    {key:'connection',label:'连接信息',children:<div className="source-connection-detail"><p className="source-connection-hint">连接配置来自数据源登记记录。点击右侧按钮可复制地址或其他字段；密码和密钥不会显示。</p>{detailsQuery.loading&&!detailDraft?<span>正在读取连接信息…</span>:connectionEntries.length?<Descriptions bordered column={1} items={connectionEntries.map(field=>({key:field.key,label:field.label,children:<div className="source-connection-value"><code>{field.value}</code><Tooltip title={`复制${field.label}`}><Button size="small" type="text" icon={<CopyOutlined/>} aria-label={`复制${field.label}`} onClick={()=>void copyConnection(field.value)}/></Tooltip></div>}))}/>:!detailsQuery.error?<Alert type="info" showIcon title="暂无可展示的连接信息" description="登记记录没有提供地址字段，可联系数据源管理员补充。"/>:null}</div>},
    {key:'objects',label:'数据表 '+detailTables.total,children:<DataTable rows={detailTables.rows} loading={detailTablesLoading} error={detailTablesError} onRefresh={()=>setDetailTablesRevision(value=>value+1)} titleKey="source-detail-live-objects" showExport={false} onSearch={value=>{setDetailTableKeyword(value);setDetailTablePage(1);}} searchPlaceholder="按表名或说明查询" serverPagination={{page:detailTablePage,size:detailTableSize,total:detailTables.total,onChange:(page,size)=>{setDetailTablePage(page);setDetailTableSize(size);}}} columns={[{title:'数据表',dataIndex:'displayName',render:(_,r)=><span className="wx-cell-stack"><b>{r.displayName||r.name}</b><small>{r.name}</small></span>},{title:'类型',dataIndex:'kind',render:v=>objectKindLabel(v)},{title:'字段',dataIndex:'fieldCount'},{title:'操作',width:116,render:()=> <Button type="link" onClick={()=>viewTables(source)}>查看数据表</Button>}]}/>},
    {key:'history',label:'采集记录',children:<><Alert type="info" title="原接口提供最近一次表采集任务，不提供完整历史列表" style={{marginBottom:16}}/>{metadataQuery.error&&<Alert type="error" showIcon title="采集记录读取失败" description={metadataQuery.error} action={<Button onClick={metadataQuery.refresh}>重试</Button>}/>}<DataTable rows={history} loading={metadataQuery.loading} titleKey="source-detail-live-history" columns={[{title:'任务',dataIndex:'name'},{title:'状态',dataIndex:'status',render:v=><Status value={v}/>},{title:'执行阶段',dataIndex:'phase'},{title:'操作',width:144,render:()=> <Button type="link" onClick={()=>{setDetails(undefined);setBrowse(source);}}>查看采集进度</Button>}]}/></>},
   ]}/></>}
  </Drawer>
  <SourceCollectionDrawer source={browse} onClose={()=>{setBrowse(null);q.refresh();}} onComplete={()=>{q.refresh();metadataQuery.refresh();setDetailTablesRevision(value=>value+1);}}/>
 </Page>;
}
