import { type Row } from '../../../services/api';
import { readMetadata, metadataScope, metadataWritable, saveMetadataRelation, deleteMetadataRelation, discoverMetadataRelations, validateMetadataRelation } from '../../../services/metadata';
import { metadataSnapshot, metadataRelationship, metadataEvidence, canonicalId, sourceIdentity } from '../../../services/metadataSnapshot';
import { listModelViews, saveModelView, removeModelView } from '../../../services/metadataViews';
import type { Entity, MetadataSnapshot, Relationship, RelationCreate } from '../types/domain';
import type { JobProgress, ViewModel, WorkspaceData } from '../core/model';
const versions=new Map<string,number>();let activeModel='';let discoveryController:AbortController|undefined;
function layout(v:ViewModel){return {nodes:v.nodes,librarySourceIds:v.librarySourceIds??[],hiddenRelationshipIds:v.hiddenRelationshipIds,fieldMode:v.fieldMode,relationFilter:v.relationFilter,viewport:v.viewport,showGrid:v.showGrid,snapToGrid:v.snapToGrid,showEdgeLabels:v.showEdgeLabels};}
export function modelPayload(view:ViewModel,entities:Entity[],current:Record<string,string>){const manifest={...(view.snapshotManifest||{})};for(const node of view.nodes){const entity=entities.find(e=>e.id===node.entityId);if(!entity)throw new Error('模型包含无法读取的实体');if(!manifest[entity.sourceId]){if(!current[entity.sourceId])throw new Error('数据源还没有已发布的结构快照');manifest[entity.sourceId]=current[entity.sourceId];}}return {name:view.name,code:view.modelInfo?.code||'model-'+view.id.slice(0,8),domain:view.modelInfo?.domain||'',description:view.description||'',manifest,layout:layout(view)};}
function toView(row:Row,snapshot:MetadataSnapshot):ViewModel{const entitySources=new Map(snapshot.entities.map(e=>[e.id,e.sourceId])),ids=new Set(entitySources.keys()),knownSources=new Set(snapshot.sources.map(s=>s.id));const nodes=(row.layout?.nodes||[]).filter((n:Row)=>ids.has(n.entityId));const declared=Array.isArray(row.layout?.librarySourceIds)?row.layout.librarySourceIds:row.sourceId?[row.sourceId]:[];const normalized=declared.filter((id:unknown):id is string=>typeof id==='string').map((id:string)=>knownSources.has(id)?id:sourceIdentity(id));const librarySourceIds=[...new Set([...normalized,...nodes.map((n:Row)=>entitySources.get(n.entityId))])].filter((id):id is string=>typeof id==='string'&&knownSources.has(id));return {...row.layout,id:row.id,workspaceId:metadataScope(),snapshotId:snapshot.id,name:row.name,description:row.description||'',version:Number(row.version||1),updatedAt:row.updatedAt||'',nodes,librarySourceIds,hiddenRelationshipIds:row.layout?.hiddenRelationshipIds||[],fieldMode:row.layout?.fieldMode||'key',relationFilter:row.layout?.relationFilter||['confirmed','suggested'],modelInfo:{code:row.code||'',domain:row.domain||'',layer:'',status:'BROWSER_LAYOUT'}};}
async function semantics(_modelId?:string){const data=await readMetadata();const id='shared-metadata:'+metadataScope();return {relationships:data.relations.map(r=>metadataRelationship(r,id,metadataScope())),evidence:data.relations.flatMap(r=>metadataEvidence(r,id))};}
async function load():Promise<WorkspaceData>{const data=await readMetadata(),scope=metadataScope(),snapshot=metadataSnapshot(data,scope);const rows=listModelViews();const diagrams=rows.map(r=>toView(r,snapshot));if(!diagrams.length)diagrams.push(toView({id:'metadata-default-view',name:'已采集元数据视图',version:0,layout:{nodes:snapshot.entities.filter(e=>e.fields.length).slice(0,30).map((e,i)=>({entityId:e.id,position:{x:(i%4)*390,y:Math.floor(i/4)*450}}))}},snapshot));activeModel=diagrams.find(d=>d.id===activeModel)?.id||diagrams[0].id;versions.clear();rows.forEach(r=>versions.set(r.id,Number(r.version)));return {schemaVersion:'1.0',kind:'wanxiang-workspace',snapshot,relationships:data.relations.map(r=>metadataRelationship(r,snapshot.id,scope)),evidence:data.relations.flatMap(r=>metadataEvidence(r,snapshot.id)),diagrams,activeDiagramId:activeModel,audit:[],updatedAt:new Date().toISOString()};}
async function save(data:WorkspaceData){if(!metadataWritable())throw new Error('请先登录');const v=data.diagrams.find(d=>d.id===data.activeDiagramId);if(!v)return;const result=saveModelView({name:v.name,code:v.modelInfo?.code,domain:v.modelInfo?.domain,description:v.description,layout:layout(v)},v.id,versions.get(v.id));versions.set(v.id,result.version);}
async function activate(data:WorkspaceData,id:string):Promise<WorkspaceData>{const current=await load();if(!current.diagrams.some(d=>d.id===id))throw new Error('模型视图不存在');activeModel=id;return {...data,...current,activeDiagramId:id};}
export function relationBody(value:RelationCreate|Relationship,old?:Relationship):Row{if(!value.mappings?.length||value.mappings.length>64)throw new Error('请配置 1 至 64 组字段映射');if(!['reference','join',undefined].includes(value.semanticType))throw new Error('请选择引用或连接关系');return {...(old?.id&&!old.id.startsWith('candidate:')?{tid:old.id,expectedVersion:old.version}:{}),sourceTableId:canonicalId(value.sourceEntityId),targetTableId:canonicalId(value.targetEntityId),sourceColumnId:canonicalId(value.mappings[0].sourceFieldId),targetColumnId:canonicalId(value.mappings[0].targetFieldId),mappings:value.mappings.map(m=>({sourceColumnId:canonicalId(m.sourceFieldId),targetColumnId:canonicalId(m.targetFieldId),comparisonRule:m.comparisonRule||'exact'})),conditions:(value.conditions||[]).map(t=>({side:t.side,columnId:canonicalId(t.fieldId),operator:t.operator,value:t.value})),targetsPerSource:value.targetsPerSource,sourcesPerTarget:value.sourcesPerTarget,relationName:value.name,relationType:value.semanticType==='join'?'JOIN':'REFERENCE',origin:old?.origin==='inference'?'INFERENCE':'MANUAL',status:old?.reviewStatus?.toUpperCase()||'CONFIRMED',description:value.description||'',confidence:old?.recommendation?.score||0};}
async function saveRelationship(_modelId:string,value:RelationCreate,old?:Relationship){return metadataRelationship(await saveMetadataRelation(relationBody(value,old)),'shared-metadata:'+metadataScope(),metadataScope());}
async function decide(relation:Relationship,status:string){return metadataRelationship(await saveMetadataRelation({...relationBody(relation,relation),status:status.toUpperCase()}),relation.snapshotId,metadataScope());}
export function mergeDiscoveredRelationships(existing:Relationship[],candidates:Relationship[]){
 const saved=existing.filter(r=>!r.id.startsWith('candidate:'));
 const key=(r:Relationship)=>JSON.stringify([r.sourceEntityId,r.targetEntityId,(r.mappings||[]).map(m=>[m.sourceFieldId,m.targetFieldId]).sort()]);
 const known=new Set(saved.map(key)),fresh:Relationship[]=[];
 for(const candidate of candidates){const fingerprint=key(candidate);if(!known.has(fingerprint)){known.add(fingerprint);fresh.push(candidate);}}
 return {relationships:[...saved,...fresh],newCount:fresh.length,skippedCount:candidates.length-fresh.length};
}
async function discover(snapshot:MetadataSnapshot,existing:Relationship[],scope:string[],signal:AbortSignal,onProgress:(job:JobProgress)=>void){const id=crypto.randomUUID();discoveryController=new AbortController();const combined=AbortSignal.any([signal,discoveryController.signal]);onProgress({id,status:'running',stage:1,title:'正在共享后端分析已采集表结构',processed:0,total:scope.length,newCount:0,skippedCount:0});try{const rows=await discoverMetadataRelations(scope.map(canonicalId),combined);const candidates=rows.map((r:Row)=>metadataRelationship({...r,tid:'candidate:'+r.source_table_id+':'+r.source_column_id+':'+r.target_table_id+':'+r.target_column_id,relation_origin:'INFERENCE',relation_status:'SUGGESTED'},snapshot.id,metadataScope()));const merged=mergeDiscoveredRelationships(existing,candidates);return {relationships:merged.relationships,evidence:[],job:{id,status:'completed' as const,stage:1,title:'结构候选已生成，确认后写入共享关系台账',processed:scope.length,total:scope.length,newCount:merged.newCount,skippedCount:merged.skippedCount}};}finally{discoveryController=undefined;}}
export const workspaceService={load,save,activate,saveRelationship,decide,discover,refreshSemantics:semantics,async cancel(){discoveryController?.abort();},
 async removeRelationship(id:string){if(!id.startsWith('candidate:'))await deleteMetadataRelation(id);},
 async create(name:string,source?:ViewModel):Promise<ViewModel>{const current=await readMetadata();const row=saveModelView({name,description:source?.description,domain:source?.modelInfo?.domain,layout:source?layout(source):{nodes:[]}});versions.set(row.id,row.version);return toView(row,metadataSnapshot(current,metadataScope()));},
 async remove(view:ViewModel){removeModelView(view.id,versions.get(view.id));versions.delete(view.id);},
 async rename(view:ViewModel,name:string,description?:string){const row=saveModelView({name,description:description??view.description},view.id,versions.get(view.id));versions.set(view.id,row.version);return toView(row,metadataSnapshot(await readMetadata(),metadataScope()));},
 importWorkspace(_value:unknown):WorkspaceData{throw new Error('离线快照导入已移除，请通过数据源采集更新共享元数据');},
 reset():WorkspaceData{throw new Error('不会清空共享元数据；请在模型管理中删除指定的本地视图');},
 async validate(id:string,_modelId:string,update:(job:Row)=>void){if(id.startsWith('candidate:'))throw new Error('请先确认并保存关系后再进行数据验证');update({phase:'正在读取真实联合键与条件范围（最多 30 秒）'});return validateMetadataRelation(id);}
};
