import { App, Button, Empty, Table, Tag, Tooltip } from 'antd';
import type { TableProps } from 'antd';
import { useRef, useState } from 'react';
import Icon, {type IconName} from '../design/Icon';
export function Panel({title,extra,children,className=''}:{title?:string;extra?:React.ReactNode;children:React.ReactNode;className?:string}){return <section className={`ht-panel ${className}`}>{title&&<header className="ht-panel-head"><h2>{title}</h2>{extra}</header>}<div className="ht-panel-body">{children}</div></section>;}
export function IconButton({icon,label,onClick,disabled=false,active=false}:{icon:IconName;label:string;onClick:()=>void;disabled?:boolean;active?:boolean}){return <Tooltip title={label}><Button aria-label={label} className={active?'icon-active':''} type="text" icon={<Icon name={icon}/>} onClick={onClick} disabled={disabled}/></Tooltip>;}
/** Display timestamps consistently in the workspace timezone; stable width for table cells. */
export const formatTime=(value?:string)=>{
 if(!value||!Number.isFinite(Date.parse(value)))return '—';
 const parts=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));
 const get=(type:string)=>parts.find(p=>p.type===type)?.value||'';
 return `${get('year')}-${get('month')}-${get('day')} ${get('hour')}:${get('minute')}:${get('second')}`;
};
const labels:Record<string,string>={QUEUED:'排队中',RUNNING:'运行中',SUCCEEDED:'已完成',FAILED:'失败',CANCELLED:'已取消',MATCH:'一致',DIFFERENT:'有差异',INCOMPLETE:'证据不完整',PARTIAL:'部分完成',PENDING:'待处理',HEALTHY:'可用',MAINTENANCE:'维护中',BLOCKED:'已阻断',ONLINE:'在线',OFFLINE:'离线',MISSING:'来源有 / 目标无',EXTRA:'目标多出',CONTENT:'内容不同',DUPLICATE:'主键重复',NULL_KEY:'主键为空'};
export function StateTag({state}:{state:string}){const good=['SUCCEEDED','MATCH','HEALTHY','ONLINE'],bad=['FAILED','BLOCKED','OFFLINE'],warn=['DIFFERENT','PARTIAL','INCOMPLETE'];return <Tag color={good.includes(state)?'success':bad.includes(state)?'error':warn.includes(state)?'warning':state==='RUNNING'?'processing':'default'}><span className="state-dot"/>{labels[state]||state}</Tag>;}
export function DataTable<T extends object>({columns,dataSource,...props}:TableProps<T>){return <div className="ht-table-wrap"><Table<T> size="small" columns={columns} dataSource={dataSource} scroll={{x:'max-content'}} pagination={{defaultPageSize:10,showSizeChanger:true,pageSizeOptions:[10,20,50],showTotal:n=>`共 ${n} 条记录`}} locale={{emptyText:<EmptyState title="暂无符合条件的记录" text="请调整筛选条件，或先补充任务、账单与策略样例。" compact/>}} {...props}/></div>;}
export function Loading({text='正在装载本地工作区',compact=false}:{text?:string;compact?:boolean}){return <div className={`ocean-loading ${compact?'compact':''}`} role="status" aria-live="polite"><div className="loading-path"><span/><span/><span/><i/></div><strong>{text}</strong><p>连接配置、执行记录与对账证据</p>{!compact&&<div className="skeleton-grid">{[0,1,2,3].map(i=><div key={i}/>)}</div>}</div>;}
export function EmptyState({title,text,action,compact=false}:{title:string;text:string;action?:React.ReactNode;compact?:boolean}){return <div className={`ht-empty ${compact?'compact':''}`}><div className="ht-empty-mark"><Icon name="wave" size={34}/></div><h3>{title}</h3><p>{text}</p>{action}</div>;}
export function InsightStrip({items}:{items:{label:string;value:React.ReactNode;hint?:string;icon?:IconName;tone?:'default'|'cyan'|'amber'}[]}){return <div className="insight-strip">{items.map((item,index)=><section key={index} className={`insight-item tone-${item.tone||'default'}`}><span className="insight-icon"><Icon name={item.icon||'panel'} size={18}/></span><div><small>{item.label}</small><strong>{item.value}</strong>{item.hint&&<p>{item.hint}</p>}</div></section>)}</div>;}
export function useSafeAction(){const {message}=App.useApp();const [busy,setBusy]=useState(false);const lock=useRef(false);return {busy,perform:async(fn:()=>Promise<unknown>,success?:string)=>{if(lock.current)return;lock.current=true;setBusy(true);try{const result=await fn();if(success)message.success(success);return result;}catch(e){message.error(e instanceof Error?e.message:String(e));return undefined;}finally{lock.current=false;setBusy(false);}}};}
export function FlowMini({cross=false}:{cross?:boolean}){return <div className="flow-mini">{(cross?['database','tasks','cross','database']:['database','tasks','database']).map((n,i)=><span key={i}><span className={`mini-block step-${i}`}><Icon name={n as IconName} size={16}/></span>{i<(cross?3:2)&&<span className="mini-link"/>}</span>)}</div>;}
