import { Alert, Button, Descriptions, Drawer, Progress, Space, Steps, Tabs, Tag } from 'antd';
import { useWorkbench } from '../app/Workbench';
import { DataTable, Panel, StateTag, formatTime, useSafeAction } from './Common';
import { STAGES } from '../domain/types';
import Icon from '../design/Icon';
export function TaskDetail({id,onClose}:{id:string;onClose:()=>void}){
 const {state,act,editTask,openCanvas,showRun}=useWorkbench();const {perform,busy}=useSafeAction();const t=state.tasks.find(t=>t.id===id);
 return <Drawer title={t?.name||'任务不存在'} open onClose={onClose} width={860} extra={t&&<Space><Button onClick={()=>editTask(t)}>编辑配置</Button><Button type="primary" onClick={()=>{onClose();openCanvas(id);}}>打开 NiFi 画布</Button></Space>}>
 {t&&<><Descriptions column={2} size="small" items={[{key:'code',label:'任务代码',children:t.code},{key:'type',label:'业务场景',children:t.scenario},{key:'owner',label:'责任人',children:t.owner},{key:'cluster',label:'本地运行集群',children:state.clusters.find(c=>c.id===t.clusterId)?.name},{key:'rev',label:'当前草稿',children:`v${t.revision}`},{key:'pub',label:'本地发布版本',children:t.publishedRevision?`v${t.publishedRevision}`:'未发布'},{key:'updated',label:'最后修改',children:formatTime(t.updatedAt)},{key:'schedule',label:'调度时区',children:'Asia/Shanghai'},{key:'nifi',label:'NiFi 流程 ID',children:t.nifiPipelineId||'尚未关联'}]}/>
 <Alert type="info" showIcon style={{marginBottom:16}} message="本地任务与 NiFi 流程分别保存" description="当前表映射、发布版本和模拟运行仍保存在本地工作区。打开 NiFi 画布后需配置真实节点；首次保存新流程会把流程 ID 关联到此任务，NiFi 的部署和启动在画布中操作。"/>
 <div className="detail-actions"><Button disabled={busy||t.paused||!t.published||t.archived} icon={<Icon name="play" size={17}/>} onClick={()=>void perform(async()=>{const next=await act({type:'RUN_TASK',id:t.id});showRun(next.runs[0].id);},'本地运行已登记')}>本地模拟运行</Button><Button disabled={busy||t.archived} onClick={()=>void perform(()=>act({type:'PUBLISH_TASK',id:t.id}),'校验通过，本地版本已发布')}>发布本地草稿</Button><Tag color={t.fault==='NONE'?'blue':'warning'}>本地场景：{({NONE:'正常',MISSING:'未接收差异',CONTENT:'内容差异',TRANSPORT:'确认超时'})[t.fault]}</Tag></div>
 <Tabs items={[{key:'mappings',label:`表映射 (${t.mappings.length})`,children:<div className="mapping-list">{t.mappings.map(m=><Panel key={m.id} title={`${state.tables.find(x=>x.id===m.sourceTableId)?.name} → ${state.tables.find(x=>x.id===m.targetTableId)?.name}`} extra={<Tag>{m.writeMode==='UPSERT'?'按主键更新':'追加'}</Tag>}><DataTable rowKey="sourceField" pagination={false} dataSource={m.fields} columns={[{title:'来源字段',dataIndex:'sourceField'},{title:'目标字段',dataIndex:'targetField'},{title:'转换方式',render:(_,r)=>({EXACT:'原值保留',TRIM:'去空白',UPPER:'大写',LOWER:'小写'})[r.transform]}]}/></Panel>)}</div>},
 {key:'runs',label:'运行记录',children:<DataTable rowKey="id" dataSource={state.runs.filter(r=>r.taskId===id)} columns={[{title:'批次',render:(_,r)=>r.id.slice(-8)},{title:'版本',render:(_,r)=>`v${r.task.revision}`},{title:'开始时间',render:(_,r)=>formatTime(r.startedAt)},{title:'状态',render:(_,r)=><StateTag state={r.status}/>},{title:'操作',render:(_,r)=><Button type="link" onClick={()=>showRun(r.id)}>详情</Button>}]}/>},
 {key:'published',label:'版本说明',children:<Alert type="info" showIcon message="草稿、发布、运行分别保存" description="编辑配置只增加草稿修订。运行实例引用触发时的发布版本与本地输入快照，不会随着草稿变化被改写。"/>}]}/></>}
 </Drawer>;
}
export function RunDetail({id,onClose}:{id:string;onClose:()=>void}){
 const {state,act,openCanvas}=useWorkbench();const {perform,busy}=useSafeAction();const r=state.runs.find(r=>r.id===id);
 return <Drawer title={r?`${r.task.name} · 运行详情`:'运行不存在'} open onClose={onClose} width={900}>{r&&<><div className="run-summary"><div><span className="helper">RUN / {r.id.slice(-8)}</span><h2>发布版本 v{r.task.revision}</h2><p>{formatTime(r.startedAt)}　{r.finishedAt?`结束：${formatTime(r.finishedAt)}`:'等待本地执行完成'}</p></div><StateTag state={r.status}/></div>
 <div className={`run-stage-strip ${r.status==='RUNNING'?'is-running':''}`}><Steps size="small" current={Math.max(0,r.stage)} status={r.status==='FAILED'?'error':r.status==='SUCCEEDED'?'finish':'process'} items={STAGES.map(title=>({title}))}/></div>
 <div className="detail-actions">{['QUEUED','RUNNING'].includes(r.status)&&<Button danger disabled={r.cancelRequested||busy} onClick={()=>void perform(()=>act({type:'CANCEL_RUN',id:r.id}),'取消请求已保存')}>{r.cancelRequested?'取消中':'取消未完成阶段'}</Button>}<span className="helper">运行结果取决于已保存的本地映射与运行场景；未访问外部数据库。</span></div>
 <Tabs items={[{key:'result',label:'表级结果',children:<DataTable rowKey="id" pagination={false} dataSource={r.items} columns={[{title:'目标表',render:(_,i)=>state.tables.find(t=>t.id===i.mapping.targetTableId)?.name},{title:'查询输出',dataIndex:'input'},{title:'预期',dataIndex:'expected'},{title:'确认写入',dataIndex:'written'},{title:'状态',render:(_,i)=><StateTag state={i.status}/>},{title:'说明',render:(_,i)=>i.error||'—'}]}/>},
 {key:'logs',label:`运行日志 (${r.logs.length})`,children:<div className="run-log">{r.logs.map((l,i)=><p key={i} className={`log-${l.level.toLowerCase()}`}><time>{formatTime(l.at)}</time><b>{l.level}</b><span>{l.message}</span></p>)}</div>},
 {key:'flow',label:'冻结流程',children:<div className="frozen-flow">{r.task.flow.nodes.map((n,i)=><div key={n.id}><span className={`frozen-node ${r.stage>i?'complete':''}`}><Icon name={n.kind==='read'||n.kind==='write'?'database':n.kind==='transform'?'tasks':'cross'} size={24}/><b>{n.name}</b><small>{n.kind}</small></span>{i<r.task.flow.nodes.length-1&&<Icon name="arrow"/>}</div>)}</div>},
 {key:'bills',label:'即时账单',children:<><Alert type="info" showIcon message="即时账单比对本批次的预期与接收数量，不等于全量目标表内容一致。"/><DataTable rowKey="id" dataSource={state.bills.filter(b=>b.runId===id)} columns={[{title:'账单',render:(_,b)=>b.id.slice(-8)},{title:'预期',dataIndex:'expected'},{title:'接收',dataIndex:'received'},{title:'结果',render:(_,b)=><StateTag state={b.status}/>},{title:'核销',render:(_,b)=>b.writeoff?'已核销':'待核销'}]}/></>}]}/>
 </>}</Drawer>;
}
