import { App, Alert, Button, Checkbox, Form, Input, InputNumber, Modal, Radio, Select, Space, Steps, Table, Tag } from 'antd';
import { useMemo, useState } from 'react';
import type { Scenario, TableMapping, Task, Transform } from '../domain/types';
import { clone, defaultFlow, matchingMapping, validateTask } from '../domain/rules';
import { newTask } from '../domain/engine';
import { useWorkbench } from '../app/Workbench';
import Icon from '../design/Icon';
import { FlowMini, useSafeAction } from './Common';
export default function TaskWizard({initial,scenario='接入',onClose}:{initial?:Task;scenario?:Scenario;onClose:()=>void}){
 const {state,act,openCanvas}=useWorkbench();const {modal}=App.useApp();const {busy,perform}=useSafeAction();const [step,setStep]=useState(0);
 const [draft,setDraft]=useState<Task>(()=>initial?clone(initial):newTask('',state.clusters[0].id,[],defaultFlow(scenario==='跨网'),scenario));const [baseline]=useState(()=>JSON.stringify(draft));const [touched,setTouched]=useState(false);
 const [sourceId,setSourceId]=useState(()=>state.tables.find(t=>t.id===draft.mappings[0]?.sourceTableId)?.sourceId||state.sources[0].id);
 const [targetId,setTargetId]=useState(()=>state.tables.find(t=>t.id===draft.mappings[0]?.targetTableId)?.sourceId||state.sources[2]?.id||state.sources[1].id);
 const [selectedMap,setSelectedMap]=useState(0);const active=draft.mappings[Math.min(selectedMap,draft.mappings.length-1)];
 const errors=useMemo(()=>validateTask(draft,state).filter(e=>e.level==='error'),[draft,state]);
 const update=(patch:Partial<Task>)=>{setDraft(d=>({...d,...patch}));setTouched(true);};
 const leave=()=>{if(JSON.stringify(draft)!==baseline)modal.confirm({title:'放弃尚未保存的任务修改？',content:'已发布版本和执行记录不会受到影响。',okText:'放弃修改',cancelText:'继续编辑',onOk:onClose});else onClose();};
 const mapUpdate=(m:TableMapping)=>update({mappings:draft.mappings.map(x=>x.id===m.id?m:x)});
 const save=async(publish=false,canvas=false)=>{
  if(!draft.name.trim()){setStep(0);setTouched(true);return;}
  await perform(async()=>{let next=await act({type:'SAVE_TASK',task:draft,expected:initial?.revision});if(publish)next=await act({type:'PUBLISH_TASK',id:draft.id});onClose();if(canvas)openCanvas(draft.id);return next;},publish?'任务版本已发布':'任务草稿已保存');
 };
 return <Modal title={<span className="modal-title-with-kicker"><small>任务开发</small>{initial?'编辑集成任务':'创建集成任务'}</span>} open onCancel={leave} width={1040} className="task-wizard" maskClosable={false} footer={<div className="wizard-footer"><span>本地草稿修改不影响已发布版本</span><Space><Button onClick={leave}>取消</Button><Button onClick={()=>void save()} loading={busy}>保存草稿</Button>{step>0&&<Button onClick={()=>setStep(s=>s-1)}>上一步</Button>}{step<4?<Button type="primary" onClick={()=>{if(step===0&&!draft.name.trim()){setTouched(true);return;}if(step===1&&!draft.mappings.length){setTouched(true);return;}setStep(s=>s+1);}}>下一步</Button>:<><Button onClick={()=>void save(false,true)} loading={busy}>保存并打开 NiFi 画布</Button><Button type="primary" disabled={!!errors.length} loading={busy} onClick={()=>void save(true)}>发布本地版本</Button></>}</Space></div>}>
  <Steps current={step} size="small" items={['业务场景','来源与目标','字段映射','调度与集群','校验发布'].map(title=>({title}))}/>
  <div className="wizard-content">
  {step===0&&<><div className="scenario-grid">{(['接入','同步','分发','跨网','多表同步'] as Scenario[]).map((v,i)=><button key={v} className={draft.scenario===v?'selected':''} onClick={()=>update({scenario:v,flow:defaultFlow(v==='跨网')})}><Icon name={(['ingress','tasks','distribution','cross','multi'] as const)[i]} size={26}/><strong>{v}</strong><span>{['业务源数据进入主题库','在来源与目标之间同步','将批准范围的数据分发','编排跨网发送与接收','一个流程管理多张表'][i]}</span></button>)}</div><Form layout="vertical"><div className="form-grid"><Form.Item label="任务名称" required validateStatus={touched&&!draft.name.trim()?'error':''} help={touched&&!draft.name.trim()?'请输入任务名称':undefined}><Input maxLength={80} value={draft.name} onChange={e=>update({name:e.target.value})} placeholder="例如：节目备案增量接入"/></Form.Item><Form.Item label="任务代码" required><Input value={draft.code} maxLength={40} onChange={e=>update({code:e.target.value})}/></Form.Item><Form.Item label="责任人"><Input value={draft.owner} onChange={e=>update({owner:e.target.value})}/></Form.Item></div></Form></>}
  {step===1&&<><div className="source-bridge"><Form layout="vertical"><Form.Item label="来源数据库"><Select value={sourceId} onChange={setSourceId} options={state.sources.map(s=>({value:s.id,label:`${s.name} / ${s.engine}`}))}/></Form.Item></Form><Icon name="arrow" size={28}/><Form layout="vertical"><Form.Item label="目标数据库"><Select value={targetId} onChange={setTargetId} options={state.sources.map(s=>({value:s.id,label:`${s.name} / ${s.engine}`}))}/></Form.Item></Form></div><Alert type="info" showIcon message="基于本地技术快照配置，不连接数据库；默认匹配同名字段。"/>
   <Table size="small" pagination={false} rowKey="id" dataSource={state.tables.filter(t=>t.sourceId===sourceId)} columns={[{title:'选择',width:60,render:(_,t)=><Checkbox checked={draft.mappings.some(m=>m.sourceTableId===t.id)} onChange={e=>{if(!e.target.checked)update({mappings:draft.mappings.filter(m=>m.sourceTableId!==t.id)});else {const target=state.tables.find(b=>b.sourceId===targetId&&b.label===t.label);if(target)update({mappings:[...draft.mappings,matchingMapping(t,target)]});else modal.info({title:'目标库没有可匹配表',content:'请选择具备相同业务结构的目标来源。'});}}}/>},{title:'来源表',render:(_,t)=><div className="entity-name"><b>{t.label}</b><small>{t.name}</small></div>},{title:'字段数',render:(_,t)=>t.fields.length},{title:'目标表',render:(_,t)=>{const map=draft.mappings.find(m=>m.sourceTableId===t.id);return map?<Select style={{minWidth:200}} value={map.targetTableId} onChange={id=>mapUpdate({...matchingMapping(t,state.tables.find(t=>t.id===id)!),id:map.id})} options={state.tables.filter(t=>t.sourceId===targetId).map(t=>({value:t.id,label:t.name}))}/>:<span className="muted">未选择</span>;}}]}/>{touched&&!draft.mappings.length&&<p className="error-text">请至少选择一张来源表。</p>}</>}
  {step===2&&<>{!active?<Alert type="warning" message="请先选择来源与目标"/>:<><div className="ht-toolbar"><Select style={{minWidth:260}} value={active.id} onChange={id=>setSelectedMap(draft.mappings.findIndex(m=>m.id===id))} options={draft.mappings.map(m=>({value:m.id,label:state.tables.find(t=>t.id===m.sourceTableId)?.label}))}/><Button onClick={()=>{const a=state.tables.find(t=>t.id===active.sourceTableId)!,b=state.tables.find(t=>t.id===active.targetTableId)!;mapUpdate({...active,fields:matchingMapping(a,b).fields});}}>重新匹配同名字段</Button><Select value={active.writeMode} onChange={writeMode=>mapUpdate({...active,writeMode})} options={[{value:'UPSERT',label:'按主键更新写入'},{value:'APPEND',label:'仅追加写入'}]}/></div><Table size="small" pagination={false} rowKey="sourceField" dataSource={active.fields} columns={[{title:'来源字段',dataIndex:'sourceField'},{title:'目标字段',render:(_,m)=><Select style={{width:'100%',minWidth:160}} value={m.targetField} options={state.tables.find(t=>t.id===active.targetTableId)!.fields.map(f=>({value:f.name,label:`${f.label} / ${f.name}`}))} onChange={targetField=>mapUpdate({...active,fields:active.fields.map(f=>f.sourceField===m.sourceField?{...f,targetField}:f)})}/>},{title:'转换方式',render:(_,m)=><Select style={{width:'100%',minWidth:180}} value={m.transform} options={[{value:'EXACT',label:'原值保留'},{value:'TRIM',label:'去除首尾空白'},{value:'UPPER',label:'转为大写'},{value:'LOWER',label:'转为小写'}]} onChange={(transform:Transform)=>mapUpdate({...active,fields:active.fields.map(f=>f.sourceField===m.sourceField?{...f,transform}:f)})}/>}]} /><p className="helper">映射是任务设计，不修改元数据快照。目标必填字段和主键将在发布前复核。</p></>}</>}
  {step===3&&<Form layout="vertical"><div className="form-grid"><Form.Item label="运行集群" required><Select value={draft.clusterId} options={state.clusters.map(c=>({value:c.id,label:`${c.name} · ${c.zone}`}))} onChange={clusterId=>update({clusterId})}/></Form.Item><Form.Item label="触发方式"><Radio.Group value={draft.schedule.kind} onChange={e=>update({schedule:{...draft.schedule,kind:e.target.value}})} options={[{value:'MANUAL',label:'手动触发'},{value:'DAILY',label:'每 24 小时'}]}/></Form.Item>{draft.schedule.kind==='DAILY'&&<Form.Item label="每日分钟相位（0–1439，时区 Asia/Shanghai）"><InputNumber min={0} max={1439} value={draft.schedule.phaseMinute} onChange={v=>update({schedule:{...draft.schedule,phaseMinute:v??0}})}/><span className="helper">　{String(Math.floor(draft.schedule.phaseMinute/60)).padStart(2,'0')}:{String(draft.schedule.phaseMinute%60).padStart(2,'0')}</span></Form.Item>}<Form.Item label="本地运行场景"><Select value={draft.fault} onChange={fault=>update({fault})} options={[{value:'NONE',label:'正常完成'},{value:'MISSING',label:'保留一条未接收差异'},{value:'CONTENT',label:'产生一条内容差异'},{value:'TRANSPORT',label:'模拟传输确认超时'}]}/></Form.Item></div><Alert type="info" showIcon message="运行使用本地样例记录；关闭浏览器后停止推进，重新打开后恢复。未发布草稿不参与调度。"/></Form>}
  {step===4&&<><div className="review-summary"><FlowMini cross={draft.scenario==='跨网'}/><h3>{draft.name}</h3><p>{draft.mappings.length} 组表映射 · {state.clusters.find(c=>c.id===draft.clusterId)?.name} · {draft.schedule.kind==='MANUAL'?'手动触发':'每 24 小时'}</p></div><Alert type="info" showIcon style={{marginBottom:12}} message="NiFi 画布使用真实后端流程" description="此向导的表映射与本地发布、模拟运行仍在本地工作区。首次打开 NiFi 画布需要配置真实节点；保存新流程后会自动关联当前任务。"/>{errors.length?<Alert type="error" showIcon message={`${errors.length} 项需要处理`} description={<ul>{errors.map((e,i)=><li key={i}>{e.message}</li>)}</ul>}/>:<Alert type="success" showIcon message="本地配置检查通过" description="发布会冻结当前本地任务定义；NiFi 流程需在画布中单独保存和部署。"/>}</>}
  </div>
 </Modal>;
}
