import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const from=p=>require('../.test-build/src/'+p+'.js');
const {readTheme,clampPanelWidth}=from('features/er/core/preferences');const {fingerprint,validateRelation,visibleFields,compatibleTypes}=from('features/er/core/relations');const {preserveLockedNodes,fallbackLayout}=from('features/er/core/layout');const {createSerialQueue}=from('features/er/core/saveQueue');const nav=from('app/canvasNavigation');const {modelPayload}=from('features/er/services/workspaceService');const http=from('services/api');
const doc=JSON.parse(fs.readFileSync('tests/fixtures/jdbc-model.json','utf8'));const entities=doc.entities;const orders=entities.find(e=>e.name==='ORDERS'),clients=entities.find(e=>e.name==='CLIENTS');const field=(e,n)=>e.fields.find(f=>f.name===n).id;const relation={name:'跨库联合关联',sourceEntityId:orders.id,targetEntityId:clients.id,semanticType:'reference',mappings:[{sourceFieldId:field(orders,'TENANT_ID'),targetFieldId:field(clients,'TENANT_ID'),comparisonRule:'exact'},{sourceFieldId:field(orders,'CUSTOMER_ID'),targetFieldId:field(clients,'CLIENT_ID'),comparisonRule:'exact'}]};const snapshot={id:'manifest',entities,sources:[]};
test('first visit is light, not OS-derived',()=>assert.equal(readTheme({getItem:()=>null}),'light'));
test('explicit dark selection persists',()=>assert.equal(readTheme({getItem:()=> 'dark'}),'dark'));
test('bad preference is light',()=>assert.equal(readTheme({getItem:()=> 'script'}),'light'));
test('storage-denied preference falls back light',()=>assert.equal(readTheme({getItem:()=>{throw Error();}}),'light'));
test('panel widths are bounded',()=>{assert.equal(clampPanelWidth(-1,'library'),240);assert.equal(clampPanelWidth(9999,'inspector'),620);});
test('ER is a full-screen route',()=>assert.equal(nav.isCanvasPath('/governance/metadata/er/model'),true));
test('ordinary model page is not a canvas',()=>assert.equal(nav.isCanvasPath('/governance/metadata/models'),false));
test('external return URL is rejected',()=>assert.equal(nav.canvasBackground({pathname:'https://example.invalid/'}),null));
test('canvas cannot be its own background',()=>assert.equal(nav.canvasBackground({pathname:'/governance/metadata/er/a'}),null));
test('valid source-page return preserves search',()=>assert.equal(nav.backgroundUrl(nav.canvasBackground({pathname:'/governance/metadata/catalog',search:'?q=orders'})),'/governance/metadata/catalog?q=orders'));
test('live JDBC DTO compound mapping passes frontend validation',()=>assert.deepEqual(validateRelation(relation,snapshot),[]));
test('partial tenant key is rejected',()=>assert.ok(validateRelation({...relation,mappings:relation.mappings.slice(1)},snapshot).length>0));
test('cross-entity field ownership is rejected',()=>assert.ok(validateRelation({...relation,mappings:[{sourceFieldId:clients.fields[0].id,targetFieldId:clients.fields[0].id}]},snapshot).length>0));
test('duplicate field mapping is rejected',()=>assert.ok(validateRelation({...relation,mappings:[...relation.mappings,relation.mappings[0]]},snapshot).length>0));
test('pair order does not affect fingerprint',()=>assert.equal(fingerprint(relation),fingerprint({...relation,mappings:[...relation.mappings].reverse()})));
test('re-pairing two columns changes fingerprint',()=>assert.notEqual(fingerprint(relation),fingerprint({...relation,mappings:relation.mappings.map((m,i)=>({...m,targetFieldId:relation.mappings[1-i].targetFieldId}))})));
test('array keys are not treated as scalar keys',()=>assert.equal(compatibleTypes({...orders.fields[0],typeFamily:'array'},orders.fields[0]),false));
test('collapsed node preserves every original field as hidden',()=>assert.equal(visibleFields(orders,[],'summary').hidden.length,orders.fields.length));
test('pinned field is included in key mode',()=>assert.ok(visibleFields(orders,[],'key',[field(orders,'AMOUNT')]).fields.some(f=>f.name==='AMOUNT')));
test('locked positions survive layout',()=>{const result=preserveLockedNodes([{entityId:'a',position:{x:23,y:44},locked:true},{entityId:'b',position:{x:0,y:0}}],{a:{x:0,y:0},b:{x:23,y:44}},{});assert.deepEqual(result[0].position,{x:23,y:44});assert.notDeepEqual(result[1].position,{x:23,y:44});});
test('fallback layout handles an empty graph',()=>assert.deepEqual(fallbackLayout([],'RIGHT'),{}));
test('sized layout keeps linked tables together and separates tall independent tables',()=>{const {clusteredLayout}=from('features/er/core/clusterLayout');const boxes=[{id:'a',width:280,height:620},{id:'b',width:280,height:160},{id:'c',width:280,height:500},{id:'d',width:280,height:240}];for(const direction of ['RIGHT','DOWN']){const positions=clusteredLayout(boxes,[{source:'a',target:'b'},{source:'b',target:'c'}],undefined,direction);assert.deepEqual(Object.keys(positions).sort(),['a','b','c','d']);for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j],p=positions[a.id],q=positions[b.id];assert.ok(p.x+a.width+32<=q.x||q.x+b.width+32<=p.x||p.y+a.height+32<=q.y||q.y+b.height+32<=p.y,`${direction}: ${a.id} and ${b.id} overlap`);}assert.ok(positions.d.y>=Math.max(...boxes.slice(0,3).map(box=>positions[box.id].y+box.height))+32);}});
test('model payload preserves independent source snapshots',()=>{const view={...doc.model,...doc.model.layout,snapshotManifest:doc.model.manifest};const p=modelPayload(view,entities,doc.model.manifest);assert.equal(Object.keys(p.manifest).length,2);assert.equal(p.layout.nodes.length,3);});
test('missing entity cannot be silently saved',()=>assert.throws(()=>modelPayload({...doc.model,...doc.model.layout,nodes:[{entityId:'not-real'}]},entities,{})));
test('serial persistence keeps older writes before later writes',async()=>{const q=createSerialQueue(),out=[];await Promise.all([q(async()=>{await new Promise(r=>setTimeout(r,5));out.push(1);}),q(async()=>out.push(2))]);assert.deepEqual(out,[1,2]);});
test('failed write does not poison the next queue item',async()=>{const q=createSerialQueue();await assert.rejects(q(async()=>{throw Error('failed');}));assert.equal(await q(async()=>42),42);});
test('shared login does not create a mock workspace or start local preview operations',async()=>{
 let requests=0;const prior={fetch:globalThis.fetch,location:globalThis.location,localStorage:globalThis.localStorage,sessionStorage:globalThis.sessionStorage};
 globalThis.location={href:'http://localhost:3000/',origin:'http://localhost:3000',replace:()=>{}};
 globalThis.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};globalThis.sessionStorage={getItem:()=>JSON.stringify('test-only-token')};
 globalThis.fetch=async url=>{requests++;return new Response(JSON.stringify({code:0,data:String(url).includes('/sym/user/me')?{id:'real-user',realName:'平台用户',orgName:'测试部门',roles:['admin']}:{tid:'test-tenant',name:'测试租户'}}));};
 try{const session=await http.loadSession();assert.equal(session.principalId,'real-user');assert.equal(session.name,'平台用户');assert.deepEqual(session.workspaces,[]);await assert.rejects(http.api('models'),e=>e.code==='WORKSPACE_REQUIRED');assert.equal(requests,2);}finally{Object.assign(globalThis,prior);}
});
test('preview transport is isolated from the shared backend adapter',()=>{const api=fs.readFileSync('src/services/api.ts','utf8');assert.match(api,/localRequest/);assert.doesNotMatch(api,/fetch\(|XMLHttpRequest/);});
test('no component silently reloads old demo stores',()=>{for(const p of ['src/app/useWorkspaceLifecycle.ts','src/features/er/services/workspaceService.ts','src/app/App.tsx'])assert.doesNotMatch(fs.readFileSync(p,'utf8'),/from ['"].*(?:data\/governance|services\/storage|demoService)/);});
