import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
import {magicScript} from './helpers/magic-resources.mjs';
const require=createRequire(import.meta.url),from=p=>require('../.test-build/src/'+p+'.js'),index=from('features/er/core/canvasIndex'),snap=from('services/metadataSnapshot'),lineage=from('services/lineage');
test('new processing edges name the default component outlet, not the native success relationship',()=>{assert.deepEqual(lineage.processingEdge('e','s','m'),{id:'e',source:'s',target:'m',outlet:'default'});const ui=fs.readFileSync('src/features/platform/ProcessingLineagePage.tsx','utf8');assert.match(ui,/processingEdge\(crypto.randomUUID\(\),c.source,c.target\)/);assert.doesNotMatch(ui,/outlet:'success'/);});
test('large immutable catalog index is reused and rebuilt only for a new snapshot',()=>{const snapshot={sources:[{id:'s'}],entities:Array.from({length:17624},(_,i)=>({id:'t'+i}))};const first=index.canvasSnapshotIndex(snapshot);for(let i=0;i<1000;i++)assert.strictEqual(index.canvasSnapshotIndex(snapshot),first);assert.strictEqual(first.entities.get('t17623'),snapshot.entities[17623]);assert.notStrictEqual(index.canvasSnapshotIndex({...snapshot}),first);});
test('incident index deduplicates self relationships and excludes archived/rejected edges',()=>{const rows=[{id:'a',sourceEntityId:'a',targetEntityId:'a',reviewStatus:'confirmed'},{id:'b',sourceEntityId:'a',targetEntityId:'b',reviewStatus:'archived'}];const first=index.canvasRelationIndex(rows);assert.equal(first.byEntity.get('a').length,1);assert.equal(first.byId.size,2);assert.strictEqual(index.canvasRelationIndex(rows),first);});
test('complete relationship definitions and latest real evidence round-trip through shared adapters',()=>{const row={tid:'r',source_table_id:'a',target_table_id:'b',relation_type:'REFERENCE',version_no:9,definition_json:JSON.stringify({mappings:[{sourceColumnId:'a1',targetColumnId:'b1'},{sourceColumnId:'a2',targetColumnId:'b2'}],conditions:[{side:'source',columnId:'a2',operator:'in',value:[1,2]}],targetsPerSource:{min:'1',max:'1',basis:'business'}}),validation_json:JSON.stringify({id:'ev',capturedAt:'2026-09-29',validationStatus:'inconclusive',metrics:{containmentRatio:null}}),physical_fk_json:JSON.stringify({constraintName:'fk_test',ddl:'ALTER TABLE fixture'})};const r=snap.metadataRelationship(row,'s','scope');assert.equal(r.mappings.length,2);assert.equal(r.conditions[0].fieldId,'shared-column:a2');assert.equal(r.version,9);assert.equal(r.verification.status,'inconclusive');assert.equal(r.physicalForeignKey.constraintName,'fk_test');const [ev]=snap.metadataEvidence(row,'s');assert.equal(ev.simulated,false);assert.equal(ev.metrics.containmentRatio,null);});
test('corrupt relation JSON remains an explicit error, never an empty saved definition',()=>{for(const v of ['{broken','[]','null'])assert.throws(()=>snap.relationJson(v));assert.deepEqual(snap.relationJson(null),{});});
test('processing graph rejects cycles, duplicate IDs and dangling connections',()=>{const nodes=[{id:'a',manifestKey:'source.jdbc'},{id:'b',manifestKey:'sink.jdbc'}];for(const edges of [[{id:'1',source:'a',target:'x'}],[{id:'1',source:'a',target:'a'}],[{id:'1',source:'a',target:'b'},{id:'2',source:'b',target:'a'}]])assert.throws(()=>lineage.validateProcessingGraph({nodes,edges}));assert.doesNotThrow(()=>lineage.validateProcessingGraph({nodes,edges:[{id:'1',source:'a',target:'b'}]}));});
test('field dependency inference uses explicit paths and boundaries, not substring guessing',()=>{assert.deepEqual(lineage.mappingDependencies({from:'/order_id'},['id','order_id']),['order_id']);assert.deepEqual(lineage.mappingDependencies({expression:'UPPER("name") || CAST("id" AS VARCHAR)'},['name','id','me']),['name','id']);assert.deepEqual(lineage.mappingDependencies({expression:"'constant'"},['other']),[]);});
test('field dependency inference excludes literals and respects explicit shared DSL references',()=>{assert.deepEqual(lineage.mappingDependencies({expression:"'name' || UPPER(${field:code}) /* id */"},['name','code','id','UPPER']),['code']);assert.deepEqual(lineage.mappingDependencies({fromList:['/id','/name','/id']},[]),['id','name']);});
test('physical database changes require preview and an explicit independent confirmation',()=>{const ui=fs.readFileSync('src/features/er/components/Inspector.tsx','utf8'),service=fs.readFileSync('src/services/metadata.ts','utf8');assert.match(ui,/预检查并创建物理外键/);assert.match(ui,/if\(!agreed\)/);assert.match(service,/confirmPhysicalChange:true/);assert.match(ui,/plan\.hash/);});
test('dragging uses canvas-local positions and commits once on stop',()=>{const ui=fs.readFileSync('src/features/er/components/ERCanvas.tsx','utf8');assert.match(ui,/applyNodeChanges\(changes,previous\)/);assert.match(ui,/dragPositions\.current,positions/);assert.match(ui,/state\.updatePositions\(dragPositions\.current,false\)/);assert.match(ui,/onlyRenderVisibleElements/);assert.doesNotMatch(ui,/importantMapping\(r,data.snapshot\)/);});
test('quality and technical field references stay on authoritative physical columns and server tenant',()=>{for(const id of ['dwm_metadata_governance_bindings_list_01','dwm_metadata_governance_bindings_save_01']){const s=magicScript(id);assert.match(s,/tenantRuntime.id\(\)/);assert.doesNotMatch(s,/principal.tenantId|body.tenantId|data_prop_t|INSERT INTO .*rule/);}const s=magicScript('dwm_metadata_governance_bindings_save_01');assert.match(s,/metadata_binding_version=metadata_binding_version\+1/);assert.match(s,/q.table_id=#\{tableId\}/);assert.match(s,/引用循环/);});

test('Magic Script uses its own for-in syntax rather than JavaScript variable declarations',()=>{for(const id of ['dwm_metadata_governance_catalog_01','dwm_metadata_governance_validate_01','dwm_metadata_governance_fk_preview_01','dwm_metadata_governance_fk_create_01','dwm_metadata_governance_bindings_list_01','dwm_metadata_governance_bindings_save_01','dwm_metadata_governance_summary_01','datapd_catalog_delete_01'])assert.doesNotMatch(magicScript(id),/for\s*\(\s*(?:var|let|const)\s+\w+\s+in\b/);});

test('processing canvas handles local position changes before persisting the shared DSL',()=>{const ui=fs.readFileSync('src/features/platform/ProcessingLineagePage.tsx','utf8');assert.match(ui,/nodes=\{canvasNodes\} onNodesChange=\{onNodesChange\}/);assert.match(ui,/applyNodeChanges\(changes,previous\)/);assert.match(ui,/onNodeDragStop=/);});
