import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),from=p=>require('../.test-build/src/'+p+'.js');
const {moduleVisuals,getModuleVisual}=from('design/moduleVisuals'),{moduleIconPaths}=from('design/iconPaths'),{navigation}=from('app/routes');
const {sourceStatistics,sourceEndpoint,sourceScope,objectKindLabel}=from('shared/sourcePresentation');
const {qualityRuleLabel,dataTypeLabel}=from('shared/businessLabels');
const {sourceAnnotations}=from('mocks/sourceAnnotations'),{stableId,WORKSPACE,STORAGE_KEY}=from('mocks/types'),{LocalMockEngine}=from('mocks/engine');
const text=p=>fs.readFileSync(p,'utf8');
function local(){let clock=Date.parse('2026-09-27T08:00:00Z');const map=new Map();const storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};const engine=new LocalMockEngine({storage,clock:()=>clock});const request=(p,body,version,method)=>engine.request(`/workspaces/${WORKSPACE}/${p}`,{method:method??(body===undefined?'GET':'POST'),body,version});return{request,storage,advance:async()=>{clock+=2200;await engine.tick();}};}
test('each visible menu entry has its own module visual and product icon',()=>{const items=navigation.flatMap(g=>g.children);assert.equal(items.length,18);assert.equal(new Set(items.map(i=>i.icon)).size,18);for(const item of items){assert.ok(moduleIconPaths[item.icon]);assert.equal(getModuleVisual(item.label)?.id,item.icon);}});
test('all 19 semantic icon geometries differ, not recoloured duplicates',()=>assert.equal(new Set(Object.values(moduleIconPaths).map(x=>JSON.stringify(x))).size,19));
test('every module has meaningful description and three concise highlights',()=>{assert.equal(moduleVisuals.length,19);for(const m of moduleVisuals){assert.ok(m.description.length>=25);assert.ok(m.promise.length>=7);assert.equal(m.highlights.length,3);assert.equal(new Set(m.highlights).size,3);assert.ok(m.highlights.every(s=>s.length>=4&&s.length<=12));}});
for(const mode of ['light','dark'])test(`all module assets exist and contain no remote resource: ${mode}`,()=>{for(const m of moduleVisuals){const s=text(`src/assets/heroes/${m.id}-${mode}.svg`);assert.match(s,/<svg/);assert.doesNotMatch(s,/<script|<foreignObject|href="https?:/);}});
test('19 themes each have a separately tuned dark asset',()=>{for(const m of moduleVisuals)assert.notEqual(text(`src/assets/heroes/${m.id}-light.svg`),text(`src/assets/heroes/${m.id}-dark.svg`));});
test('the eight pinned database brands remain distinct after adding platform connector icons',()=>{const files=JSON.parse(text('src/assets/databases/sources.json')).assets.map(a=>a.file);assert.equal(files.length,8);assert.equal(new Set(files.map(f=>fs.readFileSync('src/assets/databases/'+f).toString('base64'))).size,8);});
test('vendor asset resolver uses validated engine class, not arbitrary path interpolation',()=>{const s=text('src/design/Visuals.tsx');assert.match(s,/key=engineClass\(engine\)/);assert.doesNotMatch(s,/databases\/\$\{/);});
test('hero resolver explicitly imports local image assets and keeps approved overview',()=>{const s=text('src/design/heroAssets.ts');assert.match(s,/governance-landscape-light.svg/);assert.equal((s.match(/new URL\(/g)||[]).length,38);});
test('source statistics are exact and isolated by source',()=>{const rows=[{id:'a',sourceId:'s',kind:'table',fields:[{},{}]},{id:'b',sourceId:'s',kind:'collection',fields:[{}]},{id:'c',sourceId:'other',fields:[{},{},{}]}];const result=sourceStatistics('s',rows,[{},{}],[{layout:{nodes:[{entityId:'a'}]}},{layout:{nodes:[{entityId:'c'}]}}]);assert.deepEqual(result,{entityCount:2,fieldCount:3,tableCount:1,collectionCount:1,indexCount:0,viewCount:0,catalogCount:2,modelCount:1});});
test('empty source does not get fictitious counts',()=>{const r=sourceStatistics('x',[]);assert.equal(r.entityCount,0);assert.equal(r.fieldCount,0);assert.equal(r.modelCount,0);});
test('endpoint supports IPv6 and unknown values',()=>{assert.equal(sourceEndpoint({connection:{host:'2001:db8::1',port:5236}}),'[2001:db8::1]:5236');assert.equal(sourceEndpoint({}),'未登记地址');assert.equal(sourceScope({connection:{database:'db',schema:'public'}}),'db / public');});
test('seed metadata enrichment respects edited empty strings and unknown sources',()=>{assert.equal(sourceAnnotations({id:stableId('source-CORE')}).domain,'基础数据域');assert.equal(sourceAnnotations({id:stableId('source-CORE'),domain:''}).domain,'');assert.equal(sourceAnnotations({id:'unrelated'}).owner,'');});
test('source list and detail return matching enriched fields and counts',async()=>{const {request}=local();const s=(await request('sources')).items[0],d=await request(`sources/${s.id}`),q=(await request('queries/sources')).items.find(x=>x.id===s.id);assert.equal(s.entityCount,3);assert.ok(s.fieldCount>0);assert.equal(d.domain,s.domain);assert.equal(q.fieldCount,s.fieldCount);});
test('governance-only source edit persists owner/domain without invalidating configuration',async()=>{const {request}=local();const s=(await request('sources')).items[0];await request(`sources/${s.id}`,{name:s.name,domain:'财务共享域',owner:'责任小组',environment:'测试范围',businessSystem:'共享中心'},s.version,'PUT');const d=await request(`sources/${s.id}`);assert.equal(d.owner,'责任小组');assert.equal(d.domain,'财务共享域');assert.equal(d.status,'READY');assert.equal(d.last_test_at,s.last_test_at);assert.equal(d.version,s.version+1);});
test('connection change invalidates test rather than displaying old success',async()=>{const {request}=local();const s=(await request('sources')).items[0];await request(`sources/${s.id}`,{connection:{...s.connection,host:'changed-host'}},s.version,'PUT');const d=await request(`sources/${s.id}`);assert.equal(d.status,'DRAFT');assert.equal(d.last_test_at,null);});
test('editing connection of a disabled source does not silently enable it',async()=>{const {request}=local();let s=(await request('sources')).items[0];s=await request(`sources/${s.id}/status`,{status:'DISABLED'},s.version);await request(`sources/${s.id}`,{connection:{...s.connection,host:'changed-host'}},s.version,'PUT');assert.equal((await request(`sources/${s.id}`)).status,'DISABLED');});
test('invalid governance annotations fail atomically',async()=>{const {request}=local();const s=(await request('sources')).items[0];await assert.rejects(request(`sources/${s.id}`,{owner:'x'.repeat(129)},s.version,'PUT'));assert.equal((await request(`sources/${s.id}`)).version,s.version);});
test('new custom sources have no invented domain and no harvested object count',async()=>{const {request}=local();const s=await request('sources',{name:'新来源',code:'NEW32',engine:'MYSQL',connection:{host:'local',port:3306}});const d=await request(`sources/${s.id}`);assert.equal(d.domain,'');assert.equal(d.entityCount,0);assert.equal(d.fieldCount,0);assert.equal(d.catalogCount,3);});
test('source counts update after collecting only selected templates',async()=>{const {request,advance}=local();let s=await request('sources',{name:'范围验证',code:'PART32',engine:'MYSQL',connection:{host:'local',port:3306}});s=await request(`sources/${s.id}/test`,{},s.version);const objects=(await request(`sources/${s.id}/objects`)).items;const plan=await request('collection-plans',{name:'采集两表',sourceId:s.id,selectionTokens:objects.slice(0,2).map(x=>x.selectionToken)});await request(`collection-plans/${plan.id}/run`,{});await advance();const d=await request(`sources/${s.id}`);assert.equal(d.entityCount,2);assert.equal(d.catalogCount,3);assert.ok(d.lastCollectedAt);});
test('upgrading preserves the v3.1 storage key and existing workspaces',async()=>{const {request,storage}=local();const s=(await request('sources')).items[0];await request(`sources/${s.id}`,{owner:'已维护责任人'},s.version,'PUT');const before=JSON.parse(storage.getItem(STORAGE_KEY));const engine=new LocalMockEngine({storage});const list=await engine.request(`/workspaces/${WORKSPACE}/sources`);assert.equal(list.items[0].owner,'已维护责任人');assert.equal(JSON.parse(storage.getItem(STORAGE_KEY)).workspaces[0].models.length,before.workspaces[0].models.length);});
test('backup contains saved source metadata and import preview retains it',async()=>{const {request}=local();const s=(await request('sources')).items[0];await request(`sources/${s.id}`,{owner:'保留人员',domain:'保留业务域'},s.version,'PUT');const backup=await request('backup');assert.equal(backup.workspace.sources[0].owner,'保留人员');const batch=await request('imports',backup);assert.ok(batch.batchId);});
test('native rail removes title nodes when collapsed, supports keyboard navigation',()=>{const n=text('src/app/ProductNavigation.tsx');assert.match(n,/!collapsed && <span className="wx-nav-label"/);assert.match(n,/ArrowDown/);assert.match(n,/aria-current/);assert.match(n,/aria-label=\{item.label\}/);assert.doesNotMatch(n,/inlineIndent|ant-menu-title/);});
test('source page keeps primary collection and groups connection status and test beside recent collection',()=>{const s=text('src/features/platform/SourcesPage.tsx');assert.match(s,/<Dropdown trigger=\{\['click'\]\}/);assert.match(s,/source-collect-button/);assert.match(s,/最近采集/);assert.match(s,/source-status-trigger/);assert.match(s,/source-test-link/);assert.doesNotMatch(s,/{title:'连接状态'/);assert.doesNotMatch(s,/key:'test',label:'测试连接'/);});
test('drawer and source table declare the real shared backend boundary',()=>assert.match(text('src/features/platform/SourcesPage.tsx'),/连接测试访问真实数据库/));
test('catalog scope links and vendor symbols are shared with ER library/nodes',()=>{assert.match(text('src/features/platform/MetadataPages.tsx'),/params.get\('source'\)/);for(const n of ['EntityNode','EntityLibrary'])assert.match(text(`src/features/er/components/${n}.tsx`),/SourceIcon/);});
test('technical labels keep stable codes but add business meaning',()=>{assert.equal(qualityRuleLabel('NOT_NULL'),'完整性 · 非空');assert.equal(dataTypeLabel('integer'),'整数');assert.equal(objectKindLabel('collection'),'集合');assert.equal(objectKindLabel('custom'),'custom');});
test('polish CSS is the final imported layer and contains no page scaling',()=>{const s=text('src/main.tsx');assert.ok(s.lastIndexOf('studio-polish.css')>s.lastIndexOf('refined.css'));assert.doesNotMatch(text('src/styles/studio-polish.css'),/\bzoom\s*:/);});


test('live review displays real definitions and uses the shared publish status',()=>{const s=text('src/features/platform/StandardPages.tsx');assert.match(s,/filter\(r=>!published\(r\)\)/);assert.match(s,/ElementInformation row=\{item\}/);assert.match(s,/setElementPublished\(item!,true\)/);assert.doesNotMatch(s,/review-members|applicant_id|frozen/);});
test('live mapping resolves authoritative standard names without invented revision identity',()=>{const s=text('src/features/platform/StandardPages.tsx');assert.match(s,/已发布的数据元标准/);assert.match(s,/standardIndex\.get\(id\)/);assert.match(s,/expectedStandardId/);assert.doesNotMatch(s,/publishedRevisionId|绑定具体修订/);});
