import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {Worker as NodeWorker} from 'node:worker_threads';
import {spawnSync} from 'node:child_process';
const require=createRequire(import.meta.url),standards=require('../.test-build/src/services/standards.js');
const raw={tid:'208410983168269926511',metaName:'资源标识',metaCode:'ResourceCode',standardEncode:'BC00002',bizDef:'数据资源的唯一标识',fieldType:'varchar',dataTypeId:'字符串型C',fieldLength:50,publishStatus:0,isNullable:0,dataLevel:'2',dataCategoryId:'category',dataCategoryName:'基础标准',dataCategoryPath:'0.category',valueDomainId:'dictionary',formatPattern:'^WX-[0-9]{6}$',exampleValue:'WX-000001',customRule:'保存原有说明',qualityRule:'rule-a,rule-b',versionNo:'0.1',tenantId:'forbidden'};
const classes=[{id:'category',name:'基础标准',path:'0.category'}];
const transport=require('../.test-build/src/shared/platformApi.js'),session=require('../.test-build/src/services/api.js');
async function withTransport(handler,work){const oldCall=transport.platformApi,oldSession=session.getSession;transport.platformApi=handler;session.getSession=()=>({authenticated:true,principalId:'fixture-user'});try{return await work();}finally{transport.platformApi=oldCall;session.getSession=oldSession;}}
test('standard projection uses exact canonical IDs and omits tenant payloads',()=>{const row=standards.elementRow(raw);assert.equal(row.id,raw.tid);assert.equal(row.status,'PENDING');assert.equal(row.fieldLength,50);assert.equal('tenantId' in row,false);assert.equal(standards.elementRow({...raw,publishStatus:1}).status,'PUBLISHED');assert.equal(standards.elementRow({...raw,publishStatus:null}).status,'PENDING');});
test('element DTO preserves original missing fields and enforces simple pending state',()=>{const row=standards.elementRow(raw);const body=standards.elementBody({...standards.elementForm(row),name:'改名'},classes,row);assert.equal(body.metaName,'改名');assert.equal(body.publishStatus,0);assert.equal(body.valueDomainId,'dictionary');assert.equal(body.customRule,'保存原有说明');assert.equal(body.qualityRule,'rule-a,rule-b');assert.equal(body.exampleValue,'WX-000001');assert.equal(body.dataCategoryPath,'0.category');assert.equal(body.isNullable,0);for(const key of ['tenantId','tenant_id','definition','revisionId','versionNo','status'])assert.equal(key in body,false);});
test('standard validation matches shared physical field capacities',()=>{const row=standards.elementRow(raw);assert.throws(()=>standards.elementBody({...row,name:'名'.repeat(51)},classes,row),/50/);assert.throws(()=>standards.elementBody({...row,fieldLength:0},classes,row),/整数长度/);assert.throws(()=>standards.elementBody({...row,numericPrecision:4,numericScale:5},classes,row),/小数位/);assert.throws(()=>standards.elementBody({...row,dataCategoryId:'wrong'},classes,row),/分类/);assert.throws(()=>standards.elementBody({...row,dataLevel:'8'},classes,row),/分级/);});
test('class and page contracts accept real nested paging but fail closed on malformed pages',()=>{assert.deepEqual(standards.pageOf({list:{list:[raw],total:1}}),{list:[raw],total:1});assert.throws(()=>standards.pageOf({error:'offline'}),/返回/);assert.equal(standards.classesOf({tid:'0',children:[{tid:'category',label:'基础标准',treePath:'0.category'}]})[0].id,'category');});
test('flat code values preserve leading zeroes, descriptions and opaque legacy metadata',()=>{const items=standards.parseCodeItems('[{"code":"01","name":"第一项","description":"说明"},{"code":"02","name":"第二项","parent":"01"}]');const body=standards.codeBody({name:'测试代码',code:'CODE',status:'DRAFT',items,dataCategoryId:'category'},null,classes);assert.equal(body.status,0);assert.equal(body.codeValue,'__HEADER__');assert.equal(JSON.parse(body.dictItemValue)[0].code,'01');assert.equal(JSON.parse(body.dictItemValue)[1].parent,'01');assert.equal(JSON.parse(body.dictItemValue)[0].description,'说明');assert.equal('tenantId' in body,false);});
test('flat code validation keeps required values, uniqueness and individual field safety',()=>{assert.throws(()=>standards.parseCodeItems('not-json'),/不会被空数据覆盖/);assert.throws(()=>standards.codeBody({name:'代码',code:'C',items:[{value:'1',label:'甲'},{value:'1',label:'乙'}]}),/重复/);assert.throws(()=>standards.codeBody({name:'代码',code:'C',items:[{value:'1',label:''}]}),/必须填写/);assert.throws(()=>standards.codeBody({name:'代码',code:'C',items:[{value:'1'.repeat(129),label:'甲'}]}),/长度/);});
test('flat editing does not interpret or reject historical hierarchy metadata',()=>{const items=standards.parseCodeItems('[{"code":"01","name":"第一项","parent":"missing"},{"code":"02","name":"第二项","parent":"02"}]');items[0].label='修改显示名称';const body=standards.codeBody({name:'代码',code:'C',items});const saved=JSON.parse(body.dictItemValue);assert.equal(saved[0].name,'修改显示名称');assert.equal(saved[0].parent,'missing');assert.equal(saved[1].parent,'02');const flat=JSON.parse(standards.codeBody({name:'代码',code:'C',items:[{value:'03',label:'新条目'}]}).dictItemValue);assert.equal('parent' in flat[0],false);});
test('code item lists do not impose a fixed 1000-character aggregate capacity',()=>{const items=Array.from({length:200},(_,i)=>({value:String(i).padStart(4,'0'),label:'很长的名称'.repeat(10),description:'保存完整条目'}));const body=standards.codeBody({name:'代码',code:'C',items});assert.ok(body.dictItemValue.length>1000);const saved=JSON.parse(body.dictItemValue);assert.equal(saved.length,200);assert.equal(saved.at(-1).code,'0199');assert.equal(saved.at(-1).name,items.at(-1).label);});
test('code normalization does not mutate unsaved UI input',()=>{const items=[{value:' 01 ',label:' 第一项 '}];standards.codeBody({name:'代码',code:'C',items});assert.equal(items[0].value,' 01 ');assert.equal(items[0].label,' 第一项 ');});
test('controlled encoding segments round-trip only through the real format pattern',()=>{const definition=[{type:'LITERAL',value:'WX.+'},{type:'DIGITS',length:6},{type:'LETTERS',length:2},{type:'ALPHANUMERIC',length:3}];const compiled=standards.compileSegments(definition);assert.equal(compiled.length,15);assert.deepEqual(standards.segmentsFromPattern(compiled.pattern),definition);assert.equal(new RegExp(compiled.pattern).test('WX.+000001Az09Z'),true);assert.equal(standards.segmentsFromPattern('^(ab+)+$'),null);assert.throws(()=>standards.compileSegments([{type:'DIGITS',length:0}]),/长度/);});
test('all standard menus use live APIs, not local revision/approval/preview persistence',()=>{const page=fs.readFileSync('src/features/platform/StandardPages.tsx','utf8');assert.doesNotMatch(page,/(?<![.\w])(?:api|all|canReview|canWrite|versionOf)\(|publishedRevisionId|applicant_id|frozen|opinion_text|localStorage/);for(const action of ['saveElement','setElementPublished','saveBinding','saveCode','saveEncoding','deleteElement','deleteCode'])assert.ok(page.includes(action));});
test('standard pages retain requested revision columns but remove discarded version and landing fields',()=>{const page=fs.readFileSync('src/features/platform/StandardPages.tsx','utf8');for(const label of ['当前修订','提交修订','提交时间'])assert.ok(page.includes(`title:'${label}'`));for(const label of ['草稿版本','发布版本','目标修订'])assert.ok(!page.includes(`title:'${label}'`));assert.doesNotMatch(page,/draftVersion|publishedVersion|targetVersion|mappingNote|审批台账|审批记录|版本记录/);});
test('code drawer offers only flat business fields and no hierarchy or capacity controls',()=>{const page=fs.readFileSync('src/features/platform/StandardPages.tsx','utf8'),drawer=page.slice(page.indexOf('<Drawer width={800}'),page.indexOf('function EncodingFields'));assert.match(drawer,/\['value','label','description'\]/);assert.match(drawer,/同一代码集中的代码值不能重复/);assert.doesNotMatch(drawer,/父代码|容量|1000|parent:/);});
test('new center and its standards verifier do not offer or exercise offline snapshot import',()=>{const source=fs.readFileSync('src/features/platform/SourcesPage.tsx','utf8'),verifier=fs.readFileSync('scripts/verify-shared-standards.mjs','utf8');assert.doesNotMatch(source,/导入结构|离线元数据|importSnapshot/);assert.doesNotMatch(verifier,/importSnapshot|offline-snapshot-preview|hierarchy|parent:'01'/);assert.match(source,/批量检查/);assert.match(verifier,/\/dwm\/standard\/landing\/save/);});
test('center menu keeps five groups, exposes the three shared centers without product names, and retains profile content',()=>{const registry=fs.readFileSync('src/shared/centerNavigation.ts','utf8');for(const group of ['数据建设','治理与管控','运营与交付','分析与应用','平台支撑'])assert.ok(registry.includes(group));for(const name of ['数据资源中心','数据资产中心','数据治理中心'])assert.ok(registry.includes(`name:'${name}'`));const shell=fs.readFileSync('src/app/PlatformShell.tsx','utf8');assert.match(shell,/center==='resource'\?'数据资源中心'/);assert.match(shell,/center==='asset'\?'数据资产中心':'数据治理中心'/);assert.match(shell,/<small>政务大数据平台<\/small>/);for(const label of ['所属机构','手机号','当前租户','角色','退出登录'])assert.ok(shell.includes(label));});
test('new shared field-binding route never invokes bulk registration or catalog/index writes',()=>{const script=fs.readFileSync('backend/standard-landing/02.保存字段标准引用.ms','utf8');assert.match(script,/tenantRuntime.id\(\)/);assert.match(script,/expectedStandardId/);assert.match(script,/standard.publishStatus != 1/);assert.doesNotMatch(script,/body\.tenantId|principal\.tenantId|registeredTableCatalogProjection\(|esCommonService|asset_status\s*:|annotated\s*:/);assert.match(script,/set data_standard_id=/);});
test('first field binding supports both Dameng null-empty semantics and MySQL empty strings atomically',()=>{const script=fs.readFileSync('backend/standard-landing/02.保存字段标准引用.ms','utf8');assert.match(script,/expectedDbId = expectedStandardId == '' \? null : expectedStandardId/);assert.match(script,/#\{expectedDbId\} is null/);assert.match(script,/data_standard_id is null or trim\(data_standard_id\) is null or trim\(data_standard_id\)=''/);assert.match(script,/or trim\(data_standard_id\)=#\{expectedDbId\}/);assert.doesNotMatch(script,/coalesce\(data_standard_id,''\)=/);});

test('live standard reader advances pages and deduplicates canonical IDs',async()=>withTransport(async(_path,body)=>body.pageNum===1?{list:[raw],total:2}:{list:[{...raw,tid:'second'}],total:2},async()=>assert.equal((await standards.listElements()).length,2)));
test('live reader refuses repeated pagination and API errors without preview fallback',async()=>{await withTransport(async()=>({list:[raw],total:2}),async()=>assert.rejects(standards.listElements(),/没有推进/));await withTransport(async()=>{throw new Error('service offline');},async()=>assert.rejects(standards.listElements(),/service offline/));});
test('live create submits shared fields, pending publication and real audit identity',async()=>withTransport(async(path,body)=>{assert.equal(path,'/dwm/standard/element/metaSaveOrUpdate');assert.equal(body.publishStatus,0);assert.equal(body.createdBy,'fixture-user');assert.equal(body.formatPattern,raw.formatPattern);return {...body,tid:'created'};},async()=>assert.equal((await standards.saveElement(standards.elementForm(standards.elementRow(raw)),classes)).id,'created')));
test('published standards cannot be edited or deleted through the new adapter',async()=>withTransport(async(path)=>{assert.equal(path,'/dwm/standard/element/queryById');return {...raw,publishStatus:1};},async()=>{const row=standards.elementRow(raw);await assert.rejects(standards.saveElement(row,classes,row),/先下线/);await assert.rejects(standards.deleteElement(row),/先下线/);}));
test('simple approval changes only shared publication status and validates result',async()=>{const sent=[];await withTransport(async(path,body)=>{sent.push({path,body});return path.endsWith('queryById')?raw:{...raw,publishStatus:body.publishStatus};},async()=>assert.equal((await standards.setElementPublished(standards.elementRow(raw),true)).status,'PUBLISHED'));assert.deepEqual(Object.keys(sent[1].body).sort(),['expectedPublishStatus','publishStatus','tid','updatedBy']);assert.equal(sent[1].body.publishStatus,1);});
test('referenced standards cannot be deleted until their real field references are cleared',async()=>withTransport(async path=>{if(path.endsWith('queryById'))return raw;assert.equal(path,'/dwm/standard/landing/list');return {items:[{target_id:raw.tid}]};},async()=>assert.rejects(standards.deleteElement(standards.elementRow(raw)),/仍被 1 个字段引用/)));
test('standard deletion uses the existing typo-compatible endpoint, not a cloned API',async()=>{const paths=[];await withTransport(async path=>{paths.push(path);return path.endsWith('queryById')?raw:path.endsWith('landing/list')?{items:[]}:{deleted:true};},async()=>standards.deleteElement(standards.elementRow(raw)));assert.equal(paths.at(-1),'/dwm/standard/element/meatDeleteById');});
test('field binding whitelists IDs and expected reference without registration side effects',async()=>withTransport(async(path,body)=>{assert.equal(path,'/dwm/standard/landing/save');assert.deepEqual(body,{tableId:'table',columnId:'field',standardId:raw.tid,expectedStandardId:'old'});return {saved:true};},async()=>{await standards.saveBinding({entityId:'table',fieldId:'field',targetId:raw.tid,expectedStandardId:'old',tenantId:'forbidden',note:'not a persisted field'});await assert.rejects(standards.saveBinding({mode:'INVALID'}),/无效/);}));
test('encoding create compiles segments into the same pending data-element record',async()=>withTransport(async(path,body)=>{assert.equal(path,'/dwm/standard/element/metaSaveOrUpdate');assert.equal(body.formatPattern,'^WX-[0-9]{6}$');assert.equal(body.fieldLength,9);assert.equal(body.publishStatus,0);assert.equal(body.bizDef,'编码说明');assert.equal('segments' in body,false);return {...body,tid:'encoding'};},async()=>standards.saveEncoding({name:'编码规范',code:'WX_RULE',standardEncode:'WX001',description:'编码说明',definition:{segments:[{type:'LITERAL',value:'WX-'},{type:'DIGITS',length:6}]}},[])));
test('published code set preflight blocks editing and referenced code set blocks deletion',async()=>{const code={tid:'dictionary',dictName:'代码',dictCode:'C',dictItemValue:'[]',status:1};await withTransport(async path=>{assert.ok(path.endsWith('queryById'));return code;},async()=>assert.rejects(standards.saveCode({name:'代码'},[],{id:'dictionary'}),/先下线/));await withTransport(async path=>path.endsWith('queryById')?{...code,status:0}:{list:[raw],total:1},async()=>assert.rejects(standards.deleteCode({id:'dictionary'}),/仍被 1 个数据元引用/));});

async function withWorker(work){const prior=globalThis.Worker;const code=fs.readFileSync('.test-build/src/services/encodingValidation.worker.js','utf8');globalThis.Worker=class{constructor(){this.worker=new NodeWorker(`const {parentPort}=require('node:worker_threads'); const self={postMessage:value=>parentPort.postMessage(value)}; ${code}; parentPort.on('message',data=>self.onmessage({data}));`,{eval:true});this.worker.on('message',data=>this.onmessage?.({data}));this.worker.on('error',error=>this.onerror?.(error));}postMessage(value){this.worker.postMessage(value);}terminate(){return this.worker.terminate();}};try{return await work();}finally{globalThis.Worker=prior;}}
test('actual format worker checks a full match, rejects invalid format and bad regex',async()=>withWorker(async()=>{assert.equal((await standards.testEncoding('^WX-[0-9]{6}$','WX-000001')).valid,true);assert.equal((await standards.testEncoding('[0-9]{2}','x12')).valid,false);await assert.rejects(standards.testEncoding('[','x'),/不是有效的正则表达式/);}));
test('legacy pathological encoding cannot hang the UI thread',async()=>withWorker(async()=>{await assert.rejects(standards.testEncoding('^(a+)+$','a'.repeat(80)+'!'),/执行超时/);}));
test('credential-free shared control delta reproduces the published source artifacts',()=>{const generated=spawnSync(process.execPath,['scripts/build-standard-landing-delta.mjs'],{encoding:'utf8'});assert.equal(generated.status,0);assert.equal(generated.stdout.trim(),fs.readFileSync('backend/standard-landing/control-resource-delta.sql','utf8').trim());assert.equal((generated.stdout.match(/INSERT INTO baseline\.api_file_t/g)||[]).length,4);assert.doesNotMatch(generated.stdout,/PASSWORD|INSERT INTO baseline_beijing_gd/);});
