/* Isolated DOM style review. React hooks, Ant Design and X6 are explicitly substituted.
 * Produces inspectable snapshots from the real TSX, data and CSS; NOT an application E2E test. */
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const root=path.resolve(__dirname,'../..');let ts;try{ts=require('typescript');}catch{ts=require(require('node:child_process').execFileSync('npm',['root','-g'],{encoding:'utf8'}).trim()+'/typescript');}
const h=(type,props={},...children)=>({type,props:{...props,...(children.length?{children}: {})}});let idCounter=0;let pageRoute='/overview',dark=false,collapsed=false;
global.localStorage={getItem:k=>k==='haitong:collapsed'?String(collapsed):null,setItem(){}};global.window={addEventListener(){},removeEventListener(){},location:{reload(){}}};global.document={};
const react={createElement:h,Fragment:'fragment',useState:v=>[typeof v==='function'?v():v,()=>{}],useEffect(){},useLayoutEffect(){},useRef:v=>({current:v}),useMemo:f=>f(),useCallback:f=>f,useId:()=>`review-${++idCounter}`,createContext:v=>({value:v}),useContext:c=>c.value};react.default=react;
const nullFunc=()=>{};const messages={success:nullFunc,error:nullFunc,warning:nullFunc,info:nullFunc};let context;
const ant={};const wrap=(tag,cls)=>(p)=>h(tag,{className:cls+(p.className?' '+p.className:''),style:p.style},p.children);
ant.Button=p=>h('button',{className:`ant-btn ant-btn-${p.type||'default'} ${p.danger?'ant-btn-dangerous':''} ${p.className||''}`,disabled:p.disabled,style:p.style,'aria-label':p['aria-label']},p.icon,p.loading?h('span',{className:'review-spinner'}):null,p.children);
ant.Space=p=>h('span',{className:'ant-space',style:{gap:typeof p.size==='number'?p.size:8,...p.style}},p.children);
ant.Tag=p=>h('span',{className:`ant-tag ant-tag-${p.color||'default'}`},p.children);
ant.Tooltip=p=>p.children;
ant.Dropdown=p=>p.children;
ant.Avatar=p=>h('span',{className:'ant-avatar',style:{width:p.size||32,height:p.size||32,...p.style}},p.children);
ant.Input=p=>h('span',{className:'ant-input-affix-wrapper',style:p.style},p.prefix,h('input',{className:'ant-input',value:p.value||'',placeholder:p.placeholder,readOnly:true}));
ant.Input.TextArea=p=>h('textarea',{className:'ant-input',rows:p.rows||3,placeholder:p.placeholder},p.value||'');ant.Input.Search=ant.Input;
ant.InputNumber=p=>h('input',{className:'ant-input',type:'number',value:p.value||0,readOnly:true});
ant.Select=p=>h('span',{className:'ant-select',style:p.style},(p.options||[]).find(o=>o.value===p.value)?.label||p.placeholder||String(p.value||'请选择'),h('span',{className:'review-arrow'},'⌄'));
ant.Checkbox=p=>h('label',{className:'ant-checkbox-wrapper'},h('input',{type:'checkbox',checked:p.checked,disabled:p.disabled}),p.children);
ant.Switch=p=>h('button',{className:'ant-switch '+(p.checked?'ant-switch-checked':'')},h('i'));
ant.Form=wrap('form','ant-form');ant.Form.Item=p=>h('div',{className:'ant-form-item'},p.label&&h('label',{className:'ant-form-item-label'},p.required?h('i',{},'* '):null,p.label),p.children,p.help&&h('small',{},p.help));
ant.Radio={Group:p=>h('div',{className:'ant-radio-group'},(p.options||[]).map(o=>h('label',{},h('input',{type:'radio',checked:o.value===p.value}),o.label)))};
ant.Modal=p=>p.open?h('section',{className:'review-modal'},h('h2',{},p.title),p.children,p.footer):null;
ant.Drawer=p=>p.open?h('section',{className:'review-drawer'},h('header',{},p.title,p.extra),p.children):null;
ant.Alert=p=>h('div',{className:`ant-alert ant-alert-${p.type||'info'} ${p.className||''}`,style:p.style},h('b',{},p.message),p.description&&h('div',{className:'ant-alert-description'},p.description));
ant.Empty=p=>h('div',{className:'ant-empty'},p.description||'暂无数据');ant.Empty.PRESENTED_IMAGE_SIMPLE='';
ant.Result=p=>h('div',{className:'ant-result'},h('h2',{},p.title),h('p',{},p.subTitle),p.extra);
ant.Progress=p=>p.type==='circle'?h('div',{className:'ant-progress-circle',style:{width:p.size,height:p.size}},h('svg',{width:p.size,height:p.size,viewBox:'0 0 120 120'},h('circle',{cx:60,cy:60,r:49,fill:'none',stroke:'var(--primary-soft)',strokeWidth:9}),h('circle',{cx:60,cy:60,r:49,fill:'none',stroke:'var(--primary)',strokeWidth:9,strokeDasharray:`${p.percent/100*308} 308`,transform:'rotate(-90 60 60)'})),h('div',{className:'ant-progress-text'},typeof p.format==='function'?p.format(p.percent):`${p.percent}%`)):h('div',{className:'ant-progress-line'},h('i',{style:{width:`${p.percent}%`}}),h('span',{},p.percent+'%'));
ant.Table=p=>{
 const rows=(p.dataSource||[]).slice(0,p.pagination===false?50:10),cols=p.columns||[];
 const colgroup=h('colgroup',{},cols.map(c=>h('col',{style:c.width?{width:c.width}:undefined})));
 const header=h('thead',{className:'ant-table-thead'},h('tr',{},cols.map(c=>h('th',{},c.title))));
 const bodyRows=rows.length?rows.map((r,i)=>h('tr',{},cols.map(c=>h('td',{className:'ant-table-cell'},c.render?c.render(c.dataIndex?r[c.dataIndex]:undefined,r,i):r[c.dataIndex]??'—')))):h('tr',{},h('td',{colSpan:cols.length||1},p.locale?.emptyText||'暂无记录'));
 const body=h('tbody',{className:'ant-table-tbody'},bodyRows);
 const table=h('table',{},colgroup,header,body);
 const pagination=p.pagination!==false?h('div',{className:'ant-pagination'},`共 ${(p.dataSource||[]).length} 条记录　 ‹ `,h('b',{},'1'),'　2　›　10 条 / 页'):null;
 return h('div',{className:'ant-table-wrapper'},h('div',{className:'ant-table'},h('div',{className:'ant-table-container'},table)),pagination);
};
ant.Descriptions=p=>h('div',{className:'ant-descriptions'},(p.items||[]).map(i=>h('div',{},h('span',{},i.label),h('b',{},i.children))));
ant.Tabs=p=>h('div',{className:'ant-tabs'},h('div',{className:'ant-tabs-nav'},(p.items||[]).map((i,n)=>h('span',{className:n===0?'active':''},i.label))),p.items?.[0]?.children);
ant.Steps=p=>h('div',{className:'ant-steps'},(p.items||[]).map((i,n)=>h('div',{className:`ant-steps-item ${n<=(p.current||0)?'ant-steps-item-process':''}`},h('span',{className:'ant-steps-icon'},n+1),h('b',{},i.title))));
ant.App=p=>p.children;ant.App.useApp=()=>({message:messages,modal:{info:nullFunc,confirm:()=>({destroy(){}})}});
ant.ConfigProvider=p=>p.children;ant.theme={defaultAlgorithm:nullFunc,darkAlgorithm:nullFunc,compactAlgorithm:nullFunc};
const oldLoad=Module._load;
Module._load=function(request,parent,isMain){if(request==='react')return react;if(request==='react/jsx-runtime')return {jsx:(type,props)=>({type,props:props||{}}),jsxs:(type,props)=>({type,props:props||{}}),Fragment:'fragment'};if(request==='antd')return ant;if(request.startsWith('antd/locale'))return {};if(request==='react-router-dom')return {useNavigate:()=>nullFunc,useLocation:()=>({pathname:pageRoute,search:'',state:null}),useSearchParams:()=>[new URLSearchParams('task=task-1'),nullFunc],Link:wrap('a',''),Navigate:()=>null};
 if(request.endsWith('/Workbench'))return {useWorkbench:()=>context};if(request.includes('design/theme'))return {useOceanTheme:()=>({dark,motion:false,toggle(){},toggleMotion(){}})};
 if(request==='@uiw/react-codemirror')return {__esModule:true,default:p=>h('pre',{className:'cm-editor',style:{height:p.height}},p.value||p.placeholder)};
 if(request.startsWith('@codemirror/'))return {json:()=>[],sql:()=>[]};if(request==='@antv/x6')return {Graph:{registerNode(){}}};if(request.startsWith('@antv/x6-plugin-'))return {};
 if(request==='@tanstack/react-query')return {useQuery:()=>({data:context.state}),useQueryClient:()=>({invalidateQueries(){}})};
 return oldLoad.apply(this,arguments);
};
for(const ext of ['.ts','.tsx'])Module._extensions[ext]=(mod,filename)=>{const output=ts.transpileModule(fs.readFileSync(filename,'utf8'),{fileName:filename,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;mod._compile(output,filename);};
const {createSeed}=require(root+'/src/domain/seed.ts');const state=createSeed();context={state,act:async()=>state,editTask:nullFunc,showTask:nullFunc,showRun:nullFunc,openCanvas:nullFunc};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const unitless=new Set(['opacity','zIndex','fontWeight','flex','flexGrow','flexShrink','order','lineHeight','strokeWidth']);
function styles(obj){return Object.entries(obj||{}).filter(([k,v])=>v!=null).map(([k,v])=>`${k.startsWith('--')?k:k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}:${typeof v==='number'&&!unitless.has(k)&&!k.startsWith('--')?v+'px':v}`).join(';');}
const voids=new Set(['input','img','br','hr','col','meta','link']);
function render(el){if(el===null||el===undefined||typeof el==='boolean')return '';if(Array.isArray(el))return el.map(render).join('');if(typeof el==='string'||typeof el==='number')return esc(el);if(typeof el.type==='function')return render(el.type(el.props));if(el.type==='fragment')return render(el.props.children);if(typeof el.type!=='string')return '';const attrs=Object.entries(el.props||{}).filter(([k,v])=>!['children','ref','key','dangerouslySetInnerHTML'].includes(k)&&!k.startsWith('on')&&typeof v!=='function'&&v!==null&&v!==undefined&&v!==false).map(([k,v])=>{if(k==='style')return `style="${esc(styles(v))}"`;if(k==='className')k='class';if(k==='htmlFor')k='for';if(/^(strokeWidth|strokeLinecap|strokeLinejoin|fillRule|clipRule|stopColor|stopOpacity|strokeDasharray|strokeDashoffset)$/.test(k))k=k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase());return `${k}="${esc(v===true?'':v)}"`;}).join(' ');return `<${el.type} ${attrs}>${voids.has(el.type)?'':render(el.props.children)+`</${el.type}>`}`;}
const shell=require(root+'/src/layout/AppLayout.tsx').default;
const pages=[['overview','/overview','overview/OverviewPage'],['tasks','/development/tasks','development/TaskListPage'],['batch','/development/batch','development/BatchCreatePage'],['registry','/development/registry','development/TaskRegistryPage'],['multi','/development/multi-table','development/MultiTableSyncPage'],['ingress','/ops/ingress','ops/IngressMonitorPage'],['distribution','/ops/distribution','ops/DistributionMonitorPage'],['clusters','/ops/clusters','ops/ClusterMonitorPage'],['cross','/ops/cross-network','ops/CrossNetworkPage'],['instant','/reconcile/instant','reconcile/InstantReconcilePage'],['inventory','/reconcile/inventory','reconcile/InventoryReconcilePage'],['statements','/reconcile/statements','reconcile/InventoryStatementsPage'],['canvas','/development/canvas','development/CanvasPage']];
const out=path.resolve(root,'../logs/haitong/review/dom-review');fs.mkdirSync(out,{recursive:true});
const css=fs.readFileSync(root+'/src/styles/global.css','utf8'),shim=fs.readFileSync(__dirname+'/review-ant.css','utf8');const logo=fs.readFileSync(root+'/public/brand/haitong-mark.svg').toString('base64');
function graphSnapshot(){const nodes=state.tasks[0].flow.nodes,edges=state.tasks[0].flow.edges;const c=dark?{fill:'#1C2D47',stroke:'#456087',text:'#E3EDFF',secondary:'#ADC0DF'}:{fill:'#fff',stroke:'#C1D0E8',text:'#172B4D',secondary:'#667994'};return `<svg viewBox="0 0 1050 650" width="100%" height="100%"><defs><pattern id="g" width="16" height="16" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="${dark?'#344761':'#CDD8E9'}"/></pattern></defs><rect width="100%" height="100%" fill="url(#g)"/>${edges.map(e=>{const a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target);return `<path d="M${a.x+216} ${a.y+49}H${b.x}" stroke="#426FD5" stroke-width="2" fill="none"/>`;}).join('')}${nodes.map(n=>`<g transform="translate(${n.x},${n.y})"><rect width="216" height="98" rx="10" fill="${c.fill}" stroke="${c.stroke}"/><rect x="0" y="10" width="3" height="78" rx="2" fill="#2457D6"/><rect x="14" y="13" width="30" height="30" rx="8" fill="#E8EFFF"/><path d="M22 20h14v16H22zM22 25h14M22 30h14" fill="none" stroke="#2457D6"/><text x="54" y="27" fill="${c.text}" font-size="14" font-weight="600">${esc(n.name)}</text><text x="54" y="44" fill="${c.secondary}" font-size="11">${n.kind.toUpperCase()}</text><path d="M14 59H202" stroke="${c.stroke}"/><text x="15" y="79" font-size="12" fill="${c.secondary}">${n.kind==='read'?'读取本地表快照和样例记录':n.kind==='write'?'向本地目标表应用写入策略':'使用任务已配置的字段映射'}</text><circle cx="216" cy="49" r="5" fill="${c.fill}" stroke="#2457D6"/></g>`).join('')}<text x="25" y="605" font-size="12" fill="${c.secondary}">隔离布局样板 · X6 未在此截图中运行</text></svg>`;}
for(const isDark of [false,true])for(const isCollapsed of [false,true])for(const[name,route,module]of pages){dark=isDark;collapsed=isCollapsed;pageRoute=route;idCounter=0;const Page=require(root+'/src/pages/'+module+'.tsx').default;let html=render(name==='canvas'?h(Page):h(shell,{},h(Page)));if(name==='canvas')html=html.replace(/<div class="flow-graph-host"[^>]*><\/div>/,`<div class="flow-graph-host">${graphSnapshot()}</div>`);html=html.replaceAll('src="brand/haitong-mark.svg"',`src="data:image/svg+xml;base64,${logo}"`);fs.writeFileSync(`${out}/${name}-${dark?'dark':'light'}-${collapsed?'collapsed':'expanded'}.html`,`<!DOCTYPE html><html lang="zh-CN" data-theme="${dark?'dark':'light'}" data-motion="off"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>海通隔离样式评审</title><style>${css}\n${shim}</style><body>${html}</body></html>`);}
// SVG variants exported from the real component, not generated from screenshots.
const Art=require(root+'/src/design/OceanArt.tsx').default;const artDir=root+'/public/heroes';fs.mkdirSync(artDir,{recursive:true});for(const file of fs.readdirSync(artDir))if(file.endsWith('.svg'))fs.unlinkSync(artDir+'/'+file);for(const d of [false,true]){dark=d;for(const name of ['overview','tasks','registry','batch','multi','ingress','distribution','clusters','cross','instant','inventory','statements']){let svg=render(h(Art,{kind:name}));svg=svg.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" ').replaceAll('var(--art-card,#fff)',dark?'#253D61':'#FFFFFF').replace('class="ocean-art"','');fs.writeFileSync(`${artDir}/${name}-${dark?'dark':'light'}.svg`,svg);}}
console.log('Rendered 52 isolated TSX/DOM snapshots and 24 vector hero assets. NO React/Ant/X6 runtime validation.');
