import { theme, type ThemeConfig } from 'antd';
import { typeScale, typeColor, bodyFontFamily } from './typography';
/** Aurora Blue 管理工作区：保留小尺寸组件语义，表格与表单采用舒展间距。见 /design.md。 */
export const appTheme: ThemeConfig = {
    algorithm: theme.compactAlgorithm,
    token: {
        colorPrimary: '#5267F5', colorInfo: '#5267F5', colorSuccess: '#12B886',
        colorWarning: '#F59A23', colorError: '#F25569', colorText: typeColor.body,
        colorTextSecondary: typeColor.secondary, colorTextDescription: typeColor.secondary, colorTextHeading: typeColor.heading,
        colorBgLayout: '#F4F7FC', colorBgContainer: '#FFFFFF', colorBgMask: 'rgba(16,31,65,.16)',
        colorBorder: '#DFE6F3', colorBorderSecondary: '#EDF1F8', colorFillAlter: '#F7F9FD',
        borderRadius: 6, borderRadiusLG: 12, borderRadiusSM: 4,
        fontSize: typeScale.body.size, fontSizeSM: typeScale.caption.size,
        fontSizeLG: typeScale.section.size, fontSizeXL: typeScale.page.size,
        fontSizeHeading1: typeScale.display.size, fontSizeHeading2: typeScale.page.size,
        fontSizeHeading3: typeScale.panel.size, fontSizeHeading4: typeScale.section.size,
        fontSizeHeading5: typeScale.body.size, fontWeightStrong: 600,
        lineHeight: typeScale.body.lineHeight / typeScale.body.size,
        lineHeightSM: typeScale.caption.lineHeight / typeScale.caption.size,
        lineHeightLG: typeScale.section.lineHeight / typeScale.section.size,
        lineHeightHeading1: typeScale.display.lineHeight / typeScale.display.size,
        lineHeightHeading2: typeScale.page.lineHeight / typeScale.page.size,
        lineHeightHeading3: typeScale.panel.lineHeight / typeScale.panel.size,
        lineHeightHeading4: typeScale.section.lineHeight / typeScale.section.size,
        lineHeightHeading5: typeScale.body.lineHeight / typeScale.body.size,
        controlHeight: 36, controlHeightSM: 34, controlHeightLG: 40,
        padding: 16, paddingLG: 20, paddingSM: 10, paddingXS: 6,
        margin: 16, marginLG: 20, marginSM: 10, marginXS: 6,
        fontFamily: bodyFontFamily,
        boxShadow: '0 8px 32px rgba(36,59,114,.08)',
        boxShadowSecondary: '0 12px 40px rgba(36,59,114,.12)',
    },
    components: {
        Layout: { headerBg: '#ffffff', siderBg: '#111D35', bodyBg: '#F4F7FC', headerHeight: 56, headerPadding: '0 16px' },
        Menu: { fontSize: typeScale.navigation.size, darkItemBg: 'transparent', darkSubMenuItemBg: 'transparent', darkItemColor: typeColor.onDark, darkItemHoverColor: '#FFFFFF', darkItemSelectedBg: '#314978', darkItemSelectedColor: '#FFFFFF', darkPopupBg: '#172640', itemHeight: 34, itemMarginInline: 8, itemMarginBlock: 2, itemBorderRadius: 6, subMenuItemBg: 'transparent', iconSize: 16, groupTitleFontSize: 12 },
        Card: { bodyPadding: 20, bodyPaddingSM: 16, headerFontSize: typeScale.section.size, headerFontSizeSM: typeScale.section.size, headerHeight: 48, headerHeightSM: 48, headerPadding: 20, headerPaddingSM: 16, colorBorderSecondary: '#EDF1F8', boxShadowTertiary: '0 4px 24px rgba(40,62,114,.035)' },
        Button: { contentFontSize: typeScale.body.size, contentFontSizeSM: typeScale.body.size, primaryShadow: '0 4px 10px rgba(82,103,245,.19)', defaultShadow: '0 1px 2px rgba(35,60,110,.025)', fontWeight: 500, paddingInlineSM: 10 },
        Table: { headerBg: '#F7F9FD', headerColor: '#667493', headerSplitColor: 'transparent', rowHoverBg: '#F5F7FF', rowSelectedBg: '#EDF1FF', cellPaddingBlockSM: 10, cellPaddingInlineSM: 14, cellFontSizeSM: typeScale.body.size, cellFontSize: typeScale.body.size, cellFontSizeMD: typeScale.body.size, cellPaddingBlockMD: 12, cellPaddingInlineMD: 16, borderColor: '#EDF1F8' },
        Tabs: { titleFontSize: typeScale.body.size, titleFontSizeSM: typeScale.body.size, itemColor: '#7A86A2', itemSelectedColor: '#5267F5', inkBarColor: '#5267F5', horizontalItemGutter: 20, horizontalItemPaddingSM: '8px 0' },
        Input: { inputFontSize: typeScale.body.size, inputFontSizeSM: typeScale.body.size, activeShadow: '0 0 0 3px rgba(82,103,245,.08)', hoverBorderColor: '#9EABFF' },
        Select: { fontSize: typeScale.body.size, optionFontSize: typeScale.body.size, optionSelectedBg: '#EEF2FF', optionActiveBg: '#F7F9FD', optionHeight: 34 },
        Tree: { fontSize: typeScale.body.size, nodeHoverBg: '#F5F7FF', nodeSelectedBg: '#EDF2FF', titleHeight: 30 },
        Tag: { fontSize: typeScale.caption.size, fontSizeSM: typeScale.caption.size, defaultBg: '#F3F6FC', defaultColor: '#667493' },
        Drawer: { fontSizeLG: typeScale.panel.size, footerPaddingBlock: 14, footerPaddingInline: 24 },
        Descriptions: { fontSize: typeScale.body.size, fontSizeLG: typeScale.section.size, labelColor: typeColor.secondary, contentColor: '#243354', itemPaddingBottom: 10 },
        Breadcrumb: { fontSize: typeScale.navigation.size },
        InputNumber: { inputFontSize: typeScale.body.size, inputFontSizeSM: typeScale.body.size },
        DatePicker: { inputFontSize: typeScale.body.size, inputFontSizeSM: typeScale.body.size },
        Pagination: { fontSize: typeScale.body.size },
        Segmented: { fontSize: typeScale.body.size, trackBg: '#F1F4FA', itemSelectedBg: '#FFFFFF', itemSelectedColor: '#5267F5' },
        Form: { labelColor: '#5D6C8D', labelFontSize: typeScale.body.size, verticalLabelPadding: '0 0 6px', itemMarginBottom: 18 },
        Modal: { titleFontSize: typeScale.panel.size },
        Statistic: { titleFontSize: typeScale.body.size, contentFontSize: typeScale.statistic.size },
    },
};

/** 认证页面独立使用标准算法和舒展尺寸，继承系统颜色与文字层级。 */
export const authTheme: ThemeConfig = {
    algorithm: theme.defaultAlgorithm,
    token: { controlHeight: 44, controlHeightSM: 36, controlHeightLG: 44 },
    components: {
        Form: { itemMarginBottom: 24, verticalLabelPadding: '0 0 8px' },
        Input: { inputFontSizeLG: typeScale.body.size, paddingInlineLG: 14 },
        Button: { contentFontSizeLG: typeScale.body.size, paddingInlineLG: 16 },
        Segmented: { controlHeightLG: 40 },
    },
};
